* Landesgruppe
**  Wichtige Info Aufrufe Newsletter
Diesen Newsletter findet ihr ab jetzt auch auf Whatsapp! Dafür einfach über diesen Link beitreten: https://chat.whatsapp.com/GBCBuLIU2U78zpim5yGxLF
---

Sehr gerne nehmen wir eure Aufrufe oder Danksagungen in den wöchentlichen Newsletter auf.

Schreibt mir (shh-newsletter@yfu-deutschland.de) dafür einfach immer bis *Mittwochs 12:00 Uhr* eure Aufrufe, damit ich sie noch in den Newsletter der aktuellen Woche mit aufnehmen kann. Ansonsten nehme ich die Aufrufe natürlich gerne in den nächsten auf.

Vielen lieben Dank und ich freue mich auf eure Emails.

Liebe Grüße
Aimo
** Communitea Einladung
Liebe Community,
wir haben News! 🎄✨

wir möchten euch herzlich zu einem weihnachtlichen Communitea-Treffen einladen. Gemeinsam wollen wir zusammen mit den Austauschschüler*innen das Jahr ausklingen lassen. 

📅 Wann? 20. Dezember, um 11 Uhr
📍 Wo? Geschäftsstelle 

Wir bereiten gemeinsamen Punsch zu und basteln Weihnachtssterne. Wer möchte, kann gern Kekse oder andere kleine Snacks zum Teilen mitbringen.

Wenn ihr dabei seid, meldet euch bitte [[https://forms.office.com/Pages/ResponsePage.aspx?id=QqKWNFDLrkCVZmI1B908iRyBOzkwWXZFoqlrTkGPt6NUOVZYVUFXWThPOVFPTDVESUVMMTZVS08xNC4u][hier]] kurz an. 
Wir freuen uns auf euch und auf ein gemütliches Treffen zum Jahresabschluss!

Liebe Grüße
Leah, Aimo und Ole
** Seminarleitungsschulung (SLS) 2026: Vom 30. Januar bis 1. Februar 2026 in Hamburg – sei dabei! 💪

Du hast Erfahrung als Teamer*in gesammelt, fühlst dich methodisch fit und suchst nach der nächsten Herausforderung? Du wünschst dir eine gute Vorbereitung auf die Rolle als Seminarleitung oder noch mehr Sicherheit, bevor du die erste oder eine weitere Leitung übernimmst? Dann ist die Seminarleitungsschulung (SLS) in Hamburg genau das Richtige für dich. 🚀

In dieser Schulung wird es um die Basics gehen, die du als Seminarleitung kennen solltest sowie eine Vertiefung dieses Wissens. Du lernst, welche Verantwortung bei dir als Leitung liegt, worauf du achten solltest und wie du für ein gutes Teamwork sorgst.

[[https://eur05.safelinks.protection.outlook.com/?url=https%3A%2F%2Fforms.office.com%2Fe%2Fk57ZeStKUB&data=05%7C02%7Cshh-newsletter%40yfu-deutschland.de%7C8e659064ec854e96526e08de370d7b08%7C3496a242cb5040ae9566623507dd3c89%7C0%7C0%7C639008728190782834%7CUnknown%7CTWFpbGZsb3d8eyJFbXB0eU1hcGkiOnRydWUsIlYiOiIwLjAuMDAwMCIsIlAiOiJXaW4zMiIsIkFOIjoiTWFpbCIsIldUIjoyfQ%3D%3D%7C0%7C%7C%7C&sdata=ALMq6UlEIOS6TkCINdhnELobhxNMQRIfZ2EvFQI35h8%3D&reserved=0][Melde dich gleich an!]]

Mehr Infos findest du in der Anmelde-Abfrage. Bei weiteren Fragen kontaktiere Rahel aus der GS ([[mailto://ehrenamt@yfu.de][ehrenamt@yfu.de]], Durchwahl -44). (Hinweis: Ein Angebot für erfahrenere Leitungen wird es Anfang Oktober 2026 geben.)
* Externes und Überregionales
** Mitarbeiter-Gesuche/Stellen 
*Das Ehrenamtliche Cloud Adminteam sucht nach Unterstützung*

YFU-Ehrenamt ohne Mailsystem ist in vielen Fällen nicht mehr wegzudenken. Mit der Erweiterung der Systeme durch aktuelle Zwänge benötigen das Cloud Adminteam mit seinen Teilgruppen Microsoft 365 und Google Workspace tatkräftige Unterstützung im Bereich Support/Nutzerbetreuung und Konzeption. Zusätzlich ist auch Unterstützung des Leiters Cloud Adminteam von großem Bedarf. Wir freuen uns über Meldungen. Gefragt ist jede:r mit Interesse oder schon vorhandenem technischem Wissen und Lernfreude an solchen Systemen, bevor man damit irgendwann im Berufsleben arbeiten muss. Die Ausschreibung für die Unterstützung des Leiters findest Du *[[https://eur05.safelinks.protection.outlook.com/?url=https%3A%2F%2Fintranet.yfu.de%2Fdownloads%2Ffiles%2F3813&data=05%7C02%7Chh-newsletter%40yfu-deutschland.de%7Cc5b31a9bb4ee417c313208de37e36532%7C3496a242cb5040ae9566623507dd3c89%7C0%7C0%7C639009646971390632%7CUnknown%7CTWFpbGZsb3d8eyJFbXB0eU1hcGkiOnRydWUsIlYiOiIwLjAuMDAwMCIsIlAiOiJXaW4zMiIsIkFOIjoiTWFpbCIsIldUIjoyfQ%3D%3D%7C0%7C%7C%7C&sdata=hNK%2FZPjfvVsfp8YvFzPxv3AS%2FvIkvc4%2FZt1A6ZvW1zo%3D&reserved=0][hier]]*, die Ausschreibung für die Teilgruppe Microsoft 365 *[[https://eur05.safelinks.protection.outlook.com/?url=https%3A%2F%2Fintranet.yfu.de%2Fdownloads%2Ffiles%2F3513&data=05%7C02%7Chh-newsletter%40yfu-deutschland.de%7Cc5b31a9bb4ee417c313208de37e36532%7C3496a242cb5040ae9566623507dd3c89%7C0%7C0%7C639009646971401405%7CUnknown%7CTWFpbGZsb3d8eyJFbXB0eU1hcGkiOnRydWUsIlYiOiIwLjAuMDAwMCIsIlAiOiJXaW4zMiIsIkFOIjoiTWFpbCIsIldUIjoyfQ%3D%3D%7C0%7C%7C%7C&sdata=XKh%2B3lqnbdPxbk9i4cns0Ru6zWfLW4D6oABG7wITRuU%3D&reserved=0][hier]]* und für die neue Teilgruppe Google Workspace *[[https://eur05.safelinks.protection.outlook.com/?url=https%3A%2F%2Fintranet.yfu.de%2Fdownloads%2Ffiles%2F3841&data=05%7C02%7Chh-newsletter%40yfu-deutschland.de%7Cc5b31a9bb4ee417c313208de37e36532%7C3496a242cb5040ae9566623507dd3c89%7C0%7C0%7C639009646971412731%7CUnknown%7CTWFpbGZsb3d8eyJFbXB0eU1hcGkiOnRydWUsIlYiOiIwLjAuMDAwMCIsIlAiOiJXaW4zMiIsIkFOIjoiTWFpbCIsIldUIjoyfQ%3D%3D%7C0%7C%7C%7C&sdata=%2FK6Fa8K7TUTBrmv8iU%2FYRzg3Bj%2Bw2NkQyJpszm4yQAw%3D&reserved=0][hier]]*

*Mitorganisator*in für länderspezifische Webinare 2026 gesucht*

Die Länderwebinare finden digital statt und gehören zur länderspezifischen Vorbereitung der Teilnehmenden.
Die Aufgaben bestehen darin, gemeinsam mit Lätizia Teamer*innen zu finden und in Teams einzuteilen, die Treffen über Microsoft Teams anzulegen und die Teilnehmenden in Zusammenarbeit mit der Geschäftsstelle einzuladen.
Du solltest Erfahrung im grundsätzlichen Umgang mit Microsoft Word und Excel haben. Die Planung beginnt im Januar, die Webinare finden ab April bis Juli statt.
Bei Interesse oder Fragen melde dich bitte bei Lätizia Bresler unter laetizia.bresler@yfu-deutschland.de

*Leitungen und Teamer*innen für VBTs 2026 gesucht*

Du hast Lust, 2026 eine VBT zu teamen oder zu leiten?
Dann trage dich jetzt in den Leitungs- und Team-Survey ein (verfügbar bis zum 05.01.2026):
[[https://eur05.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.yfu-survey.org%2Fpoll%2Findex.php%2F176719%3Flang%3Dde-informal&data=05%7C02%7Chh-newsletter%40yfu-deutschland.de%7Cc5b31a9bb4ee417c313208de37e36532%7C3496a242cb5040ae9566623507dd3c89%7C0%7C0%7C639009646971424006%7CUnknown%7CTWFpbGZsb3d8eyJFbXB0eU1hcGkiOnRydWUsIlYiOiIwLjAuMDAwMCIsIlAiOiJXaW4zMiIsIkFOIjoiTWFpbCIsIldUIjoyfQ%3D%3D%7C0%7C%7C%7C&sdata=hpTfYkjm6BqJFYqE4hQ3R3OQRb50ty9XduAo%2FLDs4BQ%3D&reserved=0][VBT-Saison 2026 Leitungs- und Teamsuche]]
Bei Fragen erreichst du Fenja unter vbt@yfu.de

*⛄ Weihnachts-Feuerwehr-Familien gesucht! ⛄*

Das Jahr neigt sich dem Ende zu und wir stehen erneut vor vielen kurzfristigen Familienwechseln. Besonders über die Feiertage benötigen wir dringend Ersatz- und Übergangsfamilien für Austauschschüler*innen.
Kennt ihr Familien – oder habt ihr selbst Kapazität –, die über die Feiertage aufnehmen können? Aktuell fehlen uns noch einige Familien, die über die Feiertage unterstützen können.
Dann meldet euch bitte mit dem möglichen Zeitraum unter gastfamilien@yfu.de.
Vielen Dank für eure Unterstützung und eine schöne Vorweihnachtszeit! 🎄

*Male Teamer wanted! 🕵🏻‍♀️*

Für unsere Mittelseminare suchen wir dringend männliche Unterstützung, die idealerweise Erfahrung auf AP-Tagungen mitbringt und Lust hat, im Februar/März eine Woche in Berlin/Hamburg/Possenhofen zu verbringen und eine gute Zeit mit unseren AP-Schüler*innen zu haben! 🧡
Fast alle Seminare brauchen noch männliche Unterstützung, daher check doch einmal deinen Kalender, ob vielleicht ein Seminar zeitlich passt und trag dich in die [[https://eur05.safelinks.protection.outlook.com/?url=https%3A%2F%2Fforms.office.com%2FPages%2FResponsePage.aspx%3Fid%3DOqhNyXAcyk-Cu3mnrCJZh6KOYPtMfppBhidNFBnWvdtUQjVZVjZVV0NQSDdDTTI1NDVUM0pOTDBMSS4u&data=05%7C02%7Chh-newsletter%40yfu-deutschland.de%7Cc5b31a9bb4ee417c313208de37e36532%7C3496a242cb5040ae9566623507dd3c89%7C0%7C0%7C639009646971438463%7CUnknown%7CTWFpbGZsb3d8eyJFbXB0eU1hcGkiOnRydWUsIlYiOiIwLjAuMDAwMCIsIlAiOiJXaW4zMiIsIkFOIjoiTWFpbCIsIldUIjoyfQ%3D%3D%7C0%7C%7C%7C&sdata=TBrA%2BJ%2F2MPM8Xz1vOa2pYRlc3lLyga6cC5TgdykD5SA%3D&reserved=0][Umfrage]] ein oder melde dich per Mail unter ap-seminare@yfu.de! 🚀

** Schulungen
*Seminarleitungsschulung (SLS) 2026: Vom 30. Januar bis 1. Februar 2026 in Hamburg – sei dabei! 💪*

Du hast Erfahrung als Teamer*in gesammelt, fühlst dich methodisch fit und suchst nach der nächsten Herausforderung? Du wünschst dir eine gute Vorbereitung auf die Rolle als Seminarleitung oder noch mehr Sicherheit, bevor du die erste oder eine weitere Leitung übernimmst? Dann ist die Seminarleitungsschulung (SLS) in Hamburg genau das Richtige für dich. 🚀 In dieser Schulung wird es um die Basics gehen, die du als Seminarleitung kennen solltest sowie eine Vertiefung dieses Wissens. Du lernst, welche Verantwortung bei dir als Leitung liegt, worauf du achten solltest und wie du für ein gutes Teamwork sorgst. [[https://eur05.safelinks.protection.outlook.com/?url=https%3A%2F%2Fforms.office.com%2Fe%2Fk57ZeStKUB&data=05%7C02%7Chh-newsletter%40yfu-deutschland.de%7Cc5b31a9bb4ee417c313208de37e36532%7C3496a242cb5040ae9566623507dd3c89%7C0%7C0%7C639009646971453418%7CUnknown%7CTWFpbGZsb3d8eyJFbXB0eU1hcGkiOnRydWUsIlYiOiIwLjAuMDAwMCIsIlAiOiJXaW4zMiIsIkFOIjoiTWFpbCIsIldUIjoyfQ%3D%3D%7C0%7C%7C%7C&sdata=UImpFnxN03e05p%2F16W4alD%2BDREYEYZCkt8RqCl7vuLs%3D&reserved=0][Melde dich gleich an!]] Mehr Infos findest du in der Anmelde-Abfrage. Bei weiteren Fragen kontaktiere Rahel aus der GS (ehrenamt@yfu.de, Durchwahl -44). (Hinweis: Ein Angebot für erfahrenere Leitungen wird es Anfang Oktober 2026 geben.)

*🚀 Powerstart ins Ehrenamt*

Du möchtest aktiv werden oder wieder einsteigen und brauchst für den Start noch ein bisschen Orientierung? Dann haben wir einen Tipp für dich🔥! Starte mit unseren Ehrenamtlichen beim digitalen Powerstart ins Ehrenamt durch. Lerne das YFU 1x1, finde heraus, was es für dich zu tun gibt, wie du dich mit YFUler*innen in deiner Umgebung vernetzen kannst und welche Vorteile du als YFUler*in genießt.
🔥 Aktuelle Termine: https://sway.cloud.microsoft/WKISSAGmmiab4CYG

** Sonstiges / Externes
*✨ Winter-Moment-Giveaway! ✨*

Winter is coming – Omas Wollsocken, eine kuschelige Decke und ein heißer Tee mit Bratapfelgeschmack. ❄ Wir wollen die schönsten First-Moments im Winterkontext aus unserer Community sehen! Ob Plätzchenbacken mit dem Gastkind, Winterferien mit der Gastfamilie, besondere Feiertage oder auf Reisen – egal ob ehemalige*r ATS, Engagierte*r oder Gastfamilienmitglied.
📝 *So machst du mit:* Schick uns ein oder mehrere Fotos von deinem Wintermoment plus 2-3 Sätze, in denen du beschreibst, was du damit verbindest, zusammen mit deinem Vor- und Nachnamen bis *16.12.2025* an community@yfu.de.
😍 *Gewinn:* Unter allen Teilnehmenden verlosen wir einen *cozy YFU-Hoodie*.
🔁 *Was passiert mit deinem Beitrag?* Die schönsten Einsendungen teilen wir in der WhatsApp-Community, auf Social Media und im MeinYFU-Newsletter. Alle Einsendungen bis zum *16.12.2025* nehmen an der Verlosung des Hoodies teil!
🔒 *Datenschutz:* Mit der Teilnahme erklärst du dich einverstanden, dass dein Foto und Beitrag veröffentlicht wird. Deine Daten werden nur für das Gewinnspiel genutzt. Mehr Infos: yfu.de/datenschutz.

*Hilfe für Sarah*

Sarah, YFU-Ehemalige und Ehrenamtliche, braucht Unterstützung und hat uns gebeten, ihren Spendenaufruf zu teilen. [[https://eur05.safelinks.protection.outlook.com/?url=https%3A%2F%2Fintranet.yfu.de%2Fdownloads%2Ffiles%2F3914&data=05%7C02%7Chh-newsletter%40yfu-deutschland.de%7Cc5b31a9bb4ee417c313208de37e36532%7C3496a242cb5040ae9566623507dd3c89%7C0%7C0%7C639009646971464988%7CUnknown%7CTWFpbGZsb3d8eyJFbXB0eU1hcGkiOnRydWUsIlYiOiIwLjAuMDAwMCIsIlAiOiJXaW4zMiIsIkFOIjoiTWFpbCIsIldUIjoyfQ%3D%3D%7C0%7C%7C%7C&sdata=SQIB1KUX8mRX%2FsrxuYnc4iurFrwgWETjBg2vrI40uUo%3D&reserved=0][Hier]] erfährst du, worum es geht und wie du Sarah unterstützen kannst.  
*Achtung:* in dem folgenden Aufruf werden sexualisierte Gewalt und ihre Folgen thematisiert.  
*Ansprechpartner:* Christian Andersch, Kinderschutzbeauftragter, andersch@yfu.de 

*Kostenloser Messenger-Kurs gegen Missbrauch "7 Wochen 7 Tipps"*

Dieser Kurs ist Teil der Kampagne "Nicht wegschieben" der UBSKM. Über sieben Wochen hinweg bekommen Teilnehmer:innen ein bis zwei Nachrichten pro Woche direkt per Whatsapp auf ihr Handy. Es werden keine Daten der Nutzenden abgefragt und auch keine Daten gespeichert. Die Nummer wird von Superchat eine Woche nach Ende des Chats gelöscht.
Mehr Infos und Anmeldung hier: https://nicht-wegschieben.de/aktiv-werden/kinder-vor-gewalt-schuetzen/kurs
*Ansprechpartner:* Christian Andersch, Kinderschutzbeauftragter, andersch@yfu.de

*Externe Beratungsstellen*

Es gibt verschiedene Beratungsstellen, bei denen man sich Hilfe und Beratung holen kann. Diese sind z.B. [[https://eur05.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.wildwasser.de%2F&data=05%7C02%7Chh-newsletter%40yfu-deutschland.de%7Cc5b31a9bb4ee417c313208de37e36532%7C3496a242cb5040ae9566623507dd3c89%7C0%7C0%7C639009646971499727%7CUnknown%7CTWFpbGZsb3d8eyJFbXB0eU1hcGkiOnRydWUsIlYiOiIwLjAuMDAwMCIsIlAiOiJXaW4zMiIsIkFOIjoiTWFpbCIsIldUIjoyfQ%3D%3D%7C0%7C%7C%7C&sdata=ZfbRhLwdjtkcF%2B0wnC7QfXjTxYkO1UEA3W1qdTGDKF8%3D&reserved=0][Wildwasser]], [[https://eur05.safelinks.protection.outlook.com/?url=https%3A%2F%2Fzartbitter.de%2F&data=05%7C02%7Chh-newsletter%40yfu-deutschland.de%7Cc5b31a9bb4ee417c313208de37e36532%7C3496a242cb5040ae9566623507dd3c89%7C0%7C0%7C639009646971511537%7CUnknown%7CTWFpbGZsb3d8eyJFbXB0eU1hcGkiOnRydWUsIlYiOiIwLjAuMDAwMCIsIlAiOiJXaW4zMiIsIkFOIjoiTWFpbCIsIldUIjoyfQ%3D%3D%7C0%7C%7C%7C&sdata=TgKO%2BTVFRx8HJgPHdEOq8suQBpUbVL7uNFv%2Ft8BckSI%3D&reserved=0][Zartbitter]], [[https://eur05.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.schattenriss.de%2F&data=05%7C02%7Chh-newsletter%40yfu-deutschland.de%7Cc5b31a9bb4ee417c313208de37e36532%7C3496a242cb5040ae9566623507dd3c89%7C0%7C0%7C639009646971524123%7CUnknown%7CTWFpbGZsb3d8eyJFbXB0eU1hcGkiOnRydWUsIlYiOiIwLjAuMDAwMCIsIlAiOiJXaW4zMiIsIkFOIjoiTWFpbCIsIldUIjoyfQ%3D%3D%7C0%7C%7C%7C&sdata=panABz%2FEXyDTaPLqo6XCuE8vq1sh0pBV%2BxMQzRRBWwM%3D&reserved=0][Schattenriss]], [[https://eur05.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.violetta-hannover.de%2F&data=05%7C02%7Chh-newsletter%40yfu-deutschland.de%7Cc5b31a9bb4ee417c313208de37e36532%7C3496a242cb5040ae9566623507dd3c89%7C0%7C0%7C639009646971535515%7CUnknown%7CTWFpbGZsb3d8eyJFbXB0eU1hcGkiOnRydWUsIlYiOiIwLjAuMDAwMCIsIlAiOiJXaW4zMiIsIkFOIjoiTWFpbCIsIldUIjoyfQ%3D%3D%7C0%7C%7C%7C&sdata=3KYycIenFbkqo8SDxCIqz7RqOyFlVjLTiKxGHV3C3pY%3D&reserved=0][Violetta]] und der [[https://eur05.safelinks.protection.outlook.com/?url=https%3A%2F%2Fkinderschutzbund.de%2F&data=05%7C02%7Chh-newsletter%40yfu-deutschland.de%7Cc5b31a9bb4ee417c313208de37e36532%7C3496a242cb5040ae9566623507dd3c89%7C0%7C0%7C639009646971546222%7CUnknown%7CTWFpbGZsb3d8eyJFbXB0eU1hcGkiOnRydWUsIlYiOiIwLjAuMDAwMCIsIlAiOiJXaW4zMiIsIkFOIjoiTWFpbCIsIldUIjoyfQ%3D%3D%7C0%7C%7C%7C&sdata=fOi0QXZPrmBOE17RY2cESJLC1Vplhxa2NgoFhPs14IU%3D&reserved=0][Kinderschutzbund]]. YFU Deutschland unterstützt Betroffene bei Bedarf gerne bei der Kontaktaufnahme zu einer Beratungsstelle in ihrer Nähe. Auch das Hilfeportal Sexueller Missbrauch bietet Informationen und Unterstützungsangebote (www.hilfeportal-missbrauch.de).
* Terminübersicht
** TERMINE 2025
*30.01. - 02.02.2026* &nbsp;&nbsp;&nbsp; Seminarleitungsschulung (SLS)

*31.01. - 01.02.2026* &nbsp;&nbsp;&nbsp; *(LG)* Referent*innen/ Landesgruppenwochenende in Kiel (Anmeldung für alle offen)

*20.03. - 22.03.2026* &nbsp;&nbsp;&nbsp; Gremiensitzung Frühjahr

*05.06. - 07.06.2026* &nbsp;&nbsp;&nbsp; *(LG)* Nord-LGT

*25.09. - 27.09.2026* &nbsp;&nbsp;&nbsp; *(LG)* Aktivenwochenende 
