* Landesgruppe
**  Wichtige Info Aufrufe Newsletter
Diesen Newsletter findet ihr ab jetzt auch auf Whatsapp! Dafür einfach über diesen Link beitreten: https://chat.whatsapp.com/GBCBuLIU2U78zpim5yGxLF
---

Sehr gerne nehmen wir eure Aufrufe oder Danksagungen in den wöchentlichen Newsletter auf.

Schreibt mir (shh-newsletter@yfu-deutschland.de) dafür einfach immer bis *Mittwochs 12:00 Uhr* eure Aufrufe, damit ich sie noch in den Newsletter der aktuellen Woche mit aufnehmen kann. Ansonsten nehme ich die Aufrufe natürlich gerne in den nächsten auf.

Vielen lieben Dank und ich freue mich auf eure Emails.

Liebe Grüße
Aimo
** SAVE THE DATE: 06.12.2025 Landesversammlung 
Liebe Landesgruppe,

das Jahr 2025 neigt sich dem Ende zu und wir wollen als Landesgruppe gerne gemeinsam Revue passieren lassen, was alles so los war bei uns im Norden, und auf die Gestaltung des nächsten Jahres blicken.

Deswegen laden wir euch ganz herzlich ein zur *Landesversammlung am 06.12.2025 um 13 Uhr in der Geschäftsstelle (oder digital)*.

Wer mag, ist davor bereits *ab 12 Uhr* zum *gemeinsamen Mittagessen* eingeladen.

Die offizielle Einladung habt ihr wie immer noch mal separat erhalten, merkt euch also unbedingt schon mal das Datum vor, um einen spannenden Nachmittag mit Berichten aus den verschiedenen Bereichen unserer LG und die Wahlen der Satzungsämter nicht zu verpassen. Zur *Anmeldung* geht es [[https://eur05.safelinks.protection.outlook.com/?url=https%3A%2F%2Fforms.office.com%2Fe%2FwVzmNfaYu0&data=05%7C02%7Cshh-newsletter%40yfu-deutschland.de%7C9ff96f3ff3754cdb559008de1a35b284%7C3496a242cb5040ae9566623507dd3c89%7C0%7C0%7C638977015091536847%7CUnknown%7CTWFpbGZsb3d8eyJFbXB0eU1hcGkiOnRydWUsIlYiOiIwLjAuMDAwMCIsIlAiOiJXaW4zMiIsIkFOIjoiTWFpbCIsIldUIjoyfQ%3D%3D%7C0%7C%7C%7C&sdata=KBr86ul409%2Fr7DPEEMePpRx3oLC4ALYMUcJbsl9rkPs%3D&reserved=0][hier]].

Eingeladen sind alle aus der Landesgruppe SHH, von justee bis alter Hase und alle andere - denkt jedoch bitte daran, dass ihr nur als *Mitglied des Vereins* auch wählen dürft. (Geheimtipp, das [[https://eur05.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.yfu.de%2Fengagieren-und-in-verbindung-bleiben%2Fmitglied-werden&data=05%7C02%7Cshh-newsletter%40yfu-deutschland.de%7C9ff96f3ff3754cdb559008de1a35b284%7C3496a242cb5040ae9566623507dd3c89%7C0%7C0%7C638977015091559609%7CUnknown%7CTWFpbGZsb3d8eyJFbXB0eU1hcGkiOnRydWUsIlYiOiIwLjAuMDAwMCIsIlAiOiJXaW4zMiIsIkFOIjoiTWFpbCIsIldUIjoyfQ%3D%3D%7C0%7C%7C%7C&sdata=EDqCecOzuzheW1gOgAiW%2FAhahDvrccZM01EXfSxBkbc%3D&reserved=0][hier]] schnell online zu erledigen)

Falls ihr Fragen zur Landesversammlung oder zu freien Ämtern habt, meldet euch gerne bei mir ([[mailto://amilou.fehr@yfu-deutschland.de][amilou.fehr@yfu-deutschland.de]]) oder bei anderen Mitgliedern des erweiterten Landesgruppenvorstandes.

Wir freuen uns ganz dolle auf euch!! Kommt gut durch den November und bis bald!

Mit demokratischen Grüßen :)
Amilou für den erweiterten Landesgruppenvorstand 
* Öffentlichkeitsarbeit
** ÖA-Teamende für Jugendbildungsmesse gesucht! 
Liebe Landesgruppe,
Für die letzte ÖA-Veranstaltung im November sind wir noch auf der Suche nach jemanden für die erste Schicht der JuBi. Die Jugendbildungsmesse ist dabei Ideal als Einstieg in die ÖA, da wir schon eine erfahrene Teamerin vor Ort haben! :)

*Jugendbildungsmesse an der Stadtteilschule Bergedorf*
Wann? Sa, 15.11. 9:30 bis 13:00 Uhr 
Wo? Ladenbeker Weg 13, 21033 Hamburg
Wer? 1 Person für die erste Schicht 
Lust? Melde dich bei Duy ([[mailto://dennisle-duy.nguyen@yfu-deutschland.de][dennisle-duy.nguyen@yfu-deutschland.de]])

Wenn ihr Zeit und Lust habt uns zu unterstützen, freuen wir uns auf eure Nachrichten.
Schreibt uns auch gerne bei allen Fragen, die ihr habt!

Liebe Grüße
Annina, Simon, Duy, Kira, Anouk und Lisa
* Entsendeprogramm
** Teamende gesucht für Elternkennlerntreffen am 30.11.2025
Für das digitale Elternkennlerntreffen (EKLT) am 30.11.2025 suche ich 1-2 Teamende, die Lust haben, anhand einer bestehenden Präsentation und eigener Erfahrungen, YFU und alles, was zwischen Bewerbung, VBT, Auslandsaufenthalt und NBT stattfindet, vorzustellen.

Das Online-Treffen findet überregional statt und richtet sich an die Eltern, deren Kinder sich gerade für das Programm 2026/27 bewerben.
Beginn ist 19:30 Uhr und das EKLT dauert ca. 90 Minuten.
Erfahrung ist nicht erforderlich.

Bitte meldet euch bei Interesse oder Fragen bei mir unter 0151 75071648 oder [[mailto://natascha.kortum@yfu-deutschland.de][natascha.kortum@yfu-deutschland.de]].

Danke! 
Natascha
* Externes und Überregionales
** Mitarbeiter-Gesuche/Stellen
*Das Ehrenamtliche Cloud Adminteam sucht nach Unterstützung*

YFU-Ehrenamt ohne Mailsystem ist in vielen Fällen nicht mehr wegzudenken. Mit der Erweiterung der Systeme durch aktuelle Zwänge benötigen das Cloud Adminteam mit seinen Teilgruppen Microsoft 365 und Google Workspace tatkräftige Unterstützung im Bereich Support/Nutzerbetreuung und Konzeption. Zusätzlich ist auch Unterstützung des Leiters Cloud Adminteam von großem Bedarf. Wir freuen uns über Meldungen. Gefragt ist jede:r mit Interesse oder schon vorhandenem technischem Wissen und Lernfreude an solchen Systemen, bevor man damit irgendwann im Berufsleben arbeiten muss.

Die Ausschreibung für die Unterstützung des Leiters findest Du *hier*, die Ausschreibung für die Teilgruppe Microsoft 365 *hier* und für die neue Teilgruppe Google Workspace *hier*

*Leitungen und Teamende für Mittelseminare 2026 gesucht 🔎*

Nach dem Seminar ist vor dem Seminar! 🎉 Ganz nach diesem Motto planen wir nach dem OWO-Sommer nun den Mittelseminar-Winter ☃️ und suchen Leitungen und Teamende für die Mittelseminare. Du hast im Februar/März 2026 noch nichts vor und hast Lust auf Berlin/München/Hamburg und natürlich viele tolle ATS? Dann melde dich bei Sophia (📧 ap-seminare@yfu.de) oder fülle einfach diese Umfrage aus.

|            | Wann (meint Teamanreise) | Wo                                    |
| MS 1 Nord | 20.-25. Februar 2026       | Jugendbildungsstätte Kaubstr., Berlin     |
| MS 1 Süd  | 22.-27. Februar 2026       | Jugendherberge Possenhofen (b. München) |
| MS 2 Nord | 25. Februar-02. März 2026  | Jugendbildungsstätte Kaubstr., Berlin     |
| MS 3 Nord | 02.-07. März 2026         | Jugendbildungsstätte Kaubstr., Berlin     |
| MS 3 Süd  | 08.-13. März 2026         | Jugendherberge Possenhofen (b. München) |
| MS PPP   | 07.-13. Februar 2026       | Jugendherberge Hamburg                |

*USA for you 2026 in Georgia: männliche Programmbegleitung gesucht*

Vom 27.2. bis 13.3.2026 reisen wieder 15 Jugendliche von Hamburger Stadtteilschulen mit einem Stipendium nach Georgia, USA, um sich dort ehrenamtlich zu engagieren und Austauscherfahrungen zu sammeln - natürlich gut betreut durch Vor- und Nachbereitungen und vor allem zwei YFU-Programmbegleitungen, von der wir aktuell noch eine männliche suchen. Lust, dich zu engagieren und Teil eines ganz besonderen YFU-Programms zu werden? Dann findest du die ganze Ausschreibung hier:

Deutsches Youth For Understanding Komitee e.V. - Intranet
Bitte fülle  bei Interesse diesen Fragebogen aus:  Bewerbung als Programmbegleitung USA for you - Hamburg 2026 – Formular ausfüllen
Melde dich bei generellen Fragen gerne bei Thekla de Carvalho Rodrigues in der Geschäftsstelle (usaforyou@yfu.de; Durchwahl -77).

*9. und 10. Mai 2026: Auswahl-Mitglied für USA for you in Halle gesucht*

15 Jugendliche aus Sachsen-Anhalt werden mit einem Vollstipendium ihre Herbstferien in den USA verbringen. Damit wir aus den vielen Bewerbungen eine Gruppe zusammenstellen können, brauchen wir dich! Du hast KLT-/Auswahl-Erfahrung und Lust, möglichst an beiden Tagen als Team-Mitglied oder beim Meet & Greet bei der Auswahl mitzuwirken? Dann melde dich bei Thekla: usaforyou@yfu.de oder mit der Durchwahl -77. Mehr Infos zu USA for you findest du hier: www.yfu.de/Usa-for-you

*Juni 2026 in Halle (Saale): Germany for you-Programmbegleitung gesucht*

15 Jugendliche aus Michigan begleiten, wie sie Deutschland bei einem bunten Programm im sommerlichen Halle (Saale) entdecken ist dein Ding? Dann melde dich doch als Ehrenamtliche, um unsere Germany for you-Programmbegleitung vom 13. bis 28. Juni 2026 in Halle (Saale) zu unterstützen. Infos findest du hier: Deutsches Youth For Understanding Komitee e.V. - Intranet 
Melde dich bei Interesse und Fragen gern direkt bei Thekla: germanyforyou@yfu.de oder mit der Durchwahl -77.

*USA for you 2026 Sachsen-Anhalt in Michigan: zwei Programmbegleitungen gesucht*

Für die USA for you-Gruppe aus Sachsen-Anhalt suchen wir derzeit auch noch zwei Programmbegleitungen, die die Jugendlichen vor- und nachbereiten und auf der Reise vom 16.10. bis 30.10.2026 nach Ann Arbor, Michigan, begleiten. Die ganze Ausschreibung findet sich hier:

Deutsches Youth For Understanding Komitee e.V. - Intranet
Bitte fülle bei Interesse diesen Fragebogen aus: Bewerbung als Programmbegleitung USA for you - Sachsen-Anhalt 2026 – Formular ausfüllen
Melde dich bei generellen Fragen gerne bei Thekla de Carvalho Rodrigues in der Geschäftsstelle (usaforyou@yfu.de; Durchwahl -77).

*Instagram: Bitte kommentieren*

Aktuell erleben wir bei Instagram einen starken Reichweiten-Rückgang. Damit sind wir nicht alleine: Es scheint, als ob Accounts zu Themen wie Demokratie, Vielfalt, Gleichberechtigung u.ä. eingeschränkt werden (omasgegenrechts sind z.B. auch enorm betroffen). Um dem entgegenzutreten, brauchen wir jetzt sehr viel Interaktion. Es wäre super, wenn ihr (gerne auch häufiger) einen Kommentar unter irgendeinem Post (oder auch mehreren Posts) hinterlassen könntet. Es reicht ein kurzer Kommentar, Hauptsache ihr sagt etwas Positives ("Tolles Projekt", "Das habe ich auch gemacht, es war super", "Finde ich richtig cool" oder was auch immer euch einfällt - positive Wörter zeigen dem Algorithmus, dass unsere Seite relevant ist). Ihr müsst dafür übrigens nicht unserer Seite folgen (könnt ihr aber natürlich). DANKE für eure Unterstützung!
** Schulungen & Termine
*📣 Schnell sein lohnt sich: jetzt noch für die Teaming-Einweisung anmelden!*

Du willst als Teamer*in bei YFU loslegen, weißt aber nicht, wie und was genau von dir erwartet wird? Dann komm zur überregionalen Teaming-Einweisung (Basis) vom 28.-30.11. 2025 in Kassel und finde es heraus! Lerne, was es zu beachten gibt, damit du deine Kleingruppen auf YFU-Veranstaltungen zum Durchstarten kriegst.  Praxisnah bereiten wir dich auf deinen Einsatz als Teamende*n vor, üben Methoden und zeigen Abläufe – und du probierst dich direkt selbst aus. Dabei knüpfst du Kontakte zu anderen engagierten YFUler*innen und tankst YFU-Spirit.
💶YFU übernimmt die Kosten für Unterkunft, Verpflegung und die An- und Abreise mit der Deutschen Bahn (2. Klasse).
✍ Du willst dabei sein? Dann melde dich hier an: https://tinyurl.com/37nfnasw

*📱 Lerne von einer Content-Expertin - Social Media Workshop!*

Du bist angehende*r Social-Media-Spezialist*in oder möchtest einfach so mehr darüber lernen? Dann komme zum Social-Media-Workshop am 28./29.11. in Berlin und lerne zusammen mit anderen Engagierten, wie du Content für eine aktuelle Social-Media-Kampagne erstellen kannst. Carline Mohr zeigt dir das 1x1 der Content Creation, gibt wertvolle Tipps und hilft dir deine Skills zu erweitern.
Mehr zu Carline findest du hier: https://www.carlinemohr.de/

Die Details:
💡 Fahrt- und Übernachtungskosten werden übernommen.
📝 Jetzt anmelden bei Julia, kastner@yfu.de 
👉 Alle Infos zur Kampagne gibt es hier: https://austausch-braucht-gastfamilien.de/

*Datenschutz kompakt: Online-Einweisung am Donnerstag, 13. November um 19.00 Uhr*

Die nächste digitale Datenschutzeinweisung (ungefähr 45 min.) für Referent*innen, Gremienmitglieder und alle Interessierten findet diesen Donnerstag, 13. November um 19:00 Uhr statt! Wir freuen uns über alle, die dabei sind – gerne auch weitersagen!
Meldet euch unter datenschutz@yfu.de an. Weitere Informationen zum Thema Datenschutz bei YFU findet ihr im Intranet. Unsere aktuellen Datenschutzhinweise stehen auf unserer Webseite zur Verfügung.
** Sonstiges / Externes
*EAs für 2025 einreichen nicht vergessen!*

💸 Hast du in diesem Jahr Geld für dein Ehrenamt bei YFU oder Colored Glasses ausgegeben? 📝 Denk dran, deinen Erstattungsantrag (EA) auszufüllen!
📆 Bitte reiche deine EAs für 2025 grundsätzlich innerhalb von zwei Monaten, spätestens aber bis zum 15. Januar 2026 ein.
💡 Formulare und alle Hinweise findest du im YFU-Intranet: https://intranet.yfu.de/downloads/files?category=36.
📧 Alle Fragen an uns (Team Ehrenamt, ehrenamt@yfu.de) oder direkt an die Finanzabteilung (eas@yfu.de)
* Terminübersicht
** TERMINE 2025
*14.11. - 16.11.2025* &nbsp;&nbsp;&nbsp; Gremiensitzung, Hamburg
*14.11. - 16.11.2025* &nbsp;&nbsp;&nbsp; Colored Glasses Schulung, München

*21.11. - 23.11.2025* &nbsp;&nbsp;&nbsp; Betreuendenseminar, Fulda

*28.11. - 30.11.2025* &nbsp;&nbsp;&nbsp; Teamingeinweisung, Kassel

*28.11. - 30.11.2025* &nbsp;&nbsp;&nbsp; ÖA-Ausschuss-Wochenende, Hamburg 

*06.12.* &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; *(LG)* Landesversammlung
