* Landesgruppe
**  Wichtige Info Aufrufe Newsletter
Diesen Newsletter findet ihr ab jetzt auch auf Whatsapp! Dafür einfach über diesen Link beitreten: https://chat.whatsapp.com/GBCBuLIU2U78zpim5yGxLF
---

Sehr gerne nehmen wir eure Aufrufe oder Danksagungen in den wöchentlichen Newsletter auf.

Schreibt mir (shh-newsletter@yfu-deutschland.de) dafür einfach immer bis *Mittwochs 12:00 Uhr* eure Aufrufe, damit ich sie noch in den Newsletter der aktuellen Woche mit aufnehmen kann. Ansonsten nehme ich die Aufrufe natürlich gerne in den nächsten auf.

Vielen lieben Dank und ich freue mich auf eure Emails.

Liebe Grüße
Aimo
** Einladung zum Kiel-Stammtisch am 24. Oktober
Hallo zusammen,

Ich lade euch sehr herzlich zum nächsten Kiel-Stammtisch am *24. Oktober um 18:00 Uhr* ein.
Ich werde was veganes Kochen und freue mich, wenn möglichst viele den Weg in mein Wohnzimmer *(Wörthstraße 44, 24116 Kiel)* finden!

Meldet euch bitte bis zum 22. Oktober an, damit ist weiß wie viel Essen wir brauchen ([[mailto:Elena.Suehling@yfu-deutschland.de][Elena.Suehling@yfu-deutschland.de]]). Wer möchte kann gerne noch eine Nachspeise oder Getränke mitbringen.

Ich freue mich auf einen schönen Abend mit Euch!

Viele liebe Grüße,
Elena

PS: bei zu vielen Anmeldungen würde ich eventuell nochmal eine Alternative überlegen.
* Öffentlichkeitsarbeit
** ÖA-Teamende für Infoabende und Schulvorträge im November gesucht!
Liebe Landesgruppe,
nach den Herbstferien stehen weitere Veranstaltungen an, für die wir noch Teamende suchen. Die Infoabende, der Schulvortrag, die Infoabende oder die Jugendbildungsmesse sind ideal für den Einstieg in die ÖA, aber auch erfahrene Teamende sind natürlich immer gern gesehen :)
 
*AJA-Infoabend an der Stadtteilschule Kirchwerder*
Wann? Mi, 05.11. 19 bis 21 Uhr, Teamtreffen 18:30 Uhr
Wo? Kirchenheerweg 85, 21037 Hamburg
Wer? 1-2 erfahrene oder unerfahrene Personen
Lust? Melde dich bei Anouk ([[mailto://anouk.zink@yfu-deutschland.de][anouk.zink@yfu-deutschland.de]])
 
*YFU-Schulvortrag bei Online-Infoveranstaltung am Gymnasium Lohbrügge*
Wann? Mi, 05.11. 18 bis 19:30 Uhr
Wo? Online über Zoom
Wer? 1 erfahrene oder unerfahrene Person für einen Erfahrungsbericht
Lust? Melde dich bei Anouk ([[mailto://anouk.zink@yfu-deutschland.de][anouk.zink@yfu-deutschland.de]])
 
*Infoabend mit AFS am Marion-Dönhoff Gymnasium*
Wann? Do, 06.11. 18:00 Uhr
Wo? Willhöden 74, 22587 Hamburg-Blankenese
Wer? 1-2 erfahrene oder unerfahrene Personen für die Präsentation und Erfahrungsberichte
Lust? Melde dich bei Anouk ([[mailto://anouk.zink@yfu-deutschland.de][anouk.zink@yfu-deutschland.de]])
 
*Infoabend am Coppernicus-Gymnasium*
Wann? Do, 06.11. 18:00 Uhr
Wo? Coppernicusstraße 1, 22850 Norderstedt
Wer? 1-2 erfahrene oder unerfahrene Personen für die Präsentation und Erfahrungsberichte
Lust? Melde dich bei Anouk ([[mailto://anouk.zink@yfu-deutschland.de][anouk.zink@yfu-deutschland.de]])
 
*Berufsmesse an der ahfs-Uhlenhorst*
Wann? Do, 13.11. 14:30 bis 18:30 Uhr (auch ein Teil der Zeit wäre schon sehr hilfreich)
Wo? Bostelreihe 5, 22083 Hamburg
Wer? 1-2 erfahrene oder unerfahrene Personen für den Messestand
Lust? Melde dich bei Anouk ([[mailto://anouk.zink@yfu-deutschland.de][anouk.zink@yfu-deutschland.de]])
 
*Jugendbildungsmesse an der Stadtteilschule Bergedorf*
Wann? Sa, 15.11. 10:00 bis 13:00 Uhr und 13:00 bis 16 Uhr
Wo? Ladenbeker Weg 13, 21033 Hamburg
Wer? für beide Schichten je 1 erfahrene oder unerfahrene Personen
Lust? Melde dich bei Duy ([[mailto://dennisle-duy.nguyen@yfu-deutschland.de][dennisle-duy.nguyen@yfu-deutschland.de]])
 
Wenn ihr Zeit und Lust habt uns zu unterstützen, freuen wir uns auf eure Nachrichten.
Schreibt uns auch gerne bei allen Fragen, die ihr habt!

Liebe Grüße
Annina, Simon, Duy, Kira, Finia, Anouk und Lisa
* Aufnahmeprogramm
** Teamer-Aufruf AP-Herbsttreffen - Kinderbetreuung gesucht
Liebe Landesgruppe,

wir suchen jemanden, der Lust hat, die Kinderbetreuung zu übernehmen beim *Herbsttreffen* der Gastfamilien und Austauschschüler in Hamburg!

Worum geht es? 
Du kümmerst dich um die jüngeren *Gastgeschwister*, die noch zu klein sind, um an einer AG teilzunehmen. Ihr könnt malen, basteln, Gesellschaftsspiele spielen oder was dir sonst noch so einfällt! Bastelmaterial und Spiele stellen wir, du kannst aber natürlich gerne selbst auch was mitbringen!

Wann und wo findet das Treffen statt?
Das Treffen findet am *Sonntag, dem 9. November von 9:30 Uhr bis 17 Uhr (inklusive Vor- und Nachbesprechung) im Esche Jugendkunsthaus im Eschel​sweg 4 in 22767 Hamburg* statt.
Für die Kinderbetreuung reicht es aber, wenn du ungefähr von 10 bis 14/15 Uhr dabei bist! 

Wer Lust hat, meldet sich gerne sobald wie möglich bei mir (Imke) [[mailto://imke.plesch@yfu-deutschland.de][imke.plesch@yfu-deutschland.de]].
Meldet euch auch gerne, wenn ihr noch Fragen habt!

Ich freu mich auf euch!

Viele Grüße,
Imke
* Externes und Überregionales
** Mitarbeiter-Gesuche/Stellen 
*Koordinator*innen für Eltis-Test ab sofort gesucht*

Für die Aufnahme an einer Schule in den USA und in Australien benötigen unsere Austauschschüler*innen einen Englischtest. Zwischen Oktober und März werden die sogenannten Eltis-Tests geplant und online durchgeführt. Hierfür werden ab sofort motivierte Koordinator*innen gesucht, die die Tests organisieren. Als Eltis-Koordinator*in kannst du dir deine Arbeit sehr flexibel einteilen und bequem von zuhause aus arbeiten. Du entscheidest selbst, ob du die Tests, die du organisierst, auch selbst durchführen oder hierfür andere Teamende suchen möchtest. Möchtest du Teil des Koordinations-Teams für die Eltis-Tests werden? Dann melde dich unter usa@yfu.de bei Lisa – ich freue mich, von dir zu hören!

*Teamende für Oral English Tests gesucht*

Für die Austauschorganisation FLAG in den USA benötigen unsere Austauschschüler*innen zusätzlich zum Eltis-Test einen Oral English Test. Die Tests finden zwischen Oktober und März statt und werden als lockere, etwa 20- bis 30-minütige Telefonate auf Englisch gestaltet. Die Themen für die Gespräche können frei gewählt werden. Im Anschluss wird ein Auswertungsbogen ausgefüllt. Die Oral English Tests lassen sich sehr individuell planen, du kannst selbst einen Termin für das Gespräch mit den Austauschschüler*innen vereinbaren und kannst so dein Engagement für dich passend planen. Hast du Lust, uns bei den Oral English Tests zu unterstützen und mit ein paar zukünftigen Austauschschüler*innen interessante Gespräche zu führen? Dann melde dich unter usa@yfu.de bei Lisa – ich freue mich, von dir zu hören!

*Gesucht: Leitung für Winter-Re-Entry*

Für das Re-Entry-Seminar unserer ca. 20 Winter- und Semesterschüler*innen suchen wir noch ein Leitungsteam. 📅 5.-7. Dezember 2025 📍 Jugendherberge Kassel

Hast du Zeit und Lust? Dann melde dich bei Doro unter ap-seminare@yfu.de

*Orientierungsworkshop (OWO-)Leitung gesucht*

Du möchtest im Januar unsere neuen Winterschüler*innen begrüßen und hast Lust das once again neue OWO-Konzept auszutesten? Für die Winter-OWO werden noch eine Leitung und Teamende gesucht.

📅 25.-29. Januar 2026 – Die ca. 20 Schüler*innen reisen einen Tag später an

👉 Meldet euch, egal ob mit oder ohne Erfahrung!

📍 Jugendherberge Wiesbaden

📧 Kontakt: Sophia (ap-seminare@yfu.de)

*Leitungen und Teamende für Mittelseminare 2026 gesucht 🔎*

Nach dem Seminar ist vor dem Seminar! 🎉 Ganz nach diesem Motto planen wir nach dem OWO-Sommer nun den Mittelseminar-Winter ☃️ und suchen nun die ersten Leitungen für die Mittelseminare. Du hast im Februar/März 2026 noch nichts vor und hast Lust auf Berlin/München/Hamburg und natürlich viele tolle ATS? Dann melde dich bei Sophia (📧 ap-seminare@yfu.de)! Du möchtest (noch) nicht leiten, hast aber Interesse an einem Teamplatz? Auch Teammeldungen nehme ich gerne schon entgegen. Fülle einfach diese [[https://eur05.safelinks.protection.outlook.com/?url=https%3A%2F%2Fforms.office.com%2FPages%2FResponsePage.aspx%3Fid%3DOqhNyXAcyk-Cu3mnrCJZh6KOYPtMfppBhidNFBnWvdtUQjVZVjZVV0NQSDdDTTI1NDVUM0pOTDBMSS4u&data=05%7C02%7Chh-newsletter%40yfu-deutschland.de%7C60dcf565840a4d8e6f3f08de115a7d3a%7C3496a242cb5040ae9566623507dd3c89%7C0%7C0%7C638967277521659932%7CUnknown%7CTWFpbGZsb3d8eyJFbXB0eU1hcGkiOnRydWUsIlYiOiIwLjAuMDAwMCIsIlAiOiJXaW4zMiIsIkFOIjoiTWFpbCIsIldUIjoyfQ%3D%3D%7C0%7C%7C%7C&sdata=4QIovIvGu26R49P1TPL3k%2FpM0Yjb5u3Mjkk90VPiz04%3D&reserved=0][Umfrage]] aus.

|            | Wann (meint Teamanreise) | Wo                                    |
| MS 1 Nord | 20.-25. Februar 2026       | Jugendbildungsstätte Kaubstr., Berlin     |
| MS 1 Süd  | 22.-27. Februar 2026       | Jugendherberge Possenhofen (b. München) |
| MS 2 Nord | 25. Februar-02. März 2026  | Jugendbildungsstätte Kaubstr., Berlin     |
| MS 2 Süd  | 27. Februar-04. März 2026  | Jugendherberge Possenhofen (b. München) |
| MS 3 Nord | 03.-07. März 2026         | Jugendbildungsstätte Kaubstr., Berlin     |
| MS 3 Süd  | 08.-13. März 2026         | Jugendherberge Possenhofen (b. München) |
| MS PPP   | 07.-13. Februar 2026       | Jugendherberge Hamburg                |

*22. und 23.11.2025: Auswahl-Mitglied für USA FOR YOU in Hamburg gesucht*

Im Frühjahr 26 startet wieder eine Gruppe von 15 Jugendlichen aus Hamburg mit einem Vollstipendium in zwei aufregende Wochen in den USA und damit wir aus den Bewerbungen eine tolle Gruppe zusammenstellen können, brauchen wir noch ein erfahrenes Auswahl-Team-Mitglied (KLT-/Auswahl-Erfahrung notwendig). Ihr solltet an beiden Tagen präsent sein. Reisekosten und Unterkunft werden nach Rücksprache erstattet. Meldet euch bei Thekla: usaforyou@yfu.de oder mit der Durchwahl -77

*Teamende für PPP-Auswahlen gesucht*

Für die PPP-Auswahlen suchen wir noch Teamende mit und ohne Erfahrung in ganz Deutschland! Die Auswahlen für das PPP (ein Austauschstipendium) sind ähnlich wie Kennenlerntreffen, aber in Präsenz, intensiver und in jedem Fall sehr spannend. Es ist bestimmt auch eine in Deiner Nähe dabei! :) die Termine findest Du in der Umfrage: [[https://eur05.safelinks.protection.outlook.com/?url=https%3A%2F%2Ftinyurl.com%2FPPP-AW2025&data=05%7C02%7Chh-newsletter%40yfu-deutschland.de%7C60dcf565840a4d8e6f3f08de115a7d3a%7C3496a242cb5040ae9566623507dd3c89%7C0%7C0%7C638967277521693808%7CUnknown%7CTWFpbGZsb3d8eyJFbXB0eU1hcGkiOnRydWUsIlYiOiIwLjAuMDAwMCIsIlAiOiJXaW4zMiIsIkFOIjoiTWFpbCIsIldUIjoyfQ%3D%3D%7C0%7C%7C%7C&sdata=KZ8VTCWnYPS2nbS5AVk5FuDrdhJ2qDa2I9AFtoXPmR8%3D&reserved=0][PPP-Auswahlen 2025]]

Aktuell suchen wir vor allem für Merzenich (08.11.) und Duisburg (01.+02.11.) noch dringend Teamende!
Bei Interesse oder Fragen melde Dich bitte bei Kim (herzog@yfu.de) oder fülle unverbindlich die Umfrage aus. Danke!

** Schulungen & Termine
*Colored Glasses Schulung für neue Ehrenamtliche am 14.-16. November in München – Bis zum 02. November anmelden!*

Mit Colored Glasses Workshops begeistern wir Kinder und Jugendliche der 5. bis 13. Klasse an Schulen und Jugendeinrichtungen in ganz Deutschland für Vielfalt und Toleranz. Wir machen uns stark gegen Diskriminierung und Vorurteile durch spannende Simulationen und Diskussionen auf Augenhöhe! Die Schulung ist dein Start ins Ehrenamt: Wir zeigen dir, wie du einen Workshop planst und durchführst. Du bekommst alle Materialien, um mehr zum Thema zu lernen. Erfahrene Ehrenamtliche geben dir Tipps und Tricks, damit du auch ohne Vorerfahrung einen echten Unterschied machen kannst. Du bist zwischen 16 und 29 Jahre alt und willst aktiv werden? Melde dich jetzt zur kostenlosen Schulung am 14.-16. November in der Jugendherberge München Park hier an: https://forms.office.com/e/rknVP4dYxn. Bei Fragen wenden dich gerne an Nina unter roesch@yfu.de.

** Externes
*🔎 Deutsch-Türkische Jugendbrücke sucht Projektmanager*in schulischer und beruflicher Austausch (m/w/d)*

Die Deutsch-Türkische Jugendbrücke stellt zum nächstmöglichen Zeitpunkt eine/n Projektmanager*in für den Bereich schulischer und beruflicher Austausch ein. Die Stelle kann in Vollzeit oder Teilzeit mit mind. 32 Wochenstunden besetzt werden und bietet die Möglichkeit, bis zu drei Tage in der Woche aus dem Homeoffice zu arbeiten. Was dich erwartet: Weiterentwicklung des deutsch-türkischen schulischen und beruflichen Austauschs, Management von Förderprojekten (vom Konzept bis zur Evaluation), Planung von Fortbildungen und Veranstaltungen.  Was sie dir bieten: einen Job mit Sinn, Mitgestaltungsmöglichkeiten, faire Bezahlung, flexibles Arbeiten und ein tatkräftiges Team. Was du mitbringst: relevanten Hochschulabschluss, Berufserfahrung in der (interkulturellen) Arbeit mit Jugendlichen, Projektmanagement- und Controlling-Skills, gute Deutsch- und Englischkenntnisse. Bewerbung bis zum 17.11.2025. Hier geht’s zur [[https://eur05.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.jugendbruecke.de%2Fjobs%2Fprojektmanager-schulischer-beruflicher-austausch%2F&data=05%7C02%7Chh-newsletter%40yfu-deutschland.de%7C60dcf565840a4d8e6f3f08de115a7d3a%7C3496a242cb5040ae9566623507dd3c89%7C0%7C0%7C638967277521731000%7CUnknown%7CTWFpbGZsb3d8eyJFbXB0eU1hcGkiOnRydWUsIlYiOiIwLjAuMDAwMCIsIlAiOiJXaW4zMiIsIkFOIjoiTWFpbCIsIldUIjoyfQ%3D%3D%7C0%7C%7C%7C&sdata=eSDNJNVKCW9Y8getqku4CIBZIZVYYHj6qZCV6dsUFCM%3D&reserved=0][Ausschreibung]].
* Terminübersicht
** TERMINE 2025
*14.11. - 16.11.2025* &nbsp;&nbsp;&nbsp; Gremiensitzung, Hamburg
*14.11. - 16.11.2025* &nbsp;&nbsp;&nbsp; Colored Glasses Schulung, München

*21.11. - 23.11.2025* &nbsp;&nbsp;&nbsp; Betreuendenseminar, Fulda

*28.11. - 30.11.2025* &nbsp;&nbsp;&nbsp; Teamingeinweisung, Kassel

*28.11. - 30.11.2025* &nbsp;&nbsp;&nbsp; ÖA-Ausschuss-Wochenende, Hamburg 
