* Landesgruppe
**  Wichtige Info Aufrufe Newsletter
Diesen Newsletter findet ihr ab jetzt auch auf Whatsapp! Dafür einfach über diesen Link beitreten: https://chat.whatsapp.com/GBCBuLIU2U78zpim5yGxLF
---

Sehr gerne nehmen wir eure Aufrufe oder Danksagungen in den wöchentlichen Newsletter auf.

Schreibt mir (shh-newsletter@yfu-deutschland.de) dafür einfach immer bis *Mittwochs 12:00 Uhr* eure Aufrufe, damit ich sie noch in den Newsletter der aktuellen Woche mit aufnehmen kann. Ansonsten nehme ich die Aufrufe natürlich gerne in den nächsten auf.

Vielen lieben Dank und ich freue mich auf eure Emails.

Liebe Grüße
Aimo
** Weihnachtliches Communitea mit ATS
Liebe Community,
wir haben News! 🎄✨

wir möchten euch herzlich zu einem weihnachtlichen Communitea-Treffen einladen. Gemeinsam wollen wir zusammen mit den Austauschschüler*innen das Jahr ausklingen lassen. 

📅 *Wann? 20. Dezember, um 11 Uhr*
📍 *Wo? Geschäftsstelle*

Wir bereiten gemeinsamen Punsch zu und basteln Weihnachtssterne. Wer möchte, kann gern Kekse oder andere kleine Snacks zum Teilen mitbringen.

Wenn ihr dabei seid, meldet euch bitte [[https://forms.office.com/Pages/ResponsePage.aspx?id=QqKWNFDLrkCVZmI1B908iRyBOzkwWXZFoqlrTkGPt6NUOVZYVUFXWThPOVFPTDVESUVMMTZVS08xNC4u][hier]] kurz an. 
Wir freuen uns auf euch und auf ein gemütliches Treffen zum Jahresabschluss!

Liebe Grüße
Leah, Aimo und Ole
** Seminarleitungsschulung (SLS) 2026: Vom 30. Januar bis 1. Februar 2026 in Hamburg – sei dabei! 💪

Du hast Erfahrung als Teamer*in gesammelt, fühlst dich methodisch fit und suchst nach der nächsten Herausforderung? Du wünschst dir eine gute Vorbereitung auf die Rolle als Seminarleitung oder noch mehr Sicherheit, bevor du die erste oder eine weitere Leitung übernimmst? Dann ist die Seminarleitungsschulung (SLS) in Hamburg genau das Richtige für dich. 🚀

In dieser Schulung wird es um die Basics gehen, die du als Seminarleitung kennen solltest sowie eine Vertiefung dieses Wissens. Du lernst, welche Verantwortung bei dir als Leitung liegt, worauf du achten solltest und wie du für ein gutes Teamwork sorgst.

[[https://eur05.safelinks.protection.outlook.com/?url=https%3A%2F%2Fforms.office.com%2Fe%2Fk57ZeStKUB&data=05%7C02%7Cshh-newsletter%40yfu-deutschland.de%7C8e659064ec854e96526e08de370d7b08%7C3496a242cb5040ae9566623507dd3c89%7C0%7C0%7C639008728190782834%7CUnknown%7CTWFpbGZsb3d8eyJFbXB0eU1hcGkiOnRydWUsIlYiOiIwLjAuMDAwMCIsIlAiOiJXaW4zMiIsIkFOIjoiTWFpbCIsIldUIjoyfQ%3D%3D%7C0%7C%7C%7C&sdata=ALMq6UlEIOS6TkCINdhnELobhxNMQRIfZ2EvFQI35h8%3D&reserved=0][Melde dich gleich an!]]

Mehr Infos findest du in der Anmelde-Abfrage. Bei weiteren Fragen kontaktiere Rahel aus der GS ([[mailto://ehrenamt@yfu.de][ehrenamt@yfu.de]], Durchwahl -44). (Hinweis: Ein Angebot für erfahrenere Leitungen wird es Anfang Oktober 2026 geben.)
* Externes und Überregionales
** Mitarbeiter-Gesuche/Stellen 
*Stellenausschreibungen für das Team Entsendeprogramm in der Geschäftsstelle:*

Es stehen Veränderungen in unserem Team an. Aus diesem Grund haben wir freie Stellen zu besetzen: Falls auch bei dir Veränderungen anstehen und du für 2026 auf Jobssuche bist, schaue dir doch bitte unsere Ausschreibungen auf unserer Website an: https://www.yfu.de/ueber-yfu/jobs-praktika

Wenn du Fragen hast, melde dich gern bei Meike (neumann@yfu.de), Simone (held@yfu.de) oder Miriam (bruns@yfu.de).

*Das Ehrenamtliche Cloud Adminteam sucht nach Unterstützung*

YFU-Ehrenamt ohne Mailsystem ist in vielen Fällen nicht mehr wegzudenken. Mit der Erweiterung der Systeme durch aktuelle Zwänge benötigen das Cloud Adminteam mit seinen Teilgruppen Microsoft 365 und Google Workspace tatkräftige Unterstützung im Bereich Support/Nutzerbetreuung und Konzeption. Zusätzlich ist auch Unterstützung des Leiters Cloud Adminteam von großem Bedarf. Wir freuen uns über Meldungen. Gefragt ist jede:r mit Interesse oder schon vorhandenem technischem Wissen und Lernfreude an solchen Systemen, bevor man damit irgendwann im Berufsleben arbeiten muss. Die Ausschreibung für die Unterstützung des Leiters findest Du [[https://eur05.safelinks.protection.outlook.com/?url=https%3A%2F%2Fintranet.yfu.de%2Fdownloads%2Ffiles%2F3813&data=05%7C02%7Chh-newsletter%40yfu-deutschland.de%7C5d58651c249749b5318008de3d53a156%7C3496a242cb5040ae9566623507dd3c89%7C0%7C0%7C639015626586879853%7CUnknown%7CTWFpbGZsb3d8eyJFbXB0eU1hcGkiOnRydWUsIlYiOiIwLjAuMDAwMCIsIlAiOiJXaW4zMiIsIkFOIjoiTWFpbCIsIldUIjoyfQ%3D%3D%7C0%7C%7C%7C&sdata=VV1Fsp3Adh9ZQBWEkpy7FBv3y0s2ZCxEEqntiF%2F0AoU%3D&reserved=0][hier]], die Ausschreibung für die Teilgruppe Microsoft 365 [[https://eur05.safelinks.protection.outlook.com/?url=https%3A%2F%2Fintranet.yfu.de%2Fdownloads%2Ffiles%2F3513&data=05%7C02%7Chh-newsletter%40yfu-deutschland.de%7C5d58651c249749b5318008de3d53a156%7C3496a242cb5040ae9566623507dd3c89%7C0%7C0%7C639015626586889984%7CUnknown%7CTWFpbGZsb3d8eyJFbXB0eU1hcGkiOnRydWUsIlYiOiIwLjAuMDAwMCIsIlAiOiJXaW4zMiIsIkFOIjoiTWFpbCIsIldUIjoyfQ%3D%3D%7C0%7C%7C%7C&sdata=gOnYMiI0EJOXyZdbo3rCcB8DiaZa%2FZIB1ox01zC%2FOuw%3D&reserved=0][hier]] und für die neue Teilgruppe Google Workspace [[https://eur05.safelinks.protection.outlook.com/?url=https%3A%2F%2Fintranet.yfu.de%2Fdownloads%2Ffiles%2F3841&data=05%7C02%7Chh-newsletter%40yfu-deutschland.de%7C5d58651c249749b5318008de3d53a156%7C3496a242cb5040ae9566623507dd3c89%7C0%7C0%7C639015626586901770%7CUnknown%7CTWFpbGZsb3d8eyJFbXB0eU1hcGkiOnRydWUsIlYiOiIwLjAuMDAwMCIsIlAiOiJXaW4zMiIsIkFOIjoiTWFpbCIsIldUIjoyfQ%3D%3D%7C0%7C%7C%7C&sdata=TS0SWSd%2F4Z79MT9ldxJnU8N%2FKAU%2Bc3dAZxkWWBJ51Uw%3D&reserved=0][hier]]

*Colored Glasses Schulungen 2026 und Umfrage zu CG-Kurzschulung für YFU-Aktive*

Mit Colored Glasses (CG) Workshops begeistern wir Kinder und Jugendliche der 5. bis 13. Klasse an Schulen und Jugendeinrichtungen in ganz Deutschland für Vielfalt und Toleranz. Wir machen uns stark gegen Diskriminierung und Vorurteile durch spannende Simulationen und Diskussionen auf Augenhöhe! Die Schulung ist dein Start ins Ehrenamt: Wir zeigen dir, wie du einen Workshop planst und durchführst und erfahrene Ehrenamtliche geben dir Tipps und Tricks, damit du auch ohne Vorerfahrung einen echten Unterschied machen kannst. Merk dir schon jetzt die Schulungstermine 2026 vor und schreib uns an coloredglasses@yfu.de, um ein Update zu bekommen, wenn die Anmeldung möglich ist: 27. Feb. -01. März Jugendherberge Leipzig [[https://eur05.safelinks.protection.outlook.com/?url=https%3A%2F%2Fforms.office.com%2Fe%2FTyhKWXdhuY&data=05%7C02%7Chh-newsletter%40yfu-deutschland.de%7C5d58651c249749b5318008de3d53a156%7C3496a242cb5040ae9566623507dd3c89%7C0%7C0%7C639015626586913002%7CUnknown%7CTWFpbGZsb3d8eyJFbXB0eU1hcGkiOnRydWUsIlYiOiIwLjAuMDAwMCIsIlAiOiJXaW4zMiIsIkFOIjoiTWFpbCIsIldUIjoyfQ%3D%3D%7C0%7C%7C%7C&sdata=B81xPkjsQDQqBjtgS1ZFvj3n2HBb5p%2BDmAEceg5eeCw%3D&reserved=0][Anmeldung]] hier | 15.-17. Mai Jugendherberge Burg Schwaneck (bei München) | 20./21. Juni Liebfrauenschule Mühlhausen (bei Duisburg) | 18.-20. Sept. 2026 Jugendherberge Horner Rennbahn Hamburg | 06.-08. Nov. Jugendherberge Kassel
- Du bist YFU-Ehrenamtliche*r, bringst bereits Teaming-Erfahrung mit und hast Lust auf Colored Glasses? Füll jetzt die Umfrage zu CG-Kurzschulungsformaten aus, damit wir 2026 ein passendes Angebot für dich gestalten können: [[https://eur05.safelinks.protection.outlook.com/?url=https%3A%2F%2Fforms.office.com%2Fe%2F142QZB212a&data=05%7C02%7Chh-newsletter%40yfu-deutschland.de%7C5d58651c249749b5318008de3d53a156%7C3496a242cb5040ae9566623507dd3c89%7C0%7C0%7C639015626586923318%7CUnknown%7CTWFpbGZsb3d8eyJFbXB0eU1hcGkiOnRydWUsIlYiOiIwLjAuMDAwMCIsIlAiOiJXaW4zMiIsIkFOIjoiTWFpbCIsIldUIjoyfQ%3D%3D%7C0%7C%7C%7C&sdata=VYXs2z8snDVEaIgYmCZAKwXPKKu2n%2Ftz%2F3FVYL8QTaE%3D&reserved=0][Colored Glasses Schulung für YFU-Aktive – Formular ausfüllen]]

*Leitungen und Teamer*innen für VBTs 2026 gesucht*
- Du hast Lust, 2026 eine VBT zu teamen oder zu leiten?
- Dann trage dich jetzt in den Leitungs- und Team-Survey ein (verfügbar bis zum 05.01.2026):
- [[https://eur05.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.yfu-survey.org%2Fpoll%2Findex.php%2F176719%3Flang%3Dde-informal&data=05%7C02%7Chh-newsletter%40yfu-deutschland.de%7C5d58651c249749b5318008de3d53a156%7C3496a242cb5040ae9566623507dd3c89%7C0%7C0%7C639015626586933201%7CUnknown%7CTWFpbGZsb3d8eyJFbXB0eU1hcGkiOnRydWUsIlYiOiIwLjAuMDAwMCIsIlAiOiJXaW4zMiIsIkFOIjoiTWFpbCIsIldUIjoyfQ%3D%3D%7C0%7C%7C%7C&sdata=HtMtWNjaCRGbmrmyo6UcA08M6x8oQEFwEx80DB%2Bz1lc%3D&reserved=0][VBT-Saison 2026 Leitungs- und Teamsuche]]
- Bei Fragen erreichst du Fenja unter vbt@yfu.de

*⛄ Weihnachts-Feuerwehr-Familien gesucht! ⛄*

Das Jahr neigt sich dem Ende zu und wir stehen erneut vor vielen kurzfristigen Familienwechseln. Besonders über die Feiertage benötigen wir dringend Ersatz- und Übergangsfamilien für Austauschschüler*innen.
Kennt ihr Familien – oder habt ihr selbst Kapazität –, die über die Feiertage aufnehmen können? Aktuell fehlen uns noch einige Familien, die über die Feiertage unterstützen können.
Dann meldet euch bitte mit dem möglichen Zeitraum unter gastfamilien@yfu.de.
Vielen Dank für eure Unterstützung und eine schöne Vorweihnachtszeit! 🎄

*Teamende für Mittelseminare 2026 gesucht 🔎*

Die Mittelseminare stehen bevor und wir starten voller Energie in die Planungsvorbereitungen☃️ dafür suchen wir aktuell noch Leitungen und Teamende, v. a. für das MS 1 Nord in Berlin. Du hast im Februar/März 2026 noch nichts vor und hast Lust auf Berlin/München/Hamburg und natürlich viele tolle ATS? Dann melde dich bei Sophia (📧 ap-seminare@yfu.de) oder fülle einfach diese [[https://eur05.safelinks.protection.outlook.com/?url=https%3A%2F%2Fforms.office.com%2FPages%2FResponsePage.aspx%3Fid%3DOqhNyXAcyk-Cu3mnrCJZh6KOYPtMfppBhidNFBnWvdtUQjVZVjZVV0NQSDdDTTI1NDVUM0pOTDBMSS4u&data=05%7C02%7Chh-newsletter%40yfu-deutschland.de%7C5d58651c249749b5318008de3d53a156%7C3496a242cb5040ae9566623507dd3c89%7C0%7C0%7C639015626586943209%7CUnknown%7CTWFpbGZsb3d8eyJFbXB0eU1hcGkiOnRydWUsIlYiOiIwLjAuMDAwMCIsIlAiOiJXaW4zMiIsIkFOIjoiTWFpbCIsIldUIjoyfQ%3D%3D%7C0%7C%7C%7C&sdata=phPyrnBOvojYC%2BOSIkxJhmf7nTzh6Ye4heaIMrVOdnc%3D&reserved=0][Umfrage]] aus.
|            | Wann (meint Teamanreise) | Wo                                    | Wer                       |
| MS 1 Nord | 20.-25. Februar 2026       | Jugendbildungsstätte Kaubstr., Berlin     | Ideal: (Männlich &) erfahren |
| MS 1 Süd  | 22.-27. Februar 2026       | Jugendherberge Possenhofen (b. München) | Teamende                 |
| MS 3 Nord | 02.-07. März 2026         | Jugendbildungsstätte Kaubstr., Berlin     | Co-Leitung                 |
| MS PPP   | 07.-13. Februar 2026       | Jugendherberge Hamburg                | Teammitglied              |

*Männliche USA for you-Programmbegleitung gesucht*

Unsere Programmbegleitung hat aus beruflichen Gründen abgesagt und wir suchen dringend Ersatz. Du verbringst zwei Frühjahrswochen in Georgia mit 15 optimal von dir vorbereiten Jugendlichen aus Hamburg, die Lust haben, die Welt kennenzulernen.  Du solltest mind. 21 Jahre alt sein und zu den in der Ausschreibung genannten Terminen Zeit haben. Es ist keine Voraussetzung, dass du aus Hamburg oder Umgebung kommst - Ehrenamtliche aller Landesgruppen sind willkommen! 

Die Ausschreibung findest du hier: [[https://eur05.safelinks.protection.outlook.com/?url=https%3A%2F%2Fintranet.yfu.de%2Farticle_tool%2Farticles%2F2213&data=05%7C02%7Chh-newsletter%40yfu-deutschland.de%7C5d58651c249749b5318008de3d53a156%7C3496a242cb5040ae9566623507dd3c89%7C0%7C0%7C639015626586953111%7CUnknown%7CTWFpbGZsb3d8eyJFbXB0eU1hcGkiOnRydWUsIlYiOiIwLjAuMDAwMCIsIlAiOiJXaW4zMiIsIkFOIjoiTWFpbCIsIldUIjoyfQ%3D%3D%7C0%7C%7C%7C&sdata=V2BRjKuzXa7cOsdEiECjtd1SwlJowQ5yArCQ9NNrO5w%3D&reserved=0][Deutsches Youth For Understanding Komitee e.V. - Intranet]] Interesse oder Fragen? Dann schnell melden bei Thekla unter usaforyou@yfu.de oder Durchwahl -77

*Werde Teamer*in für USA for you-Tagungen in Hamburg*

15 sehr motivierte Jugendliche von Hamburger Statteilschulen fliegen im Frühjahr für zwei Wochen in die USA, um sich dort ehrenamtlich zu engagieren und die Welt aus einer anderen Perspektive kennenzulernen. Damit sie optimal vor- und nachbereitet werden, suchen wir noch eine*n Teamer*in für dieses ganz besondere YFU-Kurzprogramm. Getagt wird vom 13.-15.02. und vom 08.-10.05.2026 in Hamburg. Es ist keine Voraussetzung, dass du aus Hamburg kommst. 

Melde dich bei Interesse oder Fragen bei Thekla: usaforyou@yfu.de oder Durchwahl -77
** Schulungen
*Seminarleitungsschulung (SLS) 2026: Vom 30. Januar bis 1. Februar 2026 in Hamburg – sei dabei! 💪*
Du hast Erfahrung als Teamer*in gesammelt, fühlst dich methodisch fit und suchst nach der nächsten Herausforderung? Du wünschst dir eine gute Vorbereitung auf die Rolle als Seminarleitung oder noch mehr Sicherheit, bevor du die erste oder eine weitere Leitung übernimmst? Dann ist die Seminarleitungsschulung (SLS) in Hamburg genau das Richtige für dich. 🚀 In dieser Schulung wird es um die Basics gehen, die du als Seminarleitung kennen solltest sowie eine Vertiefung dieses Wissens. Du lernst, welche Verantwortung bei dir als Leitung liegt, worauf du achten solltest und wie du für ein gutes Teamwork sorgst. [[https://eur05.safelinks.protection.outlook.com/?url=https%3A%2F%2Fforms.office.com%2Fe%2Fk57ZeStKUB&data=05%7C02%7Chh-newsletter%40yfu-deutschland.de%7C5d58651c249749b5318008de3d53a156%7C3496a242cb5040ae9566623507dd3c89%7C0%7C0%7C639015626586963478%7CUnknown%7CTWFpbGZsb3d8eyJFbXB0eU1hcGkiOnRydWUsIlYiOiIwLjAuMDAwMCIsIlAiOiJXaW4zMiIsIkFOIjoiTWFpbCIsIldUIjoyfQ%3D%3D%7C0%7C%7C%7C&sdata=n3IUqJZNO8%2FFGw16BmuC0TJ3dADA2NYL2qjQdQSPMJY%3D&reserved=0][Melde dich gleich an!]] Mehr Infos findest du in der Anmelde-Abfrage. Bei weiteren Fragen kontaktiere Rahel aus der GS (ehrenamt@yfu.de, Durchwahl -44). (Hinweis: Ein Angebot für erfahrenere Leitungen wird es Anfang Oktober 2026 geben.)

*Betreuungsluft schnuppern? Jetzt zum Betreuendenseminar anmelden!*

Auf unserem Betreuendenseminar erfahrt ihr mehr über die Betreuungsarbeit allgemein und grundlegende Gesprächstechniken, die Betreuende benutzen, um Austauschschüler*innen und Gasteltern bei der Lösung von Problemen zu helfen. Es gibt Input und Übungen zu Aktivem Zuhören, Gezieltem Fragen, dem Herausarbeiten konstruktiver Ansätze, der Beobachtung und Interpretation von Kommunikationsverhalten sowie der Strukturierung eines Gespräches. Auch Besuche und Berichte werden Thema sein. Wir freuen uns auf euch! 

📅     27.-29.03.2026
📍     Präsenz in Bad Bevensen
✅     Anmeldung: https://forms.office.com/e/V0aaLhtjrM
** Sonstiges / Externes
*📣 SAY YES TO THE YES 2026 – bewirb dich bis zum 15. Januar!🤩*

Ehrenamtliche aufgepasst! Vom 22. bis 26. Juni 2026 findet wieder das berühmte Youth Empowerment Seminar (YES) am Werbellinsee in Brandenburg statt – und du kannst als eine*r von 100 Ehrenamtlichen dabei sein!
✨Einmal im Jahr treffen sich hunderte Austauschschüler*innen zum Abschluss ihres Jahres beim YES, um ihren Austausch zu feiern, gemeinsam zu lernen und Spaß zu haben. Als YFU-Volunteer gestaltest du das einwöchige Event aktiv mit, z.B. als Spirit Coordinator, Freestyler, Counselor, Group Leader ...
🤝 Dabei triffst du viele Internationals, lernst neue Skills und kannst deine Erfahrungen weitergeben.
💸 Reisekosten und Unterkunft werden bezahlt.
❗Bewerbungsfrist ist der 15. Januar 2026
✍ Hier findest du alle Infos zu den Rollen und Link zur Bewerbung: https://www.yfu-yes.org/volunteer-2wave2026

Du hast Fragen? Das YES-Team die Antworten: yes.info@yfu.world!

*25-jähriges Jubiläum von Colored Glasses in Deutschland – jetzt zur Social Media Aktion 2026 beitragen!*

Unglaublich, aber wahr: 2026 feiert Colored Glasses in Deutschland bereits 25-jähriges Jubiläum! In diesem Vierteljahrhundert haben wir gemeinsam über 1.500 Workshops umgesetzt und über 31.000 Kinder und Jugendliche für Vielfalt und Toleranz begeistert. Aus der Fülle dieser Erlebnisse wollen wir zum Jubiläum eure Geschichten hören, Colored Glasses viele Gesichter geben und unsere gemeinsame Begeisterung mit allen Unterstützer*innen auf Social Media teilen. Sei dabei! Das CG-Marketing-Team sammelt deine Highlights, Gedanken und Glückwünsche als Selfie-Video und editiert daraus Beiträge für unsere Social-Media-Kanäle. Eine Schritt-für-Schritt-Anleitung, Leitfragen und kurze Videos, wie das ganze aussehen kann, findest du hier: [[https://eur05.safelinks.protection.outlook.com/ap/b-59584e83/?url=https%3A%2F%2Fyfudtl.sharepoint.com%2F%3Ab%3A%2Ft%2Fcg-koordination%2FIQArYjy-tziDRo_UIwVCbBMOAe1-NtAmxR2rzN0fQIv1RjI%3Fe%3D7DIlK4&data=05%7C02%7Chh-newsletter%40yfu-deutschland.de%7C5d58651c249749b5318008de3d53a156%7C3496a242cb5040ae9566623507dd3c89%7C0%7C0%7C639015626586993148%7CUnknown%7CTWFpbGZsb3d8eyJFbXB0eU1hcGkiOnRydWUsIlYiOiIwLjAuMDAwMCIsIlAiOiJXaW4zMiIsIkFOIjoiTWFpbCIsIldUIjoyfQ%3D%3D%7C0%7C%7C%7C&sdata=8h2JfAFD1QhtwNKat1Ovf%2BcfSBR8Y56vnQCoLdBVr5o%3D&reserved=0][MITMACHAKTION 25 Jahre Colored Glasses (GER🇩🇪).pdf]]. Teile diesen Aufruf mit (ehemaligen) Colored Glasses Brückenbauer*innen, die unbedingt dabei sein sollten und diese Nachricht vielleicht nicht lesen.

*Colored Glasses Strategie 2027 – Update zu Erfolgen und Schwerpunktregionen*

Vor einem Jahr ist die Colored Glasses Strategie 2027 gestartet, mit der wir uns strategische Ziele gesetzt haben, um das Programm in Qualität, Wirkung und Reichweite richtig gut aufzustellen. 2025 war bereits voller Erfolge – von motivierenden T-Shirts für CG-Aktive, über ein Update für die CG-Webseite bis hin zur Verleihung des PHINEO Wirkt Siegels. Auch der Fokus auf die Schwerpunktregionen Großraum Hamburg, Großraum München, Mitteldeutschland und Rhein-Ruhr hat sich bewährt. Unter anderem konnten bei Schulungen in den Schwerpunktregionen 49 neue Ehrenamtliche ausgebildet werden, eine Kooperation mit dem Pädagogischen Institut München wurde pilotiert und eine Kooperation mit der Universität Köln ist in den Startlöchern. Ausführlichere Infos gibt’s hier und hier. 2026 setzen wir die Arbeit mit der Strategie fort. Während der Fokus für Entwicklungsvorhaben bis auf weiteres bei den Schwerpunktregionen bleibt, bieten wir weiterhin abhängig von den Verfügbarkeiten der CG-Ehrenamtlichen Toleranzworkshops bundesweit an. Alle Rückfragen beantwortet Nina unter roesch@yfu.de gerne.

*Instagram: Bitte kommentieren*

Aktuell erleben wir bei Instagram einen starken Reichweiten-Rückgang. Damit sind wir nicht alleine: Es scheint, als ob Accounts zu Themen wie Demokratie, Vielfalt, Gleichberechtigung u.ä. eingeschränkt werden (omasgegenrechts sind z.B. auch enorm betroffen). Um dem entgegenzutreten, brauchen wir jetzt sehr viel Interaktion. Es wäre super, wenn ihr (gerne auch häufiger) einen Kommentar unter irgendeinem Post (oder auch mehreren Posts) hinterlassen könntet. Es reicht ein kurzer Kommentar, Hauptsache ihr sagt etwas Positives ("Tolles Projekt", "Das habe ich auch gemacht, es war super", "Finde ich richtig cool" oder was auch immer euch einfällt - positive Wörter zeigen dem Algorithmus, dass unsere Seite relevant ist). Ihr müsst dafür übrigens nicht unserer Seite folgen (könnt ihr aber natürlich). DANKE für eure Unterstützung!
* Terminübersicht
** TERMINE 2025
*30.01. - 02.02.2026* &nbsp;&nbsp;&nbsp; Seminarleitungsschulung (SLS)

*31.01. - 01.02.2026* &nbsp;&nbsp;&nbsp; *(LG)* Referent*innen/ Landesgruppenwochenende in Kiel (Anmeldung für alle offen)

*27.02. - 01.03.2026* &nbsp;&nbsp;&nbsp; Jugendherberge Leipzig

*20.03. - 22.03.2026* &nbsp;&nbsp;&nbsp; Gremiensitzung Frühjahr

*15.05. - 17.05.2026* &nbsp;&nbsp;&nbsp; Jugendherberge Burg Schwaneck (bei München)

*29.05 - 31.05.2026* &nbsp;&nbsp;&nbsp; ÖA-Ausschusstreffen

*05.06. - 07.06.2026* &nbsp;&nbsp;&nbsp; *(LG)* Nord-LGT

*20.06. - 21.06.2026* &nbsp;&nbsp;&nbsp; Liebfrauenschule Mühlhausen (bei Duisburg)

*18.09. -20.09. 2026* &nbsp;&nbsp;&nbsp; Jugendherberge Horner Rennbahn Hamburg

*25.09. - 27.09.2026* &nbsp;&nbsp;&nbsp; *(LG)* Aktivenwochenende

*06.11. – 08.11.2026* &nbsp;&nbsp;&nbsp; Jugendherberge Kassel

*27.11. - 29.11.2026* &nbsp;&nbsp;&nbsp; ÖA-Ausschusstreffen
