* Landesgruppe
**  Wichtige Info Aufrufe Newsletter
Diesen Newsletter findet ihr ab jetzt auch auf Whatsapp! Dafür einfach über diesen Link beitreten: https://chat.whatsapp.com/GBCBuLIU2U78zpim5yGxLF
---

Sehr gerne nehmen wir eure Aufrufe oder Danksagungen in den wöchentlichen Newsletter auf.

Schreibt mir (shh-newsletter@yfu-deutschland.de) dafür einfach immer bis *Mittwochs 12:00 Uhr* eure Aufrufe, damit ich sie noch in den Newsletter der aktuellen Woche mit aufnehmen kann. Ansonsten nehme ich die Aufrufe natürlich gerne in den nächsten auf.

Vielen lieben Dank und ich freue mich auf eure Emails.

Liebe Grüße
Aimo
** SAVE THE DATE: 06.12.2025 Landesversammlung 
Liebe Landesgruppe,

das Jahr 2025 neigt sich dem Ende zu und wir wollen als Landesgruppe gerne gemeinsam Revue passieren lassen, was alles so los war bei uns im Norden, und auf die Gestaltung des nächsten Jahres blicken.

Deswegen laden wir euch ganz herzlich ein zur *Landesversammlung am 06.12.2025 um 13 Uhr in der Geschäftsstelle (oder digital)*.

Wer mag, ist davor bereits *ab 12 Uhr* zum *gemeinsamen Mittagessen* eingeladen.

Die offizielle Einladung habt ihr wie immer noch mal separat erhalten, merkt euch also unbedingt schon mal das Datum vor, um einen spannenden Nachmittag mit Berichten aus den verschiedenen Bereichen unserer LG und die Wahlen der Satzungsämter nicht zu verpassen. Zur *Anmeldung* geht es [[https://eur05.safelinks.protection.outlook.com/?url=https%3A%2F%2Fforms.office.com%2Fe%2FwVzmNfaYu0&data=05%7C02%7Cshh-newsletter%40yfu-deutschland.de%7C9ff96f3ff3754cdb559008de1a35b284%7C3496a242cb5040ae9566623507dd3c89%7C0%7C0%7C638977015091536847%7CUnknown%7CTWFpbGZsb3d8eyJFbXB0eU1hcGkiOnRydWUsIlYiOiIwLjAuMDAwMCIsIlAiOiJXaW4zMiIsIkFOIjoiTWFpbCIsIldUIjoyfQ%3D%3D%7C0%7C%7C%7C&sdata=KBr86ul409%2Fr7DPEEMePpRx3oLC4ALYMUcJbsl9rkPs%3D&reserved=0][hier]].

Eingeladen sind alle aus der Landesgruppe SHH, von justee bis alter Hase und alle andere - denkt jedoch bitte daran, dass ihr nur als *Mitglied des Vereins* auch wählen dürft. (Geheimtipp, das [[https://eur05.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.yfu.de%2Fengagieren-und-in-verbindung-bleiben%2Fmitglied-werden&data=05%7C02%7Cshh-newsletter%40yfu-deutschland.de%7C9ff96f3ff3754cdb559008de1a35b284%7C3496a242cb5040ae9566623507dd3c89%7C0%7C0%7C638977015091559609%7CUnknown%7CTWFpbGZsb3d8eyJFbXB0eU1hcGkiOnRydWUsIlYiOiIwLjAuMDAwMCIsIlAiOiJXaW4zMiIsIkFOIjoiTWFpbCIsIldUIjoyfQ%3D%3D%7C0%7C%7C%7C&sdata=EDqCecOzuzheW1gOgAiW%2FAhahDvrccZM01EXfSxBkbc%3D&reserved=0][hier]] schnell online zu erledigen)

Falls ihr Fragen zur Landesversammlung oder zu freien Ämtern habt, meldet euch gerne bei mir ([[mailto://amilou.fehr@yfu-deutschland.de][amilou.fehr@yfu-deutschland.de]]) oder bei anderen Mitgliedern des erweiterten Landesgruppenvorstandes.

Wir freuen uns ganz dolle auf euch!! Kommt gut durch den November und bis bald!

Mit demokratischen Grüßen :)
Amilou für den erweiterten Landesgruppenvorstand 
* Öffentlichkeitsarbeit
** ÖA-Teamende für Infoabende und Schulvorträge im November gesucht!
Liebe Landesgruppe,
nach den Herbstferien stehen weitere Veranstaltungen an, für die wir noch Teamende suchen. Die Infoabende, der Schulvortrag, die Infoabende oder die Jugendbildungsmesse sind ideal für den Einstieg in die ÖA, aber auch erfahrene Teamende sind natürlich immer gern gesehen :)

*Infoabend am Coppernicus-Gymnasium*
Wann? Do, 06.11. 18:00 Uhr
Wo? Coppernicusstraße 1, 22850 Norderstedt
Wer? 1-2 erfahrene oder unerfahrene Personen für die Präsentation und Erfahrungsberichte
Lust? Melde dich bei Anouk ([[mailto://anouk.zink@yfu-deutschland.de][anouk.zink@yfu-deutschland.de]])

*Berufsmesse an der ahfs-Uhlenhorst*
Wann? Do, 13.11. 14:30 bis 18:30 Uhr (auch ein Teil der Zeit wäre schon sehr hilfreich)
Wo? Bostelreihe 5, 22083 Hamburg
Wer? 1-2 erfahrene oder unerfahrene Personen für den Messestand
Lust? Melde dich bei Anouk ([[mailto://anouk.zink@yfu-deutschland.de][anouk.zink@yfu-deutschland.de]])

*Jugendbildungsmesse an der Stadtteilschule Bergedorf*
Wann? Sa, 15.11. 10:00 bis 13:00 Uhr und 13:00 bis 16 Uhr
Wo? Ladenbeker Weg 13, 21033 Hamburg
Wer? Eine erfahrene oder unerfahrene Person für 1 Schicht. 
Lust? Melde dich bei Duy ([[mailto://dennisle-duy.nguyen@yfu-deutschland.de][dennisle-duy.nguyen@yfu-deutschland.de]])

Wenn ihr Zeit und Lust habt uns zu unterstützen, freuen wir uns auf eure Nachrichten.
Schreibt uns auch gerne bei allen Fragen, die ihr habt!

Liebe Grüße
Annina, Simon, Duy, Kira, Anouk und Lisa
* Entsendeprogramm
** Teamende gesucht für Elternkennlerntreffen am 30.11.2025
Für das digitale Elternkennlerntreffen (EKLT) am 30.11.2025 suche ich 1-2 Teamende, die Lust haben, anhand einer bestehenden Präsentation und eigener Erfahrungen, YFU und alles, was zwischen Bewerbung, VBT, Auslandsaufenthalt und NBT stattfindet, vorzustellen.

Das Online-Treffen findet überregional statt und richtet sich an die Eltern, deren Kinder sich gerade für das Programm 2026/27 bewerben.
Beginn ist 19:30 Uhr und das EKLT dauert ca. 90 Minuten.
Erfahrung ist nicht erforderlich.

Bitte meldet euch bei Interesse oder Fragen bei mir unter 0151 75071648 oder [[mailto://natascha.kortum@yfu-deutschland.de][natascha.kortum@yfu-deutschland.de]].

Danke! 
Natascha
* Externes und Überregionales
** Mitarbeiter-Gesuche/Stellen 
*9. und 10. Mai 2026: Auswahl-Mitglied für USA FOR YOU in Halle gesucht*
15 Jugendliche aus Sachsen-Anhalt werden mit einem Vollstipendium ihre Herbstferien in den USA verbringen. Damit wir aus den vielen Bewerbungen eine Gruppe zusammenstellen können, brauchen wir dich! Du hast KLT-/Auswahl-Erfahrung und Lust, möglichst an beiden Tagen als Team-Mitglied oder beim Meet & Greet bei der Auswahl mitzuwirken? Dann melde dich bei Thekla: [[mailto://usaforyou@yfu.de][usaforyou@yfu.de]] oder mit der Durchwahl -77. Mehr Infos zu USA for you findest du hier: https://www.yfu.de/Usa-for-you

*Dringend gesucht: Leitung für Winter-Re-Entry*
Hast du vom 📅 5.-7. Dezember 2025 Zeit (und eine SLS)? Dann suchen wir dich als Leitung für das Re-Entry-Seminar unserer ca. 20 Winter- und Semesterschüler*innen in📍 Jugendherberge Kassel.
Hast du Lust? Dann melde dich bei Doro unter [[mailto://ap-seminare@yfu.de][ap-seminare@yfu.de]]

*Nebenjob: Erstelle Videos für YFU*
Zur Verstärkung unseres Teams in der Abteilung Marketing & PR suchen wir ab sofort eine*n Video Content Creator*in auf Honorarbasis für 7-10 Stunden/Woche. Du stehst gerne vor der Kamera und kennst dich zumindest grundlegend mit TikTok, Instagram und YouTube aus? Dann bewirb dich jetzt! Alle Infos findest du unter https://www.yfu.de/jobs

*Männlicher Teamer für Orientierungsworkshop (OWO) gesucht*
Du möchtest im Januar unsere neuen Winterschüler*innen begrüßen und hast Lust auf einen Ausflug nach Wiesbaden? Dann freue ich mich über deine Nachricht!
📅 25.-29. Januar 2026 – Die ca. 20 Schüler*innen reisen einen Tag später an
👉 Meldet euch, egal ob mit oder ohne Erfahrung!
📍 Jugendherberge Wiesbaden
📧 Kontakt: Sophia ([[mailto://ap-seminare@yfu.de][ap-seminare@yfu.de]])

*Leitungen und Teamende für Mittelseminare 2026 gesucht 🔎*
Nach dem Seminar ist vor dem Seminar! 🎉 Ganz nach diesem Motto planen wir nach dem OWO-Sommer nun den Mittelseminar-Winter ☃️ und suchen Leitungen und Teamende für die Mittelseminare. Du hast im Februar/März 2026 noch nichts vor und hast Lust auf Berlin/München/Hamburg und natürlich viele tolle ATS? Dann melde dich bei Sophia (📧 [[mailto://ap-seminare@yfu.de][ap-seminare@yfu.de]]) oder fülle einfach diese [[https://eur05.safelinks.protection.outlook.com/?url=https%3A%2F%2Fforms.office.com%2FPages%2FResponsePage.aspx%3Fid%3DOqhNyXAcyk-Cu3mnrCJZh6KOYPtMfppBhidNFBnWvdtUQjVZVjZVV0NQSDdDTTI1NDVUM0pOTDBMSS4u&data=05%7C02%7Chh-newsletter%40yfu-deutschland.de%7C7666e8b845fa44dd9fac08de1c75492f%7C3496a242cb5040ae9566623507dd3c89%7C0%7C0%7C638979487245501044%7CUnknown%7CTWFpbGZsb3d8eyJFbXB0eU1hcGkiOnRydWUsIlYiOiIwLjAuMDAwMCIsIlAiOiJXaW4zMiIsIkFOIjoiTWFpbCIsIldUIjoyfQ%3D%3D%7C0%7C%7C%7C&sdata=3iYY0OPv4Up6MHx1SIwwD8M8PPSq9hUs6sVl%2B89Rrvw%3D&reserved=0][Umfrage]] aus.
|            | Wann (meint Teamanreise) | Wo                                    |
| MS 1 Nord | 20.-25. Februar 2026       | Jugendbildungsstätte Kaubstr., Berlin     |
| MS 1 Süd  | 22.-27. Februar 2026       | Jugendherberge Possenhofen (b. München) |
| MS 2 Nord | 25. Februar-02. März 2026  | Jugendbildungsstätte Kaubstr., Berlin     |
| MS 3 Nord | 02.-07. März 2026         | Jugendbildungsstätte Kaubstr., Berlin     |
| MS 3 Süd  | 08.-13. März 2026         | Jugendherberge Possenhofen (b. München) |
| MS PPP   | 07.-13. Februar 2026       | Jugendherberge Hamburg                |

*22. und 23.11.2025: Dringend Auswahl-Mitglied für USA FOR YOU in Hamburg gesucht*
Im Frühjahr 26 startet wieder eine Gruppe von 15 Jugendlichen aus Hamburg mit einem Vollstipendium in zwei aufregende Wochen in den USA und damit wir aus den Bewerbungen eine tolle Gruppe zusammenstellen können, brauchen wir noch ein erfahrenes Auswahl-Team-Mitglied (KLT-/Auswahl-Erfahrung notwendig). Ihr solltet, wenn möglich, an beiden Tagen präsent sein. Reisekosten und Unterkunft werden nach Rücksprache erstattet. Meldet euch bei Thekla: [[mailto://usaforyou@yfu.de][usaforyou@yfu.de]] oder mit der Durchwahl -77

*Juni 2026: Ehrenamtliche*r für "Germany for you" in Halle (Saale) gesucht*
Du möchtest Teil eines außergewöhnlichen Austauschprogramms werden, lebst in Halle oder Umgebung und hast vom 13. bis 28. Juni 2026 Zeit und Lust, die Programmbegleitung bei der Begleitung der 15-köpfigen Gruppe amerikanischer Jugendlicher in Halle zu unterstützen? Dann ist Germany for you genau das richtige für dich! Schau dir gern hier die vollständige Ausschreibung an: [[https://eur05.safelinks.protection.outlook.com/?url=https%3A%2F%2Fintranet.yfu.de%2Farticle_tool%2Farticles%2F2213&data=05%7C02%7Chh-newsletter%40yfu-deutschland.de%7C7666e8b845fa44dd9fac08de1c75492f%7C3496a242cb5040ae9566623507dd3c89%7C0%7C0%7C638979487245562580%7CUnknown%7CTWFpbGZsb3d8eyJFbXB0eU1hcGkiOnRydWUsIlYiOiIwLjAuMDAwMCIsIlAiOiJXaW4zMiIsIkFOIjoiTWFpbCIsIldUIjoyfQ%3D%3D%7C0%7C%7C%7C&sdata=81XCO5KAZdqyDUpIBCvWUeYaXFtg5iqqZCL4lfp8ROU%3D&reserved=0][Deutsches Youth For Understanding Komitee e.V. - Intranet]] Melde dich bei Interesse oder Fragen bei Thekla: [[mailto://germanyforyou@yfu.de][germanyforyou@yfu.de]] oder mit der Durchwahl -77

*USA for you (27.2.-13.03.2026): männliche Programmbegleitung gesucht*
Für die Begleitung der USA for you-Gruppe aus Hamburg suchen wir noch eine männliche Programmbegleitung. Ihr findet die Ausschreibung hier: [[https://eur05.safelinks.protection.outlook.com/?url=https%3A%2F%2Fintranet.yfu.de%2Farticle_tool%2Farticles%2F2213&data=05%7C02%7Chh-newsletter%40yfu-deutschland.de%7C7666e8b845fa44dd9fac08de1c75492f%7C3496a242cb5040ae9566623507dd3c89%7C0%7C0%7C638979487245562580%7CUnknown%7CTWFpbGZsb3d8eyJFbXB0eU1hcGkiOnRydWUsIlYiOiIwLjAuMDAwMCIsIlAiOiJXaW4zMiIsIkFOIjoiTWFpbCIsIldUIjoyfQ%3D%3D%7C0%7C%7C%7C&sdata=81XCO5KAZdqyDUpIBCvWUeYaXFtg5iqqZCL4lfp8ROU%3D&reserved=0][Deutsches Youth For Understanding Komitee e.V. - Intranet]]
Meldet euch bei Thekla: [[mailto://usaforyou@yfu.de][usaforyou@yfu.de]] oder mit der Durchwahl -77

*Letzte Teamende für PPP-Auswahlen gesucht*
Für die PPP-Auswahlen suchen wir noch letzte Teamende! Die Auswahlen für das PPP (ein Austauschstipendium) sind ähnlich wie Kennenlerntreffen in Präsenz und in sehr spannend 🙂
Wir suchen noch für folgende Termine:
15.11., 16.11., 30.11. in Berlin (gerne auch unerfahren)
15.11. in Wolfsburg (gerne auch unerfahren)
22.11., 23.11. in Osnabrück (gerne auch unerfahren)
29.11. in Jena (gerne auch unerfahren)
29.11. in Hamburg (erfahren und unerfahren)
29.11. in Kempten (erfahren und unerfahren)
29.11., 30.11. in Fulda (gerne auch unerfahren)
Bei Interesse oder Fragen melde Dich bitte bei Kim ([[mailto://herzog@yfu.de][herzog@yfu.de]]). Danke!
** Schulungen & Termine
*LAST CALL: Lobbyworkshop 2.0 Gastfamilienkampagne „Offene Türen, offene Herzen – Austausch braucht Gastfamilien“ – Fokus Social Media*
Wir möchten euch gerne am 28./29.11 nach Berlin zu einem Social-Media-Workshop einladen. Dieser findet im Rahmen der Gastfamilienkampagne „Offene Türen, offene Herzen – Austausch braucht Gastfamilien“ statt und soll Content-Skills erweitern. Auch für eure Kanäle und privat könnte der Workshop relevant sein. Wir wollen Ideen für Aktionen für die Gastfamilienkampagne „Offene Türen, offene Herzen – Austausch braucht Gastfamilien“ in 2026 entwickeln, gemeinsam Strategien für mehr Sichtbarkeit erarbeiten und lernen, wie Reichweite und politische Verbindungsarbeit in den sozialen Netzwerken gelingen können. Expert*innen unterstützen uns dabei mit Impulsen und praktische Tipps zur Content-Erstellung. Neben Input, Austausch und Gruppenarbeit gibt es Gelegenheit, sich zu vernetzen und inspirieren zu lassen.
💡 Fahrt- und Übernachtungskosten werden übernommen.
📝Die Plätze sind begrenzt – jetzt anmelden bei Julia, [[mailto://kastner@yfu.de][kastner@yfu.de]]  
👉 Alle Infos zur Kampagne gibt es hier: https://austausch-braucht-gastfamilien.de/

*Datenschutz kompakt: Online-Einweisung am Donnerstag, 13. November um 19.00 Uhr*
Die nächste digitale Datenschutzeinweisung (ungefähr 45 min.) für Referent*innen, Gremienmitglieder und alle Interessierten findet am Donnerstag, 13. November um 19:00 Uhr statt! Wir freuen uns über alle, die dabei sind – gerne auch weitersagen!
Meldet euch unter [[mailto://datenschutz@yfu.de][datenschutz@yfu.de]] an. Weitere Informationen zum Thema Datenschutz bei YFU findet ihr im [[https://eur05.safelinks.protection.outlook.com/?url=https%3A%2F%2Fintranet.yfu.de%2Fdownloads%2Ffiles%3Fcategory%3D41&data=05%7C02%7Chh-newsletter%40yfu-deutschland.de%7C7666e8b845fa44dd9fac08de1c75492f%7C3496a242cb5040ae9566623507dd3c89%7C0%7C0%7C638979487245617880%7CUnknown%7CTWFpbGZsb3d8eyJFbXB0eU1hcGkiOnRydWUsIlYiOiIwLjAuMDAwMCIsIlAiOiJXaW4zMiIsIkFOIjoiTWFpbCIsIldUIjoyfQ%3D%3D%7C0%7C%7C%7C&sdata=q1piznImjvYtuH5t2AkPTvdbo9wi4vCTfdjBtqBfP38%3D&reserved=0][Intranet]]. Unsere aktuellen [[https://eur05.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.yfu.de%2Fdatenschutz&data=05%7C02%7Chh-newsletter%40yfu-deutschland.de%7C7666e8b845fa44dd9fac08de1c75492f%7C3496a242cb5040ae9566623507dd3c89%7C0%7C0%7C638979487245653803%7CUnknown%7CTWFpbGZsb3d8eyJFbXB0eU1hcGkiOnRydWUsIlYiOiIwLjAuMDAwMCIsIlAiOiJXaW4zMiIsIkFOIjoiTWFpbCIsIldUIjoyfQ%3D%3D%7C0%7C%7C%7C&sdata=4bvjoxDYoJLz95I4LQsYGQRRppNP9tac3LyvF5x%2BuYQ%3D&reserved=0][Datenschutzhinweise]] stehen auf unserer Webseite zur Verfügung.
** Sonstiges / Externes
*EAs für 2025 einreichen nicht vergessen!*
💸 Hast du in diesem Jahr Geld für dein Ehrenamt bei *YFU oder Colored Glasses* ausgegeben? 📝 Denk dran, deinen *Erstattungsantrag (EA) auszufüllen*!
📆 Bitte reiche deine EAs für 2025 grundsätzlich *innerhalb von zwei Monaten*, spätestens aber bis zum *15. Januar 2026* ein.
💡 Formulare und alle Hinweise findest du im YFU-Intranet: https://intranet.yfu.de/downloads/files?category=36.
📧 Alle Fragen an uns (Team Ehrenamt, [[mailto://ehrenamt@yfu.de][ehrenamt@yfu.de]]) oder direkt an die Finanzabteilung ([[mailto://eas@yfu.de][eas@yfu.de]])
* Terminübersicht
** TERMINE 2025
*14.11. - 16.11.2025* &nbsp;&nbsp;&nbsp; Gremiensitzung, Hamburg
*14.11. - 16.11.2025* &nbsp;&nbsp;&nbsp; Colored Glasses Schulung, München

*21.11. - 23.11.2025* &nbsp;&nbsp;&nbsp; Betreuendenseminar, Fulda

*28.11. - 30.11.2025* &nbsp;&nbsp;&nbsp; Teamingeinweisung, Kassel

*28.11. - 30.11.2025* &nbsp;&nbsp;&nbsp; ÖA-Ausschuss-Wochenende, Hamburg 
