* Landesgruppe
**  Wichtige Info Aufrufe Newsletter
Diesen Newsletter findet ihr ab jetzt auch auf Whatsapp! Dafür einfach über diesen Link beitreten: https://chat.whatsapp.com/GBCBuLIU2U78zpim5yGxLF
---

Sehr gerne nehmen wir eure Aufrufe oder Danksagungen in den wöchentlichen Newsletter auf.

Schreibt mir ([[mailto://shh-newsletter@yfu-deutschland.de][shh-newsletter@yfu-deutschland.de]]) dafür einfach immer bis *Mittwochs 17:00 Uhr* eure Aufrufe, damit ich sie noch in den Newsletter der aktuellen Woche mit aufnehmen kann. Ansonsten nehme ich die Aufrufe natürlich gerne in den nächsten auf.

Vielen lieben Dank und ich freue mich auf eure Emails.

Liebe Grüße
Aimo
* Öffentlichkeitsarbeit
** Dankeschön und Save The Date!
Liebe Landesgruppe SHH,

der Sommer ist da und damit auch die Sommerpause der ÖA. Es haben in den letzten sechs Monaten bereits 8 Veranstaltungen stattgefunden und wir möchten uns bei allen Teamenden bedanken, die dies möglich gemacht haben: Mascha, Lotta, Kira, Elene, Hilla, Duy, Henrike, Hanna und Marie. Danke für euren Einsatz in der ÖA und dafür, dass ihr YFU bereits an so viele verschiedene Orte gebracht habt!

Und wie jedes Jahr starten wir im September dann nochmal richtig durch und freuen uns über viele ÖA-Motivierte für den Rest der Saison. Ihr findet unten schonmal eine Übersicht der kommenden Veranstaltungen.
 - 05.09.2026 (Hamburg)
 - 10.09.2026 (Norderstedt)
 - 10.09.2026 (Hamburg)
 - 16.09.2026 (Hamburg)
 - 17.09.2026 (Hamburg)
 - 22.09.2026 (Hamburg)
Liebe Grüße und einen schönen Sommer wünschen
Aimo, Annina, Duy, Kira, Lisa und Sophie
* Aufnahmeprogramm
** Leitungen und Teamende für Gastfamilienvorbereitung gesucht
Liebe Landesgruppe,
 
die neue AP-Saison steht in den Startlöchern und wir sind auf der Suche nach Leuten, die unsere nächsten Gastfamilien vorbereiten wollen. Wir haben schon einige motivierte Gastfamilien, die auf den Start des Austausches warten und so viele Informationen wie möglich erhalten wollen. Die GF-Vorbereitung soll sie so gut es geht auf den Austausch vorbereiten und ganz viele offene Fragen klären.
Für die Gastfamilien Vorbereitung suchen wir zurzeit Menschen, die Lust hätten, an einem Tag ihrer Wahl (am besten am Wochenende, jedoch eignen sich ggf. auch Wochentage abends) die neuen Gastfamilien auf ihren Austausch vorzubereiten in der Geschäftsstelle.
Zur Vorbereitung unserer Gasteltern soll es im Sommer zwei-drei Termine geben. 
Termine in den Zeiträumen Ende Juli und August würden sich hier gut eignen, damit wir die Sommerferien frei halten können.  

Du würdest die Veranstaltung vor Ort leiten oder teamen, eventuell mit einer Person deiner Wahl zusammen. Eine Präsentation gibt es bereits.
Meldet euch gerne, wenn ihr interessiert seid, eine oder mehrere GF-Vorbereitung(en) zu leiten oder zu teamen. Noch sind die Termine flexibel. Meldet euch sehr gerne mit konkreten Terminvorschlägen. 

Wir freuen uns auf eure Rückmeldungen an Amilou oder mich (theda.schmidtko@yfu-deutschland.de)
 
Liebe Grüße,
Theda
* Entsendeprogramm
** Auswahlleitungen und Einzelgesprächsleitungen für die PPP-Auswahlen gesucht
Die Bewerbungssaison für den PPP-Jahrgang 2027/28 hat begonnen und mit ihr die Suche nach Auswahlleitungen und Einzelgesprächsleitungen. Wenn Du Dir vorstellen kannst, diesen Herbst eine Auswahl zu leiten oder als Einzelgesprächsleitung zu begleiten, fülle bitte diese kurze Umfrage aus: 

[[https://forms.cloud.microsoft/e/9c4d3YZ1t5][PPP-Auswahlleitungen 2026]]

Wenn Du Dir unsicher bist, ob Du die Voraussetzungen erfüllst oder (noch) keine Schulung hast, melde Dich trotzdem gerne, im Herbst werden auch wieder Schulungen stattfinden. Bei Fragen wende Dich gerne an Keira (keira.geiss@yfu.de)
** Doch noch eine NBT teamen?
Liebe Landesgruppe,

der Beginn der NBT-Saison rückt immer näher und wir sind weiterhin auf der Suche nach Personen, die unsere NBT-Teams vervollständigen möchten. Besonders über Unterstützung für unsere erste NBT würden wir uns freuen:)

Wir suchen aktuell:
*NBT SHH 1: 13.08. – 16.08.2026*, Spejdergården Tydal, Eggebek
 - Leitung oder Leitungsteam
 - 1 -2 Teamende, Erfahrung + Geschlecht egal
*NBT SHH 2: 10.09. – 13.09.2026*, CISV – Haus, Hamburg           
 - 1- 2 Teamende, gerne auch Justees
*NBT SHH 3: 01.10. – 04.10.2026*, Spejdergården Tydal, Eggebek
 - Leitung oder Leitungsteam
 - 1- 2 Teamende
 - Mit Blick auf die aktuelle Teamzusammensetzung freuen wir uns besonders über männliche Teamende und Personen mit etwas Teamingerfahrung (m/w/d) :)
Wenn ihr also Lust habt, die Austauschschüler*innen auf ihrem Rückkehrprozess zu begleiten, tolle Menschen zu sehen, YFU-Spirit zu verbreiten oder einfach mal wieder etwa für YFU zu machen oder noch Fragen habt, dann meldet euch gerne bei uns unter antonia.karg@yfu-deutschland.de oder greta.dahmen@yfu-deutschland.de.

Liebe Grüße
Greta & Antonia
* Externes und Überregionales
** Mitmachen / Stellen
*Familienbesucher*in in 27356 Rotenburg (Wümme) gesucht*
Wir haben eine engagierte Gastfamilie, die sich schon sehr auf ihr zukünftiges Gastkind freut. Was jetzt noch fehlt? Ein Familienbesuch!
Der Besuch sollte idealerweise am 07. August oder den Tagen danach stattfinden.
Du wohnst in der Nähe von Rotenburg (Wümme) oder hast Lust auf einen kleinen Ausflug? 😊 Dann melde dich für weitere Informationen in der Geschäftsstelle unter gastfamilien@yfu.de.
Auch wenn du bisher noch keine Erfahrung mit Familienbesuchen hast, aber grundsätzlich Interesse mitbringst, freuen wir uns sehr über deine Nachricht!

*🔎Erfahrener männlicher Teamer für OWO 1 gesucht*
Für die OWO 1 vom 16. - 20.08 in Mainz suchen wir noch einen erfahrenen männlichen Teamer
Wenn du Lust hast dabei zu sein, melde dich gerne bei Mareen (📧ap-seminare@yfu.de). Alle weiteren Infos findest du [[https://intranet.yfu.de/downloads/files/3970][hier]].

*📢 Flug- & Zugbegleitungen gesucht! ✈️🚆*
Für einige spannende Abreisen unserer Austauschschüler*innen freuen wir uns noch über Unterstützung:
 - 25.–26.08.: Zugbegleitung nach Frankreich inkl. Übernachtung in Paris mit der Gruppe und einer weiteren Begleitung
 - 04.–05.09.: Flugbegleitung nach Gander (Neufundland) inkl. Zwischenübernachtung in Montreal mit der Gruppe
 - 05.09.: Flugbegleitung nach Saint John
Für die Begleitung solltest du mindestens 21 Jahr alt sein.👉 Bei Interesse melde dich gerne bei Marla unter reise@yfu.de.

*Endspurt im AP: Noch 40 Jugendliche warten auf ihre Gastfamilie ab Sommer!*
Bei der Gastfamiliensuche für unsere Austauschschüler*innen hier in Deutschland läuten wir den Endspurt ein: Aktuell warten noch rund 40 Jugendliche auf den Namen ihrer Gastfamilie. Damit das Warten möglichst bald auch für die letzten Schüler*innen ein Ende hat, brauchen wir deine Unterstützung! Wie genau? Zum Beispiel, indem du noch heute [[https://yfuit.sharepoint.com/:f:/t/GSexterngeteilteDateien/IgAIkW5SfbTeToVqKWE-FwaPAWWQ0zZ17pT3oC4hv1qvLNo?e=l4u1pZ][mindestens eines dieser Sharepic-Profile]] in einem deiner digitalen Netzwerke (WhatsApp-Gruppen, Social Media, E-Mail…) postest. ODER indem du eine dir bekannte Familie auf die Gastfamiliensuche aufmerksam machst und diesen Link zu den Profilen der letzten unplatzierten Schüler*innen weiterleitest: www.yfu.de/austauschschueler. ODER vielleicht möchtest du und deine Familie selbst (noch einmal) euer Zuhause öffnen und eine*n Austauschschüler*in für die ersten drei Monate bei euch aufnehmen. Dafür kannst du dich auf der [[https://www.yfu.de/gastfamilie-werden/gastfamilienanmeldung][YFU-Website]] direkt anmelden. Was auch immer du heute für die Gastfamiliensuche tun kannst – jede Hilfe ist ein wesentlicher Beitrag, damit wir allen Jugendlichen den rechtzeitigen Start in ihre Austauschjahr und damit auch die Teilnahme an ihrer OWO ermöglichen können. Daher: Tausend Dank für deine Unterstützung beim AP-Endspurt! 💜

*Lass dich zur PPP-Auswahlleitung schulen*
Für die neue PPP-Saison wollen wir wieder neue Auswahlleitungen schulen. Du hast Lust, in der neuen Saison eine PPP-Auswahl zu leiten, aber dir fehlt noch die nötige Schulung? Dann trage dich gerne in die [[https://forms.cloud.microsoft/Pages/ResponsePage.aspx?id=QqKWNFDLrkCVZmI1B908ibDdxUEoHapOoDj4h619qOdUQUVNSUdCTEwxT1I4WFVDSTEwUEtZTTBLWi4u][Abfrage]] ein. Voraussetzungen für die Schulung sind Erfahrungen als Teammitglied/ Einzelgesprächsleitung bei PPP-Auswahlen und bestenfalls eine KLT-Schulung.
Bei Fragen melde dich gerne bei Picabo (picabo.winands@yfu-deutschland.de).
** Schulungen / Termine
*Colored Glasses Schulung am 18.-20. September in Hamburg – Starte jetzt dein Engagement für eine bunte Gesellschaft!*
Mit Colored Glasses Workshops begeistern wir Kinder und Jugendliche der 5. bis 13. Klasse an Schulen und Jugendeinrichtungen in ganz Deutschland für Vielfalt und Toleranz. Wir machen uns stark gegen Diskriminierung und Vorurteile durch spannende Simulationen und Diskussionen auf Augenhöhe! Die Schulung ist dein Start ins Ehrenamt: Wir zeigen dir, wie du einen Workshop planst und durchführst. Erfahrene Ehrenamtliche geben dir Tipps und Tricks, damit du auch ohne Vorerfahrung einen echten Unterschied machen kannst. Du bist zwischen 16 und 29 Jahre alt und willst aktiv werden? Melde dich zur kostenlosen Schulung am 18.-20. September in Hamburg [[https://forms.cloud.microsoft/e/x3uPwy2qkx][hier]] an. Gerne weitersagen, auch an Interessierte ohne YFU-Hintergrund!  Alle Infos hier als [[https://yfuit.sharepoint.com/:b:/t/GSexterngeteilteDateien/IQCYPKGgpbi7QpQ7CZyjoKDlAYz9QPWCf9MW5jmXvvjQYLQ?e=Wgi1gU][Flyer zum Download]]. Bei Fragen wenden dich gerne an Nina unter roesch@yfu.de.

*Save the date: Garbeck 2026*
Garbeck- wer oder was soll das denn sein? Garbeck ist ein kleiner Ort im Sauerland, in dem sich traditionell YFUler am letzten Wochenende vor Weihnachten (18.-20.12.26) treffen, um sich bei warmen und kalten Spaßgetränken gemeinsam auf die winterliche Feiertagszeit einzustimmen. Das Wochenende bietet uns viel Raum zum Socialn, Stricken, Spielen, Singen und alles was sonst noch so passieren soll; die einzig goldene Regel: es wird nicht gearbeitet. Ob das ganze Wochenende, nur einen Tag, oder für ein paar Stunden - alle können vorbeikommen und sind herzlich eingeladen! Es gibt einen kleinen Eigenkostenanteil, der geringer wird, je mehr Leute wir sind (letztes Jahr 40€, Solitopf bei Bedarf). Wenn ihr also bei den schwitzigen Temperaturen genauso Lust auf ein Wochenende voller winterlicher Idylle habt, dann nehmt den dicken Marker in Royal Purple raus und markiert euch das Wochenende in eurem Kalender und dem aller eurer YFU-Buddys. Bei Fragen wendet euch gerne an Caro (carolin.schmidt@yfu-deutschland.de).

*🚀 Powerstart ins Ehrenamt am 22. Juli von 19-20.30 Uhr mit Ines und Julia*
Du möchtest aktiv werden oder wieder einsteigen und brauchst für den Start noch ein bisschen Orientierung? Dann haben wir einen Tipp für dich🔥! Starte mit unseren Ehrenamtlichen beim digitalen Powerstart ins Ehrenamt durch. Lerne das YFU 1x1, finde heraus, was es für dich zu tun gibt, wie du dich mit YFUler*innen in deiner Umgebung vernetzen kannst und welche Vorteile du als YFUler*in genießt.
🔥 Anmeldung hier: https://tinyurl.com/jszynj7n
** Sonstiges / Externes
*Der Colored Glasses Jahresbericht 2025 ist da!*
55 Workshops, über 1.000 erreichte junge Menschen, 49 neue Freiwillige und fast 3.800 Stunden ehrenamtliches Engagement – 2025 war ein starkes Jahr für Colored Glasses! Zudem gab es mit dem PHINEO Wirkt-Siegel eine besondere Auszeichnung für die nachhaltige Wirkung unserer Arbeit. Danke an alle, die Colored Glasses mit ihrem Engagement und ihrer Unterstützung möglich machen
Neugierig auf die Details? Hier geht’s zum Jahresbericht: https://coloredglasses.de/jahresbericht-2025/
* Terminübersicht
** TERMINE 2026
*18.09. -20.09. 2026* &nbsp;&nbsp;&nbsp; Colored Glasses Schulung, Jugendherberge Horner Rennbahn *Hamburg*

*02.10. - 04.10.2026*  &nbsp;&nbsp;&nbsp; Seminarleitungsschulung (SLS), Jugendherberge *Kassel*
*02.10. - 04.10.2026*  &nbsp;&nbsp;&nbsp; *(LG)* Aktivenwochenende

*06.11. – 08.11.2026* &nbsp;&nbsp;&nbsp; Colored Glasses Schulung, Jugendherberge *Kassel*

*20.11. - 22.11.2026* &nbsp;&nbsp;&nbsp; Betreuendenseminar, *Jugendherberge Stuttgart*

*27.11. - 29.11.2026* &nbsp;&nbsp;&nbsp; ÖA-Ausschusstreffen, *Hamburg*

*06.05. - 09.05.2027* &nbsp;&nbsp;&nbsp; BUT 2027, *tba*
