* Landesgruppe
**  Wichtige Info Aufrufe Newsletter
Diesen Newsletter findet ihr ab jetzt auch auf Whatsapp! Dafür einfach über diesen Link beitreten: https://chat.whatsapp.com/GBCBuLIU2U78zpim5yGxLF
---

Sehr gerne nehmen wir eure Aufrufe oder Danksagungen in den wöchentlichen Newsletter auf.

Schreibt mir ([[mailto://shh-newsletter@yfu-deutschland.de][shh-newsletter@yfu-deutschland.de]]) dafür einfach immer bis *Mittwochs 17:00 Uhr* eure Aufrufe, damit ich sie noch in den Newsletter der aktuellen Woche mit aufnehmen kann. Ansonsten nehme ich die Aufrufe natürlich gerne in den nächsten auf.

Vielen lieben Dank und ich freue mich auf eure Emails.

Liebe Grüße
Aimo
* Öffentlichkeitsarbeit
** Neue Infos
Liebe Landesgruppe,

Die ersten ÖA-Veranstaltungen finden wieder statt. Im März gibt es jeweils abends einen Schulvortrag für die wir eure unterstützung brauchen. Bei beiden habt ihr die Möglichkeit einem begeisterten und interessierten Publikum von euren Erfahrungen im Austausch zu berichten. Fahrtkosten werden von YFU erstattet.

Bei Interesse meldet euch gerne bei sophie.schnippi@posteo.de oder dennisle-duy.nguyen@yfu-deutschland.de
** Schulvortrag am Gymnasium Brunsbüttel
Wann: 12.03.2026 um 18:00 Uhr.

Wo:
Gymnasium Brunsbüttel
Kopernikusstr. 1
25541 Brunsbüttel

Wer: 2-3 erfahrene und unerfahrene Personen
* Entsendeprogramm
** ❗️Leitung gesucht für Winter NBT I in Hamburg (also direkt bei dir um die Ecke!)
Für die Winter NBT I in Hamburg sind wir noch dringend auf der Suche nach einer Leitung und Co-Leitung!

🏡12. - 15.03.2026 im Haus Warwisch

Du hast Lust auf eine coole Tagung mit unseren Winter-Return-Schülis? Dann ist das die perfekte Gelegenheit für dich, egal ob du schon erfahrene Leitung bist oder dein neu erworbenes Wissen von der SLS direkt mal anwenden möchtest😊  
Keine Sorge: es gibt bereits einige Teammeldungen, du hast also direkt einen guten Start in die Planung und bekommst aus der LG-SHH und der GS auch weiterhin Unterstützung bei Bedarf! 

😍 Wenn du dir vorstellen könntest, die Leitung oder Co-Leitung zu übernehmen, melde dich bitte ASAP bei kristin.gebhardt@yfu-deutschland.de oder bei daniel.jacobi@yfu-deutschland.de !

Der Termin passt dir nicht? Kein Problem, für die Tagung vom 26-29.03.2026 in Würzburg wird auch noch eine Leitung gesucht 😊
Leitet diese Info auch gerne an alle euch bekannten Leitungen und Teamenden weiter, bei denen ihr euch vorstellen könntet, dass sie bei der NBT dabei sein wollen könnten.

Wir freuen uns, von euch zu hören! 💜💜
* Externes und Überregionales
** Mitarbeits-Gesuche/Stellen 
*Leitung eines vierwöchigen Sommerkurses für US-amerikanische Austauschschüler*innen*

Du hast vom 25. Juli-21. August 2026 noch nichts vor, hast Erfahrung in der Leitung von Teams sowie in der Jugendarbeit? Englisch beherrscht du im Schlaf und eine Ersthelfer*innen-Ausbildung bringst du auch mit? Dann suchen wir genau 👉dich für die Leitung des PPP-Sprachcamps in Bonn. Das genaue Anforderungsprofil sowie die Aufgabenbeschreibung findest du [[https://www.yfu.de/ueber-yfu/jobs-praktika][hier]].

📧Fragen und Interessensbekundungen schickst du bitte Sophia (ap-seminare@yfu.de).

*Vierwöchiges interkulturelles Training und Betreuung für US-amerikanische Austauschschüler*innen*

Im Sommer reisen 42 PPP-Stipendiat*innen aus den USA für ihren Austausch nach Deutschland. Du hast Lust, sie bei ihren ersten Wochen in Bonn zu begleiten, interkulturelle Trainings durchzuführen, ihnen bei Rat und Tat zur Seite zu stehen sowie ein buntes Rahmenprogramm zu entwerfen? Für den 25. Juli-21. August 2026 steht noch nichts in deinem Kalender 📅 ? Dann komm ins Team des PPP-Sprachcamps 🚀. Die genauen Bewerbungsvoraussetzungen und Aufgabenbeschreibungen findest du [[https://www.yfu.de/ueber-yfu/jobs-praktika][hier]] 🔎.

📧Fragen und Interessensbekundungen schickst du bitte Sophia (ap-seminare@yfu.de).

*Komm ins Colored Glasses Team – Referent*in für Motivation & Fortbildung sowie Vorstandmitglied gesucht!*

Im vergangenen Jahr wurde der Colored Glasses Vorstand um den Posten „Ehrenamts-Motivation und -Fortbildung“ erweitert. Hannes hat in dieser Funktion mit großem Erfolg die regelmäßigen Colored Glasses Community Calls etabliert. Nun soll sich zu diesem spannenden und wichtigen Aufgabenbereich ein kleines ehrenamtliches Team bilden. Du hast Lust, gemeinsam mit anderen CG-Ehrenamtlichen die Organisation und Gestaltung der Community Calls zu übernehmen und Formate für unser Ehrenamtlichen-Netzwerk weiterzuentwickeln?  Dann melde dich jetzt bei Hannes unter hannes.wollanke@yfu-deutschland.de bei Interesse oder Fragen! Weitere Infos findest du [[https://coloredglasses.de/unsere-motivation-beginnt-mit-dir/][hier]]. Außerdem ist weiterhin der Vorstandsposten zur Koordi-Koordination ausgeschrieben. Wir suchen ein Organisations- und Kommunikationstalent für das ehrenamtliche Leitungsteam. Alle Details [[https://coloredglasses.de/organisations-und-kommunikationstalent-gesucht/][hier]]. Schreib uns an vorstand@coloredglasses.de bei Fragen oder Interesse!

*Trainer*innen für Colored Glasses Schulung am 19.-21. Juni in Mühlhausen (bei Duisburg) gesucht*

Mit Colored Glasses Workshops begeistern wir Kinder und Jugendliche der 5. bis 13. Klasse an Schulen und Jugendeinrichtungen in ganz Deutschland für Vielfalt und Toleranz. Wir machen uns stark gegen Diskriminierung und Vorurteile durch spannende Simulationen und Diskussionen auf Augenhöhe! Bei dieser Schulung führen wir neue Ehrenamtliche ab 16 Jahren mit und ohne vorherigem YFU-Bezug in die Teaming Aufgaben und das Colored Glasses Konzept ein. Das Besondere an diesem Termin: die Schulung findet an einer Schule statt und gut die Hälfte der Teilnehmenden werden Schüler*innen der Schule mit eigener Austauscherfahrung sein. Du hast Erfahrung als Trainer*in bei YFU und/oder Colored Glasses Erfahrung? Dann komm ins Team! Rückmeldungen an Nina unter roesch@yfu.de.
** Schulungen / Termine
*📅 Save the dates – Termine für ToT und SLS 2026*

Du möchtest dich bei YFU in deinen didaktischen Fähigkeiten üben, andere anzuleiten und ihnen Inhalte zu vermitteln? Dann trag dir doch schonmal das Training of Trainers (ToT) vom 25.-27. September 2026 in Wiesbaden in deinen Kalender ein. Hier bekommst du Raum theoretisch und praktisch deine Trainer*innen-Kompetenzen zu erproben und Erfahrungen zu teilen.

Wenn du bereits Erfahrungen im Teamen gesammelt hast und nun gerne in die Rolle der Seminarleitung bei YFU schlüpfen möchtest, merke dir den Termin für die nächste Seminarleitungsschulung (SLS): 2.-4. Oktober 2026 in Kassel. Die Schulung ist sowohl für noch Unerfahrene als auch für diejenigen geeignet, die bereits erste Erfahrungen im Leiten sammeln konnten.

Wenn du Interesse hast, eine der Schulungen zu trainieren/zu leiten oder als Teilnehmende*r dabei zu sein, melde dich bei Rahel und ehrenamt@yfu.de.  
** Sonstiges / Externes
*Studis der TH Köln und der Uni Köln aufgepasst: Jetzt zum Colored Glasses Service Learning Seminar anmelden*

Erstmalig können im SoSe 2026 Studierende der Universität zu Köln und der Technischen Hochschule Köln im Rahmen eines Service Learning Seminars Uni Credits für das Engagement mit YFU erhalten. Konkret heißt das: nimm an einer Colored Glasses Schulung (09./10.05) und vier digitalen Seminarterminen teil und führe im Semester 2-3 Colored Glasses Workshops im Kölner Raum oder bundesweit durch und trage so den YFU-Spirit direkt im Rahmen deines Studiums weiter. Die Anmeldung ist vom 06.03. bis zum 26.03.2026 möglich. Alle Infos findest du [[https://professionalcenter.uni-koeln.de/lehre/service-learning][hier]]. Unbedingt weitersagen! Bei Fragen melde dich auch gerne bei Nina unter roesch@yfu.de. 
* Terminübersicht
** TERMINE 2026
*27.02. - 01.03.2026* &nbsp;&nbsp;&nbsp; Colored Glasses Schulung, Jugendherberge *Leipzig*

*20.03. - 22.03.2026* &nbsp;&nbsp;&nbsp; Gremiensitzung Frühjahr, Jugendherberge Horner Rennbahn *Hamburg*

*27.03. - 29.03.2026* &nbsp;&nbsp;&nbsp; Betreuendenseminar in *Bad Bevensen*

*15.05. - 17.05.2026* &nbsp;&nbsp;&nbsp; Colored Glasses Schulung, Jugendherberge Burg Schwaneck (*bei München*)

*29.05 - 31.05.2026* &nbsp;&nbsp;&nbsp; ÖA-Ausschusstreffen

*05.06. - 07.06.2026* &nbsp;&nbsp;&nbsp; *(LG)* Nord-LGT

*20.06. - 21.06.2026* &nbsp;&nbsp;&nbsp; Colored Glasses Schulung, Liebfrauenschule Mühlhausen (*bei Duisburg*)

*18.09. -20.09. 2026* &nbsp;&nbsp;&nbsp; Colored Glasses Schulung, Jugendherberge Horner Rennbahn *Hamburg*

*25.09. - 27.09.2026* &nbsp;&nbsp;&nbsp; *(LG)* Aktivenwochenende

*02.10. - 04.10.2026*  &nbsp;&nbsp;&nbsp; Seminarleitungsschulung (SLS), Jugendherberge *Kassel*

*06.11. – 08.11.2026* &nbsp;&nbsp;&nbsp; Colored Glasses Schulung, Jugendherberge *Kassel*

*27.11. - 29.11.2026* &nbsp;&nbsp;&nbsp; ÖA-Ausschusstreffen
