* Landesgruppe
**  Wichtige Info Aufrufe Newsletter
Diesen Newsletter findet ihr ab jetzt auch auf Whatsapp! Dafür einfach über diesen Link beitreten: https://chat.whatsapp.com/GBCBuLIU2U78zpim5yGxLF
---

Sehr gerne nehmen wir eure Aufrufe oder Danksagungen in den wöchentlichen Newsletter auf.

Schreibt mir ([[mailto://shh-newsletter@yfu-deutschland.de][shh-newsletter@yfu-deutschland.de]]) dafür einfach immer bis *Mittwochs 17:00 Uhr* eure Aufrufe, damit ich sie noch in den Newsletter der aktuellen Woche mit aufnehmen kann. Ansonsten nehme ich die Aufrufe natürlich gerne in den nächsten auf.

Vielen lieben Dank und ich freue mich auf eure Emails.

Liebe Grüße
Aimo
** Liebe Community,
wir haben wieder Neuigkeiten! ☀️

Bevor für viele unserer Austauschschüler*innen die Zeit in Deutschland zu Ende geht, möchten wir euch herzlich zu einem gemeinsamen Sommertreffen einladen. Zusammen wollen wir das schöne Wetter genießen, einen entspannten Nachmittag im Grünen verbringen.

📅 Wann? 14. Juni, um 15 Uhr
📍 Wo? Stadtpark Hamburg

Da der Stadtpark groß ist, treffen wir uns vor dem Lesecafé Stadtpark. Den Treffpunkt findet ihr hier: https://maps.app.goo.gl/jN2tsTRepqDfEPTH7

Gemeinsam suchen wir uns dann ein schönes Plätzchen für ein Picknick.
Damit wir am Ende ein buntes Buffet haben, freuen wir uns, wenn jede*r etwas zu essen zum Teilen mitbringt. Bitte denkt außerdem an eure eigenen Getränke, Teller und Besteck sowie, falls vorhanden, eine Picknickdecke.

Wenn ihr dabei seid, meldet euch bitte kurz über die [[https://forms.office.com/e/atAyzw3k4E][Umfrage]] an.

Wir freuen uns auf euch und auf einen schönen gemeinsamen Sommernachmittag!

Liebe Grüße
Leah, Aimo und Ole
* Öffentlichkeitsarbeit
** Schulvortrag am Gymnasium Brunsbüttel
Wann: flexibel möglich!
Meldet euch gerne bei kira.thede@yfu-deutschland.de
Wo: Gamnasium Brunsbüttel
Kopernikusstr. 1
22541 Brunsbüttel
** Schulvortrag am Goethe-Gymnasium
Wann: 15.06.2026 15:00 (Teamtreffen 13:30)
Wo: Goethe-Gymnasium Hamburg (Altona)
Rispenweg 28, 22547 Hamburg
Wer: 1-2 Teamer jedes Erfahrungsgerades
Bei Interesse: kira.thede@yfu-deutschland.de
** Schulvortrag am Gymnasium Trittau
cccWann: 18.06.2026
Wo: Gymnasium Trittau
Wer: 1-2 Teamer jedes Erfahrungsgerades
Bei Interesse: kira.thede@yfu-deutschland.de
** Schulvortrag in Büsum
Wann: 25.06.2026 19:00
Wo: Schule am Meer Büsum
Bei Interesse: kira.thede@yfu-deutschland.de
* Aufnahmeprogramm
** Gf-Besuche
Liebe Landesgruppe,

Ich suche Besucher für potentielle Gastfamilien (Gf) in der
 -  Holnisser Landstr.
  in 24975 Husby
 - An der Obertrave
   in 23552 Lübeck
Wer hat Zeit und Lust, diese Besuche zu übernehmen? 😍
Ich freue mich über eure Rückmeldungen
Ines
 
Die Gesuche für Gastfamilienbesuche poste ich meist als erstes in einer WhatsApp- und Signalgruppe.
Wer Lust hat, dort über Gf-Infos auf dem Laufenden gehalten zu werden, hier die Links dazu:
https://chat.whatsapp.com/IekwaHKc6FgBzdp3n17RSV?mode=gi_t
und
https://signal.group/#CjQKID7eirjpYr-BVlu7PkLTR4tJVCiOkxkFkrrQV2nsBk6_EhBjyeu20bhbOLYOJVIBU8dT

Und sollten Fragen aufkommen, meldet euch gerne direkt bei mir
ines.hintz@yfu-deutschland.de 😃
** Betreuungsschulung in Berlin am 13. Juni
Liebe Regionalbetreuungskolleg*innen,
Liebe AP-Leitungen (da wo es noch keine RB's gibt 😉),

ich organisiere für den 13.06. eine überregionale Betreuungsschulung - als Tagesschulung - in Berlin, und es gibt noch freie Plätze!
Es sind zwar schon etliche Anmeldungen eingegangen, aber ich würde mich sehr freuen, wenn noch ein paar dazu kommen, damit es sich richtig lohnt.
Deshalb würde ich euch gerne um etwas bitten:
Könntet ihr die Einladung - siehe unten - in eure Landesgruppen-Verteiler, LG-WhatsApp-Gruppen, etc. leiten und ggf. auch an betreuungsinteressierte Personen senden, wenn ihr welche kennt?

Für eure Unterstützung wäre ich super dankbar!

Vielen Dank und liebe Grüße aus Berlin,
Caren
** Aufruf GF Re-Entry
Liebe Landesgruppe,

für unsere Gastfamilien- Re-Entry im Haus Warwisch am 07.06. suchen wir noch dringend Teamende (Erfahrung egal). Die Veranstaltung geht meistens ca. von 12-16 Uhr - die genauen Zeiten werden noch bestätigt. Es geht darum, mit den Gastfamilien die Erfahrung gemeinsam zu reflektieren und den Nachmittag anschließend mit einem Buffet gemeinsam mit den Austauschschüler*innen ausklingen zu lassen. 

Meldet euch super gerne bei mir (amilou.fehr@yfu-deutschland.de oder unter 01786122651), wenn ihr Lust auf einen spannenden Nachmittag habt! 

LG und danke euch
Amilou
* Entsendeprogramm
** Doch noch eine NBT teamen?
Liebe Landesgruppe,

vielen Dank an alle, die sich bereits über das überregionale Teamgesuch für eine unserer NBTs gemeldet haben! An alle, die die Frist verpasst haben: es ist noch lange nicht zu spät, denn wir freuen uns weiterhin über Meldungen von vielen motivierten Teammitgliedern und Leitungen!

Wir suchen noch:
| NBT   | Zeitraum (mit VNBT) | Ort                          | Gesucht werden ...                                              |
|-------+---------------------+------------------------------+-----------------------------------------------------------------|
| SHH 1 | 13.08. – 16.08.2026 | Spejdergården Tydal, Eggebek | Teamende, gerne auch Justees oder unerfahrenere Personen        |
| SHH 2 | 10.09. – 13.09.2026 | CISV – Haus, Hamburg         | Leitung oder Leitungsteam & Teamende jeglichen Erfahrungsgrades |
| SHH 3 | 01.10. – 04.10.2026 | Spejdergården Tydal, Eggebek | Leitung oder Leitungsteam & Teamende jeglichen Erfahrungsgrades |
Wenn ihr also Lust habt, die Austauschschüler*innen auf ihrem Rückkehrprozess zu begleiten, tolle Menschen zu sehen, YFU-Spirit zu verbreiten oder einfach mal wieder etwa für YFU zu machen oder noch Fragen habt, dann meldet euch gerne bei uns unter antonia.karg@yfu-deutschland.de oder greta.dahmen@yfu-deutschland.de.

Liebe Grüße
Greta & Antonia
* Externes und Überregionales
** Mitmachen / Stellen
*OWO-Leitungen gesucht*
- Für die OWO 1 vom 16. - 20.08 in Mainz suchen wir weiterhin noch 1 erfahrene Leitung
- Für die OWO 4 vom 23. - 27.08 in Mainz suchen wir 2 Leitungen
Bitte meldet euch bei Mareen (📧 ap-seminare@yfu.de) oder füllt diese [[https://forms.office.com/e/KYWzZNfDNt?origin=lprLink][Umfrage]] aus. Alle weiteren Infos findet ihr [[https://intranet.yfu.de/downloads/files/3970][hier]].

*OWO-Teamende gesucht*
Langsam füllen sich die Teams für die OWOs (16.-20.08 und 23.-27.08)! Wir suchen jedoch insbesondere noch erfahrene Teamende sowie männliche Teamer. Grundsätzlich gilt aber für alle Interessierten: Wenn du Lust hast mitzumachen – melde dich gerne bei Mareen (📧 ap-seminare@yfu.de) oder fülle diese [[https://forms.office.com/e/KYWzZNfDNt?origin=lprLink][Umfrage]] aus. Alle weiteren Infos findest du [[https://intranet.yfu.de/downloads/files/3970][hier]].

*🏆 Qualifiziere Seminarleitungen – Eine weitere Trainer*in für die Seminarleitungsschulung (SLS) gesucht*
Du möchtest andere YFUler*innen mit deiner Erfahrung und Expertise dabei unterstützen, starke Seminarleiter*innen zu werden? Dann brauchen wir dich im Trainierenden-Team der SLS vom 02.-04.10.2026 in Kassel! Du hättest bereits Henrike Krahl, Emma Fössing und Kim Herzog als kompetente Teamkolleg*innen an deiner Seite - Fehlst nur noch du. 🫰🏻 Wenn du dabei bist oder noch Fragen hast, melde dich bei Rahel (perschke@yfu.de) aus der GS.

*Unterstütze uns als Eltern(vertreter*in), Lehrkraft oder Schüler*in an deiner Schule bei der Gastfamiliensuche!*
Wenig Aufwand für dich, viel Unterstützung für YFU: Persönliche Kontakte an Schulen sind für YFU ganz besonders wertvoll, auch bei der Suche nach Gastfamilien. Engagierst du dich als Elternvertreter*in oder bist du als Elternteil, Lehrkraft oder Schüler*in an einer Schule? Dann melde dich bei Corinna (schmidt@yfu.de) und erhalte unsere E-Mail-Vorlage für einen Gastfamilienaufruf zum Weiterleiten an die gesamte Elternschaft oder auch einen Kurzaufruf für den Klassenchat. Aufrufe an Schulen führen besonders oft zu Anmeldungen von Gastfamilien – und deine Unterstützung macht den Unterschied! 💜
** Schulungen / Termine
*Online-KLT-Schulung am 02.07. um 19:30 Uhr – jetzt anmelden!*
Bewerbende für den nächsten YFU-Jahrgang kennenlernen und dabei von euren eigenen Erfahrungen berichten – das könnt ihr bei den digitalen Kennenlerntreffen (KLTs)! Eine etwa anderthalbstündige Online-Schulung dafür wird am Donnerstag, den 02.07. um 19:30 Uhr angeboten. Bei Interesse meldet euch unter kennenlernen@yfu.de – wir freuen uns auf euch!

*Lass dich als Seminarleitung schulen – komm zur SLS vom 02.-04.10.2026 in Kassel!*
Du hast Erfahrung als Teamer*in gesammelt, fühlst dich methodisch fit und suchst nach der nächsten Herausforderung? Als bereits erfahrene Seminarleitung wünschst du dir neuen Input und Gelegenheit zur Reflexion deiner Leitungsrolle? Dann komm zur Seminarleitungsschulung (SLS) vom 2.-4. Oktober 2026 in Kassel! 🚀In dieser Schulung werden die Basics vermittelt, die du als Seminarleitung kennen solltest, aber darüber hinaus gibt es auch Angebote für erfahrene Leitungen sich bspw. zum Umgang mit Menschenfeindlichkeit und Extremismus oder dem Thema Coaching weiterzubilden. Hier findest du mehr Infos zu den angebotenen Inhalten: https://intranet.yfu.de/article_tool/articles/2225. Melde dich gleich an!(https://forms.office.com/e/GKHKtJmCfy) Bei Fragen kontaktiere Rahel aus der GS (ehrenamt@yfu.de, Durchwahl -44).

*🚀 Powerstart ins Ehrenamt am 18. Juni von 19-20.30 Uhr*
Du möchtest aktiv werden oder wieder einsteigen und brauchst für den Start noch ein bisschen Orientierung? Dann haben wir einen Tipp für dich🔥! Starte mit unseren Ehrenamtlichen beim digitalen Powerstart ins Ehrenamt durch. Lerne das YFU 1x1, finde heraus, was es für dich zu tun gibt, wie du dich mit YFUler*innen in deiner Umgebung vernetzen kannst und welche Vorteile du als YFUler*in genießt. 
🔥 Anmeldung hier: https://tinyurl.com/jszynj7n*Online-KLT-Schulung am 02.07. um 19:30 Uhr – jetzt anmelden!
** Sonstiges / Externes
*📩 Dein YFU im Wandel – bleib aktuell mit dem Strukturkompass*
Die Strukturreform klingt groß und fühlt sich immer noch ziemlich abstrakt an. 

/Was bedeutet das alles für dein Ehrenamt und deine Mitgliedschaft?/
/Wie verändert sich YFU konkret?/
/Und wo kannst du dich in Zukunft einbringen und mitgestalten?/

Der Strukturkompass gibt dir Orientierung. 
Darin informieren dich Nate aus der AG Strukturreform und Julia aus der Geschäftsstelle regelmäßig über die aktuelle Lage, teilen wichtige Vereinsentscheidungen und Meilensteine, geben Einblicke hinter die Kulissen und zeigen dir, wo und wie du mitwirken kannst. 
Jetzt ein Abo dalassen – denn gemeinsam gestalten wir die Zukunft von YFU.
📩 Hier kannst du ihn abonnieren: https://mailing.yfu.de/f/333241-426684/

*Digitale Erstattungsanträge ab sofort live! 🎉*
Eure EAs könnt ihr ab jetzt ganz entspannt digital einreichen! Das Geld für Bahntickets, Einkäufe oder Ähnliches bekommt ihr damit viel unkomplizierter zurück. Alle Infos findet ihr hier: https://intranet.yfu.de/article_tool/articles/2224.
* Terminübersicht
** TERMINE 2026
*13.06. - 13.06.2026* &nbsp;&nbsp;&nbsp; Betreuungsschulung, *Berlin*

*20.06. - 21.06.2026* &nbsp;&nbsp;&nbsp; Colored Glasses Schulung, Liebfrauenschule Mühlhausen (*bei Duisburg*)

*18.09. -20.09. 2026* &nbsp;&nbsp;&nbsp; Colored Glasses Schulung, Jugendherberge Horner Rennbahn *Hamburg*

*02.10. - 04.10.2026*  &nbsp;&nbsp;&nbsp; Seminarleitungsschulung (SLS), Jugendherberge *Kassel*
*02.10. - 04.10.2026*  &nbsp;&nbsp;&nbsp; *(LG)* Aktivenwochenende

*06.11. – 08.11.2026* &nbsp;&nbsp;&nbsp; Colored Glasses Schulung, Jugendherberge *Kassel*

*20.11. - 22.11.2026* &nbsp;&nbsp;&nbsp; Betreuendenseminar, *Jugendherberge Stuttgart*

*27.11. - 29.11.2026* &nbsp;&nbsp;&nbsp; ÖA-Ausschusstreffen, *Hamburg*

*06.05. - 09.05.2027* &nbsp;&nbsp;&nbsp; BUT 2027, *tba*
