* Landesgruppe
**  Wichtige Info Aufrufe Newsletter
Diesen Newsletter findet ihr ab jetzt auch auf Whatsapp! Dafür einfach über diesen Link beitreten: https://chat.whatsapp.com/GBCBuLIU2U78zpim5yGxLF
---

Sehr gerne nehmen wir eure Aufrufe oder Danksagungen in den wöchentlichen Newsletter auf.

Schreibt mir ([[mailto://shh-newsletter@yfu-deutschland.de][shh-newsletter@yfu-deutschland.de]]) dafür einfach immer bis *Mittwochs 17:00 Uhr* eure Aufrufe, damit ich sie noch in den Newsletter der aktuellen Woche mit aufnehmen kann. Ansonsten nehme ich die Aufrufe natürlich gerne in den nächsten auf.

Vielen lieben Dank und ich freue mich auf eure Emails.

Liebe Grüße
Aimo
** Liebe Community,
wir haben wieder Neuigkeiten! ☀️

Bevor für viele unserer Austauschschüler*innen die Zeit in Deutschland zu Ende geht, möchten wir euch herzlich zu einem gemeinsamen Sommertreffen einladen. Zusammen wollen wir das schöne Wetter genießen, einen entspannten Nachmittag im Grünen verbringen.

📅 Wann? 14. Juni, um 15 Uhr
📍 Wo? Stadtpark Hamburg

Da der Stadtpark groß ist, treffen wir uns vor dem Lesecafé Stadtpark. Den Treffpunkt findet ihr hier: https://maps.app.goo.gl/jN2tsTRepqDfEPTH7

Gemeinsam suchen wir uns dann ein schönes Plätzchen für ein Picknick.
Damit wir am Ende ein buntes Buffet haben, freuen wir uns, wenn jede*r etwas zu essen zum Teilen mitbringt. Bitte denkt außerdem an eure eigenen Getränke, Teller und Besteck sowie, falls vorhanden, eine Picknickdecke.

Wenn ihr dabei seid, meldet euch bitte kurz über die [[https://forms.office.com/e/atAyzw3k4E][Umfrage]] an.

Wir freuen uns auf euch und auf einen schönen gemeinsamen Sommernachmittag!

Liebe Grüße
Leah, Aimo und Ole
* Öffentlichkeitsarbeit
** Schulvortrag am Gymnasium Brunsbüttel
Wann: flexibel möglich!
Meldet euch gerne bei kira.thede@yfu-deutschland.de
Wo: Gamnasium Brunsbüttel
Kopernikusstr. 1
22541 Brunsbüttel
** Infoabend mit AJAOrgas in Husum
Wann: 09.06.2026 19:00
Wo: Theodor-Storm-Schule
Ludwig-Nissen-Str. 62
25813 Husum
Wer: 1-2 Teamer jedes Erfahrungsgerades
Bei Interesse: kira.thede@yfu-deutschland.de
** Schulvortrag am Goethe-Gymnasium
Wann: 15.06.2026 15:00 (Teamtreffen 13:30)
Wo: Goethe-Gymnasium Hamburg (Altona)
Rispenweg 28, 22547 Hamburg
Wer: 1-2 Teamer jedes Erfahrungsgerades
Bei Interesse: kira.thede@yfu-deutschland.de
** Schulvortrag am Gymnasium Trittau
Wann: 18.06.2026
Wo: Gymnasium Trittau
Wer: 1-2 Teamer jedes Erfahrungsgerades
Bei Interesse: kira.thede@yfu-deutschland.de
* Aufnahmeprogramm
** Gf-Besuche
Liebe Landesgruppe,

Ich suche Besucher für potentielle Gastfamilien (Gf) in der
 -  Holnisser Landstr.
  in 24975 Husby
 - An der Obertrave
   in 23552 Lübeck
Wer hat Zeit und Lust, diese Besuche zu übernehmen? 😍
Ich freue mich über eure Rückmeldungen
Ines
 
Die Gesuche für Gastfamilienbesuche poste ich meist als erstes in einer WhatsApp- und Signalgruppe.
Wer Lust hat, dort über Gf-Infos auf dem Laufenden gehalten zu werden, hier die Links dazu:
https://chat.whatsapp.com/IekwaHKc6FgBzdp3n17RSV?mode=gi_t
und
https://signal.group/#CjQKID7eirjpYr-BVlu7PkLTR4tJVCiOkxkFkrrQV2nsBk6_EhBjyeu20bhbOLYOJVIBU8dT

Und sollten Fragen aufkommen, meldet euch gerne direkt bei mir
ines.hintz@yfu-deutschland.de 😃
** Betreuungsschulung in Berlin am 13. Juni
Liebe Regionalbetreuungskolleg*innen,
Liebe AP-Leitungen (da wo es noch keine RB's gibt 😉),

ich organisiere für den 13.06. eine überregionale Betreuungsschulung - als Tagesschulung - in Berlin, und es gibt noch freie Plätze!
Es sind zwar schon etliche Anmeldungen eingegangen, aber ich würde mich sehr freuen, wenn noch ein paar dazu kommen, damit es sich richtig lohnt.
Deshalb würde ich euch gerne um etwas bitten:
Könntet ihr die Einladung - siehe unten - in eure Landesgruppen-Verteiler, LG-WhatsApp-Gruppen, etc. leiten und ggf. auch an betreuungsinteressierte Personen senden, wenn ihr welche kennt?

Für eure Unterstützung wäre ich super dankbar!

Vielen Dank und liebe Grüße aus Berlin,
Caren
** Aufruf GF Re-Entry
Liebe Landesgruppe,

für unsere Gastfamilien- Re-Entry im Haus Warwisch am 07.06. suchen wir noch dringend Teamende (Erfahrung egal). Die Veranstaltung geht meistens ca. von 12-16 Uhr - die genauen Zeiten werden noch bestätigt. Es geht darum, mit den Gastfamilien die Erfahrung gemeinsam zu reflektieren und den Nachmittag anschließend mit einem Buffet gemeinsam mit den Austauschschüler*innen ausklingen zu lassen. 

Meldet euch super gerne bei mir (amilou.fehr@yfu-deutschland.de oder unter 01786122651), wenn ihr Lust auf einen spannenden Nachmittag habt! 

LG und danke euch
Amilou
* Entsendeprogramm
** Doch noch eine NBT teamen?
Liebe Landesgruppe,

vielen Dank an alle, die sich bereits über das überregionale Teamgesuch für eine unserer NBTs gemeldet haben! An alle, die die Frist verpasst haben: es ist noch lange nicht zu spät, denn wir freuen uns weiterhin über Meldungen von vielen motivierten Teammitgliedern und Leitungen!

Wir suchen noch:
| NBT   | Zeitraum (mit VNBT) | Ort                          | Gesucht werden ...                                              |
|-------+---------------------+------------------------------+-----------------------------------------------------------------|
| SHH 1 | 13.08. – 16.08.2026 | Spejdergården Tydal, Eggebek | Teamende, gerne auch Justees oder unerfahrenere Personen        |
| SHH 2 | 10.09. – 13.09.2026 | CISV – Haus, Hamburg         | Leitung oder Leitungsteam & Teamende jeglichen Erfahrungsgrades |
| SHH 3 | 01.10. – 04.10.2026 | Spejdergården Tydal, Eggebek | Leitung oder Leitungsteam & Teamende jeglichen Erfahrungsgrades |
Wenn ihr also Lust habt, die Austauschschüler*innen auf ihrem Rückkehrprozess zu begleiten, tolle Menschen zu sehen, YFU-Spirit zu verbreiten oder einfach mal wieder etwa für YFU zu machen oder noch Fragen habt, dann meldet euch gerne bei uns unter antonia.karg@yfu-deutschland.de oder greta.dahmen@yfu-deutschland.de.

Liebe Grüße
Greta & Antonia
* Externes und Überregionales
** Mitarbeiter-Gesuche/Stellen
*Es wird sportlich: Wir brauchen jetzt Gastfamilien für viele sportliche Jungs!*
Du bist aktiv bei ... Fußball? Basketball? Volleyball? Tennis? Tischtennis? Badminton? Schwimmen? Boxen? Karate? Rugby? Skifahren? American Football? Oder eine ganz andere Sportart? Für sehr viele sportliche Jungs aus ganz verschiedenen Ländern suchen wir jetzt Gastfamilien ab Sommer 2026. Gleichzeitig haben sich bisher mehr Familien bei YFU angemeldet, die gern ein Mädchen aufnehmen möchte. Daher brauchen wir jetzt deine Hilfe! Du kannst uns über deinen Sportverein oder dein Team unterstützen und einen Aufruf weiterleiten? Großartig! Melde dich bei Corinna (schmidt@yfu.de, -65)) für Vorlagen und Kurzprofile zu passenden Schüler*innen, die du direkt und ohne viel Aufwand in der WhatsApp-Gruppe und Co deines Vereins/Teams teilen kannst. Vielen Dank schon jetzt für dein Engagement!

*Familienbesucher*in in 45968 Gladbeck gesucht*
Wir haben eine engagierte Gastfamilie, die sich schon sehr auf ihr zukünftiges Gastkind freut. Was jetzt noch fehlt? Ein Familienbesuch!
Der Besuch sollte möglichst schnell, spätestens jedoch bis Ende Juni stattfinden.
Du wohnst in der Nähe von Gladbeck (NRW) oder hast Lust auf einen kleinen Ausflug? 😊 Dann melde dich für weitere Informationen bei Magdalene unter gastfamilien@yfu.de.
Auch wenn du bisher noch keine Erfahrung mit Familienbesuchen hast, aber grundsätzlich Interesse mitbringst, freuen wir uns sehr über deine Nachricht!
** Schulungen / Termine
*Online-KLT-Schulung am 02.07. um 19:30 Uhr – jetzt anmelden!*
Bewerbende für den nächsten YFU-Jahrgang kennenlernen und dabei von euren eigenen Erfahrungen berichten – das könnt ihr bei den digitalen Kennenlerntreffen (KLTs)! Eine etwa anderthalbstündige Online-Schulung dafür wird am Donnerstag, den 02.07. um 19:30 Uhr angeboten. Bei Interesse meldet euch unter kennenlernen@yfu.de – wir freuen uns auf euch!

*Colored Glasses Schulung am 18.-20. September in Hamburg – Starte jetzt dein Engagement für eine bunte Gesellschaft!*
Mit Colored Glasses Workshops begeistern wir Kinder und Jugendliche der 5. bis 13. Klasse an Schulen und Jugendeinrichtungen in ganz Deutschland für Vielfalt und Toleranz. Wir machen uns stark gegen Diskriminierung und Vorurteile durch spannende Simulationen und Diskussionen auf Augenhöhe! Die Schulung ist dein Start ins Ehrenamt: Wir zeigen dir, wie du einen Workshop planst und durchführst. Erfahrene Ehrenamtliche geben dir Tipps und Tricks, damit du auch ohne Vorerfahrung einen echten Unterschied machen kannst. Du bist zwischen 16 und 29 Jahre alt und willst aktiv werden? Melde dich zur kostenlosen Schulung am 18.-20. September in Hamburg hier an.  Bei Fragen wenden dich gerne an Nina unter roesch@yfu.de.

*Powerstart ins Ehrenamt am 18. Juni von 19-20.30 Uhr*
Du möchtest aktiv werden oder wieder einsteigen und brauchst für den Start noch ein bisschen Orientierung? Dann haben wir einen Tipp für dich🔥! Starte mit unseren Ehrenamtlichen beim digitalen Powerstart ins Ehrenamt durch. Lerne das YFU 1x1, finde heraus, was es für dich zu tun gibt, wie du dich mit YFUler*innen in deiner Umgebung vernetzen kannst und welche Vorteile du als YFUler*in genießt. 
🔥 Anmeldung hier: https://tinyurl.com/jszynj7n
** Sonstiges / Externes
*📩 Dein YFU im Wandel – bleib aktuell mit dem Strukturkompass*
Die Strukturreform klingt groß und fühlt sich immer noch ziemlich abstrakt an. 

/Was bedeutet das alles für dein Ehrenamt und deine Mitgliedschaft?/
/Wie verändert sich YFU konkret?/
/Und wo kannst du dich in Zukunft einbringen und mitgestalten?/

Der Strukturkompass gibt dir Orientierung. 
Darin informieren dich Nate aus der AG Strukturreform und Julia aus der Geschäftsstelle regelmäßig über die aktuelle Lage, teilen wichtige Vereinsentscheidungen und Meilensteine, geben Einblicke hinter die Kulissen und zeigen dir, wo und wie du mitwirken kannst. 
Jetzt ein Abo dalassen – denn gemeinsam gestalten wir die Zukunft von YFU.
📩 Hier kannst du ihn abonnieren: https://mailing.yfu.de/f/333241-426684/

*📝Umfrage zur Wertschätzung im Ehrenamt*
Ehrenamtliches Engagement ist das Herzstück von YFU – ohne euch wäre unsere Arbeit nicht möglich. Umso wichtiger ist es uns, besser zu verstehen, wie ihr eure ehrenamtliche Tätigkeit erlebt und in welchen Bereichen ihr euch mehr Wertschätzung wünscht. 
👉Daher möchten wir euch bitten, an dieser kurzen, anonymen [[https://forms.office.com/e/MLY2yUUbju?origin=lprLink][Umfrage]] teilzunehmen. Vielen Dank für eure Unterstützung! 💜

*Kostenlose Fortbildung „Conflictual Potentials: Training Courses on Conflict Transformation and Combating Othering” von planIMPACT e.V.*
Mit dem Projekt werden 25 Jugendleiter*innen, Aktivist*innen und Youth Worker dabei unterstützt, Kompetenzen in gewaltfreier Konflikttransformation, interkulturellem Verständnis und dem Abbau von Stereotypen und „Othering“ zu entwickeln — und das Gelernte als Multiplikator*innen in ihre lokalen Communities weiterzutragen. 31.08. – 07.09.2026 & 16.11. – 23.11.2026 (inklusive Reisetage) in Pullach/München; Reise-, Unterkunfts- und Verpflegungskosten werden durch das Projekt gedeckt; Voraussetzungen: Du bist über 18 und arbeitest mit Jugendlichen oder zu Jugendthemen. Ein B2-Niveau in Englisch ist erforderlich! Alle Infos [[https://medium.com/@planimpactgroup/e5c6b676b18d][hier]].
* Terminübersicht
** TERMINE 2026
*05.06. - 07.06.2026* &nbsp;&nbsp;&nbsp; *(LG)* Nord-LGT

*13.06. - 13.06.2026* &nbsp;&nbsp;&nbsp; Betreuungsschulung, *Berlin*

*20.06. - 21.06.2026* &nbsp;&nbsp;&nbsp; Colored Glasses Schulung, Liebfrauenschule Mühlhausen (*bei Duisburg*)

*18.09. -20.09. 2026* &nbsp;&nbsp;&nbsp; Colored Glasses Schulung, Jugendherberge Horner Rennbahn *Hamburg*

*25.09. - 27.09.2026* &nbsp;&nbsp;&nbsp; *(LG)* Aktivenwochenende

*02.10. - 04.10.2026*  &nbsp;&nbsp;&nbsp; Seminarleitungsschulung (SLS), Jugendherberge *Kassel*

*06.11. – 08.11.2026* &nbsp;&nbsp;&nbsp; Colored Glasses Schulung, Jugendherberge *Kassel*

*20.11. - 22.11.2026* &nbsp;&nbsp;&nbsp; Betreuendenseminar, *Jugendherberge Stuttgart*

*27.11. - 29.11.2026* &nbsp;&nbsp;&nbsp; ÖA-Ausschusstreffen, *Hamburg*

*06.05. - 09.05.2027* &nbsp;&nbsp;&nbsp; BUT 2027, *tba*
