* Landesgruppe
**  Wichtige Info Aufrufe Newsletter
Diesen Newsletter findet ihr ab jetzt auch auf Whatsapp! Dafür einfach über diesen Link beitreten: https://chat.whatsapp.com/GBCBuLIU2U78zpim5yGxLF
---

Sehr gerne nehmen wir eure Aufrufe oder Danksagungen in den wöchentlichen Newsletter auf.

Schreibt mir ([[mailto://shh-newsletter@yfu-deutschland.de][shh-newsletter@yfu-deutschland.de]]) dafür einfach immer bis *Mittwochs 17:00 Uhr* eure Aufrufe, damit ich sie noch in den Newsletter der aktuellen Woche mit aufnehmen kann. Ansonsten nehme ich die Aufrufe natürlich gerne in den nächsten auf.

Vielen lieben Dank und ich freue mich auf eure Emails.

Liebe Grüße
Aimo
** Einladung Landesgruppen-Wochenende SHH vom 02.10. bis 04.10.26 Villa Falkenstein (Kiel)
Liebe Landesgruppe,

hiermit übersende ich euch die Einladung zum Landesgruppenwochenende vom 02.10 bis 04.10.26 in der Villa Falkenhorst! Die Adresse lautet Villa Falkenhorst, Falkensteiner Strand 35, 24159 Kiel.

Wir starten am Freitag (02.10.) um 18 Uhr mit einem gemeinsamen Abendessen und am Sonntag (04.10.) geht es dann gegen 14 Uhr wieder nach Hause. Grundsätzlich könnt ihr euch aber auch für nur einzelne Tage (z.B. nur den Samstag) anmelden, falls ihr nicht alle drei Tage Zeit habt.

Bisher ist unser Aktivitätenplan noch nicht sehr gefüllt, weshalb wir uns über eure Rückmeldung/Angebote z.B. für Workshops mit YFU-Bezug, aber auch gerne Kreatives oder Sport freuen würden. Außerdem benötigen wir eure Unterstützung beim Einkaufen/Kochen für das Wochenende, sofern ihr dort unterstützen könnt, gebt bitte auch eine Rückmeldung.

Hier der Link für die Anmeldung:
[[https://forms.cloud.microsoft/e/jUMPju7Lgg][Anmeldung Landesgruppenwochenende 02.10.-04.10.2026]]

Mit Blick auf die Villa als Ort, bedenkt bitte:
Zum Übernachten braucht ihr zwingend einen Schlafsack/eine Decke (Bezug und Innenleben), sowie ein Kopfkissen samt Bezug und ein Bettlaken. Vor Ort gibt es nur Matratzen.
Weiterhin sind Hausschuhe und ein Handtuch von Vorteil.
Gerne könnt ihr auch Gesellschaftsspiele oder ähnliches mitbringen.

Wir freuen uns, euch vor Ort zu sehen!
Lena für den eLGV
** Jetzt anmelden: Public Viewing für die Mitgliederversammlung am 22.11. in der Geschäftsstelle
Liebe Landesgruppe,

Am 30.6. haben wir uns auf einer Mitgliederversammlung für eine neue Satzung entschieden. Damit steht der neuen Struktur nichts mehr im Wege und es wird schon fleißig daran gearbeitet, um den Übergang möglichst fließend hinzubekommen.

Am 22.11. findet die online Mitgliederversammlung statt, auf der wir die nächsten Schritte besprechen und alle Verantwortungsträger*innen und Gestalter*innen für die neue Struktur wählen. Die offizielle Einladung wird nach dem Sommer kommen.

Da die Mitgliederversammlung von 10-18 Uhr angesetzt ist (inkl. einer langen Mittagspause, also keine Angst) haben wir für diesen Tag die Geschäftsstelle reserviert und freuen uns, wenn wir gemeinsam an der Mitgliederversammlung teilnehmen werden. Anmelden könnt ihr euch hier: [[https://forms.cloud.microsoft/e/nDC41S1w9m][Anmeldung zum Public Viewing für die Mitgliederversammlung am 22.11.2026 – Formular ausfüllen]]

Wir freuen uns, wenn viele von euch an dem Tag dabei sind!
* Öffentlichkeitsarbeit
** Neue Schulvorträge und Messen
Liebe Landesgruppe SHH,

der Herbst ist in vollem Schwung und genauso ist es die ÖA-Arbeit in SHH. Vier Schulvorträge und eine Messe konnten schon erfolgreich stattfinden - danke an alle, die das möglich gemacht haben!
Damit sind wir aber noch lange nicht fertig und möchten gerne noch einige weitere Veranstaltungen auf die Beine stellen und dafür brauchen wir wie immer euch! 
Eine Übersicht der anstehenden Termine findet ihr unten. Ganz egal welcher Erfahrungsgrad, wir freuen uns über jede Meldung und über jede*n der ÖA für YFU betreibt!

Bei Interesse meldet euch bei kira.thede@yfu-deutschland.de für die Schulvorträge und bei dennisle-duy.nguyen@yfu-deustchland.de für die Messen.

Herbstliche Grüße von Aimo, Annina, Duy und Kira

| Veranstaltung                                              | Wo                                                          | Wann                                            |
|------------------------------------------------------------+-------------------------------------------------------------+-------------------------------------------------|
| Infoabend am Gymnasium Othmarschen                         | Walderseestraße 99, 22605 Hamburg                           | Di, 22.09.2026; ab 19 Uhr                       |
| Infoabend am Gymnasium Hochrad                             | Hochrad 2, 22605 Hamburg                                    | Di, 22.09.2026; 18-19:30 Uhr                    |
| Infoabend an der Julius-Leber-Schule                       | Halstenbeker Str. 41, 22457 Hamburg                         | Di, 29.09.2026; ca. 19 Uhr                      |
| Infoveranstaltung mit AFS & YFU                            | Gymnasium Hummelsbüttel                                     | Mi, 30.09.2026; Beginn 19 Uhr, Aufbau 18:30 Uhr |
| Schulvortrag (ohne Eltern) an der ahfs Uhlenhorst          | Bostelreihe 5, 22083 Hamburg                                | Fr, 09.10.2026; 10:45–11:45 Uhr                 |
* Entsendeprogramm
** NBT Teamingaufruf SHH3
Hallo zusammen,
für unsere NBT vom 02.10. bis 04.10. in Tydal suchen wir noch dringend motivierte Leitungen und Teamer*innen. Das Team reist bereits am 01.10. zur Vor-NBT an.
Aktuell suchen wir mindestens noch einen männlichen Teamer sowie eine Person mit gültigem Erste-Hilfe-Schein. Natürlich freuen wir uns aber über alle, die Lust haben, Teil des Teams zu werden!
Wenn ihr Interesse habt oder noch Fragen meldet euch gerne bei Antonia (antonia.karg@yfu-deutschland.de) oder Greta (greta.dahmen@yfu-deutschland.de)
* Externes und Überregionales
** Mitmachen/Stellen
*Dringend Leitungsteam und Teamende für NBT in zwei Wochen gesucht*
Für die SHH3-NBT vom 02.-04.10. (Teamanreise: 01.10.) suchen wir dringend ein Leitungsteam und einige Teamende. Die NBT findet in 24825 Eggebek statt – wir freuen uns über jede Unterstützung! Melde dich bei Antonia unter antonia.karg@yfu-deutschland.de

*Team für die USA for you-Auswahl gesucht (14./15.11.26 in Hamburg)*
Im Frühjahr 2027 dürfen wieder 15 Jugendliche aus Hamburg für 14 Tage mit einem Vollstipenidum in die USA reisen und Land und Leute und besonders das ehrenamtliche Engagement dort kennenlernen. 
Am 14. und 15.11. findet die Auswahl in Hamburg statt und wir suchen noch zwei Team-Mitglieder für Gruppen- und Einzelgespräche. Idealerweise kommst du aus Hamburg oder aus der Nähe und hast ein bisschen oder auch mehr Auswahl-/KLT-Erfahrung. 
Meldet euch gern bei Thekla unter usaforyou@yfu.de oder Durchwahl -77 

*Letzte Betreuungen in Bayern gesucht:*
Inzwischen sind bis auf wenige Ausnahmen alle Austauschschüler*innen des Jahrganges 2026/2027 angereist. Leider fehlen und noch einige Betreuungen in Bayern:
| 82538 Geretsried | Markus   | m | Norwegen |                                 |
| 96242 Sonnefeld  | Fernando | m | Chile    | eine Co-Betreuung gibt es schon |
Wenn ihr euch vorstellen könnt, eine dieser Betreuungen zu übernehmen, ggfs. auch als Fernbetreuung, meldet euch bitte bei Lena und Miriam unter ap-betreuung@yfu.de

Auswahlleitungen und Einzelgesprächsleitungen für die PPP-Auswahlen gesucht*
Die Bewerbungssaison für den PPP-Jahrgang 2027/28 hat begonnen und zahlreiche Jugendliche warten auf ihre PPP-Auswahl. Dafür suchen wir immer noch dringend Auswahlleitungen und Einzelgesprächsleitungen. Vor allem in Bremen, Münster, Passau, Dresden und Berlin sind wir fehlen uns noch Leitungsmeldungen. 
Wenn Du Dir vorstellen kannst, diesen Herbst eine Auswahl zu leiten oder als Einzelgesprächsleitung zu begleiten, fülle bitte diese kurze Umfrage aus: PPP-Auswahlleitungen 2026 – Formular ausfüllen
Bei Fragen melde Dich gerne bei Keira (keira.geiss@yfu.de)

*Teams und Schlafplätze für PPP-Auswahlen gesucht*
Für die PPP-Auswahlen suchen wir Teamende mit und ohne Erfahrung in ganz Deutschland! Die Auswahlen für das PPP (ein Austauschstipendium) sind ähnlich wie Kennenlerntreffen, aber in Präsenz und intensiver. Die Termine findest Du in der Umfrage:  Termine PPP-Auswahl 2026 – Formular ausfüllen In der Umfrage kannst Du außerdem angeben, ob Du ggf. einen Schlafplatz für Teamende anbieten kannst.
Bei Interesse oder Fragen melde Dich bitte bei Keira (keira.geiss@yfu.de).Danke!

*Übernimm Verantwortung für Vielfalt mit YFU an Schulen in ganz Deutschland – komm ins Team Colored Glasses!*
Ab 2027 ist Colored Glasses mit der neuen YFU-Struktur ein offizieller Bereich im Verein. Dadurch gibt es einige neue Posten zu besetzen und wir stellen uns richtig gut auf. Insbesondere suchen wir Verstärkung im Bereich der Workshopkoordination, beim Marketing und im Team Community & Fortbildung. Du hast Interesse, dabei zu sein? Fülle jetzt die Umfrage aus. Für Rückfragen wende dich gerne an den Colored Glasses Vorstand unter vorstand@coloredglasses.de.

*Stellenausschreibung für das Team Entsendeprogramm in der Geschäftsstelle:*
Wir suchen eine*n neue*n Mitarbeiter*in für unser Team Programmorganisation! Ihr findet die Ausschreibung für die Stelle Programmassistent*in auf unserer Website: https://www.yfu.de/ueber-yfu/jobs-praktika Die Stelle ist für 12 Monate befristet. Falls bei dir Veränderungen anstehen und du gerade auf Jobsuche bist, schaue dir doch bitte unsere Ausschreibung an und melde dich gern, wenn du Fragen oder Interesse hast, bei Meike (neumann@yfu.de) und Simone (held@yfu.de).

*Zwei Programmbegleitungen für „USA for you – Hamburg“ gesucht (Kurzaustauschprogramm in die USA vom 26. Februar bis 13. März 2027)*
Im Frühjahr 2027 fliegen 15 Jugendliche aus Hamburg in den Kurzaustausch in den USA und wir suchen noch zwei Begleitungen für die Reise. Infos findest du hier: https://intranet.yfu.de/article_tool/articles/2227 
Bei Fragen meldet euch gern bei Thekla de Carvalho Rodrigues in der Geschäftsstelle (usaforyou@yfu.de; Durchwahl -77). Bei Interesse füllt bitte den Fragebogen unter folgendem Link aus und wir melden uns dann: https://forms.cloud.microsoft/e/Ga0KnVVREw
** Termine/Schulungen
*Colored Glasses Schulung am 06.-08. November in Kassel – Starte jetzt dein Engagement für eine bunte Gesellschaft!*
Mit Colored Glasses Workshops begeistern wir Kinder und Jugendliche der 5. bis 13. Klasse an Schulen und Jugendeinrichtungen in ganz Deutschland für Vielfalt und Toleranz. Wir machen uns stark gegen Diskriminierung und Vorurteile durch spannende Simulationen und Diskussionen auf Augenhöhe! Die Schulung ist dein Start ins Ehrenamt: Wir zeigen dir, wie du einen Workshop planst und durchführst. Erfahrene Ehrenamtliche geben dir Tipps und Tricks, damit du auch ohne Vorerfahrung einen echten Unterschied machen kannst. Du bist zwischen 16 und 29 Jahre alt und willst aktiv werden? Melde dich zur kostenlosen Schulung an. Gerne weitersagen, auch an Interessierte ohne YFU-Hintergrund! 06.-08. November in Kassel | Zur Anmeldung | Flyer als PDF - Bei Fragen wenden dich gerne an Nina unter roesch@yfu.de.

*Betreuungsluft schnuppern? Jetzt zum Betreuendenseminar anmelden!*
Auf unserem Betreuendenseminar erfahrt ihr mehr über die Betreuungsarbeit allgemein und grundlegende Gesprächstechniken, die Betreuende benutzen, um Austauschschüler*innen und Gasteltern bei der Lösung von Problemen zu helfen. Es gibt Input und Übungen zu Aktivem Zuhören, Gezieltem Fragen, dem Herausarbeiten konstruktiver Ansätze, der Beobachtung und Interpretation von Kommunikationsverhalten sowie der Strukturierung eines Gespräches. Auch Besuche und Berichte werden Thema sein. Wir freuen uns auf euch! 
📅6.-8.11.2026
📍Präsenz in Stuttgart
🦸‍♀️🦸‍♂️ Trainer*innen: Julianna Bisang & N.N.
✅ Anmeldung bis 5.10.: Anmeldung zum Betreuendenseminar in Stuttgart (6.-8.11.2026) – Formular ausfüllen
💰YFU übernimmt die Kosten für Übernachtung, Verpflegung und Anreise mit der Bahn (2. Klasse) 
** Sonstiges
*Movers of Tomorrow Award: Deine Stimme für Sela*
Die engagierte Kulturtauchen-Teamerin Sela bewirbt sich für den "Movers of Tomorrow Award" und freut sich über viele Stimmen. Sie spricht in ihrem Video auch von ihren Workshops an Schulen (über Schule Global) - und insgesamt von der Bedeutung von ehrenamtlichem Engagement für unsere Gesellschaft. Bitte anschauen und für Sela abstimmen: https://movers-of-tomorrow-award.de/videos/nicht-nur-zuschauen-geschichte-schreiben/

*🌍 Mit YFU Polen nach Krakau und Warschau reisen*
YFU Polen bietet im Schuljahr 2026/27 wieder spannende 4-tägige Städtetrips für Austauschschüler*innen an. *Und auch  Ehrenamtliche dürfen dabei sein*. Die Programme verbinden Sightseeing, Geschichte und Kultur. Gleichzeitig bieten sie dir eine tolle Gelegenheit, andere YFUler*innen kennenzulernen und gemeinsam Polen zu entdecken.
📍 Krakau | 05.–08.11.2026 | 399 €
📍 Warschau | 04.–07.03.2027 | 399 €
📍 Krakau | 22.-25.04.2027| 399 €
Im Preis enthalten sind Unterkunft, Verpflegung, Eintritte, Englische-Guides, ÖPNV, Gruppenversicherung und Support von YFU Polen. Die Reisekosten werden nicht übernommen.
👉 Die Plätze sind begrenzt und werden nach dem Prinzip „first come, first served“ vergeben!
Hier könnt ihr euch anmelden:
Kraków #1: https://forms.gle/XafpAYPo58SdSRFw6
Warsaw: https://forms.gle/LTADk5vKSJjNtPRF9
Kraków #2: https://forms.gle/mmXRJCtSFViLk38H9 
* Terminübersicht
** TERMINE 2026
*18.09. -20.09. 2026* &nbsp;&nbsp;&nbsp; Colored Glasses Schulung, Jugendherberge Horner Rennbahn *Hamburg*

*02.10. - 04.10.2026* &nbsp;&nbsp;&nbsp; Seminarleitungsschulung (SLS), Jugendherberge *Kassel*
*02.10. - 04.10.2026* &nbsp;&nbsp;&nbsp; *(LG)* Aktivenwochenende
*02.10. - 04.10.2026*  &nbsp;&nbsp;&nbsp; Überregionale Teamingeinweisung, Jugendherberge *Kassel*

*06.11. - 08.11.2026* &nbsp;&nbsp;&nbsp; Colored Glasses Schulung, Jugendherberge *Kassel*
*06.11. - 08.11.2026* &nbsp;&nbsp;&nbsp; Betreuendenseminar, *Jugendherberge Stuttgart*

*22.11.2026* &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; *(LG)* Mitgliederversammlung, *Geschäftsstelle*

*27.11. - 29.11.2026* &nbsp;&nbsp;&nbsp; Großes ÖA-Mäuse-Treffen, *Hamburg*

*06.05. - 09.05.2027* &nbsp;&nbsp;&nbsp; BUT 2027, *tba*
