* Landesgruppe
**  Wichtige Info Aufrufe Newsletter
Diesen Newsletter findet ihr ab jetzt auch auf Whatsapp! Dafür einfach über diesen Link beitreten: https://chat.whatsapp.com/GBCBuLIU2U78zpim5yGxLF
---

Sehr gerne nehmen wir eure Aufrufe oder Danksagungen in den wöchentlichen Newsletter auf.

Schreibt mir ([[mailto://shh-newsletter@yfu-deutschland.de][shh-newsletter@yfu-deutschland.de]]) dafür einfach immer bis *Mittwochs 17:00 Uhr* eure Aufrufe, damit ich sie noch in den Newsletter der aktuellen Woche mit aufnehmen kann. Ansonsten nehme ich die Aufrufe natürlich gerne in den nächsten auf.

Vielen lieben Dank und ich freue mich auf eure Emails.

Liebe Grüße
Aimo
** Communitea Anmeldung
Liebe Community,

wir haben wieder Neuigkeiten! 🐣
Wir möchten euch herzlich zu einem frühlingshaften Communitea-Treffen einladen. Gemeinsam wollen wir mit den Austauschschüler*innen ein bisschen Ostern feiern und einen entspannten Nachmittag miteinander verbringen.

📅 Wann? 3. April, um 11 Uhr 
📍 Wo? Geschäftsstelle

Wir wollen gemeinsam Ostereier bemalen und die Frühlingszeit einläuten. Wer mag, kann außerdem gerne Snacks oder andere Kleinigkeiten zum Teilen mitbringen. Außerdem wäre es hilfreich, wenn alle bereits ausgepustete Eier mitbringen könnten.

Wenn ihr dabei seid, meldet euch bitte kurz [[https://forms.office.com/?redirecturl=https%3a%2f%2fforms.office.com%2fPages%2fDesignPageV2.aspx%3fsubpage%3ddesign%26FormId%3dQqKWNFDLrkCVZmI1B908iefgPGIVnodAt7lfuSHL-ZJUNjUyWFpBUzhIUVFMOU1YVllNRVZFSFJHWS4u&auth_pvr=OrgId][hier]] an.
Wir freuen uns auf euch und auf ein gemütliches Treffen!

Liebe Grüße 
Leah, Aimo und Ole
* Öffentlichkeitsarbeit
** Neue Infos
Liebe Landesgruppe,

bald sind die Märzferien vorbei und wir suchen wieder eure Unterstützung.
Wenn ihr Zeit und Lust habt meldet euch gerne bei [[mailto:sophie.schnipkoweit@yfu-deitschland.de][sophie.schnipkoweit@yfu-deitschland.de]] oder bei [[mailto:kira.thede@yfu-deutschland.de][kira.thede@yfu-deutschland.de]]
** Schulvortrag am Gymnasium Brunsbüttel
Wann: Flexible Absprache mit Ansprechpartner der Schule

Wo:
Gymnasium Brunsbüttel
Kopernikusstr. 1
25541 Brunsbüttel

Wer: 2-3 erfahrene und unerfahrene Personen
** Schulvortrag am Gymnasium Farmsen
Wann: Am 14.04.2026; Beginn um 18 Uhr

Wo:
Gymnasium Farmsen
Swebenhöhe 50
22159 Hamburg

Wer: 1-2 erfahrene sowie unerfahrene Personen 

Meldet euch hier gerne bei Kira (kira.thede@yfu-deutschland.de)
** Schulvortrag am Johanneum Lüneburg
Wann: 23.04.2026, Vormittags

Wo:
Johanneum Lüneburg
Theodor-Heuss-Str. 1
21337 Lüneburg

Wer: 2-3 erfahrene und unerfahrene Personen 
* Aufnahmeprogramm
** Teamende für die ATS-Spaßveranstalltung
Liebe Ehrenamtliche im Aufnahmeprogramm,

beim letzten Communitea-Treffen waren viele Austauschschülerinnen dabei – was uns natürlich sehr gefreut hat! Gleichzeitig haben wir gemerkt, dass ein paar mehr Ehrenamtliche schön gewesen wären, um sich besser zu mischen, ins Gespräch zu kommen und gemeinsam Aktivitäten zu machen.

Deshalb möchten wir euch herzlich einladen, beim nächsten Communitea-Treffen dabei zu sein und ein bisschen Zeit mit den Austauschschülerinnen zu verbringen.

📅 Wann? 3. April, um 11 Uhr 
📍 Wo? Geschäftsstelle

Wir wollen gemeinsam Ostereier bemalen, uns austauschen und einen gemütlichen Vormittag verbringen. Wer möchte, kann außerdem gerne Snacks oder andere Kleinigkeiten zum Teilen mitbringen. Außerdem wäre es hilfreich, wenn alle bereits ausgepustete Eier mitbringen könnten.

Wenn ihr Zeit und Lust habt, vorbeizukommen, meldet euch bitte kurz [[https://forms.office.com/?redirecturl=https%3a%2f%2fforms.office.com%2fPages%2fDesignPageV2.aspx%3fsubpage%3ddesign%26FormId%3dQqKWNFDLrkCVZmI1B908iefgPGIVnodAt7lfuSHL-ZJUNjUyWFpBUzhIUVFMOU1YVllNRVZFSFJHWS4u&auth_pvr=OrgId][hier]] an. Wir freuen uns sehr über jede*n, der oder die dabei ist!

Liebe Grüße 
Leah, Aimo und Ole
* Externes und Überregionales
** Mitarbeiter-Gesuche/Stellen
*Leitung eines vierwöchigen Sommerkurses für US-amerikanische Austauschschüler*innen*
Du hast vom 25. Juli-21. August 2026 noch nichts vor, hast Erfahrung in der Leitung von Teams sowie in der Jugendarbeit? Englisch beherrscht du im Schlaf und eine Ersthelfer*innen-Ausbildung bringst du auch mit? Dann suchen wir genau 👉dich für die Leitung des PPP-Sprachcamps in Bonn. Das genaue Anforderungsprofil sowie die Aufgabenbeschreibung findest du [[https://www.yfu.de/ueber-yfu/jobs-praktika][hier]].
📧Fragen und Interessensbekundungen schickst du bitte Sophia (ap-seminare@yfu.de).

*Vierwöchiges interkulturelles Training und Betreuung für US-amerikanische Austauschschüler*innen*
Im Sommer reisen 42 PPP-Stipendiat*innen aus den USA für ihren Austausch nach Deutschland. Du hast Lust, sie bei ihren ersten Wochen in Bonn zu begleiten, interkulturelle Trainings durchzuführen, ihnen bei Rat und Tat zur Seite zu stehen sowie ein buntes Rahmenprogramm zu entwerfen? Für den 25. Juli-21. August 2026 steht noch nichts in deinem Kalender 📅 ? Dann komm ins Team des PPP-Sprachcamps 🚀. Die genauen Bewerbungsvoraussetzungen und Aufgabenbeschreibungen findest du [[https://www.yfu.de/ueber-yfu/jobs-praktika][hier]] 🔎.
📧Fragen und Interessensbekundungen schickst du bitte Sophia (ap-seminare@yfu.de).

*🎧 Das Podcast-Team von „YFU – In der Welt zu Hause“ sucht Verstärkung!*
Hannah, Greta und Jana suchen ehrenamtliche Unterstützung für ihren YFU‑Podcast, in dem regelmäßig spannende Menschen aus der Austauschwelt zu Wort kommen.
💡 Deine Aufgaben: Von der ersten Idee über die Gästekommunikation und Interviews bis hin zum Schnitt und zur kreativen Aufbereitung der Folgen – du kannst den gesamten redaktionellen Prozess mitgestalten.
✨ Wen wir suchen: Ob im Audio-Rampenlicht vor dem Mikro oder lieber im Hintergrund am Schnittprogramm – im Podcast-Team ist für jede Rolle etwas dabei. Wenn du bereits Erfahrung mit Audio- oder Schnittprogrammen hast, ist das natürlich ein Plus. Aber vor allem zählen Neugier, Lust auf Podcasting und die Motivation, gemeinsam etwas aufzubauen. Vorkenntnisse werden keine benötigt.
⏱️ Dein Zeitaufwand: Mit 3–10 Stunden im Monat kannst du Teil des Teams werden – je nach Rolle und dem, was gerade bei dir zeitlich passt
🌍 Klingt nach dir? Dann melde dich bei uns unter podcast@yfu-deutschland.de
Wir freuen uns auf frischen Wind im Podcast-Team! 🎤✨

*Teamende für Oral English Tests gesucht*
Für die Austauschorganisation FLAG in den USA benötigen unsere Austauschschüler*innen einen Oral English Test. In den kommenden Wochen finden die letzten Tests der Saison statt und für diesen Endspurt brauchen wir nochmal eure Unterstützung! Es handelt sich um lockere, etwa 20- bis 30-minütige Telefonate auf Englisch. Die Themen für die Gespräche können frei gewählt werden. Im Anschluss wird ein Auswertungsbogen ausgefüllt. Die Oral English Tests lassen sich sehr individuell planen, du kannst selbst einen Termin für das Gespräch mit den Austauschschüler*innen vereinbaren und kannst so dein Engagement für dich passend planen. Hast du in den nächsten zwei bis drei Wochen ein bisschen Zeit und Lust, uns bei den Oral English Tests zu unterstützen und mit ein paar zukünftigen Austauschschüler*innen interessante Gespräche zu führen? Dann melde dich unter usa@yfu.de bei Lisa – ich freue mich, von dir zu hören!
 
*🚀 Startschuss OWO-Leitungs- & Teamsuche*
Die AP-Platzierung hat begonnen und wir freuen uns auf einen neuen Schwung an ATS, die mit voller Vorfreude in ihr Austauschjahr in Deutschland starten. Dafür suchen wir für die OWOs wieder nach motivierten Leitungen und Teamenden! Du hast im August 2026 noch nichts vor und hast Lust auf viele tolle ATS? 👉 Dann melde dich bei Mareen (📧 ap-seminare@yfu.de) oder fülle diese [[https://forms.office.com/e/KYWzZNfDNt?origin=lprLink][Umfrage]] aus. Alle weiteren Infos findest du [[https://intranet.yfu.de/downloads/files/3970][hier]].
 
*Reisebegleitungen für den Sommer 2026 gesucht ✈️*
Du hast Lust eine Schüler*innen-Gruppe per Flug, Zug oder Fähre in ihren Austausch zu begleiten? Die Chance zu nutzen und etwas Neues kennenzulernen? Oder etwas Liebgewonnenes erneut zu besuchen? Dann fülle bitte bis zum 31. März die Umfrage [[https://www.yfu-survey.org/poll/index.php/124258?lang=de-informal][Reisebegleitungen 2026]] aus. Du solltest zum Zeitpunkt der Reise mindestens 21 Jahre alt sein. Auf der Startseite der Umfrage findest du die Länder und Reisedaten. Bei Fragen wende dich gerne direkt an Miriam (reise@yfu.de).

*🚀 Powerstart-Verstärkung gesucht – komm ins Powerstart-Team!*
Unser Powerstart-Team möchte wachsen. Ab sofort suchen wir erfahrene Ehrenamtliche, die sich bei YFU gut auskennen und anderen souverän über das Ehrenamt berichten können. Gerne auch Ehrenamtliche, die schon etwas mehr Lebenserfahrung mitbringen und die Elterngeneration ansprechen können.
Was springt für dich dabei raus?  Du kannst dir deinen Einsatz flexibel nach Absprache einteilen, viele neue Leute kennenlernen, deine Moderationskompetenzen erweitern und hast ein starkes Team an deiner Seite. 💪 Klingt nach einer Aufgabe für dich? Melde dich bei Julia aus der Geschäftsstelle (kastner@yfu.de).
** Schulungen / Termine
*🚀 Powerstart ins Ehrenamt am 9. April um 19 Uhr mit Julia und Ines*
Du möchtest aktiv werden oder wieder einsteigen und brauchst für den Start noch ein bisschen Orientierung? Dann haben wir einen Tipp für dich🔥! Starte mit unseren Ehrenamtlichen beim digitalen Powerstart ins Ehrenamt durch. Lerne das YFU 1x1, finde heraus, was es für dich zu tun gibt, wie du dich mit YFUler*innen in deiner Umgebung vernetzen kannst und welche Vorteile du als YFUler*in genießt.
🔥 Anmeldung und weitere Termine hier: https://sway.cloud.microsoft/WKISSAGmmiab4CYG

*Datenschutz kompakt: Online-Einweisungen am Dienstag 14.4. um 20 Uhr und Mittwoch 20.5. um 18.30 Uhr!*
Die nächsten digitalen Datenschutzeinweisungen (ungefähr 45 min.) für Referent*innen, Gremienmitglieder und alle Interessierte finden statt am
Dienstag , 14. April um 20.00 Uhr
Mittwoch, 20. Mai um 18.30 Uhr
Wir freuen uns über alle, die dabei sind – gerne auch weitersagen!
Meldet euch unter datenschutz@yfu.de an. Weitere Infos folgen dann per mail. Mehr zum Thema Datenschutz bei YFU findet ihr im [[https://intranet.yfu.de/downloads/files?category=41][Intranet]]. Unsere aktuellen [[https://www.yfu.de/datenschutz][Datenschutzhinweise]] stehen auf unserer Webseite zur Verfügung.
** Sonstiges / Externes
*📢 Petition Freiwilligendienste für die Jugend erhalten #aktionrettetkulturweit!*
Der internationale Freiwilligendienst kulturweit soll eingestellt werden. Seit vielen Jahren bietet das Programm jungen Menschen die Möglichkeit, für mehrere Monate in Kultur‑ und Bildungsprojekten weltweit mitzuwirken und internationale Zusammenarbeit aus erster Hand zu erleben. Eine Petition setzt sich dafür ein, die geplante Einstellung des Programms zu überprüfen und eine langfristige Finanzierung von kulturweit sicherzustellen.
👉 Wenn euch das Thema wichtig ist, dann könnt ihr [[https://weact.campact.de/petitions/kurzt-uns-nicht-weg-bildungsarbeit-starken-freiwilligendienst-kulturweit-erhalten-rettetkulturweit?source=rawlink&utm_medium=recommendation&utm_source=rawlink&share=3701606a-2c11-4d93-999d-af0bad21c230][hier]] ein Zeichen setzen!
 
*Alles rund um die Strukturreform – FAQ*
Dieses Jahr wird entschieden, wie das Vereinsleben von YFU in Zukunft aussehen soll. Viele Fragen werden gestellt: Was bedeuten die Veränderungen für Ehrenamtliche und Mitglieder? Wie sehen die neuen Organe aus? Wer entscheidet in Zukunft über den Verein? Damit ihr gut informiert seid, haben wir ein FAQ zur Strukturreform für euch zusammengestellt, das alle wichtigen Fragen transparent beantwortet: [[https://sway.cloud.microsoft/75ukJpXLBadjHr2v][Zum FAQ-Strukturrefor]]

*Abschlussevent Gastfamilienkampagne am 26. März - jetzt anmelden!*
Euer Engagement, eure Offenheit und eure Erfahrungen haben die Kampagne [[https://austausch-braucht-gastfamilien.de/][„Offene Türen, offene Herzen – Austausch braucht Gastfamilien“]] getragen und lebendig gemacht. Zum Abschluss der Kampagne laden der AJA und seine Mitgliedsorganisationen euch herzlich zu einer Online-Veranstaltung ein, bei der wir gemeinsam Bilanz ziehen, zurückblicken, voneinander lernen und nach vorn schauen.
📅 Donnerstag, 26. März 2026, 🕕 18:00–19:45 Uhr, 💻 via Zoom
Wir freuen uns sehr, wenn Ihr euch die Zeit nehmt und eure Erfahrungen, Gedanken und Ideen einbringt.  Anmeldung unter: https://us06web.zoom.us/meeting/register/mFrPO6xCTgKYGA3jHJi1dQ

*🌍 YFU Global feiert “75 Years of Home”!*
Seit 75 Jahren schaffen YFU-Programme weltweit Begegnungen, in denen aus Fremden enge Vertraute und aus Ländern zweite Heimaten werden.
Gemeinsam mit dem Global Office feiern wir in den kommenden Monaten unser Netzwerk, liefern euch spannende Facts über YFU und zeigen Stories von Austauschschüler*innen, Gastfamilien und Ehrenamtlichen – Menschen, die YFU seit Jahrzehnten prägen.
👉 Begleitet die internationale Kampagne auf Instagram: https://www.instagram.com/yfu_global/?hl=de – folgen, liken & teilen erwünscht!
💜 Und freut euch doppelt: 2027 feiern wir 70 Jahre YFU Deutschland – stay tuned! 

*Werde Teil der “75 Years of Home” Jubiläums-Kampagne – share your YFU-Story!*
💜 YFU volunteers, we would like to hear from you! Behind every YFU exchange are the incredible volunteers who dedicate their time, energy, and passion to making these life-changing experiences possible. You are the heart and soul of YFU and have been since YFU started 🫶
As we celebrate 75 Years of Home, we would love to learn about and share your YFU story. Whether it’s a meaningful moment, a lesson you learned, or a memory that stayed with you over the years - your experience is part of the YFU journey and deserves to be spread.
Share your story with us and inspire the next generation of YFUers 🗣️
📋 You can submit your story by filling out the form below: https://lnkd.in/erJE4ejn

*🤔 Kurz nachgefragt: Warum bist du (kein) YFU-Mitglied?*
Mitglied sein bei YFU bedeutet für viele: verbunden bleiben, Stimme geben, mitgestalten. Aber: Das ist nicht für alle gleich. Damit wir unsere Angebote und Kommunikation rund um unsere Mitgliedschaft verbessern können, fragen wir dich nach deiner Motivation und nach möglichen Stolpersteinen.
👉 Nimm dir 2 Minuten Zeit für unsere anonyme Umfrage: https://forms.cloud.microsoft/e/sDzSVHbNih
* Terminübersicht
** TERMINE 2026
*20.03. - 22.03.2026* &nbsp;&nbsp;&nbsp; Gremiensitzung Frühjahr, Jugendherberge Horner Rennbahn *Hamburg*

*27.03. - 29.03.2026* &nbsp;&nbsp;&nbsp; Betreuendenseminar in *Bad Bevensen*

*15.05. - 17.05.2026* &nbsp;&nbsp;&nbsp; Colored Glasses Schulung, Jugendherberge Burg Schwaneck (*bei München*)

*29.05 - 31.05.2026* &nbsp;&nbsp;&nbsp; ÖA-Ausschusstreffen, *Hamburg*

*05.06. - 07.06.2026* &nbsp;&nbsp;&nbsp; *(LG)* Nord-LGT

*13.06. - 13.06.2026* &nbsp;&nbsp;&nbsp; Betreuungsschulung, *Berlin*

*20.06. - 21.06.2026* &nbsp;&nbsp;&nbsp; Colored Glasses Schulung, Liebfrauenschule Mühlhausen (*bei Duisburg*)

*18.09. -20.09. 2026* &nbsp;&nbsp;&nbsp; Colored Glasses Schulung, Jugendherberge Horner Rennbahn *Hamburg*

*25.09. - 27.09.2026* &nbsp;&nbsp;&nbsp; *(LG)* Aktivenwochenende

*02.10. - 04.10.2026*  &nbsp;&nbsp;&nbsp; Seminarleitungsschulung (SLS), Jugendherberge *Kassel*

*06.11. – 08.11.2026* &nbsp;&nbsp;&nbsp; Colored Glasses Schulung, Jugendherberge *Kassel*

*20.11. - 22.11.2026* &nbsp;&nbsp;&nbsp; Betreuendenseminar, *Jugendherberge Stuttgart*

*27.11. - 29.11.2026* &nbsp;&nbsp;&nbsp; ÖA-Ausschusstreffen, *Hamburg*
