* Landesgruppe
**  Wichtige Info Aufrufe Newsletter
Diesen Newsletter findet ihr ab jetzt auch auf Whatsapp! Dafür einfach über diesen Link beitreten: https://chat.whatsapp.com/GBCBuLIU2U78zpim5yGxLF
---

Sehr gerne nehmen wir eure Aufrufe oder Danksagungen in den wöchentlichen Newsletter auf.

Schreibt mir ([[mailto://shh-newsletter@yfu-deutschland.de][shh-newsletter@yfu-deutschland.de]]) dafür einfach immer bis *Mittwochs 17:00 Uhr* eure Aufrufe, damit ich sie noch in den Newsletter der aktuellen Woche mit aufnehmen kann. Ansonsten nehme ich die Aufrufe natürlich gerne in den nächsten auf.

Vielen lieben Dank und ich freue mich auf eure Emails.

Liebe Grüße
Aimo
* Öffentlichkeitsarbeit
** Schulvortrag am Gymnasium Brunsbüttel
Wann: flexibel möglich!
Meldet euch gerne bei kira.thede@yfu-deutschland.de
Wo: Gamnasium Brunsbüttel
Kopernikusstr. 1
22541 Brunsbüttel
* Aufnahmeprogramm
** Leitungen und Teamende für Gastfamilienvorbereitung gesucht
Liebe Landesgruppe,
 
die neue AP-Saison steht in den Startlöchern und wir sind auf der Suche nach Leuten, die unsere nächsten Gastfamilien vorbereiten wollen. Wir haben schon einige motivierte Gastfamilien, die auf den Start des Austausches warten und so viele Informationen wie möglich erhalten wollen. Die GF-Vorbereitung soll sie so gut es geht auf den Austausch vorbereiten und ganz viele offene Fragen klären.
Für die Gastfamilien Vorbereitung suchen wir zurzeit Menschen, die Lust hätten, an einem Tag ihrer Wahl (am besten am Wochenende, jedoch eignen sich ggf. auch Wochentage abends) die neuen Gastfamilien auf ihren Austausch vorzubereiten in der Geschäftsstelle.
Zur Vorbereitung unserer Gasteltern soll es im Sommer zwei-drei Termine geben. 
Termine in den Zeiträumen Ende Juli und August würden sich hier gut eignen, damit wir die Sommerferien frei halten können.  

Du würdest die Veranstaltung vor Ort leiten oder teamen, eventuell mit einer Person deiner Wahl zusammen. Eine Präsentation gibt es bereits.
Meldet euch gerne, wenn ihr interessiert seid, eine oder mehrere GF-Vorbereitung(en) zu leiten oder zu teamen. Noch sind die Termine flexibel. Meldet euch sehr gerne mit konkreten Terminvorschlägen. 

Wir freuen uns auf eure Rückmeldungen an Amilou oder mich (theda.schmidtko@yfu-deutschland.de)
 
Liebe Grüße,
Theda
* Entsendeprogramm
** Auswahlleitungen und Einzelgesprächsleitungen für die PPP-Auswahlen gesucht
Die Bewerbungssaison für den PPP-Jahrgang 2027/28 hat begonnen und mit ihr die Suche nach Auswahlleitungen und Einzelgesprächsleitungen. Wenn Du Dir vorstellen kannst, diesen Herbst eine Auswahl zu leiten oder als Einzelgesprächsleitung zu begleiten, fülle bitte diese kurze Umfrage aus: 

[[https://forms.cloud.microsoft/e/9c4d3YZ1t5][PPP-Auswahlleitungen 2026]]

Wenn Du Dir unsicher bist, ob Du die Voraussetzungen erfüllst oder (noch) keine Schulung hast, melde Dich trotzdem gerne, im Herbst werden auch wieder Schulungen stattfinden. Bei Fragen wende Dich gerne an Keira (keira.geiss@yfu.de)
** Doch noch eine NBT teamen?
Liebe Landesgruppe,

vielen Dank an alle, die sich bereits über das überregionale Teamgesuch für eine unserer NBTs gemeldet haben! An alle, die die Frist verpasst haben: es ist noch lange nicht zu spät, denn wir freuen uns weiterhin über Meldungen von vielen motivierten Teammitgliedern und Leitungen!

Wir suchen noch:
| NBT   | Zeitraum (mit VNBT) | Ort                          | Gesucht werden ...                                              |
|-------+---------------------+------------------------------+-----------------------------------------------------------------|
| SHH 1 | 13.08. – 16.08.2026 | Spejdergården Tydal, Eggebek | Teamende, gerne auch Justees oder unerfahrenere Personen        |
| SHH 2 | 10.09. – 13.09.2026 | CISV – Haus, Hamburg         | Leitung oder Leitungsteam & Teamende jeglichen Erfahrungsgrades |
| SHH 3 | 01.10. – 04.10.2026 | Spejdergården Tydal, Eggebek | Leitung oder Leitungsteam & Teamende jeglichen Erfahrungsgrades |
Wenn ihr also Lust habt, die Austauschschüler*innen auf ihrem Rückkehrprozess zu begleiten, tolle Menschen zu sehen, YFU-Spirit zu verbreiten oder einfach mal wieder etwa für YFU zu machen oder noch Fragen habt, dann meldet euch gerne bei uns unter antonia.karg@yfu-deutschland.de oder greta.dahmen@yfu-deutschland.de.

Liebe Grüße
Greta & Antonia
* Externes und Überregionales
** Mitmachen / Stellen
*Jetzt schnell Ausfüllen: 3 Minuten Zeit für dein Engagement!*
Vermutlich habt ihr schon davon gehört: YFU stellt seine Vereinsstruktur neu auf, damit wir alle noch mehr Spaß an unserem Ehrenamt haben. Jetzt wollen wir wissen, wer wo mitmachen will: Worauf habt ihr Lust? Wo wollt ihr euch einbringen? Dafür haben wir eine Abfrage erstellt, welche ihr hier findet: [[https://forms.cloud.microsoft/e/LA70cZjJzG][Neue Struktur bei YFU - und nun?]]
Und übrigens: Keine Sorge, das heißt nicht, dass ihr dann bei allem dabei sein sollt oder müsst. Tausend Dank für eure Hilfe und euer Engagement!
Nate für die AG Strukturreform 💜 🙂

*Mitgestalten im Verein: Bereichsübergreifende Zusammenarbeit konzipieren!*
Im Rahmen der neuen Struktur wollen die verschiedenen Bereiche noch enger zusammenarbeiten. Dafür soll jetzt überlegt werden, wie diese Zusammenarbeit bei unterschiedlichen Themen aussehen kann. Wer noch gar keine Ahnung von der Strukturreform hat und trotzdem dabei sein will, kann sich vorab für Infos gerne bei der AG melden: vr-strukturreform@groups.yfu-deutschland.de. Unabhängig vom Wissensstand sind aber alle willkommen, mitzuwirken und sich einzubringen!    Die Termine findet ihr hier drunter, der Einwahllink gilt für alle Termine gleich: https://teams.microsoft.com/meet/326740188582254?p=SCNRQkvV08OWn4pRG8
 - Thema Schulungen: Mi, 15.07., 20 Uhr
 - Thema EP-Eltern/Gastfamilienarbeit: Di, 21.07., 20 Uhr
 - Thema Bildungs- und Konzeptarbeit: Mi, 29.07., 19 Uhr
 - Thema Wissensmanagement: Do, 06.08., 19.30 Uhr
 - Thema Zusammenarbeit in (erw.) Vorstand und Vereinsrat: Mi, 12.08., 19 Uhr
 - Thema Spaßevents: Do, 20.08., 19.30 Uhr
*🔎Erfahrener männlicher Teamer für OWO 1 gesucht*
Für die OWO 1 vom 16. - 20.08 in Mainz suchen wir noch einen erfahrenen männlichen Teamer
Wenn du Lust hast dabei zu sein, melde dich gerne bei Mareen (📧ap-seminare@yfu.de). Alle weiteren Infos findest du [[https://intranet.yfu.de/downloads/files/3970][hier]].

*📸 Neues tolles Gastfamilien-Video bei Insta und Facebook - bitte teilen! 💜*
Liebe YFU-Community, kennt ihr schon das neue Gastfamilien-Video vom Global Office? Es ist schön, kurz und emotional geworden - und enthält auch ein paar Szenen von AP-Austauschschülis und Gastfamilien aus Deutschland. Bitte anschauen, liken und auf allen euren Kanälen teilen - und damit den Endspurt der Gastfamiliensuche für diesen Sommer unterstützen!Hier findet ihr das Video: www.instagram.com/yfudeutschland und www.facebook.com/YFU.Deutschland/ Vielen lieben Dank! 💜

*5. Nebenjob: Erstelle Videos für YFU*
Zur Verstärkung unseres Teams in der Abteilung Marketing & PR suchen wir ab sofort eine*n Video Content Creator*in auf Honorarbasis für 7-10 Stunden/Woche. Du stehst gerne vor der Kamera und kennst dich zumindest grundlegend mit TikTok, Instagram und YouTube aus? Dann bewirb dich jetzt! Alle Infos findest du unter www.yfu.de/jobs

*Auswahlleitungen und Einzelgesprächsleitungen für die PPP-Auswahlen gesucht*
Die Bewerbungssaison für den PPP-Jahrgang 2027/28 hat begonnen und zahlreiche Jugendliche warten auf ihre PPP-Auswahl. Dafür suchen wir nun Auswahlleitungen und Einzelgesprächsleitungen.
Wenn Du Dir vorstellen kannst, diesen Herbst eine Auswahl zu leiten oder als Einzelgesprächsleitung zu begleiten, fülle bitte diese kurze Umfrage aus: [[https://forms.cloud.microsoft/e/9c4d3YZ1t5][PPP-Auswahlleitungen 2026 – Formular ausfüllen]]
Bei Fragen melde Dich gerne bei Keira (keira.geiss@yfu.de)

*Lass dich zur PPP-Auswahlleitung schulen*
Für die neue PPP-Saison wollen wir wieder neue Auswahlleitungen schulen. Du hast Lust, in der neuen Saison eine PPP-Auswahl zu leiten, aber dir fehlt noch die nötige Schulung? Dann trage dich gerne in die [[https://forms.cloud.microsoft/Pages/ResponsePage.aspx?id=QqKWNFDLrkCVZmI1B908ibDdxUEoHapOoDj4h619qOdUQUVNSUdCTEwxT1I4WFVDSTEwUEtZTTBLWi4u][Abfrage]] ein. Voraussetzungen für die Schulung sind Erfahrungen als Teammitglied/ Einzelgesprächsleitung bei PPP-Auswahlen und bestenfalls eine KLT-Schulung.
Bei Fragen melde dich gerne bei Picabo (picabo.winands@yfu-deutschland.de).

*Referent*innen für politische Bildungsarbeit gesucht*
Wir suchen Menschen, die spannende und zugängliche Workshops im Bereich der politischen Bildung konzipieren und durchführen können. Gesucht werden sowohl erfahrene Bildungsreferent*innen als auch Personen mit fundierten Kenntnissen und didaktischen Fähigkeiten, die ihre Expertise weitergeben möchten. Zielgruppe sind unsere PPP-Schüler*innen, thematisch soll der Fokus daher auf den politischen Systemen und aktuellen Entwicklungen in den USA und Deutschland liegen.
Wenn du Lust hast, junge Menschen oder Gruppen für politische Themen zu begeistern und komplexe Inhalte verständlich und interaktiv zu vermitteln, melde dich gern bei Lina unter ppp@yfu.de. 
** Schulungen / Termine
*🚀 Powerstart ins Ehrenamt am 22. Juli von 19-20.30 Uhr mit Ines und Julia*
Du möchtest aktiv werden oder wieder einsteigen und brauchst für den Start noch ein bisschen Orientierung? Dann haben wir einen Tipp für dich🔥! Starte mit unseren Ehrenamtlichen beim digitalen Powerstart ins Ehrenamt durch. Lerne das YFU 1x1, finde heraus, was es für dich zu tun gibt, wie du dich mit YFUler*innen in deiner Umgebung vernetzen kannst und welche Vorteile du als YFUler*in genießt.
🔥 Anmeldung hier: https://tinyurl.com/jszynj7n
** Sonstiges / Externes
*Vollzeit FSJ-Politik mit Schwerpunkt Presse- und Öffentlichkeitsarbeit/Eventbetreuung bei LIBERECO in Berlin*
LIBERECO ist eine unabhängige europäische Nichtregierungsorganisation, die sich für den Schutz der Menschenrechte in Belarus und der Ukraine engagiert. Als FSJler*in wirst du Teil ihrer Vision und unterstützt sie darin, das Thema in der Öffentlichkeit sichtbar zu machen. Bewerben kannst du dich noch bis zum 16.08.2026. Start des FSJs ist der 01.09.2026. Wir wünschen dir viel Erfolg!
👉 Alle Infos zu den Voraussetzungen und der Bewerbung findest du [[https://libereco.org/de/deutschland/jobs/fsj-politik-presse-und-oeffentlichkeitsarbeit-eventbetreuung-2026][hier]]. 

*📝Umfrage zur Wertschätzung im Ehrenamt*
Ehrenamtliches Engagement ist das Herzstück von YFU – ohne euch wäre unsere Arbeit nicht möglich. Umso wichtiger ist es uns, besser zu verstehen, wie ihr eure ehrenamtliche Tätigkeit erlebt und in welchen Bereichen ihr euch mehr Wertschätzung wünscht. 
👉Daher möchten wir euch bitten, an dieser kurzen, anonymen [[https://forms.office.com/e/MLY2yUUbju?origin=lprLink][Umfrage]] teilzunehmen.

*Frist bis zum 12. Juli verlängert: Bewirb dich als World Storyteller und reise nach New York City*🗽*
Die neue Kooperation von YFU Global und Made Impact ermöglicht 50 YFU‑Ehrenamtlichen aus unserem weltweiten Netzwerk die Teilnahme am *World Storyteller Project* – inklusive Training und großem Summit am *31. August und 1. September 2026* in NYC. *Fünf Ehrenamtliche* aus Deutschland dürfen teilnehmen!🎉
Was steckt dahinter? Das World Storyteller Project verbindet eine weltweite Storyteller-Community, die die Wirkung von internationalem Austausch sichtbar macht. Dafür sammelst du 100 Geschichten von Menschen, die an einem internationalen Austauschprogramm teilgenommen haben. Alle Stories tragen zur *Million Stories Initiative* bei – dem weltweit größten Story-Archiv zur Wirkung von Austauschprogrammen.
🎯 Das große Ziel: Gemeinsam mit Made Impact möchten wir Internationale Bildung für den Friedensnobelpreis nominieren, um politische Weichen neu zu stellen und Austauschprogramme für alle zugänglich zu machen.
👥 Die Voraussetzungen: Du bist mind. 18 Jahre alt, engagierst dich bei YFU, bringst gute Englischkenntnisse für das Training in NYC mit und bist bereit 100 Geschichten einzureichen.
💶 Die Kosten: Unterkunft und Verpflegung in New York sind für dich kostenlos. An den Flugkosten beteiligst du dich mit 300 Euro, den Rest übernehmen wir. Deine Flugkosten bekommst du zurück, sobald die 100 Geschichten eingereicht wurden.
❤️ Good to know: Wenn du dich als Storyteller bewerben möchtest, dir die Flugkosten aber gerade nicht leisten kannst, melde dich bei uns unter ehrenamt@yfu.de. Wir finden gemeinsam eine Lösung.
🔗  https://madeimpact.org/world-storyteller-project
👉  Jetzt bewerben! https://forms.office.com/pages/responsepage.aspx?id=BWlSWoAZoEWkdfNS5h_snk26cZNfjzhFnX6iITBtH2lURE8xMDE4WUZIVlRTR0FCNkVSSjVNU01CMS4u&route=shorturl
* Terminübersicht
** TERMINE 2026
*18.09. -20.09. 2026* &nbsp;&nbsp;&nbsp; Colored Glasses Schulung, Jugendherberge Horner Rennbahn *Hamburg*

*02.10. - 04.10.2026*  &nbsp;&nbsp;&nbsp; Seminarleitungsschulung (SLS), Jugendherberge *Kassel*
*02.10. - 04.10.2026*  &nbsp;&nbsp;&nbsp; *(LG)* Aktivenwochenende

*06.11. – 08.11.2026* &nbsp;&nbsp;&nbsp; Colored Glasses Schulung, Jugendherberge *Kassel*

*20.11. - 22.11.2026* &nbsp;&nbsp;&nbsp; Betreuendenseminar, *Jugendherberge Stuttgart*

*27.11. - 29.11.2026* &nbsp;&nbsp;&nbsp; ÖA-Ausschusstreffen, *Hamburg*

*06.05. - 09.05.2027* &nbsp;&nbsp;&nbsp; BUT 2027, *tba*
