* Landesgruppe
**  Wichtige Info Aufrufe Newsletter
Diesen Newsletter findet ihr ab jetzt auch auf Whatsapp! Dafür einfach über diesen Link beitreten: https://chat.whatsapp.com/GBCBuLIU2U78zpim5yGxLF
---

Sehr gerne nehmen wir eure Aufrufe oder Danksagungen in den wöchentlichen Newsletter auf.

Schreibt mir ([[mailto://shh-newsletter@yfu-deutschland.de][shh-newsletter@yfu-deutschland.de]]) dafür einfach immer bis *Mittwochs 17:00 Uhr* eure Aufrufe, damit ich sie noch in den Newsletter der aktuellen Woche mit aufnehmen kann. Ansonsten nehme ich die Aufrufe natürlich gerne in den nächsten auf.

Vielen lieben Dank und ich freue mich auf eure Emails.

Liebe Grüße
Aimo
** Communitea Anmeldung
Liebe Community,

wir haben wieder Neuigkeiten! 🐣
Wir möchten euch herzlich zu einem frühlingshaften Communitea-Treffen einladen. Gemeinsam wollen wir mit den Austauschschüler*innen ein bisschen Ostern feiern und einen entspannten Nachmittag miteinander verbringen.

📅 Wann? 3. April, um 11 Uhr 
📍 Wo? Geschäftsstelle

Wir wollen gemeinsam Ostereier bemalen und die Frühlingszeit einläuten. Wer mag, kann außerdem gerne Snacks oder andere Kleinigkeiten zum Teilen mitbringen. Außerdem wäre es hilfreich, wenn alle bereits ausgepustete Eier mitbringen könnten.

Wenn ihr dabei seid, meldet euch bitte kurz [[https://forms.office.com/?redirecturl=https%3a%2f%2fforms.office.com%2fPages%2fDesignPageV2.aspx%3fsubpage%3ddesign%26FormId%3dQqKWNFDLrkCVZmI1B908iefgPGIVnodAt7lfuSHL-ZJUNjUyWFpBUzhIUVFMOU1YVllNRVZFSFJHWS4u&auth_pvr=OrgId][hier]] an.
Wir freuen uns auf euch und auf ein gemütliches Treffen!

Liebe Grüße 
Leah, Aimo und Ole
** SAVE THE DATE: 5.- 7. JUNI, NORD-LGT 2026
Liebe Landesgruppe,

Das YFU-Sommerloch lauert (noch weit entfernt) am Horizont, doch hier kommt eure Rettung: Das Nord-LGT 2026 vom 5.-7. Juni im Victor-Andresen-Haus in Pinneberg ​! Die offizielle Anmeldung folgt noch im April, aber streicht euch den Termin am besten schon jetzt im Kalender an!

Solltet ihr davor schon Fragen haben, könnt ihr euch gerne unter nordlgt@lists.yfu-deutschland.de melden.

Wir freuen uns auf euch!
Euer Nord-LGT-Planungsteam
* Öffentlichkeitsarbeit
** Neue Infos
Liebe Landesgruppe,

bald sind die Märzferien vorbei und wir suchen wieder eure Unterstützung.
Wenn ihr Zeit und Lust habt meldet euch gerne bei [[mailto:sophie.schnipkoweit@yfu-deitschland.de][sophie.schnipkoweit@yfu-deitschland.de]] oder bei [[mailto:kira.thede@yfu-deutschland.de][kira.thede@yfu-deutschland.de]]
** Schulvortrag am Gymnasium Brunsbüttel
Wann: Flexible Absprache mit Ansprechpartner der Schule

Wo:
Gymnasium Brunsbüttel
Kopernikusstr. 1
25541 Brunsbüttel

Wer: 2-3 erfahrene und unerfahrene Personen
** Schulvortrag am Gymnasium Farmsen
Wann: Am 14.04.2026; Beginn um 18 Uhr

Wo:
Gymnasium Farmsen
Swebenhöhe 50
22159 Hamburg

Wer: 1-2 erfahrene sowie unerfahrene Personen 

Meldet euch hier gerne bei Kira (kira.thede@yfu-deutschland.de)
** Schulvortrag am Johanneum Lüneburg
Wann: 23.04.2026, Vormittags

Wo:
Johanneum Lüneburg
Theodor-Heuss-Str. 1
21337 Lüneburg

Wer: 2-3 erfahrene und unerfahrene Personen 
* Aufnahmeprogramm
** Teamende für die ATS-Spaßveranstalltung
Liebe Ehrenamtliche im Aufnahmeprogramm,

beim letzten Communitea-Treffen waren viele Austauschschülerinnen dabei – was uns natürlich sehr gefreut hat! Gleichzeitig haben wir gemerkt, dass ein paar mehr Ehrenamtliche schön gewesen wären, um sich besser zu mischen, ins Gespräch zu kommen und gemeinsam Aktivitäten zu machen.

Deshalb möchten wir euch herzlich einladen, beim nächsten Communitea-Treffen dabei zu sein und ein bisschen Zeit mit den Austauschschülerinnen zu verbringen.

📅 Wann? 3. April, um 11 Uhr 
📍 Wo? Geschäftsstelle

Wir wollen gemeinsam Ostereier bemalen, uns austauschen und einen gemütlichen Vormittag verbringen. Wer möchte, kann außerdem gerne Snacks oder andere Kleinigkeiten zum Teilen mitbringen. Außerdem wäre es hilfreich, wenn alle bereits ausgepustete Eier mitbringen könnten.

Wenn ihr Zeit und Lust habt, vorbeizukommen, meldet euch bitte kurz [[https://forms.office.com/?redirecturl=https%3a%2f%2fforms.office.com%2fPages%2fDesignPageV2.aspx%3fsubpage%3ddesign%26FormId%3dQqKWNFDLrkCVZmI1B908iefgPGIVnodAt7lfuSHL-ZJUNjUyWFpBUzhIUVFMOU1YVllNRVZFSFJHWS4u&auth_pvr=OrgId][hier]] an. Wir freuen uns sehr über jede*n, der oder die dabei ist!

Liebe Grüße 
Leah, Aimo und Ole
* Externes und Überregionales
** Mitarbeiter-Gesuche/Stellen
*Teamende für VBT _nächste Woche_ in Lauenburg gesucht!*
Für die Oster-VBT vom 04.04.-09.04. suchen wir noch vier Teammitglieder
Charlie Goetjes ist als sehr erfahrene Leitung dabei
Auch die anderen Teammitglieder sind erfahren, aber brauchen dringend noch Verstärkung
Bitte melde dich bei Fenja unter vbt@yfu.de 

*Teitungsteam für VBT Anfang April gesucht*
Für die NO2-VBT (08.04.-13.04.) in Lauenburg suchen wir eine Leitung oder ein Leitungsteam
Es steht bereits ein komplettes und erfahrenes Team bereit!
Wir unterstützen gerne bei allen Fragen und Anliegen
Bitte melde dich bei Fenja unter vbt@yfu.de

*Teamende für VBTs in Lauenburg und Mühlhausen gesucht*
Für die MD1 (14.04.-19.04.) in Mühlhausen suchen wir eine Co-Leitung und Teammitglieder
Für die SHH3 (20.-25.04.) in Lauenburg suchen wir noch Teammitglieder mit Erfahrung, es gibt bereits ein Leitungsteam
Für die MD2 (03.05.-08.06.) in Mühlhausen suchen wir Teammitglieder, Charlie Goetjes leitet
Bitte melde dich bei Fenja unter vbt@yfu.de
    
*Leitung eines vierwöchigen Sommerkurses für US-amerikanische Austauschschüler*innen*
Du hast vom 25. Juli-21. August 2026 noch nichts vor, hast Erfahrung in der Leitung von Teams sowie in der Jugendarbeit? Englisch beherrscht du im Schlaf und eine Ersthelfer*innen-Ausbildung bringst du auch mit? Dann suchen wir genau 👉dich für die Leitung des PPP-Sprachcamps in Bonn. Das genaue Anforderungsprofil sowie die Aufgabenbeschreibung findest du [[https://www.yfu.de/ueber-yfu/jobs-praktika][hier]].
📧Fragen und Interessensbekundungen schickst du bitte Sophia (ap-seminare@yfu.de).

*Vierwöchiges interkulturelles Training und Betreuung für US-amerikanische Austauschschüler*innen*
Im Sommer reisen 42 PPP-Stipendiat*innen aus den USA für ihren Austausch nach Deutschland. Du hast Lust, sie bei ihren ersten Wochen in Bonn zu begleiten, interkulturelle Trainings durchzuführen, ihnen bei Rat und Tat zur Seite zu stehen sowie ein buntes Rahmenprogramm zu entwerfen? Für den 25. Juli-21. August 2026 steht noch nichts in deinem Kalender 📅 ? Dann komm ins Team des PPP-Sprachcamps 🚀. Die genauen Bewerbungsvoraussetzungen und Aufgabenbeschreibungen findest du [[https://www.yfu.de/ueber-yfu/jobs-praktika][hier]] 🔎.
📧Fragen und Interessensbekundungen schickst du bitte Sophia (ap-seminare@yfu.de).

*Teamende für Oral English Tests gesucht*
Für die Austauschorganisation FLAG in den USA benötigen unsere Austauschschüler*innen einen Oral English Test. In den kommenden Wochen finden die letzten Tests der Saison statt und für diesen Endspurt brauchen wir nochmal eure Unterstützung! Es handelt sich um lockere, etwa 20- bis 30-minütige Telefonate auf Englisch. Die Themen für die Gespräche können frei gewählt werden. Im Anschluss wird ein Auswertungsbogen ausgefüllt. Die Oral English Tests lassen sich sehr individuell planen, du kannst selbst einen Termin für das Gespräch mit den Austauschschüler*innen vereinbaren und kannst so dein Engagement für dich passend planen. Hast du in den nächsten zwei bis drei Wochen ein bisschen Zeit und Lust, uns bei den Oral English Tests zu unterstützen und mit ein paar zukünftigen Austauschschüler*innen interessante Gespräche zu führen? Dann melde dich unter usa@yfu.de bei Lisa – ich freue mich, von dir zu hören!
 
*🚀 Startschuss OWO-Leitungs- & Teamsuche*
Die AP-Platzierung hat begonnen und wir freuen uns auf einen neuen Schwung an ATS, die mit voller Vorfreude in ihr Austauschjahr in Deutschland starten. Dafür suchen wir für die OWOs wieder nach motivierten Leitungen und Teamenden! Du hast im August 2026 noch nichts vor und hast Lust auf viele tolle ATS? 👉 Dann melde dich bei Mareen (📧 ap-seminare@yfu.de) oder fülle diese [[https://forms.office.com/e/KYWzZNfDNt?origin=lprLink][Umfrage]] aus. Alle weiteren Infos findest du [[https://intranet.yfu.de/downloads/files/3970][hier]].

*Nicht nur Ostereier, sondern auch Gastfamilien suchen!*
Du studierst oder arbeitest und fährst zu Ostern 🐰🐣 wieder in deine Heimat, um deine Familie zu besuchen? Das ist eine super Gelegenheit, um nicht nur nach bunten Ostereiern, sondern auch nach neuen Gastfamilien zu suchen: Einfach schnell noch [[https://intranet.yfu.de/process/material_orders/7843/edit?step=event][über die Material-App]] oder bei Corinna (schmidt@yfu.de, 040 227002-65) einen Schwung AP-Flyer, AP-Aushänge, AP-Türhänger, AP-Postkarten oder AP-Visitenkarten direkt an deine Heimatadresse bestellen - und dann vor Ort verteilen, zum Beispiel bei einem gemütlichen Frühlingsspaziergang. 🌷🌼 🌸 
Wir bedanken uns ganz herzlich - und wünschen allen schon jetzt fröhliche Ostern!

*Bei Colored Glasses geht es rund – sei dabei und melde dich für eine spannende Aufgabe!*
Mit den Colored Glasses Toleranzworkshops bringen wir YFU-Spirit, Vielfalt und Weltoffenheit an Schulen in ganz Deutschland. Hast du Lust, in deinem Engagement bei YFU einen neuen Schwerpunkt zu setzen oder dich mal in einem anderen Bereich auszuprobieren? Dann ist vielleicht eine dieser Ausschreibungen etwas für dich. Melde dich jetzt bei Nina unter roesch@yfu.de zurück. Viele weitere Infos findest du auch hier. Unbedingt weitersagen – auch an nicht-YFUler*innen.
- CG-Vorstandsmitglied mit Schwerpunkt Koordi-Koordination – Organisations- und Kommunikationstalente gesucht! Alle Infos [[https://coloredglasses.de/organisations-und-kommunikationstalent-gesucht/][hier]].
- Verstärkung für das Team „CG-Ehrenamts-Motivation und -Fortbildung“ – stärke das CG-Netzwerk mit deinen Ideen und weiteren Angeboten! [[https://coloredglasses.de/unsere-motivation-beginnt-mit-dir/][Hier]] gibt’s mehr Infos.
- Trainer*innen für CG-Schulung 19.-21.06. in Grefrath. Eine erfahrene Trainerin hat sich gefunden, wir suchen nun noch 1-2 Personen zur Unterstützung des Teams.
- FSJ (Politik/Demokratie) bei Colored Glasses ab September 2026 – ein ganzes Jahr bei YFU und auf CG-Workshops bundesweit. Die Stellenausschreibung findest du [[https://coloredglasses.de/dein-freiwilliges-soziales-jahr-fsj-politik-demokratie-bei-colored-glasses-m-w-d/][hier]]. 
*USA for you München 2026: Auswahl-Team gesucht*
Für die Auswahlgespräche für USA for you in München am 13. und 14. Juni 2026 suchen wir noch Team-Mitglieder. Mehr Infos zu USA for you findet ihr hier: https://www.yfu.de/kurzprogramme/usa-for-you
Meldet euch bei Interesse gern bei Thekla: usaforyou@yfu.de, Durchwahl -77

*USA for you Sachsen-Anhalt: Co-Leitung/erfahrenes Team-Mitglied für den 9.5. gesucht*
Für die Auswahl der USA for you-Gruppe am 9. Mai 2026 in Halle (Saale) suchen wir noch eine Co-Leitung oder ein erfahrenes Team-Mitglied. 
Melde dich gern bei Thekla: usaforyou@yfu.de, Durchwahl -77

*USA for you München 2026: Männliche Programmbegleitung gesucht*
15 Jugendliche von Münchener Mittelschulen starten am 24. Oktober 2026 in ein zweiwöchiges Abenteuer in Michigan mit Community Service, Sightseeing und Leben in Gastfamilien. Für die Vor- und Nachbereitung und die Begleitung der Gruppe in die USA suchen wir noch einen männlichen Ehrenamtlichen. Die Ausschreibung findest du hier: https://intranet.yfu.de/article_tool/articles/2217
Bei Fragen: Kontaktiere Thekla unter usaforyou@yfu.de oder Durchwahl -77

*Germany for you: Programmbegleitung vom 13. bis 28. Juni 2026 in Halle (Saale) gesucht (Honorarvertrag)*
Für das Germany for you-Programm suchen wir eine Programmbegleitung (m/w/d), die gemeinsam mit einer amerikanischen Programmbegleitung und weiteren Ehrenamtlichen vor Ort in Halle eine Gruppe von 15 Jugendlichen aus den USA bei einem bunten Programm aus ehrenamtlichem Einsatz, Sightseeing (in Halle und Berlin), Sprachkurs und Sportprogramm begleitet.
Mehr Infos hier: https://intranet.yfu.de/article_tool/articles/2220
Meldet euch bei Interesse gern bei Thekla: germanyforyou@yfu.de, Durchwahl -77

*Reisebegleitungen für den Sommer 2026 gesucht ✈️*
Du hast Lust eine Schüler*innen-Gruppe per Flug, Zug oder Fähre in ihren Austausch zu begleiten? Die Chance zu nutzen und etwas Neues kennenzulernen? Oder etwas Liebgewonnenes erneut zu besuchen? Dann fülle bitte bis zum 31. März die Umfrage [[https://www.yfu-survey.org/poll/index.php/124258?lang=de-informal][Reisebegleitungen 2026]] aus. Du solltest zum Zeitpunkt der Reise mindestens 21 Jahre alt sein. Auf der Startseite der Umfrage findest du die Länder und Reisedaten. Bei Fragen wende dich gerne direkt an Miriam (reise@yfu.de).

*🚀 Powerstart-Verstärkung gesucht – komm ins Powerstart-Team!*
Unser Powerstart-Team möchte wachsen. Ab sofort suchen wir erfahrene Ehrenamtliche, die sich bei YFU gut auskennen und anderen souverän über das Ehrenamt berichten können. Gerne auch Ehrenamtliche, die schon etwas mehr Lebenserfahrung mitbringen und die Elterngeneration ansprechen können.
Was springt für dich dabei raus?  Du kannst dir deinen Einsatz flexibel nach Absprache einteilen, viele neue Leute kennenlernen, deine Moderationskompetenzen erweitern und hast ein starkes Team an deiner Seite. 💪 Klingt nach einer Aufgabe für dich? Melde dich bei Julia aus der Geschäftsstelle (kastner@yfu.de).
** Schulungen / Termine
*🚀 Powerstart ins Ehrenamt am 9. April um 19 Uhr mit Julia und Ines*
Du möchtest aktiv werden oder wieder einsteigen und brauchst für den Start noch ein bisschen Orientierung? Dann haben wir einen Tipp für dich🔥! Starte mit unseren Ehrenamtlichen beim digitalen Powerstart ins Ehrenamt durch. Lerne das YFU 1x1, finde heraus, was es für dich zu tun gibt, wie du dich mit YFUler*innen in deiner Umgebung vernetzen kannst und welche Vorteile du als YFUler*in genießt.
🔥 Anmeldung und weitere Termine hier: https://sway.cloud.microsoft/WKISSAGmmiab4CYG

*Datenschutz kompakt: Online-Einweisungen am Dienstag 14.4. um 20 Uhr und Mittwoch 20.5. um 18.30 Uhr!*
Die nächsten digitalen Datenschutzeinweisungen (ungefähr 45 min.) für Referent*innen, Gremienmitglieder und alle Interessierte finden statt am
Dienstag , 14. April um 20.00 Uhr
Mittwoch, 20. Mai um 18.30 Uhr
Wir freuen uns über alle, die dabei sind – gerne auch weitersagen!
Meldet euch unter datenschutz@yfu.de an. Weitere Infos folgen dann per mail. Mehr zum Thema Datenschutz bei YFU findet ihr im [[https://intranet.yfu.de/downloads/files?category=41][Intranet]]. Unsere aktuellen [[https://www.yfu.de/datenschutz][Datenschutzhinweise]] stehen auf unserer Webseite zur Verfügung.

*Jetzt zum Interessenseminar-Lateinamerika (ISLA) anmelden!*
Das ISLA ist eine besondere Veranstaltung von YFU Deutschland. Es ist kein klassisches Aktiven-Treffen und auch kein Alumni-Treffen, sondern etwas dazwischen. Fast alle haben schon mal davon gehört. Die wenigsten waren einmal da, sondern meistens öfter. Es gibt inhaltliche und künstlerische Workshops zum Thema Lateinamerika. Schulungen zu YFU Latinx-Themen sind ebenfalls im Angebot. Wir kochen und backen zusammen länderspezifisch. Dabei gilt nicht unbedingt einfach und effektiv, sondern rafiniert und kreativ. Letztes Jahr gab es mehr Interesse als Plätze. Deshalb sind wir dieses Jahr in einem beonders großem Haus: Einem Kloster. Es gibt also ausreichend Platz für uns. Wenn du dir also vorstellen kannst, einmal bei einer etwas anderen YFU Veranstaltung dabei zu sein, freuen wir uns auf dein Kommen. Du brauchst keine besondere Verbindung zu Lateinamerika. Trau dich! Schau einfach mal bei uns vorbei!
📅 08.-10. Mai 2026 in Rinteln
Anmeldung unter: yfudelatinx.weebly.com 
** Sonstiges / Externes
*📣 LAST MINUTE CALL – weitere Teamer*innen für das YES gesucht!*
Ehrenamtliche aufgepasst! Vom 22. bis 26. Juni 2026 findet wieder das Youth Empowerment Seminar (YES) am Werbellinsee in Brandenburg statt – und du kannst jetzt noch als International Group Leader (IGL) dabei sein!
✨Einmal im Jahr treffen sich hunderte Austauschschüler*innen zum Abschluss ihres Jahres beim YES, um ihren Austausch zu feiern, gemeinsam zu lernen und Spaß zu haben.
🔎Als IGL bist du erste*r Ansprechpartner*in für eine Gruppe (vorrangig deutscher) Austauschschüler*innen, begleitest sie durch Austausch- und Reflexionsrunden und hilfst ihnen, gut auf das Ankommen zu Hause vorbereitet zu sein. Gut wäre, wenn du dich ohne Probleme auf Englisch verständigen kannst.
🤝 Beim YES triffst du viele internationale Austauschschüler*innen und Ehrenamtliche, lernst Neues und kannst deine eigenen Erfahrungen weitergeben.
💸 Reisekosten und Unterkunft werden bezahlt.
✍ Hier findest du alle Infos zum YES: https://www.yfu-yes.org/volunteer-2wave2026 - einen Einblick in die Rolle als IGL findest du auf [[https://www.instagram.com/p/DTSxEBOCNHh/?utm_source=ig_web_button_share_sheet&igsh=MzRlODBiNWFlZA==][Instagram]].
📧 Du möchtest als IGL dabei sein? Dann melde dich (auf Englisch oder Deutsch) unter igl.coordinator@yfu-yes.org bei Lätizia Bresler aus dem YES-Core-Team.
❓ Wenn du Fragen hast, stell sie am besten auch direkt Lätizia unter genannter E-Mail-Kontaktadresse oder Rahel aus der GS (perschke@yfu.de).  
 
*Alles rund um die Strukturreform – FAQ*
Dieses Jahr wird entschieden, wie das Vereinsleben von YFU in Zukunft aussehen soll. Viele Fragen werden gestellt: Was bedeuten die Veränderungen für Ehrenamtliche und Mitglieder? Wie sehen die neuen Organe aus? Wer entscheidet in Zukunft über den Verein? Damit ihr gut informiert seid, haben wir ein FAQ zur Strukturreform für euch zusammengestellt, das alle wichtigen Fragen transparent beantwortet: [[https://sway.cloud.microsoft/75ukJpXLBadjHr2v][Zum FAQ-Strukturrefor]]

*🤔 Kurz nachgefragt: Warum bist du (kein) YFU-Mitglied?*
Mitglied sein bei YFU bedeutet für viele: verbunden bleiben, Stimme geben, mitgestalten. Aber: Das ist nicht für alle gleich. Damit wir unsere Angebote und Kommunikation rund um unsere Mitgliedschaft verbessern können, fragen wir dich nach deiner Motivation und nach möglichen Stolpersteinen.
👉 Nimm dir 2 Minuten Zeit für unsere anonyme Umfrage: https://forms.cloud.microsoft/e/sDzSVHbNih
* Terminübersicht
** TERMINE 2026
*15.05. - 17.05.2026* &nbsp;&nbsp;&nbsp; Colored Glasses Schulung, Jugendherberge Burg Schwaneck (*bei München*)

*29.05 - 31.05.2026* &nbsp;&nbsp;&nbsp; ÖA-Ausschusstreffen, *Hamburg*

*05.06. - 07.06.2026* &nbsp;&nbsp;&nbsp; *(LG)* Nord-LGT

*13.06. - 13.06.2026* &nbsp;&nbsp;&nbsp; Betreuungsschulung, *Berlin*

*20.06. - 21.06.2026* &nbsp;&nbsp;&nbsp; Colored Glasses Schulung, Liebfrauenschule Mühlhausen (*bei Duisburg*)

*18.09. -20.09. 2026* &nbsp;&nbsp;&nbsp; Colored Glasses Schulung, Jugendherberge Horner Rennbahn *Hamburg*

*25.09. - 27.09.2026* &nbsp;&nbsp;&nbsp; *(LG)* Aktivenwochenende

*02.10. - 04.10.2026*  &nbsp;&nbsp;&nbsp; Seminarleitungsschulung (SLS), Jugendherberge *Kassel*

*06.11. – 08.11.2026* &nbsp;&nbsp;&nbsp; Colored Glasses Schulung, Jugendherberge *Kassel*

*20.11. - 22.11.2026* &nbsp;&nbsp;&nbsp; Betreuendenseminar, *Jugendherberge Stuttgart*

*27.11. - 29.11.2026* &nbsp;&nbsp;&nbsp; ÖA-Ausschusstreffen, *Hamburg*
