* Landesgruppe
**  Wichtige Info Aufrufe Newsletter
Diesen Newsletter findet ihr ab jetzt auch auf Whatsapp! Dafür einfach über diesen Link beitreten: https://chat.whatsapp.com/GBCBuLIU2U78zpim5yGxLF
---

Sehr gerne nehmen wir eure Aufrufe oder Danksagungen in den wöchentlichen Newsletter auf.

Schreibt mir ([[mailto://shh-newsletter@yfu-deutschland.de][shh-newsletter@yfu-deutschland.de]]) dafür einfach immer bis *Mittwochs 17:00 Uhr* eure Aufrufe, damit ich sie noch in den Newsletter der aktuellen Woche mit aufnehmen kann. Ansonsten nehme ich die Aufrufe natürlich gerne in den nächsten auf.

Vielen lieben Dank und ich freue mich auf eure Emails.

Liebe Grüße
Aimo
* Öffentlichkeitsarbeit
** Schulvortrag am Gymnasium Brunsbüttel
Wann: flexibel möglich!
Meldet euch gerne bei kira.thede@yfu-deutschland.de
Wo: Gamnasium Brunsbüttel
Kopernikusstr. 1
22541 Brunsbüttel
** Schulvortrag am Goethe-Gymnasium
Wann: 15.06.2026 15:00 (Teamtreffen 13:30)
Wo: Goethe-Gymnasium Hamburg (Altona)
Rispenweg 28, 22547 Hamburg
Wer: 1-2 Teamer jedes Erfahrungsgerades
Bei Interesse: kira.thede@yfu-deutschland.de
** Schulvortrag am Gymnasium Trittau
cccWann: 18.06.2026
Wo: Gymnasium Trittau
Wer: 1-2 Teamer jedes Erfahrungsgerades
Bei Interesse: kira.thede@yfu-deutschland.de
** Schulvortrag in Büsum
Wann: 25.06.2026 19:00
Wo: Schule am Meer Büsum
Bei Interesse: kira.thede@yfu-deutschland.de
* Aufnahmeprogramm
** Leitungen und Teamende für Gastfamilienvorbereitung gesucht
Liebe Landesgruppe,
 
die neue AP-Saison steht in den Startlöchern und wir sind auf der Suche nach Leuten, die unsere nächsten Gastfamilien vorbereiten wollen. Wir haben schon einige motivierte Gastfamilien, die auf den Start des Austausches warten und so viele Informationen wie möglich erhalten wollen. Die GF-Vorbereitung soll sie so gut es geht auf den Austausch vorbereiten und ganz viele offene Fragen klären.
Für die Gastfamilien Vorbereitung suchen wir zurzeit Menschen, die Lust hätten, an einem Tag ihrer Wahl (am besten am Wochenende, jedoch eignen sich ggf. auch Wochentage abends) die neuen Gastfamilien auf ihren Austausch vorzubereiten in der Geschäftsstelle.
Zur Vorbereitung unserer Gasteltern soll es im Sommer zwei-drei Termine geben. 
Termine in den Zeiträumen Ende Juli und August würden sich hier gut eignen, damit wir die Sommerferien frei halten können.  

Du würdest die Veranstaltung vor Ort leiten oder teamen, eventuell mit einer Person deiner Wahl zusammen. Eine Präsentation gibt es bereits.
Meldet euch gerne, wenn ihr interessiert seid, eine oder mehrere GF-Vorbereitung(en) zu leiten oder zu teamen. Noch sind die Termine flexibel. Meldet euch sehr gerne mit konkreten Terminvorschlägen. 

Wir freuen uns auf eure Rückmeldungen an Amilou oder mich (theda.schmidtko@yfu-deutschland.de)
 
Liebe Grüße,
Theda
* Entsendeprogramm
** Doch noch eine NBT teamen?
Liebe Landesgruppe,

vielen Dank an alle, die sich bereits über das überregionale Teamgesuch für eine unserer NBTs gemeldet haben! An alle, die die Frist verpasst haben: es ist noch lange nicht zu spät, denn wir freuen uns weiterhin über Meldungen von vielen motivierten Teammitgliedern und Leitungen!

Wir suchen noch:
| NBT   | Zeitraum (mit VNBT) | Ort                          | Gesucht werden ...                                              |
|-------+---------------------+------------------------------+-----------------------------------------------------------------|
| SHH 1 | 13.08. – 16.08.2026 | Spejdergården Tydal, Eggebek | Teamende, gerne auch Justees oder unerfahrenere Personen        |
| SHH 2 | 10.09. – 13.09.2026 | CISV – Haus, Hamburg         | Leitung oder Leitungsteam & Teamende jeglichen Erfahrungsgrades |
| SHH 3 | 01.10. – 04.10.2026 | Spejdergården Tydal, Eggebek | Leitung oder Leitungsteam & Teamende jeglichen Erfahrungsgrades |
Wenn ihr also Lust habt, die Austauschschüler*innen auf ihrem Rückkehrprozess zu begleiten, tolle Menschen zu sehen, YFU-Spirit zu verbreiten oder einfach mal wieder etwa für YFU zu machen oder noch Fragen habt, dann meldet euch gerne bei uns unter antonia.karg@yfu-deutschland.de oder greta.dahmen@yfu-deutschland.de.

Liebe Grüße
Greta & Antonia
* Externes und Überregionales
** Mitmachen / Stellen
*🚀 Powerstart-Verstärkung gesucht – komm ins Powerstart-Team!*
Unser Powerstart-Team möchte wachsen. Ab sofort suchen wir erfahrene Ehrenamtliche, die sich bei YFU gut auskennen und anderen souverän über das Ehrenamt berichten können. Gerne auch Ehrenamtliche, die schon etwas mehr Lebenserfahrung mitbringen und die Elterngeneration ansprechen können.
Was springt für dich dabei raus?  Du kannst dir deinen Einsatz flexibel nach Absprache einteilen, viele neue Leute kennenlernen, deine Moderationskompetenzen erweitern und hast ein starkes Team an deiner Seite. 💪 Klingt nach einer Aufgabe für dich? Melde dich bei Julia aus der Geschäftsstelle (kastner@yfu.de).

*Gesucht: Prozesssteuerung für die Umsetzung der Strukturreform*
Du hast Lust, dich in den nächsten Monaten intensiver im Verein zu engagieren? Du magst Projektaufgaben, die ein absehbares Ende haben? Du behältst normalerweise die Ruhe und den Überblick, auch wenn es mal komplexer wird? Und hast vielleicht schon ein wenig Erfahrung im Projektmanagement? Oder kennst eine Person, auf die diese Beschreibung zutrifft? Dann schau dir unbedingt die [[https://intranet.yfu.de/downloads/files/3976][Stellenausschreibung für die ehrenamtliche Prozesssteuerung]] in der Umsetzungsphase unserer Strukturreform an! Der Vorstand schreibt diese wichtige Position aus und freut sich über Interessensbekundungen. Sei aktiv dabei, wenn YFU-Geschichte geschrieben wird!

*erfahrene Leitung für OWO 4 in Mainz gesucht 🚨*
Für die OWO 4 vom 23.-27.08. in Mainz suchen wir nach einer erfahrenen Leitung (gerne männlich, aber kein Muss). Es gibt bereits eine Co-Leitung und ein Team. Wenn du Lust hast mitzumachen, melde dich gerne bei Mareen (📧ap-seminare@yfu.de). Alle weiteren Infos findet ihr [[https://intranet.yfu.de/downloads/files/3970][hier]].

*🔎 Teamende für OWOs gesucht*
 - Für die OWO 2 vom 16. - 20.08 in Bingen am Rhein suchen wir einen männlichen Teamer (gerne Ü23, aber kein Muss).
 - Für die OWO 5 vom 23. - 27.08 in Bingen am Rhein suchen wir eine*n erfahrene Teamer*in
Wenn du Lust hast mitzumachen, melde dich gerne bei Mareen (📧ap-seminare@yfu.de). Alle weiteren Infos findest du [[https://intranet.yfu.de/downloads/files/3970][hier]].

*🏆 Qualifiziere Seminarleitungen – Eine weitere Trainer*in für die Seminarleitungsschulung (SLS) gesucht*
Du möchtest andere YFUler*innen mit deiner Erfahrung und Expertise dabei unterstützen, starke Seminarleiter*innen zu werden? Dann brauchen wir dich im Trainierenden-Team der SLS vom 02.-04.10.2026 in Kassel! Du hättest bereits Henrike Krahl, Emma Fössing und Kim Herzog als kompetente Teamkolleg*innen an deiner Seite - Fehlst nur noch du. 🫰🏻 Wenn du dabei bist oder noch Fragen hast, melde dich bei Rahel (perschke@yfu.de) aus der GS.
** Schulungen / Termine
*Lass dich als Seminarleitung schulen – komm zur SLS vom 02.-04.10.2026 in Kassel!*
Du hast Erfahrung als Teamer*in gesammelt, fühlst dich methodisch fit und suchst nach der nächsten Herausforderung? Als bereits erfahrene Seminarleitung wünschst du dir neuen Input und Gelegenheit zur Reflexion deiner Leitungsrolle? Dann komm zur Seminarleitungsschulung (SLS) vom 2.-4. Oktober 2026 in Kassel! 🚀In dieser Schulung werden die Basics vermittelt, die du als Seminarleitung kennen solltest, aber darüber hinaus gibt es auch Angebote für erfahrene Leitungen sich bspw. zum Umgang mit Menschenfeindlichkeit und Extremismus oder dem Thema Coaching weiterzubilden. Hier findest du mehr Infos zu den angebotenen Inhalten: https://intranet.yfu.de/article_tool/articles/2225. Melde dich gleich an!(https://forms.office.com/e/GKHKtJmCfy) Bei Fragen kontaktiere Rahel aus der GS (ehrenamt@yfu.de, Durchwahl -44).

*Engagiere dich mit YFU für Vielfalt und Verständigung an Schulen in ganz Deutschland – jetzt anmelden zur nächsten Colored Glasses Schulung*
Du machst den Unterschied für eine bunte Welt! Mit Colored Glasses setzt du dich aktiv für Vielfalt und ein faires Miteinander ein – direkt im Klassenzimmer durch interaktive Workshops auf Augenhöhe. Du diskutierst mit jungen Menschen über Toleranz und Diskriminierung, probierst dich aus und übernimmst Verantwortung. Starte mit der kostenlosen Schulung und entscheide selbst, wie oft du aktiv wirst. Lerne neue Skills in Moderation, Kommunikation und Teamarbeit. Engagement, das einen echten Unterschied macht – auch für dich! Du bist 16-26 Jahre alt und hast Lust, aktiv zu werden? Melde dich jetzt für die nächste Schulung an: 18.-20. Sept. 2026,  Jugendherberge “Horner Rennbahn” in Hamburg [[https://yfuit.sharepoint.com/:b:/t/GSexterngeteilteDateien/IQCYPKGgpbi7QpQ7CZyjoKDlAYz9QPWCf9MW5jmXvvjQYLQ?e=LCFSCg][Flyer]] | [[https://forms.cloud.microsoft/e/x3uPwy2qkx][Anmeldung]] | [[https://coloredglasses.de/ehrenamtlich-aktiv-werden/schulungen-fortbildungen/][weitere Informationen]] 
** Sonstiges / Externes
*Bewirb dich als World Storyteller und reise nach New York City🗽*
Die neue Kooperation von YFU Global und Made Impact ermöglicht 50 YFU‑Ehrenamtlichen aus unserem weltweiten Netzwerk die Teilnahme am [[https://madeimpact.org/world-storyteller-project][World Storyteller Project]] – inklusive Training und großem Summit am 31. August und 1. September 2026 in NYC. Fünf Ehrenamtliche aus Deutschland dürfen auch mitteilnehmen!🎉
Was steckt dahinter? Das World Storyteller Project verbindet eine weltweite Storyteller-Community, die die Wirkung von internationalem Austausch sichtbar macht. Dafür sammelst du 100 Geschichten von Menschen, die an einem internationalen Austauschprogramm teilgenommen haben. Alle Stories tragen zur Million Stories Initiative bei – dem weltweit größten Story-Archiv zur Wirkung von Austauschprogrammen.
🎯 Das große Ziel: Gemeinsam mit Made Impact möchten wir Internationale Bildung für den Friedensnobelpreis nominieren, um politische Weichen neu zu stellen und Austauschprogramme für alle zugänglich zu machen.
👥 Die Voraussetzungen: Du bist mind. 18 Jahre alt, engagierst dich ehrenamtlich bei YFU, bringst gute Englischkenntnisse und ein super Smartphone für das Training in NYC mit und bist bereit 100 Geschichten einzureichen.
💶 Die Kosten: Unterkunft und Verpflegung in New York sind für dich kostenlos. An den Flugkosten beteiligst du dich mit 300 Euro, den Rest übernehmen wir. Deine Flugkosten bekommst du zurück, sobald die 100 Geschichten eingereicht wurden.
❤️ Good to know: Wenn du dich als Storyteller bewerben möchtest, dir die Flugkosten aber gerade nicht leisten kannst, melde dich bei uns unter ehrenamt@yfu.de. Wir finden gemeinsam eine Lösung.
🔗  [[https://madeimpact.org/world-storyteller-project][Mehr erfahren]] 
👉 [[https://forms.office.com/pages/responsepage.aspx?id=BWlSWoAZoEWkdfNS5h_snk26cZNfjzhFnX6iITBtH2lURE8xMDE4WUZIVlRTR0FCNkVSSjVNU01CMS4u&route=shorturl][Jetzt bewerben!]] 
⏰ Deadline: 28 Juni 2026

*9.📝Umfrage zur Wertschätzung im Ehrenamt*
Ehrenamtliches Engagement ist das Herzstück von YFU – ohne euch wäre unsere Arbeit nicht möglich. Umso wichtiger ist es uns, besser zu verstehen, wie ihr eure ehrenamtliche Tätigkeit erlebt und in welchen Bereichen ihr euch mehr Wertschätzung wünscht. 
👉Daher möchten wir euch bitten, an dieser kurzen, anonymen [[https://forms.office.com/e/MLY2yUUbju?origin=lprLink][Umfrage]] teilzunehmen. 

*💪🏻 Kostenlose Selbstbehauptungstraining für Engagierte der DSEE*
Du engagierst dich – und bekommst dafür Gegenwind? Wer Haltung im Ehrenamt zeigt, wird leider immer häufiger mit verbalen Angriffen, Bedrohungen oder sogar körperlicher Gewalt konfrontiert. Mit dem kostenfreien Selbstbehauptungskurs für Engagierte möchte die [[https://www.deutsche-stiftung-engagement-und-ehrenamt.de/][Stiftung für Engagement und Ehrenamt]] euch dort stärken, wo es zählt. Gemeinsam mit erfahrenen Trainerinnen und Trainern erlernt ihr Strategien und Techniken, um in schwierigen oder bedrohlichen Situationen sicher zu reagieren. Der Fokus liegt darauf, Konflikte frühzeitig zu erkennen, souverän aufzutreten und Eskalationen möglichst zu vermeiden. So könnt ihr auch in angespannten Momenten handlungsfähig bleiben – und euer Engagement mit mehr Sicherheit ausüben. Von Juli bis Oktober 2026 könnt ihr einem der 10 Termine in Cottbus, Ulm, Kassel, Gera, Hamburg, Berlin, Essen, Nürnberg, Magdeburg oder Bremen teilnehmen. 👉🏻 [[https://www.deutsche-stiftung-engagement-und-ehrenamt.de/mitmachen/selbstbehauptung-fuer-engagierte/#toggle-id-2-closed][Weiter Infos und Anmeldung]]  

*Digitale Erstattungsanträge ab sofort live! 🎉*
Eure EAs könnt ihr ab jetzt ganz entspannt digital einreichen! Das Geld für Bahntickets, Einkäufe oder Ähnliches bekommt ihr damit viel unkomplizierter zurück. Alle Infos findet ihr hier: https://intranet.yfu.de/article_tool/articles/2224.

*⛑️ Kostenlose Erste-Hilfe-Kurse für Engagierte der DSEE*
Notfälle können überall passieren. Dann kommt es darauf an, schnell und richtig zu reagieren. In den angebotenen Erste-Hilfe-Kursen, die sich speziell an Engagierte richten, könnt ihr eure Kenntnisse auffrischen und Sicherheit gewinnen. Die Kurse werden bundesweit angeboten, sind kostenlos und auf kleine Gruppen von bis zu 15 Engagierten ausgelegt. 👉🏻 [[https://www.deutsche-stiftung-engagement-und-ehrenamt.de/aktuelles/erste-hilfe-kurse-fuer-engagierte-2026/#toggle-id-3-closed][Schaut hier gleich nach Terminen und Städten und meldet euch an!]] Kein Angebot in der deiner Nähe dabei? Dann lies [[https://intranet.yfu.de/downloads/files/3528][hier]] nach, zu welchen Konditionen du eine Erste-Hilfe-Ausbildung für YFU besuchen kannst, für die unsere Versicherung die Kosten übernimmt. Bei Fragen melde dich unter ehrenamt@yfu.de bei uns.

*Tipp der Woche: Better Allies Newsletter*
Jede Woche teilt die Autorin Karen Catlin von [[https://betterallies.com/][Better Allies]], fünf einfache, konkrete Impulse, mit denen du zu einem inklusiven Arbeitsumfeld beitragen kannst, in dem sich alle entfalten können. Hier bekommst du einen ersten Vorgeschmack: [[https://us19.campaign-archive.com/?u=cc808df089bf312fc1a37916d&id=eea87a0f51][5 Ally Actions - Jun 12, 2026]]
Hier kannst du ihn abonnieren: [[https://betterallies.com/subscribe/][subscribe – Better Allies®]] 
* Terminübersicht
** TERMINE 2026
*20.06. - 21.06.2026* &nbsp;&nbsp;&nbsp; Colored Glasses Schulung, Liebfrauenschule Mühlhausen (*bei Duisburg*)

*18.09. -20.09. 2026* &nbsp;&nbsp;&nbsp; Colored Glasses Schulung, Jugendherberge Horner Rennbahn *Hamburg*

*02.10. - 04.10.2026*  &nbsp;&nbsp;&nbsp; Seminarleitungsschulung (SLS), Jugendherberge *Kassel*
*02.10. - 04.10.2026*  &nbsp;&nbsp;&nbsp; *(LG)* Aktivenwochenende

*06.11. – 08.11.2026* &nbsp;&nbsp;&nbsp; Colored Glasses Schulung, Jugendherberge *Kassel*

*20.11. - 22.11.2026* &nbsp;&nbsp;&nbsp; Betreuendenseminar, *Jugendherberge Stuttgart*

*27.11. - 29.11.2026* &nbsp;&nbsp;&nbsp; ÖA-Ausschusstreffen, *Hamburg*

*06.05. - 09.05.2027* &nbsp;&nbsp;&nbsp; BUT 2027, *tba*
