* Landesgruppe
**  Wichtige Info Aufrufe Newsletter
Diesen Newsletter findet ihr ab jetzt auch auf Whatsapp! Dafür einfach über diesen Link beitreten: https://chat.whatsapp.com/GBCBuLIU2U78zpim5yGxLF
---

Sehr gerne nehmen wir eure Aufrufe oder Danksagungen in den wöchentlichen Newsletter auf.

Schreibt mir ([[mailto://shh-newsletter@yfu-deutschland.de][shh-newsletter@yfu-deutschland.de]]) dafür einfach immer bis *Mittwochs 17:00 Uhr* eure Aufrufe, damit ich sie noch in den Newsletter der aktuellen Woche mit aufnehmen kann. Ansonsten nehme ich die Aufrufe natürlich gerne in den nächsten auf.

Vielen lieben Dank und ich freue mich auf eure Emails.

Liebe Grüße
Aimo
* Öffentlichkeitsarbeit
** Schulvortrag am Gymnasium Brunsbüttel
Wann: flexibel möglich!
Meldet euch gerne bei kira.thede@yfu-deutschland.de
Wo: Gamnasium Brunsbüttel
Kopernikusstr. 1
22541 Brunsbüttel
** Infoabend mit AJAOrgas in Husum
Wann: 09.06.2026 19:00
Wo: Theodor-Storm-Schule
Ludwig-Nissen-Str. 62
25813 Husum
Wer: 1-2 Teamer jedes Erfahrungsgerades
Bei Interesse: kira.thede@yfu-deutschland.de
** Schulvortrag am Goethe-Gymnasium
Wann: 15.06.2026 15:00 (Teamtreffen 13:30)
Wo: Goethe-Gymnasium Hamburg (Altona)
Rispenweg 28, 22547 Hamburg
Wer: 1-2 Teamer jedes Erfahrungsgerades
Bei Interesse: kira.thede@yfu-deutschland.de
** Schulvortrag am Gymnasium Trittau
Wann: 18.06.2026
Wo: Gymnasium Trittau
Wer: 1-2 Teamer jedes Erfahrungsgerades
Bei Interesse: kira.thede@yfu-deutschland.de
* Aufnahmeprogramm
** Betreuungsschulung in Berlin am 13. Juni
Liebe Regionalbetreuungskolleg*innen,
Liebe AP-Leitungen (da wo es noch keine RB's gibt 😉),

ich organisiere für den 13.06. eine überregionale Betreuungsschulung - als Tagesschulung - in Berlin, und es gibt noch freie Plätze!
Es sind zwar schon etliche Anmeldungen eingegangen, aber ich würde mich sehr freuen, wenn noch ein paar dazu kommen, damit es sich richtig lohnt.
Deshalb würde ich euch gerne um etwas bitten:
Könntet ihr die Einladung - siehe unten - in eure Landesgruppen-Verteiler, LG-WhatsApp-Gruppen, etc. leiten und ggf. auch an betreuungsinteressierte Personen senden, wenn ihr welche kennt?

Für eure Unterstützung wäre ich super dankbar!

Vielen Dank und liebe Grüße aus Berlin,
Caren
** Aufruf GF Re-Entry
Liebe Landesgruppe,

für unsere Gastfamilien- Re-Entry im Haus Warwisch am 07.06. suchen wir noch dringend Teamende (Erfahrung egal). Die Veranstaltung geht meistens ca. von 12-16 Uhr - die genauen Zeiten werden noch bestätigt. Es geht darum, mit den Gastfamilien die Erfahrung gemeinsam zu reflektieren und den Nachmittag anschließend mit einem Buffet gemeinsam mit den Austauschschüler*innen ausklingen zu lassen. 

Meldet euch super gerne bei mir (amilou.fehr@yfu-deutschland.de oder unter 01786122651), wenn ihr Lust auf einen spannenden Nachmittag habt! 

LG und danke euch
Amilou
** Teamergesuch Re-Entry SHH
Moin,
Gibt es unter euch noch jemanden, der Zeit und Lust hat, die SHH-Re-Entry vom 5. - 7.6.26 in Warwisch zu unterstützen?

Erfahrung ist egal, Anreise ist Freitagvormittag.😃
Falls ja - oder es vorher noch Fragen gibt -, meldet euch seeeehr gerne direkt bei mir unter Ines.hintz@yfu-deutschland.de oder 0163-9180370.

Schon mal ein großes DANKESCHÖN!
Ines
* Entsendeprogramm
** Teamende und Leitungen für die NBT-Saison gesucht
Liebe Landesgruppe,

es ist so weit, die NBT-Saison steht vor der Tür und wir suchen viele begeisterte Teamende und Leitungen.
Dieses Jahr organisieren wir drei NBTs in Schleswig-Holstein-Hamburg.

NBT SHH 1: *13.08. – 16.08.2026* (inklusive VNBT) Spejdergården Tydal, Eggebek
NBT SHH 2: *10.09. - 13.09.2026* (inklusive VNBT) CISV-Haus, Hamburg 
NBT SHH 3: *01.10. – 04.10.2026* (inklusive VNBT) Spejdergården Tydal, Eggebek

Wenn ihr also Lust habt, die Austauschschüler*innen auf ihrem Rückkehrprozess zu begleiten, tolle Menschen zu sehen, YFU-Spirit zu verbreiten oder einfach mal wieder etwa für YFU zu machen, dann meldet euch gerne bis zum 31.05.2025 unter folgendem Link an: https://tinyurl.com/YFUNBTEhrenamtlichensuche2026

Für die NBTs der anderen LGs könnt ihr euch ebenfalls unter diesem Link anmelden.

Bei Fragen meldet euch gerne bei uns unter antonia.karg@yfu-deutschland.de.
 
Liebe Grüße
Greta & Antonia
* Externes und Überregionales
** Mitarbeiter-Gesuche/Stellen
*USA for you Sachsen-Anhalt: Programmbegleitung (m/d) gesucht*
Für die Begleitung der USA for you-Teilnehmenden aus Sachsen-Anhalt nach Michigan vom 16. bis 30.10.2026 suchen noch eine Person (m/d), die die Gruppe in die USA begleitet und auch die VBT und die NBT gemeinsam mit der weiteren Programmbegleitung leitet. 
Die Ausschreibung findet ihr hier: https://intranet.yfu.de/article_tool/articles/2216
Für Fragen könnt ihr Thekla unter usaforyou@yfu.de, Durchwahl -77, kontaktieren.

*Germany for you in Halle (Saale): Teamer*in für zwei Workshops gesucht:*
Die amerikanischen Jugendlichen, die mit Germany for you für zwei Wochen in Halle sind, haben einen Arrival- und einen Pre-Departure Workshop. Dafür suchen wir noch eine Person (m/w/d), die am 15.6. und 16.6. (jeweils 8:30 - 12:00 Uhr) sowie am 26.6. (8:30-12:00 Uhr) unterstützt.
Meldet euch dazu gern bei Thekla: germanyforyou@yfu.de, Durchwahl -77

*OWO-Leitungen gesucht*
 - Für die OWO 1 vom 16. - 20.08 in Mainz suchen wir 1 erfahrene Leitung
 - Für die OWO 4 vom 23. - 27.08 in Mainz suchen wir 2 Leitungen
Bitte meldet euch bei Mareen (📧 ap-seminare@yfu.de) oder füllt diese [[https://forms.office.com/e/KYWzZNfDNt?origin=lprLink][Umfrage]] aus. Alle weiteren Infos findet ihr [[https://intranet.yfu.de/downloads/files/3970][hier]].

*OWO-Teamende gesucht*
Du hast Lust auf Seminare im Aufnahmeprogramm? Du möchtest Austauschschüler*innen bei ihrem Start in ihr Austauschjahr unterstützen und sie für das Zusammenleben mit ihrer Gastfamilie wappnen? Du möchtest andere YFUler*innen wiedertreffen? Du kennst dich mit Kommunikation und Kultur super aus und hast vom 16. - 20.08 oder 23. - 27.08 Zeit? Dann sind das Top Voraussetzungen, um eine OWO zu teamen! Bitte melde dich bei Mareen (📧 ap-seminare@yfu.de) oder fülle diese [[https://forms.office.com/e/KYWzZNfDNt?origin=lprLink][Umfrage]] aus. Alle weiteren Infos findest du [[https://intranet.yfu.de/downloads/files/3970][hier]].

*💬 Engagiere dich beim RHWF Re-Entry in Wuppertal vom 4. bis 7. Juni*
Für alle Erfahrungslevel geeignet
Wir suchen dringend Teamende, auch für das Re-Entry (inkl. Elterntreffen). Du unterstützt gemeinsam mit anderen Ehrenamtlichen die Durchführung und bringst dich ins Programm ein.
Wann & wo? 🗓 4. bis 7. Juni 📍 Wuppertal
👉 Interesse? Melde dich gern bei mir: friederike.klaas@yfu-deutschland.de
** Schulungen / Termine
*Powerstart ins Ehrenamt am 18. Juni von 19-20.30 Uhr*
Du möchtest aktiv werden oder wieder einsteigen und brauchst für den Start noch ein bisschen Orientierung? Dann haben wir einen Tipp für dich🔥! Starte mit unseren Ehrenamtlichen beim digitalen Powerstart ins Ehrenamt durch. Lerne das YFU 1x1, finde heraus, was es für dich zu tun gibt, wie du dich mit YFUler*innen in deiner Umgebung vernetzen kannst und welche Vorteile du als YFUler*in genießt. 
🔥 Anmeldung hier: https://tinyurl.com/jszynj7n
** Sonstiges / Externes
*Jetzt noch schnell rein in den Verein: Mitglied werden und am 30. Juni mitstimmen!*
⏳ Der Countdown läuft! Am 30. Juni ist die YFU-Mitgliederversammlung. Wir entscheiden gemeinsam über die Zukunft unseres Vereins. Auf der Mitgliederversammlung wird über die neue Satzung abgestimmt. Wir wollen die Weichen stellen für eine starke und zukunftsfähige Organisation.
👉 Jetzt in 2 Minuten Mitglied werden und mitstimmen: [[https://mailing.yfu.de/c2/BEFM7SI/333241-16967789/d95ac54a40a9-df6370d2c29c-f359f5f56d34-dfc858e4fc03-da0349b118f0-456473d7aa10-6bf9556bd9ce-62eb4be5619c-c3c4a2a44a84-494d9928fdfc-35f2c233/][Mitgliedsantrag]] ausfüllen
(💡 /Mitgliedsanträge können bis 26.06.26 für die Mitgliederversammlung berücksichtigt werden. Erst nach Annahme des Antrags wird das Stimmrecht aktiv./)

*📩 Dein YFU im Wandel – bleib aktuell mit dem Strukturkompass*
Die Strukturreform klingt groß und fühlt sich immer noch ziemlich abstrakt an. 

/Was bedeutet das alles für dein Ehrenamt und deine Mitgliedschaft?/
/Wie verändert sich YFU konkret?/
/Und wo kannst du dich in Zukunft einbringen und mitgestalten?/

Der Strukturkompass gibt dir Orientierung. 
Darin informieren dich Nate aus der AG Strukturreform und Julia aus der Geschäftsstelle regelmäßig über die aktuelle Lage, teilen wichtige Vereinsentscheidungen und Meilensteine, geben Einblicke hinter die Kulissen und zeigen dir, wo und wie du mitwirken kannst. 
Jetzt ein Abo dalassen – denn gemeinsam gestalten wir die Zukunft von YFU.
📩 Hier kannst du ihn abonnieren: https://mailing.yfu.de/f/333241-426684/

*📝 Mach mit: Umfrage der AG Prävention sexualisierter Gewalt*
Die AG Prävention sexualisierter Gewalt arbeitet derzeit an einem Schutzkonzept, das in Zukunft helfen soll, YFU Deutschland sicherer zu machen. Dazu führen wir eine Umfrage unter allen aktuellen und ehemaligen Mitarbeitenden durch – egal, wie aktiv ihr momentan seid oder welche Erfahrungen ihr gemacht habt. Eure Antworten helfen uns. Die Umfrage läuft bis zum 31.05.26. Vielen Dank für eure Unterstützung! https://www.yfu-survey.org/poll/index.php/314721?lang=de-informal

*📝Umfrage zur Wertschätzung im Ehrenamt*
Ehrenamtliches Engagement ist das Herzstück von YFU – ohne euch wäre unsere Arbeit nicht möglich. Umso wichtiger ist es uns, besser zu verstehen, wie ihr eure ehrenamtliche Tätigkeit erlebt und in welchen Bereichen ihr euch mehr Wertschätzung wünscht. 
👉Daher möchten wir euch bitten, an dieser kurzen, anonymen [[https://forms.office.com/e/MLY2yUUbju?origin=lprLink][Umfrage]] teilzunehmen. Vielen Dank für eure Unterstützung! 💜
* Terminübersicht
** TERMINE 2026
*29.05 - 31.05.2026* &nbsp;&nbsp;&nbsp; ÖA-Ausschusstreffen, *Hamburg*

*05.06. - 07.06.2026* &nbsp;&nbsp;&nbsp; *(LG)* Nord-LGT

*13.06. - 13.06.2026* &nbsp;&nbsp;&nbsp; Betreuungsschulung, *Berlin*

*20.06. - 21.06.2026* &nbsp;&nbsp;&nbsp; Colored Glasses Schulung, Liebfrauenschule Mühlhausen (*bei Duisburg*)

*18.09. -20.09. 2026* &nbsp;&nbsp;&nbsp; Colored Glasses Schulung, Jugendherberge Horner Rennbahn *Hamburg*

*25.09. - 27.09.2026* &nbsp;&nbsp;&nbsp; *(LG)* Aktivenwochenende

*02.10. - 04.10.2026*  &nbsp;&nbsp;&nbsp; Seminarleitungsschulung (SLS), Jugendherberge *Kassel*

*06.11. – 08.11.2026* &nbsp;&nbsp;&nbsp; Colored Glasses Schulung, Jugendherberge *Kassel*

*20.11. - 22.11.2026* &nbsp;&nbsp;&nbsp; Betreuendenseminar, *Jugendherberge Stuttgart*

*27.11. - 29.11.2026* &nbsp;&nbsp;&nbsp; ÖA-Ausschusstreffen, *Hamburg*

*06.05. - 09.05.2027* &nbsp;&nbsp;&nbsp; BUT 2027, *tba*
