* Landesgruppe
**  Wichtige Info Aufrufe Newsletter
Diesen Newsletter findet ihr ab jetzt auch auf Whatsapp! Dafür einfach über diesen Link beitreten: https://chat.whatsapp.com/GBCBuLIU2U78zpim5yGxLF
---

Sehr gerne nehmen wir eure Aufrufe oder Danksagungen in den wöchentlichen Newsletter auf.

Schreibt mir ([[mailto://shh-newsletter@yfu-deutschland.de][shh-newsletter@yfu-deutschland.de]]) dafür einfach immer bis *Mittwochs 17:00 Uhr* eure Aufrufe, damit ich sie noch in den Newsletter der aktuellen Woche mit aufnehmen kann. Ansonsten nehme ich die Aufrufe natürlich gerne in den nächsten auf.

Vielen lieben Dank und ich freue mich auf eure Emails.

Liebe Grüße
Aimo
** Einladung zum Nord-LGT 2026
Liebe Nord-LGs,
Wir konnten es alle kaum abwarten, aber jetzt ist es endlich so weit: das nächste Nord-LGT steht an! Wir freuen uns auf ein sommerliches Wochenende mit euch in Barmstedt bei Pinneberg (keine Sorge, das ist vom Hamburger Hauptbahnhof gut mit der Bahn erreichbar) mit vielen tollen Workshops, einem unterhaltsamen Programm und Zeit dafür, alte und neue Bekanntschaften wiederzusehen.

Wann? 05.-07..06.2026
Wo? Victor-Andersen-Haus Pinneberg (Düsterlohe 5, 25355 Barmstedt )
 
Meldet euch ab jetzt bis Mitte Mai über diesen Link an: [[https://forms.cloud.microsoft/e/JQQUuacHDj][Nord-LGT 2026 – Formular ausfüllen]]
Die Plätze sind begrenzt, also meldet euch schnell an. Anmeldeschluss ist der 15.05.2026.

Wir haben dieses Jahr eine Teilnahmegebühr von 20€. Solltet ihr Schwierigkeiten haben, diese zu erbringen, meldet euch gerne per Mail bei uns und wir finden eine Lösung dafür. Fahrtkosten erstatten wir für alle, die wollen, bis zu 30€, wenn ihr günstig und früh bucht. Das heißt bis 2 Wochen vor dem 05.06. (also 21.05.) und achtet gerne auf BahnCard und Deutschlandticket.  

Solltet ihr noch irgendwelche Fragen haben, erreicht ihr uns alle unter dieser Mailadresse: nordlgt@lists.yfu-deutschland.de. Wir freuen uns auf eure Anmeldungen!

Euer Nord-LGT Orga Team
* Öffentlichkeitsarbeit
** Neue Infos
Hallo liebe Landesgruppe,

die neue Bewerbungssaison bei YFU für das Programmjahr 2027/28 hat Anfang April gestartet und daher gibt es auch in der ÖA in den nächsten Wochen und Monaten immer wieder was zu tun! Um weiterhin viele Schüler für ein Auslandsjahr zu begeistern, brauchen wir wie immer eure Unterstützung. Wenn ihr also Lust und Zeit habt, meldet euch für die folgenden Termine gerne bei kira.thede@yfu-deutschland.de
** AJA-Schulvortrag an der THS Pinneberg

Wann: 05.05.26, 19:00 Uhr (Aufbau bzw. Treffen bereits 18:30 Uhr)
Wo: Theodor-Heuss-Schule Pinneberg, 
Datumer Chaussee 2, 
25421 Pinneberg
Wer: 2-3 motivierte Teamer jedes Erfahrungsgerades
* Aufnahmeprogramm
** Aufruf GF Re-Entry
Liebe Landesgruppe,

für unsere Gastfamilien- Re-Entry im Haus Warwisch am 07.06. suchen wir noch dringend Teamende (Erfahrung egal). Die Veranstaltung geht meistens ca. von 12-16 Uhr - die genauen Zeiten werden noch bestätigt. Es geht darum, mit den Gastfamilien die Erfahrung gemeinsam zu reflektieren und den Nachmittag anschließend mit einem Buffet gemeinsam mit den Austauschschüler*innen ausklingen zu lassen. 

Meldet euch super gerne bei mir (amilou.fehr@yfu-deutschland.de oder unter 01786122651), wenn ihr Lust auf einen spannenden Nachmittag habt! 

LG und danke euch
Amilou
* Externes und Überregionales
** Mitarbeiter-Gesuche/Stellen
*Erfahrene Teamende für VBT im Mai in Mühlhausen gesucht*
Die VBT findet statt vom 03.05.-08.05. in Mühlhausen
Es gibt mit u.a. Charlie Goetjes ein sehr erfahrenes Leitungsteam
Wir brauchen erfahrene Teamende, die Charlie und Max auf der VBT unterstützen, damit sie stattfinden kann
Bitte meldet euch bei Fenja unter vbt@yfu.de

*Eine weibliche erfahrene Teamerin für VBT in Mühlhausen gesucht*
Für die erste BY-VBT vom 08.-13.05. in Mühlhausen suchen wir eine weitere Person für das Team
Vorzugsweise weiblich, aber auf jeden Fall erfahren
Leitung und das restliche Team stehen bereits
Bitte melde dich bei Fenja unter vbt@yfu.de
 
*Teamende für VBT Mitte Mai in Mühlhausen gesucht*
Die VBT findet statt vom 16.05.-21.05. in Mühlhausen
Wir brauchen erfahrene Teamende, die die bestehende Leitung unterstützen und das Team vervollständigen
Bitte meldet euch bei Fenja unter vbt@yfu.de

*🏆 Qualifiziere Seminarleitungen – Werde Trainer*in bei der Seminarleitungsschulung (SLS) im Oktober in Kassel*
Du möchtest andere YFUler*innen dabei unterstützen starke Seminarleiter*innen zu werden? Dann werde Teil des Trainierenden-Teams bei der SLS im Oktober! Du hättest bereits drei kompetente Menschen als Teamkolleg*innen an deiner Seite. 💪🏻 Die Schulung findet vom 02.-04.10.2026 in Kassel statt. Ein Konzept für den Rahmen der Schulung gibt es bereits, bei der Umsetzung hast du gestalterischen Spielraum, deine Ideen, Erfahrung und Methoden einzubringen. Es ist vorgesehen, dass sowohl Inhalte für Einsteiger*innen als auch zur Vertiefung für Menschen mit Leitungserfahrung angeboten werden. Wenn das das Richtige für dich ist oder du noch Fragen hast, melde dich bei Rahel (perschke@yfu.de) und sei dabei!

*👑 Weiterhin Trainierende für das Training of Trainers (ToT) vom 25.-27.09. in Wiesbaden gesucht!*
Du hast Erfahrung als Workshop-Gebende*r, fühlst dich sicher in der Methodenauswahl und hast Strategien parat, mit Herausforderungen in der Workshop-Durchführung umzugehen. Du möchtest dein Expert*innen-Wissen und deine Erfahrung als Trainer*in an YFU-Ehrenamtliche weitergeben? Dann werde Teil des Trainierenden-Teams für das nächste ToT vom 25.-27. September 2026 in Wiesbaden und unterstütze andere dabei, selbst Workshops und Schulungen geben zu können. Lust bekommen oder Fragen? Dann melde dich bei Rahel (perschke@yfu.de, +49 40 22 70 02 44) aus der Geschäftsstelle.

*Colored Glasses sucht Verstärkung für das ehrenamtliche Marketing-Team im Bereich Social Media*
Du möchtest kreativ werden und gleichzeitig etwas bewegen? Dann werde Teil unseres ehrenamtlichen Marketing-Teams! Im Marketing-Team geben wir Colored Glasses auch online ein Gesicht. Gemeinsam arbeiten wir daran, unsere Botschaft nach außen zu tragen und noch mehr junge Menschen für unsere Workshops zu begeistern. Zu deinen Aufgaben gehört vor allem die Erstellung von Content, sowie die Entwicklung neuer Formate und Kampagnen, bei denen du deine Ideen einbringen und direkt umsetzten kannst. Dabei sammelst du Erfahrungen im Bereich Marketing & Öffentlichkeitsarbeit – ganz flexibel von zu Hause oder Unterwegs. Außerdem hast du die Möglichkeit, an Calls und Treffen teilzunehmen und darüber zu berichten. Melde dich jetzt bei Anjuli unter anjuli-thiel@yfu-deutschland.de. Mehr Infos gibt’s [[https://coloredglasses.de/wp-content/uploads/2026/04/CG-Stellenausschreibung-Referentin-fuer-Marketing.pdf][hier]].  

*USA for you: Teamer*in für die NBT in Hamburg vom 8. bis 10. Mai gesucht*
Für die Nachbereitung der USA for you-Gruppe aus Hamburg suchen wir noch ehrenamtliche Unterstützung (m/w/d). Die Tagung geht von Freitagnachmittag bis Sonntagnachmittag und wird von den beiden Programmbegleitungen, die mit der Gruppe in den USA waren, geleitet. 
Meldet euch bei Interesse bei Thekla: usaforyou@yfu.de, Durchwahl -77

*USA for you-Auswahl in Halle (Saale): Ein Team-Mitglied für den 09. Mai 2026 gesucht*
Um aus den zahlreichen USA for you-Bewerbungen wieder eine tolle Gruppe zusammenzustellen, suchen wir noch eine Person, die das Team bei der Auswahl unterstützt.  Reisekosten und ggf. Unterkunft werden übernommen. 
Meldet euch bei Interesse bei Thekla: usaforyou@yfu.de, Durchwahl -77

*Germany for you: Programmbegleitung vom 13. bis 28. Juni 2026 in Halle (Saale) gesucht (Honorarvertrag)*
Für das Germany for you-Programm suchen wir eine Programmbegleitung (m/w/d), die gemeinsam mit einer amerikanischen Programmbegleitung und weiteren Ehrenamtlichen vor Ort in Halle eine Gruppe von 15 Jugendlichen aus den USA bei einem bunten Programm aus ehrenamtlichem Einsatz, Sightseeing (in Halle und Berlin), Sprachkurs und Sportprogramm begleitet.
Mehr Infos hier: https://intranet.yfu.de/article_tool/articles/2220
Meldet euch bei Interesse gern bei Thekla: germanyforyou@yfu.de, Durchwahl -77

*USA for you Sachsen-Anhalt: Programmbegleitungen gesucht*
Für die Begleitung der USA for you-Teilnehmenden aus Sachsen-Anhalt nach Michigan vom 16. bis 30.10.2026 suchen wir zwei Ehrenamtliche, die die Gruppe in die USA begleiten und auch die VBT und die NBT gemeinsam leiten. 
Die Ausschreibung findet ihr hier: https://intranet.yfu.de/article_tool/articles/2216
Für Fragen könnt ihr Thekla unter usaforyou@yfu.de, Durchwahl -77, kontaktieren.

*Germany for you in Halle (Saale): Teamer*in für zwei Workshops gesucht:*
Die amerikanischen Jugendlichen, die mit Germany for you für zwei Wochen in Halle sind, haben einen Arrival- und einen Pre-Departure Workshop. Dafür suchen wir noch eine Person (m/w/d), die am 15.6. und 16.6. (jeweils 8:30 - 12:00 Uhr) sowie am 26.6. (8:30-12:00 Uhr) unterstützt.
Meldet euch dazu gern bei Thekla: germanyforyou@yfu.de, Durchwahl -77

*Familienbesucher*innen gesucht!*
Wir haben ein paar engagierte Gastfamilie, die sich vorstellen können, ins Programm zu kommen und bereits voller Vorfreude auf ihr Gastkind sind. Was noch fehlt? Der Familienbesuch!
Die Familien wohnen an folgenden Orten:
 - 06242 Roßbach
 - 36414 Unterbreizbach
 - 56477 Zehnhausen
Du wohnst in der Nähe der Familien oder hast Lust auf einen Ausflug? 😊 Dann melde dich für die Details bei uns (gastfamilien@yfu.de). Melde dich auch gerne, wenn du bisher keine Erfahrung mit Familienbesuchen hast, aber grundsätzlich interessiert bist.
** Schulungen / Termine
*Colored Glasses Schulung am 15.-17. Mai bei München und am 20./21. Juni bei Duisburg – Starte jetzt dein Engagement für eine bunte Gesellschaft!*
Mit Colored Glasses Workshops begeistern wir Kinder und Jugendliche der 5. bis 13. Klasse an Schulen und Jugendeinrichtungen in ganz Deutschland für Vielfalt und Toleranz. Wir machen uns stark gegen Diskriminierung und Vorurteile durch spannende Simulationen und Diskussionen auf Augenhöhe! Die Schulung ist dein Start ins Ehrenamt: Wir zeigen dir, wie du einen Workshop planst und durchführst. Erfahrene Ehrenamtliche geben dir Tipps und Tricks, damit du auch ohne Vorerfahrung einen echten Unterschied machen kannst. Du bist zwischen 16 und 29 Jahre alt und willst aktiv werden? Melde dich zur kostenlosen Schulung an: am 15.-17.05. in der Jugendherberge Burg Schwaneck (bei München) [[https://forms.cloud.microsoft/e/e4gc6GAqC0][hier]] oder am 20./21.06. an der Liebfrauenschule Mühlhausen in Grefrath (bei Duisburg) [[https://forms.cloud.microsoft/e/vB4gw7NGtJ][hier]].  Für beide Termine sind nur noch wenige Plätze frei! Bei Fragen wenden dich gerne an Nina unter roesch@yfu.de.
** Sonstiges / Externes
*📝 Mach mit: Umfrage der AG Prävention sexualisierter Gewalt*
Die AG Prävention sexualisierter Gewalt arbeitet derzeit an einem Schutzkonzept, das in Zukunft helfen soll, YFU Deutschland sicherer zu machen. Dazu führen wir eine Umfrage unter allen aktuellen und ehemaligen Mitarbeitenden durch – egal, wie aktiv ihr momentan seid oder welche Erfahrungen ihr gemacht habt. Eure Antworten helfen uns. Die Umfrage läuft bis zum 31.05.26. Vielen Dank für eure Unterstützung! https://www.yfu-survey.org/poll/index.php/314721?lang=de-informal

*Jetzt bewerben – Summer Academy 2026 „Building Bridges: Leading, Participating, and Reasoning for Europe’s Future“*
In einer Welt, die von gesellschaftlichem und politischem Wandel geprägt ist, brauchen junge Menschen Räume für (politischen) Austausch, Vernetzung und gemeinsames Lernen.
Die Summer Academy „Building Bridges: Leading, Participating, and Reasoning for Europe’s Future“ 2026 wird von InterCultur gGmbH organisiert und durchgeführt. In Kooperation mit der Stiftung Mercator und der Karlshochschule International University geht es darum, junge Changemaker zu befähigen, sich unter Einbezug globaler Zusammenhänge und individueller Erfahrungen, politische, gesellschaftliche und ethische Perspektiven auf Europas Rolle in globalen Transformationsprozessen zu erarbeiten, diese gemeinsam zu diskutieren und weiterzuentwickeln.
📆 Vom 28. Juni bis 5. Juli 2026 an der Karlshochschule International University
👉 Weitere Informationen zur Academy findet ihr hier: https://intercultur.de/aktuelles/ 
📝 Hier kannst du dich bis zum 26. April bewerben: https://tinyurl.com/27pa5hfa

*💜🤝Was hat dein Ehrenamt mit dir gemacht?*
Ehrenamt verändert. Es bringt neue Perspektiven, stärkt Selbstvertrauen, schafft Begegnungen und hinterlässt oft mehr, als man im ersten Moment merkt.
Genau das möchten wir sichtbar machen. Erzähl uns, wie dich dein Ehrenamt verändert hat: Füll unsere kurze Umfrage aus, schick uns ein Foto von dir und werde Teil unserer Community‑Aktion!
Die Einsendungen veröffentlichen wir in unserer Community, auf Instagram, im Vereinsnewsletter und auf weiteren Social‑Media‑Kanälen – um Danke zu sagen, Engagement wertzuschätzen und andere zu ermutigen, selbst aktiv zu werden.
✨ Mach mit und zeig, wie Ehrenamt wirkt: https://forms.office.com/e/ERkvky3x6R
* Terminübersicht
** TERMINE 2026
*08.05. - 10.05.2026* &nbsp;&nbsp;&nbsp; Interessenseminar-Lateinamerika (ILSA), *in Rinteln*

*15.05. - 17.05.2026* &nbsp;&nbsp;&nbsp; Colored Glasses Schulung, Jugendherberge Burg Schwaneck (*bei München*)

*29.05 - 31.05.2026* &nbsp;&nbsp;&nbsp; ÖA-Ausschusstreffen, *Hamburg*

*05.06. - 07.06.2026* &nbsp;&nbsp;&nbsp; *(LG)* Nord-LGT

*13.06. - 13.06.2026* &nbsp;&nbsp;&nbsp; Betreuungsschulung, *Berlin*

*20.06. - 21.06.2026* &nbsp;&nbsp;&nbsp; Colored Glasses Schulung, Liebfrauenschule Mühlhausen (*bei Duisburg*)

*18.09. -20.09. 2026* &nbsp;&nbsp;&nbsp; Colored Glasses Schulung, Jugendherberge Horner Rennbahn *Hamburg*

*25.09. - 27.09.2026* &nbsp;&nbsp;&nbsp; *(LG)* Aktivenwochenende

*02.10. - 04.10.2026*  &nbsp;&nbsp;&nbsp; Seminarleitungsschulung (SLS), Jugendherberge *Kassel*

*06.11. – 08.11.2026* &nbsp;&nbsp;&nbsp; Colored Glasses Schulung, Jugendherberge *Kassel*

*20.11. - 22.11.2026* &nbsp;&nbsp;&nbsp; Betreuendenseminar, *Jugendherberge Stuttgart*

*27.11. - 29.11.2026* &nbsp;&nbsp;&nbsp; ÖA-Ausschusstreffen, *Hamburg*
