* Landesgruppe
**  Wichtige Info Aufrufe Newsletter
Diesen Newsletter findet ihr ab jetzt auch auf Whatsapp! Dafür einfach über diesen Link beitreten: https://chat.whatsapp.com/GBCBuLIU2U78zpim5yGxLF
---

Sehr gerne nehmen wir eure Aufrufe oder Danksagungen in den wöchentlichen Newsletter auf.

Schreibt mir ([[mailto://shh-newsletter@yfu-deutschland.de][shh-newsletter@yfu-deutschland.de]]) dafür einfach immer bis *Mittwochs 17:00 Uhr* eure Aufrufe, damit ich sie noch in den Newsletter der aktuellen Woche mit aufnehmen kann. Ansonsten nehme ich die Aufrufe natürlich gerne in den nächsten auf.

Vielen lieben Dank und ich freue mich auf eure Emails.

Liebe Grüße
Aimo

* Öffentlichkeitsarbeit
** Neue Infos
Liebe Landesgruppe,

bald sind die Märzferien vorbei und wir suchen wieder eure Unterstützung.
Wenn ihr Zeit und Lust habt meldet euch gerne bei [[mailto:sophie.schnipkoweit@yfu-deitschland.de][sophie.schnipkoweit@yfu-deitschland.de]] oder bei [[mailto:kira.thede@yfu-deutschland.de][kira.thede@yfu-deutschland.de]]
** Schulvortrag am Gymnasium Brunsbüttel
Wann: Flexible Absprache mit Ansprechpartner der Schule

Wo:
Gymnasium Brunsbüttel
Kopernikusstr. 1
25541 Brunsbüttel

Wer: 2-3 erfahrene und unerfahrene Personen
** Schulvortrag am Gymnasium Farmsen
Wann: Am 14.04.2026; Beginn um 18 Uhr

Wo:
Gymnasium Farmsen
Swebenhöhe 50
22159 Hamburg

Wer: 1-2 erfahrene sowie unerfahrene Personen 

Meldet euch hier gerne bei Kira (kira.thede@yfu-deutschland.de)
** Schulvortrag am Johanneum Lüneburg
Wann: 23.04.2026, Vormittags

Wo:
Johanneum Lüneburg
Theodor-Heuss-Str. 1
21337 Lüneburg

Wer: 2-3 erfahrene und unerfahrene Personen 
* Entsendeprogramm
** Teaming-Aufruf Elternarbeit
Liebe Ehrenamtliche, 

für die diesjährigen online Elterntreffen zum Thema Rückkehr suchen wir noch Teamende. Du brauchst keine Vorerfahrung, es geht nur darum mit den Eltern darüber zu sprechen wie sie ihre Kinder bei der Rückkehr und dem Ankommen in Deutschland unterstützen können. 

Die Termine finden alle über Microsoft Teams statt. Die Termine sind:
- am Sonntag den 19.04.2026 um 19:00 Uhr
- am Dienstag den 21.04.2026 um 19:00 Uhr
- am Montag den 27.04.2026 um 19:00 Uhr 
Über Unterstützung würden wir uns sehr freuen.

Meldet euch gerne bei mir.
Paula 0151 724 36 887 / paula.seeburg@yfu-deutschland.de
* Externes und Überregionales
** Mitarbeiter-Gesuche/Stellen
*Teamende für VBT nächste Woche in Mühlhausen gesucht*
Für die MD1 vom 14.04.-19.04. suchen noch Teamende mit Erfahrung!
Es gibt bereits ein Leitungsteam, aber einige Teamende werden noch dringend gebraucht
Bitte melde dich bei Angela unter angela.wagner@yfu-deutschland.de

*Teamende für VBT im April in Lauenburg gesucht*
Für die SHH3 vom 20.-25.04. suchen wir noch Teamende mit Erfahrung!
Es gibt bereits ein Leitungsteam, aber einige Teamende werden noch dringend gebraucht
Bitte melde dich bei Ines unter ines.hintz@yfu-deutschland.de
 
*Teamende für VBT im Mai in Mühlhausen gesucht*
Für die MD2 vom 03.05.-08.05. suchen noch Teamende
Es gibt bereits ein Leitungsteam, aber einige Teamende werden noch gebraucht
Bitte melde dich unter vbt@yfu.de
 
*Teamende für VBT im Mai in Mühlhausen gesucht*
Für die BY2 vom 16.-21.05. suchen wir noch erfahrene und unerfahrene Teamende
Es gibt bereits ein Leitungsteam, aber einige Teamende werden noch gebraucht
Bitte melde dich bei Kati unter katarzyna.krajnik@yfu-deutschland.de
 
*Teamende für VBT im Juni in Mühlhausen gesucht*
Für die BY4 vom 03.-08.05. suchen wir noch erfahrene Teamende
Es gibt bereits ein Leitungsteam, aber einige Teamende werden noch gebraucht
Bitte melde dich bei Kati unter katarzyna.krajnik@yfu-deutschland.de
  
*Leitung eines vierwöchigen Sommerkurses für US-amerikanische Austauschschüler*innen*
Du hast vom 25. Juli-21. August 2026 noch nichts vor, hast Erfahrung in der Leitung von Teams sowie in der Jugendarbeit? Englisch beherrscht du im Schlaf und eine Ersthelfer*innen-Ausbildung bringst du auch mit? Dann suchen wir genau 👉dich für die Leitung des PPP-Sprachcamps in Bonn. Das genaue Anforderungsprofil sowie die Aufgabenbeschreibung findest du [[https://www.yfu.de/ueber-yfu/jobs-praktika][hier]].
📧Fragen und Interessensbekundungen schickst du bitte Sophia (ap-seminare@yfu.de).

*Vierwöchiges interkulturelles Training und Betreuung für US-amerikanische Austauschschüler*innen*
Im Sommer reisen 42 PPP-Stipendiat*innen aus den USA für ihren Austausch nach Deutschland. Du hast Lust, sie bei ihren ersten Wochen in Bonn zu begleiten, interkulturelle Trainings durchzuführen, ihnen bei Rat und Tat zur Seite zu stehen sowie ein buntes Rahmenprogramm zu entwerfen? Für den 25. Juli-21. August 2026 steht noch nichts in deinem Kalender 📅 ? Dann komm ins Team des PPP-Sprachcamps 🚀. Die genauen Bewerbungsvoraussetzungen und Aufgabenbeschreibungen findest du [[https://www.yfu.de/ueber-yfu/jobs-praktika][hier]] 🔎.
📧Fragen und Interessensbekundungen schickst du bitte Sophia (ap-seminare@yfu.de).

*👑 Werde Teil des Trainierenden-Teams beim Training of Trainers (ToT) vom 25.-27.09. in Wiesbaden!*
Du hast Erfahrung als Workshop-Gebende*r, fühlst dich sicher in der Methodenauswahl und hast Strategien parat, mit Herausforderungen in der Workshop-Durchführung umzugehen. Du möchtest dein Expert*innen-Wissen und deine Erfahrung als Trainer*in an YFU-Ehrenamtliche weitergeben? Dann werde Teil des Trainierenden-Teams für das nächste ToT vom 25.-27. September 2026 in Wiesbaden und unterstütze andere dabei, selbst Workshops und Schulungen geben zu können. Lust bekommen oder Fragen? Dann melde dich bei Rahel (perschke@yfu.de, +49 40 22 70 02 44) aus der Geschäftsstelle.

*Gastfamilien finden: Dein Status für YFU!*
Für Geschenke ist es nie zu spät. 😉🐰 Mache YFU ein kleines Oster-Geschenk und unterstütze uns mit wenigen Klicks bei der Gastfamiliensuche! Lade den [[https://yfuit.sharepoint.com/:f:/t/GSexterngeteilteDateien/IgCw9jIbw-vJSYGj1T3Z9alPAVomgsuvBjfL4-eRnOjfpO4?e=tVEtXW][Gastfamilien-Aufruf zum Teilen bei WhatsApp und Co]] herunter und schenke YFU deinen Status, um auf die Anreise von über 200 Austauschschüler*innen diesen Sommer aufmerksam zu machen – und auf die Möglichkeit, als Gastfamilie für eine*n von ihnen zu Hause die Welt zu entdecken. 🏡🌎 Jedes Teilen hilft, damit wir möglichst bald alle Austauschschüler*innen über Ihre Gastfamilie informieren können. Tausend Dank für deine Unterstützung! 💜

*Die OWOs rufen! Bist du dabei?*
Du hast Lust auf Seminare im Aufnahmeprogramm? Du möchtest Austauschschüler*innen bei ihrem Start in ihr Austauschjahr unterstützen und sie für das Zusammenleben mit ihrer Gastfamilie wappnen? Du kennst dich mit Kommunikation und Kultur super aus und hast im August 2026 noch etwas Zeit? Dann brauchen wir genau dich als Leitung oder Teamer*in für die OWOs! Melde dich gerne bei Mareen (📧 ap-seminare@yfu.de) oder fülle diese Umfrage aus. Alle weiteren Infos findest du hier.

*Co-Leitung und Team PPP-Fahrt nach Berlin*
Für die Fahrt der amerikanischen PPP-Stipendiat*innen nach Berlin suchen wir noch eine Co-Leitung sowie Teamende. Die Fahrt findet vom19.-23.5.2026 statt (Anreise des Teams ist am 18.5.). Höhepunkt der Fahrt wird der Berlin-Tag am 21.5. sein, der vom Deutschen Bundestag für die amerikanischen PPPler*innen aller Austauschorganisationen durchgeführt wird.
Bitte melde dich bei Magdalene (lindemann@yfu.de), wenn du Lust hast dabei zu sein. 
** Schulungen / Termine
*Online-KLT-Schulung am 14.04. um 19:30 Uhr – jetzt anmelden!*
Bewerbende für den nächsten YFU-Jahrgang kennenlernen und dabei von euren eigenen Erfahrungen berichten – das könnt ihr bei den digitalen Kennenlerntreffen (KLTs)! Eine etwa anderthalbstündige Online-Schulung dafür wird am Dienstag, den 14.04. um 19:30 Uhr angeboten. Bei Interesse meldet euch unter kennenlernen@yfu.de – wir freuen uns auf euch!
** Sonstiges / Externes
*2 Plätze auf Reise nach Danzig mit YFU Polen*
Wir dürfen zwei Ehrenamtliche auf eine Reise, die von YFU Polen für Austauschschüler*innen und Gastgeschwister organisiert wird, in die wunderschöne Hafenstadt Danzig (Gdańsk) vom 16. – 19. April 2026 mitschicken. Die Reise kostet euch nichts und was genau euch erwartet, könnt ihr in der Trip Offer nachlesen. Einzige Bedingung: Ihr müsst euch nur ganz schnell entscheiden und bis spätestens Freitag (10.04.) bei Rahel (ehrenamt@yfu.de oder +49-40-227002-44) melden. Lust bekommen? First come first served.

*📣 Bewirb dich für einen Ausbildungskurs zur/zum Demokratietrainer*in!*
Interessierst du dich für Themen wie Rassismus-Kritik und Antisemitismus in Vergangenheit und Gegenwart? Möchtest du zukünftig als Trainer*in mit Jugendlichen in Workshops zu diesen Themen arbeiten? Dann bewirb dich als Demokratietrainer*in bei der Bildungsstätte Anne Frank. Bewerben können sich junge Menschen bis 27 Jahren, die in oder kurz vor einer Berufsausbildung oder einem Studium in Hessen stehen. Bewerbungsfrist ist der 31. Mai.2026.
Alle Infos zum Programm und der Bewerbung findest du hier: https://www.bs-anne-frank.de/angebote/demokratietrainer 
* Terminübersicht
** TERMINE 2026
*08.05. - 10.05.2026* &nbsp;&nbsp;&nbsp; Interessenseminar-Lateinamerika (ILSA), *in Rinteln*

*15.05. - 17.05.2026* &nbsp;&nbsp;&nbsp; Colored Glasses Schulung, Jugendherberge Burg Schwaneck (*bei München*)

*29.05 - 31.05.2026* &nbsp;&nbsp;&nbsp; ÖA-Ausschusstreffen, *Hamburg*

*05.06. - 07.06.2026* &nbsp;&nbsp;&nbsp; *(LG)* Nord-LGT

*13.06. - 13.06.2026* &nbsp;&nbsp;&nbsp; Betreuungsschulung, *Berlin*

*20.06. - 21.06.2026* &nbsp;&nbsp;&nbsp; Colored Glasses Schulung, Liebfrauenschule Mühlhausen (*bei Duisburg*)

*18.09. -20.09. 2026* &nbsp;&nbsp;&nbsp; Colored Glasses Schulung, Jugendherberge Horner Rennbahn *Hamburg*

*25.09. - 27.09.2026* &nbsp;&nbsp;&nbsp; *(LG)* Aktivenwochenende

*02.10. - 04.10.2026*  &nbsp;&nbsp;&nbsp; Seminarleitungsschulung (SLS), Jugendherberge *Kassel*

*06.11. – 08.11.2026* &nbsp;&nbsp;&nbsp; Colored Glasses Schulung, Jugendherberge *Kassel*

*20.11. - 22.11.2026* &nbsp;&nbsp;&nbsp; Betreuendenseminar, *Jugendherberge Stuttgart*

*27.11. - 29.11.2026* &nbsp;&nbsp;&nbsp; ÖA-Ausschusstreffen, *Hamburg*
