* Landesgruppe
**  Wichtige Info Aufrufe Newsletter
Diesen Newsletter findet ihr ab jetzt auch auf Whatsapp! Dafür einfach über diesen Link beitreten: https://chat.whatsapp.com/GBCBuLIU2U78zpim5yGxLF
---

Sehr gerne nehmen wir eure Aufrufe oder Danksagungen in den wöchentlichen Newsletter auf.

Schreibt mir ([[mailto://shh-newsletter@yfu-deutschland.de][shh-newsletter@yfu-deutschland.de]]) dafür einfach immer bis *Mittwochs 17:00 Uhr* eure Aufrufe, damit ich sie noch in den Newsletter der aktuellen Woche mit aufnehmen kann. Ansonsten nehme ich die Aufrufe natürlich gerne in den nächsten auf.

Vielen lieben Dank und ich freue mich auf eure Emails.

Liebe Grüße
Aimo
* Öffentlichkeitsarbeit
** Neue Infos
Liebe Landesgruppe,

Die ersten ÖA-Veranstaltungen finden wieder statt. Im März gibt es jeweils abends einen Schulvortrag für die wir eure unterstützung brauchen. Bei beiden habt ihr die Möglichkeit einem begeisterten und interessierten Publikum von euren Erfahrungen im Austausch zu berichten. Fahrtkosten werden von YFU erstattet.

Bei Interesse meldet euch gerne bei sophie.schnippi@posteo.de oder dennisle-duy.nguyen@yfu-deutschland.de
** Schulvortrag am Gymnasium Brunsbüttel
Wann: 12.03.2026 um 18:00 Uhr.

Wo:
Gymnasium Brunsbüttel
Kopernikusstr. 1
25541 Brunsbüttel

Wer: 2-3 erfahrene und unerfahrene Personen
** Schulvortrag mit AFS (gemeinsame Präsi)
Wann: 25.03.2026 ist um 18:00 Uhr Treffen und um 18:30 geht es los.

Wo:
Max-Brauer-Schule
Daimlerstr. 40
22763 Hamburg-Altona

Wer: 2 erfahrene und unerfahrene Personen
* Entsendeprogramm
** ❗️Leitung gesucht für Winter NBT I in Hamburg (also direkt bei dir um die Ecke!)
Für die Winter NBT I in Hamburg sind wir noch dringend auf der Suche nach einer Leitung und Co-Leitung!

🏡12. - 15.03.2026 im Haus Warwisch

Du hast Lust auf eine coole Tagung mit unseren Winter-Return-Schülis? Dann ist das die perfekte Gelegenheit für dich, egal ob du schon erfahrene Leitung bist oder dein neu erworbenes Wissen von der SLS direkt mal anwenden möchtest😊  
Keine Sorge: es gibt bereits einige Teammeldungen, du hast also direkt einen guten Start in die Planung und bekommst aus der LG-SHH und der GS auch weiterhin Unterstützung bei Bedarf! 

😍 Wenn du dir vorstellen könntest, die Leitung oder Co-Leitung zu übernehmen, melde dich bitte ASAP bei kristin.gebhardt@yfu-deutschland.de oder bei daniel.jacobi@yfu-deutschland.de !

Der Termin passt dir nicht? Kein Problem, für die Tagung vom 26-29.03.2026 in Würzburg wird auch noch eine Leitung gesucht 😊
Leitet diese Info auch gerne an alle euch bekannten Leitungen und Teamenden weiter, bei denen ihr euch vorstellen könntet, dass sie bei der NBT dabei sein wollen könnten.

Wir freuen uns, von euch zu hören! 💜💜
* Externes und Überregionales
*USA for you Sachsen-Anhalt: Programmbegleitungen gesucht*

Für die Begleitung der USA for you-Teilnehmenden aus Sachsen-Anhalt nach Michigan vom 16. bis 30.10.2026 suchen wir zwei Ehrenamtliche, die auch die VBT und die NBT gemeinsam leiten. 
Die Ausschreibung findet ihr hier: https://intranet.yfu.de/article_tool/articles/2216
Für Fragen könnt ihr Thekla unter usaforyou@yfu.de, Durchwahl -77, kontaktieren.

*USA for you München 2026: Männliche Programmbegleitung gesucht*

15 Jugendliche von Münchener Mittelschulen starten am 24. Oktober 2026 in ein zweiwöchiges Abenteuer in Michigan mit Community Service, Sightseeing und Leben in Gastfamilien. Für die Vor- und Nachbereitung und die Begleitung der Gruppe in die USA suchen wir noch einen männlichen Ehrenamtlichen. Die Ausschreibung findest du hier: https://intranet.yfu.de/article_tool/articles/2217

Bei Fragen: Kontaktiere Thekla unter usaforyou@yfu.de oder Durchwahl -77

*USA for you München 2026: Auswahl-Leitung und -Team gesucht*

Für die Auswahlgespräche für USA for you in München am 13. und 14. Juni 2026 suchen wir noch eine Leitung und Team-Mitglieder. Mehr Infos zu USA for you findet ihr hier: [[https://eur05.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.yfu.de%2Fkurzprogramme%2Fusa-for-you&data=05%7C02%7Chh-newsletter%40yfu-deutschland.de%7Cfe3f9afa2c384dbe6b8608de6efe83be%7C3496a242cb5040ae9566623507dd3c89%7C0%7C0%7C639070236573044819%7CUnknown%7CTWFpbGZsb3d8eyJFbXB0eU1hcGkiOnRydWUsIlYiOiIwLjAuMDAwMCIsIlAiOiJXaW4zMiIsIkFOIjoiTWFpbCIsIldUIjoyfQ%3D%3D%7C0%7C%7C%7C&sdata=8OkKOn6fMnNmsRrBry7pt%2BZfpI4u6RXBSmVN2KeghD0%3D&reserved=0][USA for you]]

Meldet euch bei Interesse gern bei Thekla: usaforyou@yfu.de, Durchwahl -77

*NBT-Leitungen für März gesucht*
- Für die NBT bei Hamburg suchen wir Leitungen
  - Donnerstag, 12.03.2026, bis Sonntag, 15.03.2026 in Hamburg (Anreise Teilnehmende 13.03.)
- Für die NBT in Würzburg suchen wir eine Co-Leitung und Teamende
  - Donnerstag, 26.03.2025, bis Sonntag, 29.03.2025, in Würzburg (Anreise Teilnehmende 27.03.)
- Wenn du Interesse am Leiten oder Teamen hast, melde dich gern bei uns unter nachbereitung@yfu-deutschland.de
*VBT-Leitungen für März, April oder Mai gesucht*
- Für die Landesgruppen NO, SHH und MD suchen wir dich als VBT-Leitung
- Du hast bereits VBT- oder Seminarerfahrung und eine SLS-Schulung
- 23.03.-28.03. (NO), 04.04.-09.04. (NO) oder 08.04.-13.04. (SHH) in Lauenburg
- 14.04.-19.04. (MD Co-Leitung) oder 03.05.-08.05. (MD) in Mühlhausen
- Melde dich bei Fenja unter vbt@yfu.de
*Wir suchen dich als Expert*in für unsere Länderwebinare*
- Du warst selbst im Ausland und hast Lust, deine Erfahrungen mit zukünftigen Austauschschüler*innen teilen?
- Du kommst aus einem anderen Land und hast Lust, Tipps und Erfahrungen dazu zu teilen – komplett online!
- Dann werde Teamer*in auf einem Länderwebinar für den Jahrgang 26/27
- Trag dich noch bis 28.02. in den Survey [[https://eur05.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.yfu-survey.org%2Fpoll%2Findex.php%2F574632%3Flang%3Dde-informal&data=05%7C02%7Chh-newsletter%40yfu-deutschland.de%7Cfe3f9afa2c384dbe6b8608de6efe83be%7C3496a242cb5040ae9566623507dd3c89%7C0%7C0%7C639070236573062613%7CUnknown%7CTWFpbGZsb3d8eyJFbXB0eU1hcGkiOnRydWUsIlYiOiIwLjAuMDAwMCIsIlAiOiJXaW4zMiIsIkFOIjoiTWFpbCIsIldUIjoyfQ%3D%3D%7C0%7C%7C%7C&sdata=I2C6oEMPDmyYaGh6VfgS9dVMkgzvP39Xz22GeWvOMSk%3D&reserved=0][hier]] ein und wir melden uns bei dir!
* Terminübersicht
** TERMINE 2026
*27.02. - 01.03.2026* &nbsp;&nbsp;&nbsp; Colored Glasses Schulung, Jugendherberge *Leipzig*

*20.03. - 22.03.2026* &nbsp;&nbsp;&nbsp; Gremiensitzung Frühjahr, Jugendherberge Horner Rennbahn *Hamburg*

*27.03. - 29.03.2026* &nbsp;&nbsp;&nbsp; Betreuendenseminar in *Bad Bevensen*

*15.05. - 17.05.2026* &nbsp;&nbsp;&nbsp; Colored Glasses Schulung, Jugendherberge Burg Schwaneck (*bei München*)

*29.05 - 31.05.2026* &nbsp;&nbsp;&nbsp; ÖA-Ausschusstreffen

*05.06. - 07.06.2026* &nbsp;&nbsp;&nbsp; *(LG)* Nord-LGT

*20.06. - 21.06.2026* &nbsp;&nbsp;&nbsp; Colored Glasses Schulung, Liebfrauenschule Mühlhausen (*bei Duisburg*)

*18.09. -20.09. 2026* &nbsp;&nbsp;&nbsp; Colored Glasses Schulung, Jugendherberge Horner Rennbahn *Hamburg*

*25.09. - 27.09.2026* &nbsp;&nbsp;&nbsp; *(LG)* Aktivenwochenende

*02.10. - 04.10.2026*  &nbsp;&nbsp;&nbsp; Seminarleitungsschulung (SLS), Jugendherberge *Kassel*

*06.11. – 08.11.2026* &nbsp;&nbsp;&nbsp; Colored Glasses Schulung, Jugendherberge *Kassel*

*27.11. - 29.11.2026* &nbsp;&nbsp;&nbsp; ÖA-Ausschusstreffen
