* Landesgruppe
**  Wichtige Info Aufrufe Newsletter
Diesen Newsletter findet ihr ab jetzt auch auf Whatsapp! Dafür einfach über diesen Link beitreten: https://chat.whatsapp.com/GBCBuLIU2U78zpim5yGxLF
---

Sehr gerne nehmen wir eure Aufrufe oder Danksagungen in den wöchentlichen Newsletter auf.

Schreibt mir ([[mailto://shh-newsletter@yfu-deutschland.de][shh-newsletter@yfu-deutschland.de]]) dafür einfach immer bis *Mittwochs 17:00 Uhr* eure Aufrufe, damit ich sie noch in den Newsletter der aktuellen Woche mit aufnehmen kann. Ansonsten nehme ich die Aufrufe natürlich gerne in den nächsten auf.

Vielen lieben Dank und ich freue mich auf eure Emails.

Liebe Grüße
Aimo
** Communitea Anmeldung
Liebe Community,

wir haben wieder Neuigkeiten! 🐣
Wir möchten euch herzlich zu einem frühlingshaften Communitea-Treffen einladen. Gemeinsam wollen wir mit den Austauschschüler*innen ein bisschen Ostern feiern und einen entspannten Nachmittag miteinander verbringen.

📅 Wann? 3. April, um 11 Uhr 
📍 Wo? Geschäftsstelle

Wir wollen gemeinsam Ostereier bemalen und die Frühlingszeit einläuten. Wer mag, kann außerdem gerne Snacks oder andere Kleinigkeiten zum Teilen mitbringen. Außerdem wäre es hilfreich, wenn alle bereits ausgepustete Eier mitbringen könnten.

Wenn ihr dabei seid, meldet euch bitte kurz [[https://forms.office.com/?redirecturl=https%3a%2f%2fforms.office.com%2fPages%2fDesignPageV2.aspx%3fsubpage%3ddesign%26FormId%3dQqKWNFDLrkCVZmI1B908iefgPGIVnodAt7lfuSHL-ZJUNjUyWFpBUzhIUVFMOU1YVllNRVZFSFJHWS4u&auth_pvr=OrgId][hier]] an.
Wir freuen uns auf euch und auf ein gemütliches Treffen!

Liebe Grüße 
Leah, Aimo und Ole
* Öffentlichkeitsarbeit
** Neue Infos
Liebe Landesgruppe,

bald sind die Märzferien vorbei und wir suchen wieder eure Unterstützung.
Wenn ihr Zeit und Lust habt meldet euch gerne bei [[mailto:sophie.schnipkoweit@yfu-deitschland.de][sophie.schnipkoweit@yfu-deitschland.de]] oder bei [[mailto:kira.thede@yfu-deutschland.de][kira.thede@yfu-deutschland.de]]
** Schulvortrag am Gymnasium Brunsbüttel
Wann: Flexible Absprache mit Ansprechpartner der Schule

Wo:
Gymnasium Brunsbüttel
Kopernikusstr. 1
25541 Brunsbüttel

Wer: 2-3 erfahrene und unerfahrene Personen
** Schulvortrag am Gymnasium Farmsen
Wann: Am 14.04.2026; Beginn um 18 Uhr

Wo:
Gymnasium Farmsen
Swebenhöhe 50
22159 Hamburg

Wer: 1-2 erfahrene sowie unerfahrene Personen 

Meldet euch hier gerne bei Kira (kira.thede@yfu-deutschland.de)
** Schulvortrag am Johanneum Lüneburg
Wann: 23.04.2026, Vormittags

Wo:
Johanneum Lüneburg
Theodor-Heuss-Str. 1
21337 Lüneburg

Wer: 2-3 erfahrene und unerfahrene Personen 
* Aufnahmeprogramm
** Teamende für die ATS-Spaßveranstalltung
Liebe Ehrenamtliche im Aufnahmeprogramm,

beim letzten Communitea-Treffen waren viele Austauschschülerinnen dabei – was uns natürlich sehr gefreut hat! Gleichzeitig haben wir gemerkt, dass ein paar mehr Ehrenamtliche schön gewesen wären, um sich besser zu mischen, ins Gespräch zu kommen und gemeinsam Aktivitäten zu machen.

Deshalb möchten wir euch herzlich einladen, beim nächsten Communitea-Treffen dabei zu sein und ein bisschen Zeit mit den Austauschschülerinnen zu verbringen.

📅 Wann? 3. April, um 11 Uhr 
📍 Wo? Geschäftsstelle

Wir wollen gemeinsam Ostereier bemalen, uns austauschen und einen gemütlichen Vormittag verbringen. Wer möchte, kann außerdem gerne Snacks oder andere Kleinigkeiten zum Teilen mitbringen. Außerdem wäre es hilfreich, wenn alle bereits ausgepustete Eier mitbringen könnten.

Wenn ihr Zeit und Lust habt, vorbeizukommen, meldet euch bitte kurz [[https://forms.office.com/?redirecturl=https%3a%2f%2fforms.office.com%2fPages%2fDesignPageV2.aspx%3fsubpage%3ddesign%26FormId%3dQqKWNFDLrkCVZmI1B908iefgPGIVnodAt7lfuSHL-ZJUNjUyWFpBUzhIUVFMOU1YVllNRVZFSFJHWS4u&auth_pvr=OrgId][hier]] an. Wir freuen uns sehr über jede*n, der oder die dabei ist!

Liebe Grüße 
Leah, Aimo und Ole
* Externes und Überregionales
** Mitarbeiter-Gesuche/Stellen
*Erfahrene Leitung sucht Teamende für Oster-VBT in Lauenburg*
Für eine VBT der Landesgruppe SHH vom 04.04. bis 09.04. suchen wir noch Teamende. Es gibt schon eine erfahrene Leitung und einige Teamende, wir suchen aber noch weitere Teamende, um das Team zu vervollständigen. Melde dich bitte bei Fenja unter vbt@yfu.de

*VBT-Leitung für Team in der Landesgruppe Nordost gesucht*
Für die VBT vom 08.-13.04. in Lauenburg suchen wir Leitungen für ein bestehendes Team mit Erfahrung. Bitte melde dich bei Fenja unter vbt@yfu.de

*(Co)-Leitungen für VBTs in Mühlhausen gesucht*
Für die VBT der LG MD vom 14.-19.04. in Mühlhausen suchen wir eine Co-Leitung für die bereits feststehende und erfahrene Leitung.
Für die VBT der LG MD vom 03.-08.05. in Mühlhausen suchen wir eine erfahrene Leitung, eine Co-Leitung gibt es schon.
Bitte melde dich bei Fenja unter vbt@yfu.de

*Leitung eines vierwöchigen Sommerkurses für US-amerikanische Austauschschüler*innen*
Du hast vom 25. Juli-21. August 2026 noch nichts vor, hast Erfahrung in der Leitung von Teams sowie in der Jugendarbeit? Englisch beherrscht du im Schlaf und eine Ersthelfer*innen-Ausbildung bringst du auch mit? Dann suchen wir genau 👉dich für die Leitung des PPP-Sprachcamps in Bonn. Das genaue Anforderungsprofil sowie die Aufgabenbeschreibung findest du [[https://www.yfu.de/ueber-yfu/jobs-praktika][hier]].
📧Fragen und Interessensbekundungen schickst du bitte Sophia (ap-seminare@yfu.de).

*Vierwöchiges interkulturelles Training und Betreuung für US-amerikanische Austauschschüler*innen*
Im Sommer reisen 42 PPP-Stipendiat*innen aus den USA für ihren Austausch nach Deutschland. Du hast Lust, sie bei ihren ersten Wochen in Bonn zu begleiten, interkulturelle Trainings durchzuführen, ihnen bei Rat und Tat zur Seite zu stehen sowie ein buntes Rahmenprogramm zu entwerfen? Für den 25. Juli-21. August 2026 steht noch nichts in deinem Kalender 📅 ? Dann komm ins Team des PPP-Sprachcamps 🚀. Die genauen Bewerbungsvoraussetzungen und Aufgabenbeschreibungen findest du [[https://www.yfu.de/ueber-yfu/jobs-praktika][hier]] 🔎.
📧Fragen und Interessensbekundungen schickst du bitte Sophia (ap-seminare@yfu.de).

*USA for you Sachsen-Anhalt: Programmbegleitungen gesucht*
Für die Begleitung der USA for you-Teilnehmenden aus Sachsen-Anhalt nach Michigan vom 16. bis 30.10.2026 suchen wir zwei Ehrenamtliche, die auch die VBT und die NBT gemeinsam leiten. 
Die Ausschreibung findet ihr hier: https://intranet.yfu.de/article_tool/articles/2216
Für Fragen könnt ihr Thekla unter usaforyou@yfu.de, Durchwahl -77, kontaktieren.

*USA for you München 2026: Männliche Programmbegleitung gesucht*
15 Jugendliche von Münchener Mittelschulen starten am 24. Oktober 2026 in ein zweiwöchiges Abenteuer in Michigan mit Community Service, Sightseeing und Leben in Gastfamilien. Für die Vor- und Nachbereitung und die Begleitung der Gruppe in die USA suchen wir noch einen männlichen Ehrenamtlichen. Die Ausschreibung findest du hier: https://intranet.yfu.de/article_tool/articles/2217
Bei Fragen: Kontaktiere Thekla unter usaforyou@yfu.de oder Durchwahl -77

*USA for you München 2026: Auswahl-Leitung und -Team gesucht*
Für die Auswahlgespräche für USA for you in München am 13. und 14. Juni 2026 suchen wir noch eine Leitung und Team-Mitglieder. Mehr Infos zu USA for you findet ihr hier: https://www.yfu.de/kurzprogramme/usa-for-you
Meldet euch bei Interesse gern bei Thekla: usaforyou@yfu.de, Durchwahl -77

*🚀 Powerstart-Verstärkung gesucht – komm ins Powerstart-Team!*
Unser Powerstart-Team möchte wachsen. Ab sofort suchen wir erfahrene Ehrenamtliche, die sich bei YFU gut auskennen und anderen souverän über das Ehrenamt berichten können. Gerne auch Ehrenamtliche, die schon etwas mehr Lebenserfahrung mitbringen und die Elterngeneration ansprechen können.
Was springt für dich dabei raus?  Du kannst dir deinen Einsatz flexibel nach Absprache einteilen, viele neue Leute kennenlernen, deine Moderationskompetenzen erweitern und hast ein starkes Team an deiner Seite. 💪 Klingt nach einer Aufgabe für dich? Melde dich bei Julia aus der Geschäftsstelle (kastner@yfu.de).
** Schulungen / Termine
*🚀 Powerstart ins Ehrenamt am 9. April um 19 Uhr mit Julia und Ines*
Du möchtest aktiv werden oder wieder einsteigen und brauchst für den Start noch ein bisschen Orientierung? Dann haben wir einen Tipp für dich🔥! Starte mit unseren Ehrenamtlichen beim digitalen Powerstart ins Ehrenamt durch. Lerne das YFU 1x1, finde heraus, was es für dich zu tun gibt, wie du dich mit YFUler*innen in deiner Umgebung vernetzen kannst und welche Vorteile du als YFUler*in genießt.
🔥 Anmeldung und weitere Termine hier: https://sway.cloud.microsoft/WKISSAGmmiab4CYG
** Sonstiges / Externes
*Alles rund um die Strukturreform – FAQ*
Dieses Jahr wird entschieden, wie das Vereinsleben von YFU in Zukunft aussehen soll. Viele Fragen werden gestellt: Was bedeuten die Veränderungen für Ehrenamtliche und Mitglieder? Wie sehen die neuen Organe aus? Wer entscheidet in Zukunft über den Verein? Damit ihr gut informiert seid, haben wir ein FAQ zur Strukturreform für euch zusammengestellt, das alle wichtigen Fragen transparent beantwortet: [[https://sway.cloud.microsoft/75ukJpXLBadjHr2v][Zum FAQ-Strukturrefor]]

*Abschlussevent Gastfamilienkampagne am 26. März - jetzt anmelden!*
Euer Engagement, eure Offenheit und eure Erfahrungen haben die Kampagne [[https://austausch-braucht-gastfamilien.de/][„Offene Türen, offene Herzen – Austausch braucht Gastfamilien“]] getragen und lebendig gemacht. Zum Abschluss der Kampagne laden der AJA und seine Mitgliedsorganisationen euch herzlich zu einer Online-Veranstaltung ein, bei der wir gemeinsam Bilanz ziehen, zurückblicken, voneinander lernen und nach vorn schauen.
📅 Donnerstag, 26. März 2026, 🕕 18:00–19:45 Uhr, 💻 via Zoom
Wir freuen uns sehr, wenn Ihr euch die Zeit nehmt und eure Erfahrungen, Gedanken und Ideen einbringt.  Anmeldung unter: https://us06web.zoom.us/meeting/register/mFrPO6xCTgKYGA3jHJi1dQ

*🌍 YFU Global feiert “75 Years of Home”!*
Seit 75 Jahren schaffen YFU-Programme weltweit Begegnungen, in denen aus Fremden enge Vertraute und aus Ländern zweite Heimaten werden.
Gemeinsam mit dem Global Office feiern wir in den kommenden Monaten unser Netzwerk, liefern euch spannende Facts über YFU und zeigen Stories von Austauschschüler*innen, Gastfamilien und Ehrenamtlichen – Menschen, die YFU seit Jahrzehnten prägen.
👉 Begleitet die internationale Kampagne auf Instagram: https://www.instagram.com/yfu_global/?hl=de – folgen, liken & teilen erwünscht!
💜 Und freut euch doppelt: 2027 feiern wir 70 Jahre YFU Deutschland – stay tuned! 

*🤔 Kurz nachgefragt: Warum bist du (kein) YFU-Mitglied?*
Mitglied sein bei YFU bedeutet für viele: verbunden bleiben, Stimme geben, mitgestalten. Aber: Das ist nicht für alle gleich. Damit wir unsere Angebote und Kommunikation rund um unsere Mitgliedschaft verbessern können, fragen wir dich nach deiner Motivation und nach möglichen Stolpersteinen.
👉 Nimm dir 2 Minuten Zeit für unsere anonyme Umfrage: https://forms.cloud.microsoft/e/sDzSVHbNih
* Terminübersicht
** TERMINE 2026
*20.03. - 22.03.2026* &nbsp;&nbsp;&nbsp; Gremiensitzung Frühjahr, Jugendherberge Horner Rennbahn *Hamburg*

*27.03. - 29.03.2026* &nbsp;&nbsp;&nbsp; Betreuendenseminar in *Bad Bevensen*

*15.05. - 17.05.2026* &nbsp;&nbsp;&nbsp; Colored Glasses Schulung, Jugendherberge Burg Schwaneck (*bei München*)

*29.05 - 31.05.2026* &nbsp;&nbsp;&nbsp; ÖA-Ausschusstreffen, *Hamburg*

*05.06. - 07.06.2026* &nbsp;&nbsp;&nbsp; *(LG)* Nord-LGT

*13.06. - 13.06.2026* &nbsp;&nbsp;&nbsp; Betreuungsschulung, *Berlin*

*20.06. - 21.06.2026* &nbsp;&nbsp;&nbsp; Colored Glasses Schulung, Liebfrauenschule Mühlhausen (*bei Duisburg*)

*18.09. -20.09. 2026* &nbsp;&nbsp;&nbsp; Colored Glasses Schulung, Jugendherberge Horner Rennbahn *Hamburg*

*25.09. - 27.09.2026* &nbsp;&nbsp;&nbsp; *(LG)* Aktivenwochenende

*02.10. - 04.10.2026*  &nbsp;&nbsp;&nbsp; Seminarleitungsschulung (SLS), Jugendherberge *Kassel*

*06.11. – 08.11.2026* &nbsp;&nbsp;&nbsp; Colored Glasses Schulung, Jugendherberge *Kassel*

*20.11. - 22.11.2026* &nbsp;&nbsp;&nbsp; Betreuendenseminar, *Jugendherberge Stuttgart*

*27.11. - 29.11.2026* &nbsp;&nbsp;&nbsp; ÖA-Ausschusstreffen, *Hamburg*
