* Landesgruppe
**  Wichtige Info Aufrufe Newsletter
Diesen Newsletter findet ihr ab jetzt auch auf Whatsapp! Dafür einfach über diesen Link beitreten: https://chat.whatsapp.com/GBCBuLIU2U78zpim5yGxLF
---

Sehr gerne nehmen wir eure Aufrufe oder Danksagungen in den wöchentlichen Newsletter auf.

Schreibt mir ([[mailto://shh-newsletter@yfu-deutschland.de][shh-newsletter@yfu-deutschland.de]]) dafür einfach immer bis *Mittwochs 17:00 Uhr* eure Aufrufe, damit ich sie noch in den Newsletter der aktuellen Woche mit aufnehmen kann. Ansonsten nehme ich die Aufrufe natürlich gerne in den nächsten auf.

Vielen lieben Dank und ich freue mich auf eure Emails.

Liebe Grüße
Aimo
* Öffentlichkeitsarbeit
** Schulvortrag am Gymnasium Brunsbüttel
Wann: flexibel möglich!
Meldet euch gerne bei kira.thede@yfu-deutschland.de
Wo: Gamnasium Brunsbüttel
Kopernikusstr. 1
22541 Brunsbüttel
** Schulvortrag in Büsum
Wann: 25.06.2026 19:00
Wo: Schule am Meer Büsum
Bei Interesse: kira.thede@yfu-deutschland.de
* Aufnahmeprogramm
** Gastfamilienbesuche
Liebe Landesgruppe,

Ich suche DRINGEND einen Besucher für eine potentielle Gastfamilie (Gf) im
 - Steinmoor in
 25355 Barmstedt. 
Wer hat Kapazitäten, diesen Besuch zu übernehmen? 
Ein zukünftiger Austauschschüler ist euch mit Sicherheit dankbar…😍
… und ich auch!! 💜
Ines

Die Gesuche für Gastfamilienbesuche poste ich meist als erstes in einer WhatsApp- und Signalgruppe.
Wer Lust hat, dort über Gf-Infos auf dem Laufenden gehalten zu werden und einen Besuch zu übernehmen, hier die Links dazu:

https://chat.whatsapp.com/IekwaHKc6FgBzdp3n17RSV?mode=gi_t
und
https://signal.group/#CjQKID7eirjpYr-BVlu7PkLTR4tJVCiOkxkFkrrQV2nsBk6_EhBjyeu20bhbOLYOJVIBU8dT

Der Vorteil ist, dass ihr euch selbständig auf die offenen Besuche melden könnt, ggf. können die auch zu zweit gemacht werden, wenn man sich Unterstützung dabei wünscht.
Und sollten Fragen aufkommen, meldet euch gerne direkt bei mir ines.hintz@yfu-deutschland.de
** Leitungen und Teamende für Gastfamilienvorbereitung gesucht
Liebe Landesgruppe,
 
die neue AP-Saison steht in den Startlöchern und wir sind auf der Suche nach Leuten, die unsere nächsten Gastfamilien vorbereiten wollen. Wir haben schon einige motivierte Gastfamilien, die auf den Start des Austausches warten und so viele Informationen wie möglich erhalten wollen. Die GF-Vorbereitung soll sie so gut es geht auf den Austausch vorbereiten und ganz viele offene Fragen klären.
Für die Gastfamilien Vorbereitung suchen wir zurzeit Menschen, die Lust hätten, an einem Tag ihrer Wahl (am besten am Wochenende, jedoch eignen sich ggf. auch Wochentage abends) die neuen Gastfamilien auf ihren Austausch vorzubereiten in der Geschäftsstelle.
Zur Vorbereitung unserer Gasteltern soll es im Sommer zwei-drei Termine geben. 
Termine in den Zeiträumen Ende Juli und August würden sich hier gut eignen, damit wir die Sommerferien frei halten können.  

Du würdest die Veranstaltung vor Ort leiten oder teamen, eventuell mit einer Person deiner Wahl zusammen. Eine Präsentation gibt es bereits.
Meldet euch gerne, wenn ihr interessiert seid, eine oder mehrere GF-Vorbereitung(en) zu leiten oder zu teamen. Noch sind die Termine flexibel. Meldet euch sehr gerne mit konkreten Terminvorschlägen. 

Wir freuen uns auf eure Rückmeldungen an Amilou oder mich (theda.schmidtko@yfu-deutschland.de)
 
Liebe Grüße,
Theda
* Entsendeprogramm
** Doch noch eine NBT teamen?
Liebe Landesgruppe,

vielen Dank an alle, die sich bereits über das überregionale Teamgesuch für eine unserer NBTs gemeldet haben! An alle, die die Frist verpasst haben: es ist noch lange nicht zu spät, denn wir freuen uns weiterhin über Meldungen von vielen motivierten Teammitgliedern und Leitungen!

Wir suchen noch:
| NBT   | Zeitraum (mit VNBT) | Ort                          | Gesucht werden ...                                              |
|-------+---------------------+------------------------------+-----------------------------------------------------------------|
| SHH 1 | 13.08. – 16.08.2026 | Spejdergården Tydal, Eggebek | Teamende, gerne auch Justees oder unerfahrenere Personen        |
| SHH 2 | 10.09. – 13.09.2026 | CISV – Haus, Hamburg         | Leitung oder Leitungsteam & Teamende jeglichen Erfahrungsgrades |
| SHH 3 | 01.10. – 04.10.2026 | Spejdergården Tydal, Eggebek | Leitung oder Leitungsteam & Teamende jeglichen Erfahrungsgrades |
Wenn ihr also Lust habt, die Austauschschüler*innen auf ihrem Rückkehrprozess zu begleiten, tolle Menschen zu sehen, YFU-Spirit zu verbreiten oder einfach mal wieder etwa für YFU zu machen oder noch Fragen habt, dann meldet euch gerne bei uns unter antonia.karg@yfu-deutschland.de oder greta.dahmen@yfu-deutschland.de.

Liebe Grüße
Greta & Antonia
* Externes und Überregionales
** Mitmachen / Stellen
*👨‍👩‍👧‍👦 Familienbesucher*innen gesucht*
Wir haben mehrere motivierte Gastfamilien, die noch dringend auf einen YFU-Besuch warten.
Die Familien leben an folgenden Orten:
 - 14947 Nuthe-Urstromtal
 - 57548 Kirchen (Sieg)
 - 57567 Daaden
 - 63225 Langen
 - 65614 Beselich
Wohnst du in der Nähe der Familien oder hast Lust auf einen Ausflug? 😊 Die Reisekosten werden dir von YFU erstattet.
Bei Interesse einen oder mehrere der Besuche zu übernehmen, melde dich bei Magdalene (gastfamilien@yfu.de).
Auch wenn du bisher noch keine Erfahrung mit Familienbesuchen hast, aber grundsätzlich Interesse mitbringst, freuen wir uns sehr über deine Nachricht!

*🔎 Teamende für OWO 5 gesucht*
Für die OWO 5 vom 23. - 27.08 in Bingen am Rhein suchen wir erfahrene Teamer*innen
Wenn du Lust hast dabei zu sein, melde dich gerne bei Mareen (📧ap-seminare@yfu.de). Alle weiteren Infos findest du [[https://intranet.yfu.de/downloads/files/3970][hier]].

*🎓 Qualifiziere Seminarleitungen – Eine weitere Trainer*in für die Seminarleitungsschulung (SLS) gesucht*
Du möchtest andere YFUler*innen mit deiner Erfahrung und Expertise dabei unterstützen, starke Seminarleiter*innen zu werden? Dann brauchen wir dich im Trainierenden-Team der SLS vom 02.-04.10.2026 in Kassel! Du hättest bereits Henrike Krahl, Emma Fössing und Kim Herzog als kompetente Teamkolleg*innen an deiner Seite - Fehlst nur noch du. 🫰🏻 Wenn du dabei bist oder noch Fragen hast, melde dich bei Rahel (perschke@yfu.de) aus der GS.

*🚀 Neue PPP-Auswahlleitungen gesucht*
Für die neue PPP-Saison wollen wir wieder neue Auswahlleitungen schulen. Du hast Lust, in der neuen Saison eine PPP-Auswahl zu leiten, aber dir fehlt noch die nötige Schulung? Dann trage dich gerne in die [[https://forms.cloud.microsoft/Pages/ResponsePage.aspx?id=QqKWNFDLrkCVZmI1B908ibDdxUEoHapOoDj4h619qOdUQUVNSUdCTEwxT1I4WFVDSTEwUEtZTTBLWi4u][Abfrage]] ein.  Voraussetzungen für die Schulung sind Erfahrungen als Teammitglied/ Einzelgesprächsleitung bei PPP-Auswahlen und bestenfalls eine KLT-Schulung. Bei Fragen melde dich gerne bei Picabo (picabo.winands@yfu-deutschland.de).

*🎤 Vierwöchiges interkulturelles Training und Betreuung für US-amerikanische Austauschschüler*innen*
In einem Monat reisen 42 PPP-Stipendiat*innen aus den USA für ihren Austausch nach Deutschland. Du hast Lust, sie bei ihren ersten Wochen in Bonn zu begleiten, interkulturelle Trainings durchzuführen, ihnen bei Rat und Tat zur Seite zu stehen sowie ein buntes Rahmenprogramm zu entwerfen? Für den 25. Juli - 21. August 2026 steht noch nichts in deinem Kalender 📅 ? Dann komm ins Team des PPP-Sprachcamps 🚀. Die genauen Bewerbungsvoraussetzungen und Aufgabenbeschreibungen findest du [[https://www.yfu.de/ueber-yfu/jobs-praktika][hier]] 🔎. 
** Schulungen / Termine
*Lass dich als Seminarleitung schulen – komm zur SLS vom 02.-04.10.2026 in Kassel!*
Du hast Erfahrung als Teamer*in gesammelt, fühlst dich methodisch fit und suchst nach der nächsten Herausforderung? Als bereits erfahrene Seminarleitung wünschst du dir neuen Input und Gelegenheit zur Reflexion deiner Leitungsrolle? Dann komm zur Seminarleitungsschulung (SLS) vom 2.-4. Oktober 2026 in Kassel! 🚀In dieser Schulung werden die Basics vermittelt, die du als Seminarleitung kennen solltest, aber darüber hinaus gibt es auch Angebote für erfahrene Leitungen sich bspw. zum Umgang mit Menschenfeindlichkeit und Extremismus oder dem Thema Coaching weiterzubilden. Hier findest du mehr Infos zu den angebotenen Inhalten: https://intranet.yfu.de/article_tool/articles/2225. Melde dich gleich an!(https://forms.office.com/e/GKHKtJmCfy) Bei Fragen kontaktiere Rahel aus der GS (ehrenamt@yfu.de, Durchwahl -44).

*Online-KLT-Schulung am 02.07. um 19:30 Uhr – jetzt anmelden!*
Bewerbende für den nächsten YFU-Jahrgang kennenlernen und dabei von euren eigenen Erfahrungen berichten – das könnt ihr bei den digitalen Kennenlerntreffen (KLTs)! Eine etwa anderthalbstündige Online-Schulung dafür wird am Donnerstag, den 02.07. um 19:30 Uhr angeboten. Bei Interesse meldet euch unter kennenlernen@yfu.de – wir freuen uns auf euch!
** Sonstiges / Externes
*x⛵Segel-Retreat “Atempause” für Ehrenamtliche vom 13. – 16. August 2026 ab/bis Lübeck*
Zunehmende gesellschaftliche Polarisierung, immer enger werdende Räume für Engagement und begrenzte Ressourcen bei gleichzeitig immer größer werdenden Bedarfen führen oft zu Überlastung oder Erschöpfung bei Engagierten. Atempause bietet Ehrenamtlichen eine Auszeit auf See – um Abstand zu gewinnen, neue Kraft zu schöpfen und inmitten von Wind, Wellen und Gemeinschaft wieder Orientierung zu finden. Begleitet werden die Teilnehmenden von 2 Heldenrat-Coaches und 3 Crewmitgliedern. Die Teilnahmegebühr beträgt 300 Euro, aber bei Flaute in der Kasse werden solidarische Lösungen gefunden. Segel-Kenntnisse brauchst du keine. Mehr Infos auf https://www.heldenrat.org/projekte/atempause

*📝Umfrage zur Wertschätzung im Ehrenamt*
Ehrenamtliches Engagement ist das Herzstück von YFU – ohne euch wäre unsere Arbeit nicht möglich. Umso wichtiger ist es uns, besser zu verstehen, wie ihr eure ehrenamtliche Tätigkeit erlebt und in welchen Bereichen ihr euch mehr Wertschätzung wünscht. 
👉Daher möchten wir euch bitten, an dieser kurzen, anonymen [[https://forms.office.com/e/MLY2yUUbju?origin=lprLink][Umfrage]] teilzunehmen.

*Goodbye Partner? Zur Geschichte und Zukunft der transatlantischen Beziehungen*
[[https://www.law-school.de/termin/goodbye-partner-zur-geschichte-und-zukunft-der-transatlantischen-beziehungen][Hier]] ein Hinweis auf diese spannende und kostenlose Veranstaltung zum Thema transatlantische Beziehungen mit Aydan Özuguz (Mitglied im YFU-Kuratorium)
Zu Gast an der Bucerius Law School sind Dr. Emily Haber, Aydan Özoğuz MdB und Dr. Elisabeth Winter: 01. Juli 2026, 19:00-20:30 Uhr
* Terminübersicht
** TERMINE 2026
*18.09. -20.09. 2026* &nbsp;&nbsp;&nbsp; Colored Glasses Schulung, Jugendherberge Horner Rennbahn *Hamburg*

*02.10. - 04.10.2026*  &nbsp;&nbsp;&nbsp; Seminarleitungsschulung (SLS), Jugendherberge *Kassel*
*02.10. - 04.10.2026*  &nbsp;&nbsp;&nbsp; *(LG)* Aktivenwochenende

*06.11. – 08.11.2026* &nbsp;&nbsp;&nbsp; Colored Glasses Schulung, Jugendherberge *Kassel*

*20.11. - 22.11.2026* &nbsp;&nbsp;&nbsp; Betreuendenseminar, *Jugendherberge Stuttgart*

*27.11. - 29.11.2026* &nbsp;&nbsp;&nbsp; ÖA-Ausschusstreffen, *Hamburg*

*06.05. - 09.05.2027* &nbsp;&nbsp;&nbsp; BUT 2027, *tba*
