* Landesgruppe
**  Wichtige Info Aufrufe Newsletter
Diesen Newsletter findet ihr ab jetzt auch auf Whatsapp! Dafür einfach über diesen Link beitreten: https://chat.whatsapp.com/GBCBuLIU2U78zpim5yGxLF
---

Sehr gerne nehmen wir eure Aufrufe oder Danksagungen in den wöchentlichen Newsletter auf.

Schreibt mir ([[mailto://shh-newsletter@yfu-deutschland.de][shh-newsletter@yfu-deutschland.de]]) dafür einfach immer bis *Mittwochs 17:00 Uhr* eure Aufrufe, damit ich sie noch in den Newsletter der aktuellen Woche mit aufnehmen kann. Ansonsten nehme ich die Aufrufe natürlich gerne in den nächsten auf.

Vielen lieben Dank und ich freue mich auf eure Emails.

Liebe Grüße
Aimo
* Aufnahmeprogramm
** Schulungen für neue Betreuer*innen 2026
Liebe AP-Mitarbeitenden,

ich hoffe, ihr seid gut ins neue Jahr gestartet! Es kommt mir schon viel länger vor als erst ein paar Wochen 😉

Ich möchte euch heute einen Überblick über die geplanten Schulungen/Seminare für neue Betreuer*innen sowie Menschen, die sich für die YFU-Betreuungsarbeit interessieren, geben.

Wir hatten ursprünglich geplant auf unserem Seminar in Bad Bevensen Ende März eine Einheit für neue Betreuer*innen anzubieten, haben unsere Pläne aber noch einmal geändert, da sich so viele erfahrene Betreuer*innen für die internationalen Workshops angemeldet haben, dass wir die Plätze dafür aufgestockt haben. Eine Einheit 1 wird in Bad Bevensen nun nicht stattfinden.

Stattdessen sind für 2026 jedoch folgende Termine für neue Betreuer*innen und Interessent*innen geplant:

Online Co-Betreuungsschulung/Refresh für Betreuenden
📅Dienstag, 3.2. um 19 Uhr für ca. 3 Stunden (weiterer Termin voraussichtlich im September)
📍Online
🦸‍♀️Trainerinnen: Caren Spamer & Ines Hintz
✅ Anmeldung: Anmeldung zur Co-Betreuungsschulung/Refresh für Betreuende

Eintägige Betreuungsschulung in Präsenz
📅Samstag, 13.6.
📍Berlin
🦸‍♀️Trainerinnen: Caren Spamer & N.N.
✅ Vormerkung per E-Mail bei Magdalene (lindemann@yfu.de) möglich

4-Module-Online-Schulung
📅voraussichtlich im September 2026
✅ weitere Infos tba

Wochenendseminar in Präsenz
📅voraussichtlich im November 2026
✅ weitere Infos tba

Leitet diese Infos gerne auch an interessierte Personen weiter.

Wir freuen uns darauf, viele von euch bei den Schulungen und Seminaren in Präsenz oder online kennenzulernen.

Liebe Grüße aus Hamburg
Magdalene
* Entsendeprogramm
** Leitung und Co-Leitung für die VBT SHH1 vom 04.04.26 bis 09.04.26 in Lauenburg gesucht
Du hast Leitungserfahrung und Lust eine VBT zu teamen?
Vom 04. – 09.04.26 findet in Lauenburg die SHH1 VBT statt. Es gibt auch schon viele Teammeldungen, du kannst dich also praktisch ins gemachte Nest setzen.
Für alle anderen Wünsche steht dir die EP-Leitung und die VBT-Referentin zur Seite.

Du hast eine Leitungsschulung hinter dir aber noch keine Erfahrung im Leiten?
Auch kein Problem! Wir suchen für die SHH1 VBT auch noch eine Co-Leitung. Das ist der perfekte Start um etwas Übung zu bekommen!

Bei Interesse meldet euch gerne bei Caren Bremer (caren.bremer@yfu-deutschland.de)
** Teamende für Goee-Treffen im Februar und März gesucht
Hei,

Ich suche aktuell einige Teamende, die Lust haben im Februar und März Treffen für Goees in Hamburg und/oder Schleswig-Holstein zu teamen. Die bisher durchgeführten Spieleabende kamen bei den Teilnehmenden sehr gut an. Terminlich seid ihr relativ flexibel solange die Termine in den Zeitraum von Februar bis Ende März liegen. Falls ihr darauf Lust hättet oder eine andere Idee für eine schöne Spaßveranstaltung für die Goees zum Kennenlernen habt meldet euch sehr gerne bei mir unter caren.bremer@yfu-deutschland.de

Liebe Grüße
Caren
* Externes und Überregionales
** Mitarbeiter-Gesuche/Stellen 
*Leitung eines vierwöchigen Sommerkurses für US-amerikanische Austauschschüler*innen*

Du hast vom 25. Juli-21. August 2026 noch nichts vor, hast Erfahrung in der Leitung von Teams sowie in der Jugendarbeit? Englisch beherrscht du im Schlaf und eine Ersthelfer*innen-Ausbildung bringst du auch mit? Dann suchen wir genau 👉dich für die Leitung des PPP-Sprachcamps in Bonn. Das genaue Anforderungsprofil sowie die Aufgabenbeschreibung findest du [[https://eur05.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.yfu.de%2Fueber-yfu%2Fjobs-praktika&data=05%7C02%7Chh-newsletter%40yfu-deutschland.de%7C5ca997e4205944c5350208de5e754459%7C3496a242cb5040ae9566623507dd3c89%7C0%7C0%7C639052054944754561%7CUnknown%7CTWFpbGZsb3d8eyJFbXB0eU1hcGkiOnRydWUsIlYiOiIwLjAuMDAwMCIsIlAiOiJXaW4zMiIsIkFOIjoiTWFpbCIsIldUIjoyfQ%3D%3D%7C0%7C%7C%7C&sdata=XHXqb%2F1VY2f%2BBVwAGHWm7RDPb%2Fq0XGfQOjiQy1uQg94%3D&reserved=0][hier]].

📧Fragen und Interessensbekundungen schickst du bitte Sophia (ap-seminare@yfu.de).

*Vierwöchiges interkulturelles Training und Betreuung für US-amerikanische Austauschschüler*innen*

Im Sommer reisen 42 PPP-Stipendiat*innen aus den USA für ihren Austausch nach Deutschland. Du hast Lust, sie bei ihren ersten Wochen in Bonn zu begleiten, interkulturelle Trainings durchzuführen, ihnen bei Rat und Tat zur Seite zu stehen sowie ein buntes Rahmenprogramm zu entwerfen? Für den 25. Juli-21. August 2026 steht noch nichts in deinem Kalender 📅 ? Dann komm ins Team des PPP-Sprachcamps 🚀. Die genauen Bewerbungsvoraussetzungen und Aufgabenbeschreibungen findest du [[https://eur05.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.yfu.de%2Fueber-yfu%2Fjobs-praktika&data=05%7C02%7Chh-newsletter%40yfu-deutschland.de%7C5ca997e4205944c5350208de5e754459%7C3496a242cb5040ae9566623507dd3c89%7C0%7C0%7C639052054944785535%7CUnknown%7CTWFpbGZsb3d8eyJFbXB0eU1hcGkiOnRydWUsIlYiOiIwLjAuMDAwMCIsIlAiOiJXaW4zMiIsIkFOIjoiTWFpbCIsIldUIjoyfQ%3D%3D%7C0%7C%7C%7C&sdata=g9ho0KFHbICN174QsU0%2BXpWz%2FQskzdNTrfs2hqRXU1c%3D&reserved=0][hier]] 🔎.

📧Fragen und Interessensbekundungen schickst du bitte Sophia (ap-seminare@yfu.de).

*Familienbesucher*in für einen Besuch in Waren (Müritz) gesucht!*

Wir haben eine engagierte Gastfamilie, die sich schon sehr auf ihr zukünftiges Gastkind freut. Was jetzt noch fehlt? Ein Familienbesuch!

Der Besuch sollte möglichst zeitnah, spätestens jedoch bis Ende Februar stattfinden.
Du wohnst in der Nähe von Waren (Müritz) oder hast Lust auf einen kleinen Ausflug? 😊 Dann melde dich für weitere Informationen bei Sophia unter gastfamilien@yfu.de. 

Auch wenn du bisher noch keine Erfahrung mit Familienbesuchen hast, aber grundsätzlich Interesse mitbringst, freuen wir uns sehr über deine Nachricht!

*9. und 10. Mai 2026: Auswahl-Mitglied für USA FOR YOU in Halle (Saale) gesucht*

15 Jugendliche aus Sachsen-Anhalt werden mit einem Vollstipendium ihre Herbstferien in den USA verbringen. Damit wir aus den vielen Bewerbungen eine Gruppe zusammenstellen können, brauchen wir dich! Du hast KLT-/Auswahl-Erfahrung und Lust, möglichst an beiden Tagen als Team-Mitglied oder beim Meet & Greet bei der Auswahl mitzuwirken? Dann melde dich bei Thekla: usaforyou@yfu.de oder mit der Durchwahl -77. Mehr Infos zu USA for you findest du hier: www.yfu.de/Usa-for-you

*Hilf uns, junge Menschen in Mitteldeutschland für ehrenamtliches Engagement zu begeistern – mach Werbung für die nächste Colored Glasses Schulung 27.02.-01.03. in Leipzig!*

Mit Colored Glasses begeistern wir seit 25 Jahren Kinder und Jugendliche ab der 5. Klasse für Vielfalt und Toleranz. Wir machen uns stark gegen Diskriminierung und Vorurteile im Peer-to-Peer Ansatz, durch erfahrungsbasiertes Lernen, spannende Simulationen und Diskussionen auf Augenhöhe! Als Bildungsprogramm von YFU gelingt es uns regelmäßig, junge Menschen zwischen 16 und 29 Jahren mit und ohne vorherigen YFU-Bezug für des Ehrenamt zu gewinnen. Für die nächste Schulung sind noch einige Plätze frei. Deine Hilfe ist gefragt: Teile die [[https://eur05.safelinks.protection.outlook.com/?url=https%3A%2F%2Fcoloredglasses.de%2Fehrenamtlich-aktiv-werden%2Fengagement-moeglichkeiten%2F&data=05%7C02%7Chh-newsletter%40yfu-deutschland.de%7C5ca997e4205944c5350208de5e754459%7C3496a242cb5040ae9566623507dd3c89%7C0%7C0%7C639052054944821114%7CUnknown%7CTWFpbGZsb3d8eyJFbXB0eU1hcGkiOnRydWUsIlYiOiIwLjAuMDAwMCIsIlAiOiJXaW4zMiIsIkFOIjoiTWFpbCIsIldUIjoyfQ%3D%3D%7C0%7C%7C%7C&sdata=wfQtvJQt%2Bf%2FUzGjOOjH26i08Cg1m%2BVzddT2tpGHdNPc%3D&reserved=0][Infos]] mit deinen Kontakten in der Region. Gib den [[https://eur05.safelinks.protection.outlook.com/?url=https%3A%2F%2Fcoloredglasses.de%2Fwp-content%2Fuploads%2F2025%2F07%2F2026-Flyer-CG-CG-Schulung-Leipzig.pdf&data=05%7C02%7Chh-newsletter%40yfu-deutschland.de%7C5ca997e4205944c5350208de5e754459%7C3496a242cb5040ae9566623507dd3c89%7C0%7C0%7C639052054944841663%7CUnknown%7CTWFpbGZsb3d8eyJFbXB0eU1hcGkiOnRydWUsIlYiOiIwLjAuMDAwMCIsIlAiOiJXaW4zMiIsIkFOIjoiTWFpbCIsIldUIjoyfQ%3D%3D%7C0%7C%7C%7C&sdata=qUxWNBAXHw6pYUlJd1%2F56LmeJgmjoHeOfHoVrUE09Sc%3D&reserved=0][Flyer]] an Schulen, Jugendeinrichtungen und Universitäten/Hochschulen weiter. Sprich YFU-Justees an, um sie zum Engagement zu motivieren. Auch Interessierte aus anderen Regionen sind herzlich eingeladen!  27. Februar bis 01. März | Jugendherberge Leipzig | [Anmeldung]Anmeldung | Fragen an Nina unter roesch@yfu.de

*Der Colored Glasses Vorstand sucht Verstärkung: Organisations- und Kommunikationstalent für die ehrenamtliche Koordi-Koordination gesucht*

Unser langjähriges CG-Vorstandsmitglied Marius übernimmt ab diesem Jahr neue Aufgaben innerhalb des CG-Vorstands, weshalb wir Unterstützung in seinem bisherigen Arbeitsbereich suchen. Du hast Lust, die strategische Entwicklung von Colored Glasses mitzugestalten und Verantwortung für die Koordination des ehrenamtlichen Koordi-Teams und das Koordi-Wissensmanagement zu übernehmen? Du bist kommunikativ, verlässlich und bringst idealerweise Erfahrung als CG-Teamer*in und/oder CG-Koordi mit? Dann schreib uns an vorstand@coloredglasses.de! Alle Details zur Ausschreibung findest du hier: [[https://eur05.safelinks.protection.outlook.com/ap/b-59584e83/?url=https%3A%2F%2Fyfudtl.sharepoint.com%2F%3Ab%3A%2Ft%2Fcg-vorstand%2FIQAK9lLVwmpPQabQV2Nnzi3_AQVszVcWjO_fpJmflOwst9M%3Fe%3Dh0lq8O&data=05%7C02%7Chh-newsletter%40yfu-deutschland.de%7C5ca997e4205944c5350208de5e754459%7C3496a242cb5040ae9566623507dd3c89%7C0%7C0%7C639052054944860209%7CUnknown%7CTWFpbGZsb3d8eyJFbXB0eU1hcGkiOnRydWUsIlYiOiIwLjAuMDAwMCIsIlAiOiJXaW4zMiIsIkFOIjoiTWFpbCIsIldUIjoyfQ%3D%3D%7C0%7C%7C%7C&sdata=BPR7Srlnp%2BQG%2BZQVbilizvwdOJgtStD3SOLi2%2Fw7wSo%3D&reserved=0][2026 CG Stellenausschreibung Vorstand Koordi.pdf]]. Für alle Rückfragen stehen wir dir ebenfalls zur Verfügung.

*Wir suchen dich als Expert*in für unsere Länderwebinare*
- Du warst selbst im Ausland und hast Lust, deine Erfahrungen mit zukünftigen Austauschschüler*innen teilen?
- Du kommst aus einem anderen Land und hast Lust, Tipps und Erfahrungen dazu zu teilen?
- Dann werde Teamer*in auf einem Länderwebinar für den Jahrgang 26/27
- Trag dich gleich in den Survey hier ein und wir melden uns bei dir!
** Schulungen/Termine
*Datenschutz kompakt: Online-Einweisung am Dienstag, 11. Februar um 18.00 Uhr sowie 10. März um 19 Uhr*

Die nächsten digitalen Datenschutzeinweisungen (ungefähr 45 min.) für Referent*innen, Gremienmitglieder und alle Interessierten finden statt am
- Mittwoch, 11. Februar um 18.00 Uhr
- Dienstag , 10. März um 19.00 Uhr
Wir freuen uns über alle, die dabei sind – gerne auch weitersagen!
Meldet euch unter datenschutz@yfu.de an. Weitere Infos folgen dann per mail. Mehr zum Thema Datenschutz bei YFU findet ihr im Intranet. Unsere aktuellen Datenschutzhinweise stehen auf unserer Webseite zur Verfügung.

*🚀 Powerstart ins Ehrenamt am 5.2. um 18.30 Uhr mit Lotta und Taina*

Du möchtest aktiv werden oder wieder einsteigen und brauchst für den Start noch ein bisschen Orientierung? Dann haben wir einen Tipp für dich🔥! Starte mit unseren Ehrenamtlichen beim digitalen Powerstart ins Ehrenamt durch. Lerne das YFU 1x1, finde heraus, was es für dich zu tun gibt, wie du dich mit YFUler*innen in deiner Umgebung vernetzen kannst und welche Vorteile du als YFUler*in genießt.

🔥 Anmeldung und aktuelle Termine: https://sway.cloud.microsoft/WKISSAGmmiab4CYG
** Sonstiges / Externes
*100 Botschafter*innen für "Offene Türen, offene Herzen" - jetzt noch mitmachen!*

Fast 60 Botschafter*innen unterstützen mittlerweile AJA-Gastfamilien-Kampagne „Offene Türen, offene Herzen – Austausch braucht Gastfamilien“ (www.austausch-braucht-gastfamilien.de). Unser Ziel: Bis Ende März 2026 sollen es 100 werden! Da es in den letzten Jahren zunehmend schwieriger geworden ist, neue Gastfamilien zu finden, riefen der AJA und seine Mitgliedsorganisationen - darunter YFU - im Sommer 2025 die Kampagne ins Leben, um das Engagement von Gastfamilien sichtbarer zu machen, mehr Familien zu gewinnen und den internationalen Jugendaustausch zu stärken.

Jetzt kommst du ins Spiel: Sprich deine*n Bürgermeister*in und Landtags- oder Bundestagsabgeordnete aus deinem Wahlkreis persönlich an und lade sie ein, Gastfamilien-Botschafter*in zu werden! Das ist ganz einfach, denn fertige E-Mail-Vorlagen und einen Gesprächsleitfaden dazu gibt es bei Annina (duchardt@yfu.de) - melde dich einfach kurz per Mail. Danke!
* Terminübersicht
** TERMINE 2026
*30.01. - 02.02.2026* &nbsp;&nbsp;&nbsp; Seminarleitungsschulung (SLS) Jugendherberge Horner Rennbahn *Hamburg*

*31.01. - 01.02.2026* &nbsp;&nbsp;&nbsp; *(LG)* Referent*innen/ Landesgruppenwochenende *in Kiel* (Anmeldung für alle offen)

*27.02. - 01.03.2026* &nbsp;&nbsp;&nbsp; Colored Glasses Schulung, Jugendherberge *Leipzig*

*20.03. - 22.03.2026* &nbsp;&nbsp;&nbsp; Gremiensitzung Frühjahr, Jugendherberge Horner Rennbahn *Hamburg*

*27.03. - 29.03.2026* &nbsp;&nbsp;&nbsp; Betreuendenseminar in *Bad Bevensen*

*15.05. - 17.05.2026* &nbsp;&nbsp;&nbsp; Colored Glasses Schulung, Jugendherberge Burg Schwaneck (*bei München*)

*29.05 - 31.05.2026* &nbsp;&nbsp;&nbsp; ÖA-Ausschusstreffen

*05.06. - 07.06.2026* &nbsp;&nbsp;&nbsp; *(LG)* Nord-LGT

*20.06. - 21.06.2026* &nbsp;&nbsp;&nbsp; Colored Glasses Schulung, Liebfrauenschule Mühlhausen (*bei Duisburg*)

*18.09. -20.09. 2026* &nbsp;&nbsp;&nbsp; Colored Glasses Schulung, Jugendherberge Horner Rennbahn *Hamburg*

*25.09. - 27.09.2026* &nbsp;&nbsp;&nbsp; *(LG)* Aktivenwochenende

*02.10. - 04.10.2026*  &nbsp;&nbsp;&nbsp; Seminarleitungsschulung (SLS), Jugendherberge *Kassel*

*06.11. – 08.11.2026* &nbsp;&nbsp;&nbsp; Colored Glasses Schulung, Jugendherberge *Kassel*

*27.11. - 29.11.2026* &nbsp;&nbsp;&nbsp; ÖA-Ausschusstreffen
