* Landesgruppe
**  Wichtige Info Aufrufe Newsletter
Diesen Newsletter findet ihr ab jetzt auch auf Whatsapp! Dafür einfach über diesen Link beitreten: https://chat.whatsapp.com/GBCBuLIU2U78zpim5yGxLF
---

Sehr gerne nehmen wir eure Aufrufe oder Danksagungen in den wöchentlichen Newsletter auf.

Schreibt mir ([[mailto://shh-newsletter@yfu-deutschland.de][shh-newsletter@yfu-deutschland.de]]) dafür einfach immer bis *Mittwochs 17:00 Uhr* eure Aufrufe, damit ich sie noch in den Newsletter der aktuellen Woche mit aufnehmen kann. Ansonsten nehme ich die Aufrufe natürlich gerne in den nächsten auf.

Vielen lieben Dank und ich freue mich auf eure Emails.

Liebe Grüße
Aimo

* Öffentlichkeitsarbeit
** Neue Infos
Liebe Landesgruppe,

bald sind die Märzferien vorbei und wir suchen wieder eure Unterstützung.
Wenn ihr Zeit und Lust habt meldet euch gerne bei [[mailto:sophie.schnipkoweit@yfu-deitschland.de][sophie.schnipkoweit@yfu-deitschland.de]] oder bei [[mailto:kira.thede@yfu-deutschland.de][kira.thede@yfu-deutschland.de]]
** Schulvortrag am Gymnasium Brunsbüttel
Wann: Flexible Absprache mit Ansprechpartner der Schule

Wo:
Gymnasium Brunsbüttel
Kopernikusstr. 1
25541 Brunsbüttel

Wer: 2-3 erfahrene und unerfahrene Personen
** Schulvortrag am Gymnasium Farmsen
Wann: Am 14.04.2026; Beginn um 18 Uhr

Wo:
Gymnasium Farmsen
Swebenhöhe 50
22159 Hamburg

Wer: 1-2 erfahrene sowie unerfahrene Personen 

Meldet euch hier gerne bei Kira (kira.thede@yfu-deutschland.de)
** Schulvortrag am Johanneum Lüneburg
Wann: 23.04.2026, Vormittags

Wo:
Johanneum Lüneburg
Theodor-Heuss-Str. 1
21337 Lüneburg

Wer: 2-3 erfahrene und unerfahrene Personen 
* Entsendeprogramm
** Teamaufruf VBT 3
Wir suchen noch immer Teamer*innen für die VBT vom 20.-25.04. in Lauenburg.
Egal ob ihr schon Erfahrung im Teaming habt oder ganz neu dabei seid, wenn ihr Lust und Zeit habt, meldet euch gerne bei Ines (ines.hintz@yfu-deutschland.de)
** Teaming-Aufruf Elternarbeit
Liebe Ehrenamtliche, 

für die diesjährigen online Elterntreffen zum Thema Rückkehr suchen wir noch Teamende. Du brauchst keine Vorerfahrung, es geht nur darum mit den Eltern darüber zu sprechen wie sie ihre Kinder bei der Rückkehr und dem Ankommen in Deutschland unterstützen können. 

Die Termine finden alle über Microsoft Teams statt. Die Termine sind:
- am Sonntag den 19.04.2026 um 19:00 Uhr
- am Dienstag den 21.04.2026 um 19:00 Uhr
- am Montag den 27.04.2026 um 19:00 Uhr 
Über Unterstützung würden wir uns sehr freuen.

Meldet euch gerne bei mir.
Paula 0151 724 36 887 / paula.seeburg@yfu-deutschland.de
* Externes und Überregionales
** Mitarbeiter-Gesuche/Stellen
*Erfahrene Teamende für VBT nächste Woche in Lauenburg gesucht*
Für die SHH3 vom 20.-25.04. in Lauenburg suchen wir erfahrene Teamende
Leitungsteam und ein Großteil des Teams stehen schon, aber es wird noch dringend Unterstützung gesucht
Gerade Menschen mit Tagungserfahrung werden gebraucht
Bitte meldet euch direkt bei Amelie und Ines unter ines.hintz@yfu-deutschland.de 

*Teamende für VBT Anfang Mai in Mühlhausen gesucht*
Für die MD2 vom 03.05.-08.05. in Mühlhausen suchen wir Teamende
Ein Leitungsteam steht mit Charlie Goetjes und Max Panzner, aber wir suchen noch Teamende
Es werden sowohl Menschen mit viel Erfahrung als auch andere Erfahrungsgrade gesucht
Bitte meldet euch unter vbt@yfu.de
 
*Landesgruppe Bayern sucht Teamende für VBTs im Mai und Juni*
Für die BY1 vom 08.-13.05. in Mühlhausen wird eine vorzugsweise weibliche Teamerin mit Erfahrung gesucht
Für die BY2 vom 16.-21.05. in Mühlhausen werden erfahrene und unerfahrene Teamende gesucht
Für die BY4 vom 03.-08.06. in Mühlhausen werden erfahrene Teamende gesucht
Bitte meldet euch bei Kati unter katarzyna.krajnik@yfu-deutschland.de

*USA for you-NBT in Hamburg, 8.-11. Mai 2026: Teamer*in gesucht*
Für die Nachbereitung der diesjährigen Hamburger USA for you-Gruppe (Kurzprogramm) suchen wir noch eine*n Teamer*in - gerne mit USA-Erfahrung, aber kein Muss. 
Meldet euch bei Interesse bitte bei Thekla: usaforyou@yfu.de, Durchwahl -77

*KLT-Aufruf: Unterstützt motivierte Bewerbende!*
Unsere neue Saison ist erfolgreich gestartet – mit vielen engagierten Bewerbenden!
Möchtet ihr sie bei ihrem ersten Schritt Richtung Austauschjahr begleiten und von euren Erfahrungen berichten?
Wir bieten regelmäßige Schulungen für digitale und Präsenz KLTs an.
Eure Unterstützung macht einen großen Unterschied!
👉 Interesse? kennenlernen@yfu.de

*Co-Leitung und Team PPP-Fahrt nach Berlin*
Für die Fahrt der amerikanischen PPP-Stipendiat*innen nach Berlin suchen wir noch eine Co-Leitung sowie Teamende. Die Fahrt findet vom19.-23.5.2026 statt (Anreise des Teams ist am 18.5.). Höhepunkt der Fahrt wird der Berlin-Tag am 21.5. sein, der vom Deutschen Bundestag für die amerikanischen PPPler*innen aller Austauschorganisationen durchgeführt wird.
Bitte melde dich bei Magdalene (lindemann@yfu.de), wenn du Lust hast dabei zu sein.

*📣Die OWOs rufen! Bist du dabei?*
Du hast Lust auf Seminare im Aufnahmeprogramm? Du möchtest Austauschschüler*innen bei ihrem Start in ihr Austauschjahr unterstützen und sie für das Zusammenleben mit ihrer Gastfamilie wappnen? Du kennst dich mit Kommunikation und Kultur super aus und hast im August 2026 noch etwas Zeit? Dann brauchen wir genau dich als Leitung oder Teamer*in für die OWOs! Melde dich gerne bei Mareen (📧 ap-seminare@yfu.de) oder fülle diese [[https://forms.office.com/e/KYWzZNfDNt?origin=lprLink][Umfrage]] aus. Alle weiteren Infos findest du [[https://intranet.yfu.de/downloads/files/3970][hier]].

*Germany for you: Programmbegleitung vom 13. bis 28. Juni 2026 in Halle (Saale) gesucht (Honorarvertrag)*
Für das Germany for you-Programm suchen wir eine Programmbegleitung (m/w/d), die gemeinsam mit einer amerikanischen Programmbegleitung und weiteren Ehrenamtlichen vor Ort in Halle eine Gruppe von 15 Jugendlichen aus den USA bei einem bunten Programm aus ehrenamtlichem Einsatz, Sightseeing (in Halle und Berlin), Sprachkurs und Sportprogramm begleitet.
Mehr Infos hier: https://intranet.yfu.de/article_tool/articles/2220
Meldet euch bei Interesse gern bei Thekla: germanyforyou@yfu.de, Durchwahl -77

*USA for you-Auswahl in Halle (Saale): Ein Team-Mitglied für den 09. Mai 2026 gesucht*
Um aus den zahlreichen USA for you-Bewerbungen wieder eine tolle Gruppe zusammenzustellen, suchen wir noch eine Person, die das Team bei der Auswahl unterstützt. Gerne mit KLT-/Auswahl-Erfahrung. Reisekosten und ggf. Unterkunft werden übernommen. 
Meldet euch bei Interesse bei Thekla: usaforyou@yfu.de, Durchwahl -77

*USA for you Sachsen-Anhalt: Programmbegleitungen gesucht*
Für die Begleitung der USA for you-Teilnehmenden aus Sachsen-Anhalt nach Michigan vom 16. bis 30.10.2026 suchen wir zwei Ehrenamtliche, die die Gruppe in die USA begleiten und auch die VBT und die NBT gemeinsam leiten. 
Die Ausschreibung findet ihr hier: https://intranet.yfu.de/article_tool/articles/2216
Für Fragen könnt ihr Thekla unter usaforyou@yfu.de, Durchwahl -77, kontaktieren.
** Schulungen / Termine
*Einladung zum EKLT‑Austausch am 29.04. um 19:30 Uhr*
Die Eltern‑Kennenlerntreffen (EKLT) unterstützen Eltern im Bewerbungsprozess und sind Teil unserer Elternarbeit.
Dieser Abend ist offen für alle, die reinschnuppern, Fragen stellen oder sich vernetzen möchten– egal ob mit Erfahrung in der Elternarbeit oder ganz neu..
Gemeinsam schauen wir auf Erfahrungen, aktuelle Entwicklungen und den Austausch miteinander.
Fühlt euch herzlich eingeladen, dabei zu sein! Bei Fragen: kennenlernen@yfu.de.
👉 Anmeldung: [[https://forms.cloud.microsoft/e/EbrLQV5fqu][Anmeldung EKLT Info- und Austauschrunde – Formular ausfüllen]] 

*Betreuungsschulung in Berlin am 13.6.2026*
Du hast Lust, Austauschschüler*innen und Gastfamilien in unserem Aufnahmeprogramm zu betreuen? Am 13.6. (Samstag) findet eine eintägige Betreuungsschulung in Berlin-Kreuzberg statt. Die Schulung richtet sich an alle, die in die Betreuung einsteigen möchten oder bereits eingestiegen sind und noch keine Schulung/kein Seminar besucht haben. Beginn ist am 13.6. um 9:00 Uhr und Ende gegen 18:30 Uhr, für Verpflegung wird gesorgt, und die Fahrt- sowie mögliche Übernachtungskosten (im Hostel) werden von YFU übernommen. Anmelden kannst du dich unter diesem Link: Anmeldung zur Betreuungsschulung - Tagesschulung in Berlin
Falls du Fragen hast, melde dich bei Magdalene (lindemann@yfu.de).

*Schule Global-Online-Infoveranstaltung für Haupt- und Ehrenamtliche*
am Mittwoch, 22. April von 14:00 Uhr bis 14:45 Uhr, online, via Zoom
Du möchtest Schule Global besser kennenlernen - als Schüler*in, engagiertes Elternteil oder Lehrkraft? Super! Wir wollen dir in einem kurzen Online-Meeting die gemeinsame AJA-Initiative zur Förderung von interkultureller Bildung und Internationalisierung an Schulen gern vorstellen und alle deine Fragen beantworten. Zusammen wollen wir überlegen, wie wir die großen Netzwerke von YFU und allen AJA-Mitgliedsorganisationen besser nutzen können, damit noch mehr Schulen von Schule Global erfahren und Teil unseres Schul-Netzwerks werden.
Hier anmelden: https://us06web.zoom.us/meeting/register/tgCzxhPjTmOIutanxNYadg
Übrigens: Auch in diesem Jahr freuen wir uns über eine große Förderung für Schule Global vom BMBSFSJ, von der möglichst viele Schule profitieren sollen. Hilfst du mit? Bei Fragen melde dich gern bei Annina (duchardt@yfu.de) oder Dorothee (nyga@yfu.de).
** Sonstiges / Externes
*2 Plätze auf Reise nach Danzig mit YFU Polen*
Wir dürfen zwei Ehrenamtliche auf eine Reise, die von YFU Polen für Austauschschüler*innen und Gastgeschwister organisiert wird, in die wunderschöne Hafenstadt Danzig (Gdańsk) vom 16. – 19. April 2026 mitschicken. Die Reise kostet euch nichts und was genau euch erwartet, könnt ihr in der Trip Offer nachlesen. Einzige Bedingung: Ihr müsst euch nur ganz schnell entscheiden und bis spätestens Freitag (10.04.) bei Rahel (ehrenamt@yfu.de oder +49-40-227002-44) melden. Lust bekommen? First come first served.

*📣 Bewirb dich für einen Ausbildungskurs zur/zum Demokratietrainer*in!*
Interessierst du dich für Themen wie Rassismus-Kritik und Antisemitismus in Vergangenheit und Gegenwart? Möchtest du zukünftig als Trainer*in mit Jugendlichen in Workshops zu diesen Themen arbeiten? Dann bewirb dich als Demokratietrainer*in bei der Bildungsstätte Anne Frank. Bewerben können sich junge Menschen bis 27 Jahren, die in oder kurz vor einer Berufsausbildung oder einem Studium in Hessen stehen. Bewerbungsfrist ist der 31. Mai.2026.
Alle Infos zum Programm und der Bewerbung findest du hier: https://www.bs-anne-frank.de/angebote/demokratietrainer

*Colored Glasses Schulung am 15.-17. Mai bei München und am 20./21. Juni bei Duisburg – Starte jetzt dein Engagement für eine bunte Gesellschaft!*
Mit Colored Glasses Workshops begeistern wir Kinder und Jugendliche der 5. bis 13. Klasse an Schulen und Jugendeinrichtungen in ganz Deutschland für Vielfalt und Toleranz. Wir machen uns stark gegen Diskriminierung und Vorurteile durch spannende Simulationen und Diskussionen auf Augenhöhe! Die Schulung ist dein Start ins Ehrenamt: Wir zeigen dir, wie du einen Workshop planst und durchführst. Erfahrene Ehrenamtliche geben dir Tipps und Tricks, damit du auch ohne Vorerfahrung einen echten Unterschied machen kannst. Du bist zwischen 16 und 29 Jahre alt und willst aktiv werden? Melde dich zur kostenlosen Schulung an: am 15.-17.05. in der Jugendherberge Burg Schwaneck (bei München) [[https://forms.cloud.microsoft/e/e4gc6GAqC0][hier]] oder am 20./21.06. an der Liebfrauenschule Mühlhausen in Grefrath (bei Duisburg) [[https://forms.cloud.microsoft/e/vB4gw7NGtJ][hier]].  Für beide Termine sind nur noch wenige Plätze frei! Bei Fragen wenden dich gerne an Nina unter roesch@yfu.de.
* Terminübersicht
** TERMINE 2026
*08.05. - 10.05.2026* &nbsp;&nbsp;&nbsp; Interessenseminar-Lateinamerika (ILSA), *in Rinteln*

*15.05. - 17.05.2026* &nbsp;&nbsp;&nbsp; Colored Glasses Schulung, Jugendherberge Burg Schwaneck (*bei München*)

*29.05 - 31.05.2026* &nbsp;&nbsp;&nbsp; ÖA-Ausschusstreffen, *Hamburg*

*05.06. - 07.06.2026* &nbsp;&nbsp;&nbsp; *(LG)* Nord-LGT

*13.06. - 13.06.2026* &nbsp;&nbsp;&nbsp; Betreuungsschulung, *Berlin*

*20.06. - 21.06.2026* &nbsp;&nbsp;&nbsp; Colored Glasses Schulung, Liebfrauenschule Mühlhausen (*bei Duisburg*)

*18.09. -20.09. 2026* &nbsp;&nbsp;&nbsp; Colored Glasses Schulung, Jugendherberge Horner Rennbahn *Hamburg*

*25.09. - 27.09.2026* &nbsp;&nbsp;&nbsp; *(LG)* Aktivenwochenende

*02.10. - 04.10.2026*  &nbsp;&nbsp;&nbsp; Seminarleitungsschulung (SLS), Jugendherberge *Kassel*

*06.11. – 08.11.2026* &nbsp;&nbsp;&nbsp; Colored Glasses Schulung, Jugendherberge *Kassel*

*20.11. - 22.11.2026* &nbsp;&nbsp;&nbsp; Betreuendenseminar, *Jugendherberge Stuttgart*

*27.11. - 29.11.2026* &nbsp;&nbsp;&nbsp; ÖA-Ausschusstreffen, *Hamburg*
