* Landesgruppe
**  Wichtige Info Aufrufe Newsletter
Diesen Newsletter findet ihr ab jetzt auch auf Whatsapp! Dafür einfach über diesen Link beitreten: https://chat.whatsapp.com/GBCBuLIU2U78zpim5yGxLF
---

Sehr gerne nehmen wir eure Aufrufe oder Danksagungen in den wöchentlichen Newsletter auf.

Schreibt mir ([[mailto://shh-newsletter@yfu-deutschland.de][shh-newsletter@yfu-deutschland.de]]) dafür einfach immer bis *Mittwochs 17:00 Uhr* eure Aufrufe, damit ich sie noch in den Newsletter der aktuellen Woche mit aufnehmen kann. Ansonsten nehme ich die Aufrufe natürlich gerne in den nächsten auf.

Vielen lieben Dank und ich freue mich auf eure Emails.

Liebe Grüße
Aimo
** Save the date: gemeinsame Mitgliederversammlung am 22.11.  in der Geschäftsstelle
Liebe Landesgruppe, 

Am 30.6. haben wir uns auf einer Mitgliederversammlung für eine neue Satzung entschieden. Damit steht der neuen Struktur nichts mehr im Wege und es wird schon fleißig daran gearbeitet, um den Übergang möglichst fließend hinzubekommen. 

Am 22.11. findet die online Mitgliederversammlung statt, auf der wir die nächsten Schritte besprechen und alle Verantwortungsträger*innen und Gestalter*innen für die neue Struktur wählen. Die offizielle Einladung wird nach dem Sommer kommen. 

Da die Mitgliederversammlung von 10-18 Uhr angesetzt ist (inkl. einer langen Mittagspause, also keine Angst) haben wir für diesen Tag die Geschäftsstelle reserviert und freuen uns, wenn wir gemeinsam an der Mitgliederversammlung teilnehmen werden. 
Markiert diesen Tag schon einmal im Kalender. Mehr Informationen kommen, sobald der Termin näher rückt.  

Wir freuen uns, wenn viele von euch an dem Tag dabei sind!
** Unterstützung als kleiner Flughafendienst gesucht am Freitag, 28.08.26 ca. 10:30 Uhr
Für eine Abreisegruppe vom Hamburger Flughafen suchen wir noch eine Person, die 
Lust hätte die deutschen Austauschschüler*innen zu unterstützen. Hintergrund 
ist, dass die Reisegruppe bestehend aus 5 Teilnehmer*innen ohne Flugbegleitung 
abfliegen wird. Deine Aufgabe wäre es lediglich vor Ort zu sein/Präsenz zu 
zeigen und den Teilnehmer*innen gegebenfalls beim Check-In am Schalter zu helfen.

Der Flug (nach Dublin) geht am 28.08. um 13:35 Uhr. Treffpunkt und Zeit ist 3 
Stunden vor Abflug (also 10:35 Uhr) beim Check-In Schalter. Sobald alle 
Teilnehmer*innen eingecheckt sind, ihr Gepäck aufgegeben haben und in der 
Sicherheitskontrolle sind ist deine Aufgabe dann auch schon wieder erledigt 😄

Wenn du an dem Freitag Zeit und Lust hast, den Teilnehmer*innen zu helfen, melde 
dich bitte bei Jessi:
E-Mail: jessica.piedziak@yfu.de

Oder allgemein unter:
E-Mail (travel): reise@yfu.de
* Öffentlichkeitsarbeit
** Infoabend im August
Liebe Landesgruppe SHH,
wir haben die erste Veranstalltung im August für euch!

*Infoabend Auslandsaufenthalt*
- beim Lise-Meitner-Gymnasium
- Do, 27.08.2026
- 18-19h
* Entsendeprogramm
** Auswahlleitungen und Einzelgesprächsleitungen für die PPP-Auswahlen gesucht
Die Bewerbungssaison für den PPP-Jahrgang 2027/28 hat begonnen und mit ihr die Suche nach Auswahlleitungen und Einzelgesprächsleitungen. Wenn Du Dir vorstellen kannst, diesen Herbst eine Auswahl zu leiten oder als Einzelgesprächsleitung zu begleiten, fülle bitte diese kurze Umfrage aus: 

[[https://forms.cloud.microsoft/e/9c4d3YZ1t5][PPP-Auswahlleitungen 2026]]

Wenn Du Dir unsicher bist, ob Du die Voraussetzungen erfüllst oder (noch) keine Schulung hast, melde Dich trotzdem gerne, im Herbst werden auch wieder Schulungen stattfinden. Bei Fragen wende Dich gerne an Keira (keira.geiss@yfu.de)
** Es werden immernoch NBT teamende gesucht!
Liebe Landesgruppe,

wir sind nach wie vor auf der Suche nach Personen, die unsere diesjährigen NBTs unterstützen möchten.

*NBT SHH 1: 13.08. – 16.08.2026, Spejdergården Tydal, Eggebek*
- 1-2 Teamende, gerne mit etwas Teamingerfahrung oder eine Person, die sich ausschließlich um die Verpflegung kümmern möchte.
Meldet euch gerne direkt bei Leon (leon.otten@yfu-deutschland.de)
*NBT SHH 2: 10.09. – 13.09.2026, CISV – Haus, Hamburg*
- 1-2 Teamende: Erfahrung egal, mind eine nicht-weibliche Person
*NBT SHH 3: 01.10. – 04.10.2026, Spejdergården Tydal, Eggebek*
- Leitung oder Leitungsteam
-  2- 3 Teamende, mind. eine nicht weibliche Person, gerne auch Personen mit etwas Erfahrung, aber wir freuen uns über alle Meldungen:)
Wenn ihr also Lust habt, die Austauschschüler*innen auf ihrem Rückkehrprozess zu begleiten, tolle Menschen zu sehen, YFU-Spirit zu verbreiten oder einfach mal wieder etwa für YFU zu machen oder noch Fragen habt, dann meldet euch gerne bei uns unter antonia.karg@yfu-deutschland.de oder greta.dahmen@yfu-deutschland.de.

Liebe Grüße
Greta &  Antonia
* Externes und Überregionales
** Mitmachen / Stellen
*Dringend (Co)-Leitung für NBT nächste Woche gesucht*
Die NH-NBT nächste Woche rückt näher und uns fehlt nur noch eine zweite Leitung oder Co-Leitung, dann ist das Team komplett - du hast Lust die frisch zurück gekehrten Schüler*innen willkommen zu heißen und ihnen den Start in den Alltag in Deutschland etwas zu erleichtern? Dann bist du perfekt für unsere NH-NBT! Die NBT findet vom 07-09.08.2026 (Teamanreise 06.08) in Sibbesse statt. Das Team ist super motiviert und bringt selbst einiges an Erfahrung mit.
Melden kannst du dich gerne bei Julia (julia.glatthaar@yfu-deutschland.de) oder Finja (finja.weinert@yfu-deutschland.de). Dankeschön vorab!

*Teamende für NBT Mitte August gesucht*
Für die SHH1-NBT vom 14.-16.08. (Teamanreise 13.08.) in 24825 Eggebek suchen wir noch 2 Teamenden, sowohl erfahren als auch unerfahren, und außerdem eine teamende Person, die Lust hat, sich um Kochen und Verpflegung zu kümmern, und freuen uns, dich im Team zu haben!
Melde dich bei Antonia Karg (antonia.karg@yfu-deutschland.de)

*Leitungsteam für NBT Ende August gesucht*
Für die RHWF-NBT vom 29.-31.08. (Teamanreise 28.08.) in 58091 Hagen suchen wir ein erfahrenes Leitungsteam. Ein vierköpfiges Team steht bereits, ebenso gibt es ein Auto – wir suchen ein Leitungsteam, dass die NBT komplettiert. Bitte melde dich bei Hendrik Röhr unter (hendrik.roehr@yfu-deutschland.de). Achtung: Die NBT geht bis Montag!

*Leitung und 2 Teamende für NBT Anfang September gesucht*
Für die MD-NBT vom 04.09.-06.09. (Teamanreise 03.09.) in 99974 Mühlhausen suchen wir noch eine erfahrene Leitung oder ein Leitungsteam sowie zwei Teamende, insbesondere einen männlichen Teamer. Wenn du Lust hast, die frisch zurückgekehrten Teilnehmenden nachzubereiten und coole neue Leute im Team kennenzulernen, oder alte Bekannte wiederzusehen, dann melde dich bei Anabel Drews (anabel.drews@yfu-deutschland.de)

*Co-Leitung und Teamende für NBT Anfang/Mitte September gesucht*
Bock auf einen All-Inclusive-Kurztrip in den Spreewald? Dann komm ins NBT-Team! Für unsere NO2-NBT vom 10.9. (Teamanreise) bis zum 13.9. in 03096 Burg (Spreewald) suchen wird noch dringend eine Co-Leitung sowie Teamende. Besonders freuen wir uns über Meldungen von Menschen mit etwas Erfahrung, aber melde dich gerne auch, wenn du bisher noch keine Teamingerfahrung gesammelt hast. Überzeugt? Dann melde dich bei Karla unter karla.golze@yfu-deutschland.de

*✨ Hier sehen wir dich: Komm ins Community-Team deiner Region*
Wir suchen Ehrenamtliche, die....neue YFUlis kennenlernen wollen...gerne Social-Media-Content machen 📱...Lust auf Eventplanung haben 🥳...leidenschaftlich Texte für Newsletter usw. schreiben 📝...den Lead übernehmen wollen 🦾
✨ Denn ab 2027 wollen wir richtig durchstarten.*
Unsere Vision: Mehr Begegnungen, mehr Veranstaltungen, mehr Gemeinschaft. Und mehr Menschen, die Lust haben, sich ehrenamtlich bei uns zu engagieren. 🌱
Das Beste daran: ✅ Du hast ein tolles ehrenamtliches Team, lernst Leute aus ganz Deutschland kennen, kannst deine Kompetenzen einbringen und erweitern, bekommst Support, eine Ehrenamtskarte und ein nices Merchandise-Piece on top.
Klingt gut? Klick dich durch die Ausschreibungen und melde dich bei uns unter community@yfu.de
👉 Ausschreibungen: https://padlet.com/yfucommunity/ubersicht-community-teams-eatrra9l4sc3i6nw

*Verstärkung für das Finanzteam in der GS gesucht*
Wir suchen eine*n Referent*in Finanzen & Controlling (m/w/d) für 20 Std./Woche. Vielleicht kennt ihr jemanden mit Freude an Excel, Controlling und Finanzplanung? Die vollständige Ausschreibung findet ihr hier:
[[https://www.yfu.de/ueber-yfu/jobs-praktika][Jobs & Praktika]]

*Lass dich zur PPP-Auswahlleitung schulen*
Für die neue PPP-Saison wollen wir wieder neue Auswahlleitungen schulen. Du hast Lust, in der neuen Saison eine PPP-Auswahl zu leiten, aber dir fehlt noch die nötige Schulung? Dann trage dich gerne in die [[https://forms.cloud.microsoft/Pages/ResponsePage.aspx?id=QqKWNFDLrkCVZmI1B908ibDdxUEoHapOoDj4h619qOdUQUVNSUdCTEwxT1I4WFVDSTEwUEtZTTBLWi4u][Abfrage]] ein. Voraussetzungen für die Schulung sind Erfahrungen als Teammitglied/ Einzelgesprächsleitung bei PPP-Auswahlen und bestenfalls eine KLT-Schulung.
Bei Fragen melde dich gerne bei Picabo (picabo.winands@yfu-deutschland.de).

*Betreuungen gesucht*
Es dauert nicht mehr lange, bis die nächste Generation Austauschschüler*innen anreist und wir sind dabei Betreuungen für alle zu suchen. An einigen Orten gestaltet es sich schwierig, daher schaut doch gerne, ob ihr euch evtl. eine (Co-)Betreuung für folgende Austauschschüler*innen vorstellen könnt:
| 27245 Barenburg          | Zeynep Sahra | w | Türkei   | Betreuung und Co-Betreuung gesucht |
| 57587 Birken-Honigsessen | Akaraphat    |   | Thailand | Betreuung gesucht                  |
| 73469 Riesbürg           | Zhihan       | m | China    | Co-Betreuung gesucht               |
Wenn ihr eine der Betreuungen übernehmen könnt, meldet euch gerne bei Miriam und Lena unter ap-betreuung@yfu.de

*Leitungen für Digitale OWO gesucht 💻*
Da auch dieses Jahr wahrscheinlich nicht alle ATS pünktlich anreisen können, suchen wir zwei Personen, die Lust haben, zusammen die OWO im digitalen Format durchzuführen.
 - Für die digitale OWO gibt es ein eigenes Konzept mit 7 AGs; Zeitumfang: ca. 10 Stunden
 - Zeitraum: September, die konkrete Terminplanung liegt bei euch: Ihr könnt die OWO beispielsweise an einem Wochenende oder verteilt über mehrere Abendtermine anbieten.
 - Die genaue Anzahl der TN sowie deren Ankunftszeiten und Herkunftsländer werden erst Ende August feststehen. Die Organisation erfolgt in enger Abstimmung mit der Geschäftsstelle.
Meldet euch gerne bei Mareen (ap-seminare@yfu.de), wenn ihr euch vorstellen könnt, die digitale OWO durchzuführen.

*Dringend Gastfamilien für Schüler*innen aus der Türkei gesucht!*
Aktuell warten noch 16 Austauschschüler*innen auf den Namen ihrer Gastfamilie in Deutschland – und acht davon stammen aus der Türkei. Wie auch in den Jahren zuvor beobachten wir, dass es besonders herausfordernd ist, vor allem für unsere männlichen Schüler aus der Türkei Gastfamilien zu finden. Wir wünschen uns, dass bei YFU alle Schüler*innen die gleichen Chancen auf ein gewinnbringendes Austauschjahr haben – egal, aus welchem Land sie anreisen. Damit alle türkischen Jugendlichen rechtzeitig anreisen und an ihrer OWO teilnehmen können, brauchen sie dringend den Namen ihrer Gastfamilie in Deutschland – und wir die Unterstützung aus der YFU-Community! Wenn du dir vorstellen kannst, einen Schüler aus der Türkei von Ende August/Anfang September bis Ende November (oder auch länger) bei dir aufzunehmen, melde dich bitte schnellstmöglich bei unserem AP-Team: gastfamilien@yfu.de. Auf der YFU-Website kannst du mehr über die einzelnen Jugendlichen erfahren. Wenn du selbst nicht Gastfamilie werden kannst, freuen wir uns, wenn du innerhalb deines Umfelds auf die Gastfamiliensuche insbesondere für türkische Jugendliche aufmerksam machst. Nutze dafür bei Bedarf unsere Ordner-Symbol Sharepics, Textvorlagen schickt dir gerne Corinna. Danke für deinen Einsatz – auch im Namen von Deniz, Kağan, İnan, Melis, Doruk, Rüzgar, Mete und Aysıla, die es kaum erwarten können, endlich in ihr Austauschjahr zu starten! 💜
** Sonstiges
*Nach dem YES ist vor dem YES – Bewirb dich fürs Core Team 2027*
Vor wenigen Wochen haben noch Hunderte Schüler*innen und Ehrenamtliche aus aller Welt beim Youth Empowerment Seminar (YES) das Ende ihres Austauschjahres gefeiert. Nun suchen wir bereits wieder Ehrenamtliche für das Core Team, das das nächste YES vom 21. bis 25. Juni 2027 am Werbellinsee in Brandenburg organisiert und mit Leben füllt. 
Für diese Rollen kannst du dich bewerben: ✨ Head of Community, 📚Head of Content, 🎬Media Team Coordinator, 🧠Educational Activities Coordinator,🫂IGL Coordinator, 🎤Hosts 🧯Operations Coordinator, 🎓 Head(s) of Track, 🤳 Social Media Manager, ✈️ Travel Coordinators
Deadlines für die Bewerbung:
16. August 2026 – Head of Content, Head of Community, Media Team Coordinator, and Educational Activities Coordinator,
16. September 2026 – Alle anderen Positionen 
👉 Alle Infos zu den Aufgaben und der Bewerbung: https://www.yfu-yes.org/volunteer-2027

*Werde die Stimme von YFU in Europa! 🌍*
Hast du Lust, dich für Jugendaustausch auf politischer Ebene einzusetzen? Das Global Office sucht Ehrenamtliche aus Deutschland für den Pool of Representatives (PoR) für den Zeitraum 2027–2028!
Was machst du im PoR? Du vertrittst YFU bei internationalen Konferenzen, triffst politische Entscheidungsträger*innen und setzt dich dafür ein, dass Schüleraustausch und Ehrenamt in Europa mehr Anerkennung und Förderung erhalten.
Das erwartet dich: ✅ Vertretung von YFU auf europäischer Ebene. ✅ Professionelles Training in der Schweiz (Anfang 2027). ✅ Einzigartiges Netzwerk & wertvolle Skills.
Das bringst du mit: 👉 18+, Commitment für 2 Jahre, politisches Interesse, Wohnsitz in Europa, gutes Englisch & Reisebereitschaft.
⏳ Bewerbung bis 31.08.2026
🔗 Infos & Bewerbung: https://advocacy.yfu.org/call-for-volunteers-pool-of-representatives
* Terminübersicht
** TERMINE 2026
*18.09. -20.09. 2026* &nbsp;&nbsp;&nbsp; Colored Glasses Schulung, Jugendherberge Horner Rennbahn *Hamburg*

*25.09.-27.09.2026* &nbsp;&nbsp;&nbsp; Training of Trainers (ToT), *Wiesbaden*

*02.10. - 04.10.2026*  &nbsp;&nbsp;&nbsp; Seminarleitungsschulung (SLS), Jugendherberge *Kassel*
*02.10. - 04.10.2026*  &nbsp;&nbsp;&nbsp; *(LG)* Aktivenwochenende

*06.11. – 08.11.2026* &nbsp;&nbsp;&nbsp; Colored Glasses Schulung, Jugendherberge *Kassel*

*20.11. - 22.11.2026* &nbsp;&nbsp;&nbsp; Betreuendenseminar, *Jugendherberge Stuttgart*

*22.11.2026* &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; *(LG)* Mitgliederversammlung, *Geschäftsstelle*

*27.11. - 29.11.2026* &nbsp;&nbsp;&nbsp; ÖA-Ausschusstreffen, *Hamburg*

*06.05. - 09.05.2027* &nbsp;&nbsp;&nbsp; BUT 2027, *tba*
