* Landesgruppe
**  Wichtige Info Aufrufe Newsletter
Diesen Newsletter findet ihr ab jetzt auch auf Whatsapp! Dafür einfach über diesen Link beitreten: https://chat.whatsapp.com/GBCBuLIU2U78zpim5yGxLF
---

Sehr gerne nehmen wir eure Aufrufe oder Danksagungen in den wöchentlichen Newsletter auf.

Schreibt mir ([[mailto://shh-newsletter@yfu-deutschland.de][shh-newsletter@yfu-deutschland.de]]) dafür einfach immer bis *Mittwochs 17:00 Uhr* eure Aufrufe, damit ich sie noch in den Newsletter der aktuellen Woche mit aufnehmen kann. Ansonsten nehme ich die Aufrufe natürlich gerne in den nächsten auf.

Vielen lieben Dank und ich freue mich auf eure Emails.

Liebe Grüße
Aimo
** Einladung zum Nord-LGT 2026
Liebe Nord-LGs,
Wir konnten es alle kaum abwarten, aber jetzt ist es endlich so weit: das nächste Nord-LGT steht an! Wir freuen uns auf ein sommerliches Wochenende mit euch in Barmstedt bei Pinneberg (keine Sorge, das ist vom Hamburger Hauptbahnhof gut mit der Bahn erreichbar) mit vielen tollen Workshops, einem unterhaltsamen Programm und Zeit dafür, alte und neue Bekanntschaften wiederzusehen.

Wann? 05.-07..06.2026
Wo? Victor-Andersen-Haus Pinneberg (Düsterlohe 5, 25355 Barmstedt )
 
Meldet euch ab jetzt bis Mitte Mai über diesen Link an: [[https://forms.cloud.microsoft/e/JQQUuacHDj][Nord-LGT 2026 – Formular ausfüllen]]
Die Plätze sind begrenzt, also meldet euch schnell an. Anmeldeschluss ist der 15.05.2026.

Wir haben dieses Jahr eine Teilnahmegebühr von 20€. Solltet ihr Schwierigkeiten haben, diese zu erbringen, meldet euch gerne per Mail bei uns und wir finden eine Lösung dafür. Fahrtkosten erstatten wir für alle, die wollen, bis zu 30€, wenn ihr günstig und früh bucht. Das heißt bis 2 Wochen vor dem 05.06. (also 21.05.) und achtet gerne auf BahnCard und Deutschlandticket.  

Solltet ihr noch irgendwelche Fragen haben, erreicht ihr uns alle unter dieser Mailadresse: nordlgt@lists.yfu-deutschland.de. Wir freuen uns auf eure Anmeldungen!

Euer Nord-LGT Orga Team
* Öffentlichkeitsarbeit
** Neue Infos
Hallo liebe Landesgruppe,

die neue Bewerbungssaison bei YFU für das Programmjahr 2027/28 hat Anfang April gestartet und daher gibt es auch in der ÖA in den nächsten Wochen und Monaten immer wieder was zu tun! Um weiterhin viele Schüler für ein Auslandsjahr zu begeistern, brauchen wir wie immer eure Unterstützung. Wenn ihr also Lust und Zeit habt, meldet euch für die folgenden Termine gerne bei kira.thede@yfu-deutschland.de
** Info-Veranstalltung mit AFS am Goethe-Gymnasium
Wann: 21.05.2026
Wo: Goethe-Gymnasium Hamburg (Altona)
Rispenweg 28, 22547 Hamburg
Wer: 1-2 Teamer jedes Erfahrungsgerades
** Schulvortrag am Gymnasium Brunsbüttel
Wann: flexibel möglich!
Meldet euch gerne bei kira.thede@yfu-deutschland.de
Wo: Gamnasium Brunsbüttel
Kopernikusstr. 1
22541 Brunsbüttel
* Aufnahmeprogramm
** Betreuungsschulung in Berlin am 13. Juni
Liebe AP-Mitarbeitende,

wir möchten euch herzlich einladen zu einer Betreuungsschulung für neue Betreuer*innen und Menschen, die sich für die YFU-Betreuungsarbeit interessieren.

*Die Schulung findet am Samstag, den 13.06.2026 in Berlin statt (in Kreuzberg, Nähe Ostbahnhof).*
In dieser Schulung lernt ihr alles über die Betreuung im YFU-Aufnahmeprogramm lernen, was ihr wissen solltet: Wir beschäftigen uns mit der Rolle und den Erwartungen an Betreuende, wir erarbeiten verschiedene Gesprächstechniken, die für Gespräche hilfreich sind, und wir werfen einen Blick ins Intranet in den Bereich Betreuung und Dokumentation. Und natürlich wird es auch ausreichend Zeit geben, verschiedene Lerninhalte zu üben.

Nach der Schulung könnt ihr (z.B. zum Sommerjahrgang) direkt in die Betreuung einsteigen: als Hauptbetreuung, wenn ihr mindestens 21 Jahre alt seid oder als Co-Betreuung, wenn ihr unter 21 seid.

Hier könnt ihr euch für die Schulung anmelden:
[[https://forms.office.com/Pages/ResponsePage.aspx?id=QqKWNFDLrkCVZmI1B908iS2FBzkZ3HdJtoS0ZOggvE5UNjFPWkVMWjJQT1NYWVFRQlAwMlIyMERVWS4u][Anmeldung zur Betreuungsschulung in Berlin]]

*Die Schulung beginnt um 9:00 Uhr und dauert bis ca. 18:30 Uhr, für Verpflegung wird gesorgt, und die Fahrtkosten (mit der Bahn in der 2. Klasse) werden von YFU übernommen. Auch eine oder zwei Übernachtungen in einem nahegelegenen Hostel können wir für euch buchen.*

Bei Fragen meldet euch gerne bei uns.

Herzliche Grüße aus Hamburg
Magdalene 
* Externes und Überregionales
** Mitarbeiter-Gesuche/Stellen
*OWO-Leitungen gesucht*
- Für die OWO 1 vom 16. - 20.08 in Mainz suchen wir 1 erfahrene Leitung
- Für die OWO 4 vom 23. - 27.08 in Mainz suchen wir 2 Leitungen
- Für die OWO 5 vom 23. - 27.08 in Bingen suchen wir 1 Co-Leitung
Bitte meldet euch bei Mareen (📧 ap-seminare@yfu.de) oder füllt diese [[https://forms.office.com/e/KYWzZNfDNt?origin=lprLink][Umfrage]] aus. Alle weiteren Infos findet ihr [[https://intranet.yfu.de/downloads/files/3970][hier]].

*OWO-Teamende gesucht*
Du hast Lust auf Seminare im Aufnahmeprogramm? Du möchtest Austauschschüler*innen bei ihrem Start in ihr Austauschjahr unterstützen und sie für das Zusammenleben mit ihrer Gastfamilie wappnen? Du möchtest andere YFUler*innen wiedertreffen? Du kennst dich mit Kommunikation und Kultur super aus und hast vom 16. - 20.08 oder 23. - 27.08 Zeit? Dann sind das Top Voraussetzungen, um eine OWO zu teamen! Bitte melde dich bei Mareen (📧 ap-seminare@yfu.de) oder fülle diese [[https://forms.office.com/e/KYWzZNfDNt?origin=lprLink][Umfrage]] aus. Alle weiteren Infos findest du [[https://intranet.yfu.de/downloads/files/3970][hier]].

*USA for you-Auswahl in Halle (Saale): Ein Team-Mitglied für den 09. Mai 2026 gesucht*
Um aus den zahlreichen USA for you-Bewerbungen wieder eine tolle Gruppe zusammenzustellen, suchen wir noch eine Person, die das Team bei der Auswahl unterstützt.  Reisekosten und ggf. Unterkunft werden übernommen. 
Meldet euch bei Interesse bei Thekla: usaforyou@yfu.de, Durchwahl -77

*USA for you Sachsen-Anhalt: Programmbegleitung (m/d) gesucht*
Für die Begleitung der USA for you-Teilnehmenden aus Sachsen-Anhalt nach Michigan vom 16. bis 30.10.2026 suchen noch eine Person (m/d), die die Gruppe in die USA begleitet und auch die VBT und die NBT gemeinsam mit der weiteren Programmbegleitung leitet. 
Die Ausschreibung findet ihr hier: https://intranet.yfu.de/article_tool/articles/2216
Für Fragen könnt ihr Thekla unter usaforyou@yfu.de, Durchwahl -77, kontaktieren.

*Germany for you in Halle (Saale): Teamer*in für zwei Workshops gesucht:*
Die amerikanischen Jugendlichen, die mit Germany for you für zwei Wochen in Halle sind, haben einen Arrival- und einen Pre-Departure Workshop. Dafür suchen wir noch eine Person (m/w/d), die am 15.6. und 16.6. (jeweils 8:30 - 12:00 Uhr) sowie am 26.6. (8:30-12:00 Uhr) unterstützt.
Meldet euch dazu gern bei Thekla: germanyforyou@yfu.de, Durchwahl -77

*Jetzt YFU bei der Gastfamiliensuche unterstützen: Dein Aufruf in der Lokalpresse!*
Mit wenig Aufwand YFU bei der Suche nach Gastfamilien in Deutschland unterstützen – kannst du mit einem Aufruf in der Zeitung bei dir vor Ort! Dafür musst du keinen Artikel schreiben, sondern kannst einfach unsere Vorlagen ([[https://intranet.yfu.de/downloads/files/3643][Downloads im Intranet]]) herunterladen, mit wenigen Klicks anpassen und an die Redaktion der Lokalzeitung oder dem Anzeigenblatt bei dir vor Ort senden. Die freuen sich in der Regel über Beiträge mit regionalem Bezug und werden deinem Vorschlag viel offener gegenüberstehen als jeder Pressemitteilung aus der YFU-Geschäftsstelle. 😊 Deine Hilfe ist also Gold wert – und kann mit wenig Aufwand viele Menschen erreichen. Melde dich immer gern bei Corinna (schmidt@yfu.de) in der GS, wenn du Fragen zu den Vorlagen hast oder Unterstützung bei der Suche nach Kontaktadressen brauchst. Wir freuen uns, von dir zu hören und sagen DANKE für deine Hilfe bei der Gastfamiliensuche!

Teamende für VBT in Mühlhausen nächste Woche gesucht
- Die BY2 vom 16.-21.05. in Mühlhausen sucht noch 4-5 Teamende
- Sowohl erfahrene als auch unerfahrene Teamende werden gesucht
- Das bestehende Leitungsteam freut sich über eure Unterstützung!
- Bitte meldet euch bei Kati unter katarzyna.krajnik@yfu-deutschland.de
** Schulungen / Termine
*Datenschutz kompakt: Online-Einweisungen am Mittwoch, 20.5. um 18.30 Uhr!*
Die nächste digitale Datenschutzeinweisung (ungefähr 45 min.) für Referent*innen, Gremienmitglieder und alle Interessierte finden statt am
- Mittwoch, 20. Mai um 18.30 Uhr
Wir freuen uns über alle, die dabei sind – gerne auch weitersagen!
Meldet euch unter datenschutz@yfu.de an. Weitere Infos folgen dann per mail. Mehr zum Thema Datenschutz bei YFU findet ihr im [[https://intranet.yfu.de/downloads/files?category=41][Intranet]]. Unsere aktuellen [[https://www.yfu.de/datenschutz][Datenschutzhinweise]] stehen auf unserer Webseite zur Verfügung.

*🚀 Powerstart ins Ehrenamt am 21. Mai um 19.30 Uhr*
Du möchtest aktiv werden oder wieder einsteigen und brauchst für den Start noch ein bisschen Orientierung? Dann haben wir einen Tipp für dich🔥! Starte mit unseren Ehrenamtlichen beim digitalen Powerstart ins Ehrenamt durch. Lerne das YFU 1x1, finde heraus, was es für dich zu tun gibt, wie du dich mit YFUler*innen in deiner Umgebung vernetzen kannst und welche Vorteile du als YFUler*in genießt.
🔥 Anmeldung hier: https://sway.cloud.microsoft/WKISSAGmmiab4CYG
** Sonstiges / Externes
*📩 Dein YFU im Wandel – bleib aktuell mit dem Strukturkompass*
Die Strukturreform klingt groß und fühlt sich immer noch ziemlich abstrakt an. 

/Was bedeutet das alles für dein Ehrenamt und deine Mitgliedschaft?/
/Wie verändert sich YFU konkret?/
/Und wo kannst du dich in Zukunft einbringen und mitgestalten?/

Der Strukturkompass gibt dir Orientierung. 
Darin informieren dich Nate aus der AG Strukturreform und Julia aus der Geschäftsstelle regelmäßig über die aktuelle Lage, teilen wichtige Vereinsentscheidungen und Meilensteine, geben Einblicke hinter die Kulissen und zeigen dir, wo und wie du mitwirken kannst. 
Jetzt ein Abo dalassen – denn gemeinsam gestalten wir die Zukunft von YFU. 🫶
📩 Hier kannst du ihn abonnieren: https://mailing.yfu.de/f/333241-426684/

*📝 Mach mit: Umfrage der AG Prävention sexualisierter Gewalt*
Die AG Prävention sexualisierter Gewalt arbeitet derzeit an einem Schutzkonzept, das in Zukunft helfen soll, YFU Deutschland sicherer zu machen. Dazu führen wir eine Umfrage unter allen aktuellen und ehemaligen Mitarbeitenden durch – egal, wie aktiv ihr momentan seid oder welche Erfahrungen ihr gemacht habt. Eure Antworten helfen uns. Die Umfrage läuft bis zum 31.05.26. Vielen Dank für eure Unterstützung! https://www.yfu-survey.org/poll/index.php/314721?lang=de-informal

*Mach`s wie Mia und Nicolai: Mach mit bei "Dein Arbeitgeber für YFU"! (kleiner Aufwand für dich - große Wirkung)*
4 von 5 Unternehmen spenden für gemeinnützige Zwecke. Dein Arbeitgeber auch?  Frag deine Chefin oder deinen Chef nach der gängigen Engagement-Praxis in euren Unternehmen. Erzähle von deiner persönlichen YFU-Erfahrung und bringe YFU als unterstützenswerte Organisation ins Spiel. Biete gern an, dass sich Maren Bruzja aus der YFU-Geschäftsstelle direkt mit den Verantwortlichen aus deinem Unternehmen in Verbindung setzt, um YFU und konkrete Unterstützungsmöglichkeiten vorzustellen.
👉 Wie andere YFUler*innen ihr Unternehmen für uns gewinnen konnten und wie du konkret vorgehen kannst, erfährst du hier.
Du kannst dich auch bei Maren aus der YFU-Fundraising-Abteilung melden, um mit ihr über deine möglichen nächsten Schritte zu sprechen: bruzja@yfu.de
* Terminübersicht
** TERMINE 2026
*08.05. - 10.05.2026* &nbsp;&nbsp;&nbsp; Interessenseminar-Lateinamerika (ILSA), *in Rinteln*

*15.05. - 17.05.2026* &nbsp;&nbsp;&nbsp; Colored Glasses Schulung, Jugendherberge Burg Schwaneck (*bei München*)

*29.05 - 31.05.2026* &nbsp;&nbsp;&nbsp; ÖA-Ausschusstreffen, *Hamburg*

*05.06. - 07.06.2026* &nbsp;&nbsp;&nbsp; *(LG)* Nord-LGT

*13.06. - 13.06.2026* &nbsp;&nbsp;&nbsp; Betreuungsschulung, *Berlin*

*20.06. - 21.06.2026* &nbsp;&nbsp;&nbsp; Colored Glasses Schulung, Liebfrauenschule Mühlhausen (*bei Duisburg*)

*18.09. -20.09. 2026* &nbsp;&nbsp;&nbsp; Colored Glasses Schulung, Jugendherberge Horner Rennbahn *Hamburg*

*25.09. - 27.09.2026* &nbsp;&nbsp;&nbsp; *(LG)* Aktivenwochenende

*02.10. - 04.10.2026*  &nbsp;&nbsp;&nbsp; Seminarleitungsschulung (SLS), Jugendherberge *Kassel*

*06.11. – 08.11.2026* &nbsp;&nbsp;&nbsp; Colored Glasses Schulung, Jugendherberge *Kassel*

*20.11. - 22.11.2026* &nbsp;&nbsp;&nbsp; Betreuendenseminar, *Jugendherberge Stuttgart*

*27.11. - 29.11.2026* &nbsp;&nbsp;&nbsp; ÖA-Ausschusstreffen, *Hamburg*
