* Landesgruppe
**  Wichtige Info Aufrufe Newsletter
Diesen Newsletter findet ihr ab jetzt auch auf Whatsapp! Dafür einfach über diesen Link beitreten: https://chat.whatsapp.com/GBCBuLIU2U78zpim5yGxLF
---

Sehr gerne nehmen wir eure Aufrufe oder Danksagungen in den wöchentlichen Newsletter auf.

Schreibt mir ([[mailto://shh-newsletter@yfu-deutschland.de][shh-newsletter@yfu-deutschland.de]]) dafür einfach immer bis *Mittwochs 17:00 Uhr* eure Aufrufe, damit ich sie noch in den Newsletter der aktuellen Woche mit aufnehmen kann. Ansonsten nehme ich die Aufrufe natürlich gerne in den nächsten auf.

Vielen lieben Dank und ich freue mich auf eure Emails.

Liebe Grüße
Aimo
** Einladung Landesgruppen-Wochenende SHH vom 02.10. bis 04.10.26 Villa Falkenstein (Kiel)
Liebe Landesgruppe,

hiermit übersende ich euch die Einladung zum Landesgruppenwochenende vom 02.10 bis 04.10.26 in der Villa Falkenhorst! Die Adresse lautet Villa Falkenhorst, Falkensteiner Strand 35, 24159 Kiel.

Wir starten am Freitag (02.10.) um 18 Uhr mit einem gemeinsamen Abendessen und am Sonntag (04.10.) geht es dann gegen 14 Uhr wieder nach Hause. Grundsätzlich könnt ihr euch aber auch für nur einzelne Tage (z.B. nur den Samstag) anmelden, falls ihr nicht alle drei Tage Zeit habt.

Bisher ist unser Aktivitätenplan noch nicht sehr gefüllt, weshalb wir uns über eure Rückmeldung/Angebote z.B. für Workshops mit YFU-Bezug, aber auch gerne Kreatives oder Sport freuen würden. Außerdem benötigen wir eure Unterstützung beim Einkaufen/Kochen für das Wochenende, sofern ihr dort unterstützen könnt, gebt bitte auch eine Rückmeldung.

Hier der Link für die Anmeldung:
[[https://forms.cloud.microsoft/e/jUMPju7Lgg][Anmeldung Landesgruppenwochenende 02.10.-04.10.2026]]

Mit Blick auf die Villa als Ort, bedenkt bitte:
Zum Übernachten braucht ihr zwingend einen Schlafsack/eine Decke (Bezug und Innenleben), sowie ein Kopfkissen samt Bezug und ein Bettlaken. Vor Ort gibt es nur Matratzen.
Weiterhin sind Hausschuhe und ein Handtuch von Vorteil.
Gerne könnt ihr auch Gesellschaftsspiele oder ähnliches mitbringen.

Wir freuen uns, euch vor Ort zu sehen!
Lena für den eLGV
** Jetzt anmelden: Public Viewing für die Mitgliederversammlung am 22.11. in der Geschäftsstelle
Liebe Landesgruppe,

Am 30.6. haben wir uns auf einer Mitgliederversammlung für eine neue Satzung entschieden. Damit steht der neuen Struktur nichts mehr im Wege und es wird schon fleißig daran gearbeitet, um den Übergang möglichst fließend hinzubekommen.

Am 22.11. findet die online Mitgliederversammlung statt, auf der wir die nächsten Schritte besprechen und alle Verantwortungsträger*innen und Gestalter*innen für die neue Struktur wählen. Die offizielle Einladung wird nach dem Sommer kommen.

Da die Mitgliederversammlung von 10-18 Uhr angesetzt ist (inkl. einer langen Mittagspause, also keine Angst) haben wir für diesen Tag die Geschäftsstelle reserviert und freuen uns, wenn wir gemeinsam an der Mitgliederversammlung teilnehmen werden. Anmelden könnt ihr euch hier: [[https://forms.cloud.microsoft/e/nDC41S1w9m][Anmeldung zum Public Viewing für die Mitgliederversammlung am 22.11.2026 – Formular ausfüllen]]

Wir freuen uns, wenn viele von euch an dem Tag dabei sind!
* Öffentlichkeitsarbeit
** Neue Schulvorträge und Messen
Hi liebe ÖA-Begeisterte und alle die es werden wollen,

in einigen Wochen fängt die Schule wieder an und dann starten wir wie jedes Jahr nochmal richtig durch mit unseren Schulvorträgen! Außerdem kommen noch einige Messen auf uns zu, für die wir wieder mehrere Teamende suchen. Also: eure Chance (wieder) aktiv zu werden! Ganz egal ob und wie viel ÖA-Erfahrung ihr habt, wir freuen uns über alle Meldungen! 
Die genauen Termine findet ihr unten. 
Bei Interesse meldet euch bei kira.thede@yfu-deutschland.de für die Schulvorträge und bei dennisle-duy.nguyen@yfu-deutschland.de für die Messen.

Danke für euren Einsatz! 
Euer ÖA-Team SHH

| Veranstaltung                                              | Wo                                                          | Wann                                            |
|------------------------------------------------------------+-------------------------------------------------------------+-------------------------------------------------|
| Infoveranstaltung mit den Austauschexperten                | Gymnasium Norderstedt, Coppernicusstr. 1, 22850 Norderstedt | Do, 10.09.2026; ab 18:30 Uhr                    |
| Infoabend am Gymnasium Walddörfer                          | Im Allhorn 45, 22359 Hamburg                                | Di, 15.09.2026; 19–21 Uhr, Aufbau ab 18:30 Uhr  |
| Minimesse am Gymnasium Bondenwald                          | Bondenwald 14b, 22453 Hamburg                               | Mi, 16.09.2026; 19–21 Uhr, Aufbau ab 18:30 Uhr  |
| AJA-Messe in der Zinnschmelze Barmbek                      | Maurienstraße 19, 22305 Hamburg                             | Do, 17.09.2026; 17–19:30 Uhr, Aufbau ab 16 Uhr  |
| Infoabend an der Geschwister-Scholl-STS für die 10. Klasse | Glückstädter Weg 70, 22549 Hamburg                          | Do, 17.09.2026; abends                          |
| Infoveranstaltung an der Grundschule Krempe                | Am Burggraben 10, 25361 Krempe                              | Sa, 19.09.2026; 10–13 Uhr                       |
| Infoabend am Gymnasium Othmarschen                         | Walderseestraße 99, 22605 Hamburg                           | Di, 22.09.2026; ab 19 Uhr                       |
| Infoabend am Gymnasium Hochrad                             | Hochrad 2, 22605 Hamburg                                    | Di, 22.09.2026; 18-19:30 Uhr                    |
| Infoabend an der Julius-Leber-Schule                       | Halstenbeker Str. 41, 22457 Hamburg                         | Di, 29.09.2026; ca. 19 Uhr                      |
| Infoveranstaltung mit AFS & YFU                            | Gymnasium Hummelsbüttel                                     | Mi, 30.09.2026; Beginn 19 Uhr, Aufbau 18:30 Uhr |
| Schulvortrag an der ahfs Uhlenhorst                        | Bostelreihe 5, 22083 Hamburg                                | Fr, 09.10.2026; 10:45–11:45 Uhr                 |
| JuBi an der Stadtteilschule Bergedorf                      | Ladenbeker Weg 13, 21033 Hamburg                            | Sa, 14.11.2026; Zeit tba                        |
* Aufnahmeprogramm
** Teamer*innen gesucht für den Willkomemnsspaziergang (26.09)
Für den Willkommensspaziergang unserer diesjährigen Gastfamilien und den neuen Austauschschüler*innen am 26.09. suchen wir motivierte Menschen aller Erfahrungsgrade. Geplant ist ein bunter Austausch im lockeren Rahmen mit Buffet im Hamburger Stadtpark. Treffen ist fürs Team ab 13:30, das Treffen ist bis ca. 17 Uhr angesetzt. 

Melde dich gerne bei Amilou (amilou.fehr@yfu-deutschland.de), wenn du Lust hast, dabei zu sein oder irgendwelche Fragen hast. 🙂 

Wir freuen uns! 
* Entsendeprogramm
** Es werden immernoch NBT teamende gesucht!
Liebe Landesgruppe,

wir sind nach wie vor auf der Suche nach Personen, die unsere diesjährigen NBTs unterstützen möchten.
- NBT SHH 2: 10.09. – 13.09.2026, CISV – Haus, Hamburg
  männliches Teammitglied, Erfahrung egal
- NBT SHH 3: 01.10. – 04.10.2026, Spejdergården Tydal, Eggebek
  Leitung/Co-Leitung oder Leitungsteam, sowie weitere Teammitglieder
Wenn ihr also Lust habt, die Austauschschüler*innen auf ihrem Rückkehrprozess zu begleiten, tolle Menschen zu sehen, YFU-Spirit zu verbreiten oder einfach mal wieder etwa für YFU zu machen oder noch Fragen habt, dann meldet euch gerne bei uns unter antonia.karg@yfu-deutschland.de oder greta.dahmen@yfu-deutschland.de.

Liebe Grüße
Greta & Antonia
* Externes und Überregionales
** Mitmachen / Stellen
*Teams und Schlafplätze für PPP-Auswahlen gesucht*
Für die PPP-Auswahlen suchen wir Teamende mit und ohne Erfahrung in ganz Deutschland! Die Auswahlen für das PPP (ein Austauschstipendium) sind ähnlich wie Kennenlerntreffen, aber in Präsenz und intensiver. Die Termine findest Du in der Umfrage:  [[https://forms.cloud.microsoft/e/LvVh7r3F3E][Termine PPP-Auswahl 2026]] In der Umfrage kannst Du außerdem angeben, ob Du ggf. einen Schlafplatz für Teamende anbieten kannst.
👉 Bei Interesse oder Fragen melde Dich bitte bei Keira (keira.geiss@yfu.de).Danke!

*AP-Finale 2026/27: Gastfamilie für den letzten Austauschschüler gesucht!*
Erst einmal ein großes Dankeschön in die YFU-Community: Auch dank eurer Hilfe konnten wir am 31. August den letzten der in diesem Sommer anreisenden Austauschschüler platzieren! 🥳💜 Eigentlich wäre die Saison also beendet, aber auch nur eigentlich…: Denn mit Gabriele aus Italien ist ein Austauschschüler hinzugekommen, für den wir nun auch noch eine Gastfamilie von Mitte September 2026 bis Mitte Januar 2027 suchen. Gabriele ist 16 Jahre alt und hat sich kurzfristig für ein Austauschjahr in Deutschland entschieden, weil in seinem ursprünglichen Gastland nicht rechtzeitig eine Gastfamilie gefunden werden konnte. Nun freut er sich sehr auf Deutschland und wartet schon gespannt auf die Info, wo es genau hingehen wird! In seinem Kurzprofil und Vorstellungsvideo könnt ihr mehr über Gabriele erfahren: Gabriele (16 Jahre) aus Italien. Ihr könnt euch vorstellen, Gabriele ab Mitte September für fünf oder drei Monate bei euch aufzunehmen und damit auch dem letzten AP-Schüler der Saison 2026/27 seinen Traum vom Austausch zu erfüllen?
👉 Dann meldet euch schnell im AP-Team der Geschäftsstelle: gastfamilien@yfu.de, 040 227002-778. Wir freuen uns, von euch zu hören!

*Leitungsteam für NBT im Oktober gesucht*
Für die SHH3-NBT vom 02.-04.10. (Teamanreise: 03.10.) suchen wir ein Leitungsteam. Die NBT findet in 24825 Eggebek statt.
👉 Melde dich bei Antonia unter antonia.karg@yfu-deutschland.de
** Termine/Schulungen
*Betreuungsluft schnuppern? Jetzt zum Betreuendenseminar anmelden!*
Auf unserem Betreuendenseminar erfahrt ihr mehr über die Betreuungsarbeit allgemein und grundlegende Gesprächstechniken, die Betreuende benutzen, um Austauschschüler*innen und Gasteltern bei der Lösung von Problemen zu helfen. Es gibt Input und Übungen zu Aktivem Zuhören, Gezieltem Fragen, dem Herausarbeiten konstruktiver Ansätze, der Beobachtung und Interpretation von Kommunikationsverhalten sowie der Strukturierung eines Gespräches. Auch Besuche und Berichte werden Thema sein. Wir freuen uns auf euch! 
📅        6.-8.11.2026
📍        Präsenz in Stuttgart
🦸‍♀️🦸‍♂️ Trainer*innen: Julianna Bisang & N.N.
✅         Anmeldung bis 5.10.: [[https://forms.cloud.microsoft/e/29UtCYzDVd][Anmeldung zum Betreuendenseminar in Stuttgart (6.-8.11.2026)]]

*Online-KLT-Schulung am 24.09. um 19:30 Uhr – jetzt anmelden!*
Bewerbende für den nächsten YFU-Jahrgang kennenlernen und dabei von euren eigenen Erfahrungen berichten – das könnt ihr bei den digitalen Kennenlerntreffen (KLTs)! Eine etwa anderthalbstündige Online-Schulung dafür wird am Donnerstag, den 24.09. um 19:30 Uhr angeboten.
👉 Bei Interesse meldet euch unter kennenlernen@yfu.de – wir freuen uns auf euch!
** Sonstiges
*KI im Ehrenamt – kostenloses Webinar zur Veranstaltungs-Planung mit KI*
Im Rahmen der [[https://www.berlin-social-academy.de/][14. Berlin Social Academy]] von 12.-16.10.2026 werden wieder eine Reihe Pro Bono Workshops und Webinare für Non Profit Organisationen angeboten – u.a. zur Verwendung von künstlicher Intelligenz. Im Webinar „KI im Ehrenamt: Wer macht was bis wann? Mit KI zum vollständigen Veranstaltungsplan“ ([[https://programm.berlin-social-academy.de/b?p=5mjbqj][link]]) planen die Teilnehmenden in Gruppen eine eigene Veranstaltung und gehen mit einem vollständigen Veranstaltungsplan inklusive Ablauf, Aufgabenverteilung, Einladung, Checkliste sowie wiederverwendbaren Prompts aus dem Kurs. Das klingt doch vielversprechend, oder?! Das Webinar findet statt am 14. Oktober von 12-14 Uhr. Anmelden könnt ihr euch über den Link zur Veranstaltung. 
* Terminübersicht
** TERMINE 2026
*18.09. -20.09. 2026* &nbsp;&nbsp;&nbsp; Colored Glasses Schulung, Jugendherberge Horner Rennbahn *Hamburg*

*02.10. - 04.10.2026* &nbsp;&nbsp;&nbsp; Seminarleitungsschulung (SLS), Jugendherberge *Kassel*
*02.10. - 04.10.2026* &nbsp;&nbsp;&nbsp; *(LG)* Aktivenwochenende
*02.10. - 04.10.2026*  &nbsp;&nbsp;&nbsp; Überregionale Teamingeinweisung, Jugendherberge *Kassel*

*06.11. - 08.11.2026* &nbsp;&nbsp;&nbsp; Colored Glasses Schulung, Jugendherberge *Kassel*
*06.11. - 08.11.2026* &nbsp;&nbsp;&nbsp; Betreuendenseminar, *Jugendherberge Stuttgart*

*22.11.2026* &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; *(LG)* Mitgliederversammlung, *Geschäftsstelle*

*27.11. - 29.11.2026* &nbsp;&nbsp;&nbsp; Großes ÖA-Mäuse-Treffen, *Hamburg*

*06.05. - 09.05.2027* &nbsp;&nbsp;&nbsp; BUT 2027, *tba*
