* Landesgruppe
**  Wichtige Info Aufrufe Newsletter
Diesen Newsletter findet ihr ab jetzt auch auf Whatsapp! Dafür einfach über diesen Link beitreten: https://chat.whatsapp.com/GBCBuLIU2U78zpim5yGxLF
---

Sehr gerne nehmen wir eure Aufrufe oder Danksagungen in den wöchentlichen Newsletter auf.

Schreibt mir ([[mailto://shh-newsletter@yfu-deutschland.de][shh-newsletter@yfu-deutschland.de]]) dafür einfach immer bis *Mittwochs 17:00 Uhr* eure Aufrufe, damit ich sie noch in den Newsletter der aktuellen Woche mit aufnehmen kann. Ansonsten nehme ich die Aufrufe natürlich gerne in den nächsten auf.

Vielen lieben Dank und ich freue mich auf eure Emails.

Liebe Grüße
Aimo
** Einladung Landesgruppen-Wochenende SHH vom 02.10. bis 04.10.26 Villa Falkenstein (Kiel)
Liebe Landesgruppe,

hiermit übersende ich euch die Einladung zum Landesgruppenwochenende vom 02.10 bis 04.10.26 in der Villa Falkenhorst! Die Adresse lautet Villa Falkenhorst, Falkensteiner Strand 35, 24159 Kiel.

Wir starten am Freitag (02.10.) um 18 Uhr mit einem gemeinsamen Abendessen und am Sonntag (04.10.) geht es dann gegen 14 Uhr wieder nach Hause. Grundsätzlich könnt ihr euch aber auch für nur einzelne Tage (z.B. nur den Samstag) anmelden, falls ihr nicht alle drei Tage Zeit habt.

Bisher ist unser Aktivitätenplan noch nicht sehr gefüllt, weshalb wir uns über eure Rückmeldung/Angebote z.B. für Workshops mit YFU-Bezug, aber auch gerne Kreatives oder Sport freuen würden. Außerdem benötigen wir eure Unterstützung beim Einkaufen/Kochen für das Wochenende, sofern ihr dort unterstützen könnt, gebt bitte auch eine Rückmeldung.

Hier der Link für die Anmeldung:
[[https://forms.cloud.microsoft/e/jUMPju7Lgg][Anmeldung Landesgruppenwochenende 02.10.-04.10.2026]]

Mit Blick auf die Villa als Ort, bedenkt bitte:
Zum Übernachten braucht ihr zwingend einen Schlafsack/eine Decke (Bezug und Innenleben), sowie ein Kopfkissen samt Bezug und ein Bettlaken. Vor Ort gibt es nur Matratzen.
Weiterhin sind Hausschuhe und ein Handtuch von Vorteil.
Gerne könnt ihr auch Gesellschaftsspiele oder ähnliches mitbringen.

Wir freuen uns, euch vor Ort zu sehen!
Lena für den eLGV
** Jetzt anmelden: Public Viewing für die Mitgliederversammlung am 22.11. in der Geschäftsstelle
Liebe Landesgruppe,

Am 30.6. haben wir uns auf einer Mitgliederversammlung für eine neue Satzung entschieden. Damit steht der neuen Struktur nichts mehr im Wege und es wird schon fleißig daran gearbeitet, um den Übergang möglichst fließend hinzubekommen.

Am 22.11. findet die online Mitgliederversammlung statt, auf der wir die nächsten Schritte besprechen und alle Verantwortungsträger*innen und Gestalter*innen für die neue Struktur wählen. Die offizielle Einladung wird nach dem Sommer kommen.

Da die Mitgliederversammlung von 10-18 Uhr angesetzt ist (inkl. einer langen Mittagspause, also keine Angst) haben wir für diesen Tag die Geschäftsstelle reserviert und freuen uns, wenn wir gemeinsam an der Mitgliederversammlung teilnehmen werden. Anmelden könnt ihr euch hier: [[https://forms.cloud.microsoft/e/nDC41S1w9m][Anmeldung zum Public Viewing für die Mitgliederversammlung am 22.11.2026 – Formular ausfüllen]]

Wir freuen uns, wenn viele von euch an dem Tag dabei sind!
* Öffentlichkeitsarbeit
** Neue Schulvorträge und Messen
Hi liebe ÖA-Begeisterte und alle die es werden wollen,

in einigen Wochen fängt die Schule wieder an und dann starten wir wie jedes Jahr nochmal richtig durch mit unseren Schulvorträgen! Außerdem kommen noch einige Messen auf uns zu, für die wir wieder mehrere Teamende suchen. Also: eure Chance (wieder) aktiv zu werden! Ganz egal ob und wie viel ÖA-Erfahrung ihr habt, wir freuen uns über alle Meldungen! 
Die genauen Termine findet ihr unten. 
Bei Interesse meldet euch bei kira.thede@yfu-deutschland.de für die Schulvorträge und bei dennisle-duy.nguyen@yfu-deutschland.de für die Messen.

Danke für euren Einsatz! 
Euer ÖA-Team SHH
- Infoabend an der Geschwister-Scholl-STS für die 9. Klasse
 Wo: Glückstädter Weg 70, 22549 Hamburg
 Wann: Do, 03.09.2026; abends
- Infoveranstaltung mit den Austauschexperten am Gymnasium Norderstedt
  Wo: Coppernicusstr. 1, 22850 Norderstedt
  Wann: Do, 10.09.2026; ab 18:30 Uhr
- Minimesse an der Geschwister-Scholl-STS
  Wo: Glückstädter Weg 70, 22549 Hamburg
  Wann: Do, 10.09.2026; Zeit tba
- Minimesse am Gymnasium Bondenwald
  Wo: Bondenwald 14b, 22453 Hamburg
  Wann: Mi, 16.09.2026; 19 - 21 Uhr, Aufbau ab 18:30 Uhr
- AJA-Messe in der Zinnschmelze Barmbek
  Wo: Maurienstraße 19, 22305 Hamburg
  Wann: Do, 17.09.2026; 17 - 19:30 Uhr, Aufbau ab 16 Uhr
- Infoabend an der Geschwister-Scholl-STS für die 10. Klasse
  Wo: Glückstädter Weg 70, 22549 Hamburg
  Wann: Do, 17.09.2026; abends
- Infoveranstaltung an der Grundschule Krempe
  Wo: Am Burggraben 10, 25361 Krempe
  Wann: Sa, 19.09.2026; 10 - 13 Uhr
- Infoabend am Gymnasium Othmarschen
  Wo: Walderseestraße 99, 22605 Hamburg
  Wann: Di, 22.09.2026; ab 19 Uhr
- Infoabend am Gymnasium Walddörfer
  Wo: Im Allhorn 45, 22359 Hamburg
  Wann: Di, 22.09.2026; 19 - 21 Uhr, Aufbau ab 18:30 Uhr
- Infoveranstaltung mit AFS & YFU
  Wo: Gymnasium Hummelsbüttel
  Wann: Mi, 30.09.26; Beginn 19h, Aufbau 18:30h
- Schulvortrag an der ahfs Uhlenhorst
  Wo: Bostelreihe 5, 22083 Hamburg
  Wann: Fr, 09.10.2026; 10:45 - 11:45 Uhr
- JuBi an der Stadtteilschule Bergedorf
  Wo: Ladenbeker Weg 13, 21033 Hamburg
  Wann: Sa, 14.11.2026; Zeit tba
* Aufnahmeprogramm
** Teamer*innen gesucht für den Willkomemnsspaziergang (26.09)
Für den Willkommensspaziergang unserer diesjährigen Gastfamilien und den neuen Austauschschüler*innen am 26.09. suchen wir motivierte Menschen aller Erfahrungsgrade. Geplant ist ein bunter Austausch im lockeren Rahmen mit Buffet im Hamburger Stadtpark. Treffen ist fürs Team ab 13:30, das Treffen ist bis ca. 17 Uhr angesetzt. 

Melde dich gerne bei Amilou (amilou.fehr@yfu-deutschland.de), wenn du Lust hast, dabei zu sein oder irgendwelche Fragen hast. 🙂 

Wir freuen uns! 
* Entsendeprogramm
** Es werden immernoch NBT teamende gesucht!
Liebe Landesgruppe,

wir sind nach wie vor auf der Suche nach Personen, die unsere diesjährigen NBTs unterstützen möchten.
- NBT SHH 2: 10.09. – 13.09.2026, CISV – Haus, Hamburg
  männliches Teammitglied, Erfahrung egal
- NBT SHH 3: 01.10. – 04.10.2026, Spejdergården Tydal, Eggebek
  Leitung/Co-Leitung oder Leitungsteam, sowie weitere Teammitglieder
Wenn ihr also Lust habt, die Austauschschüler*innen auf ihrem Rückkehrprozess zu begleiten, tolle Menschen zu sehen, YFU-Spirit zu verbreiten oder einfach mal wieder etwa für YFU zu machen oder noch Fragen habt, dann meldet euch gerne bei uns unter antonia.karg@yfu-deutschland.de oder greta.dahmen@yfu-deutschland.de.

Liebe Grüße
Greta & Antonia
* Externes und Überregionales
** Mitmachen / Stellen
*Co-Leitung für NO2-NBT im September dringend gesucht*
Für unsere NO2-NBT vom 10.9. (Teamanreise) bis zum 13.9. in Burg (Spreewald) suchen wird noch dringend eine Co-Leitung. Es gibt bereits eine Leitung und Teamende, wir suchen eine Co-Leitung mit Erfahrung, die das Team vervollständigt. Bitte melde dich bei Karla unter karla.golze@yfu-deutschland.de

*Leitungsteam für NBT im Oktober gesucht*
Für die SHH3-NBT vom 02.-04.10. (Teamanreise: 03.10.) suchen wir ein Leitungsteam. Die NBT findet in 24825 Eggebek statt. Melde dich bei Antonia unter antonia.karg@yfu-deutschland.de

*Weiterhin gesucht: erfahrene Teamer*innen für PPP-Nachbereitungsseminar in Berlin gesucht (24.-27.9.)*
Ende September trifft sich der gerade zurückgekehrte PPP-Jahrgang in Berlin, um gemeinsam auf das Jahr in den USA zurückzublicken. Das Leitungsteam steht, viele Teamplätze sind bereits besetzt. Jetzt fehlst nur noch du - als erfahrene*r Teamer*in, um das Team zu vervollständigen!
📍 Berlin-Wannsee
📅 Seminar: 25.–27. September | Teamanreise: 24. September
Ihr habt Lust auf eine tolle Gruppe, spannende USA-Geschichten und ein buntes YFU-Wochenende? Dann meldet euch bei Lina unter ppp@yfu.de!

*Komm ins Team – werde Trainer*in bei Colored Glasses und leite noch dieses Jahr eine Schulung!*
Die Colored Glasses Schulung richtet sich an junge Menschen ab 16 Jahren, die sich bei [[https://www.yfu.de/schule-und-yfu/colored-glasses][Colored Glasses]] engagieren möchten. Als Trainer*innen begleitet ihr sie mit Methoden, Austausch und euren Erfahrungen. Materialien und Ablaufvorschläge sind vorhanden. Beim Team achten wir auf einen guten Mix aus Personen mit aktueller CG-Workshop-Erfahrung, YFU-Bezug und YFU/CG-Trainings-Erfahrung. Wenn du Lust hast, neue Ehrenamtliche auf ihrem Einstieg bei CG zu begleiten, freuen wir uns über deine Rückmeldung für die Schulungen 18.-20. September in Hamburg und 06.-08. November in Kassel. Wir suchen jeweils noch 1-2 Trainer*innen, die das Team ergänzen. Eine erfahrene CG-Trainerin haben wir bereits gewonnen. Interesse oder Fragen? Melde dich bei Nina: roesch@yfu.de

*Neues Schuljahr, neue Aufgaben bei YFU im Team von Colored Glasses?*
Vielleicht hat sich dein Alltag verändert, du hast weniger Zeit für Tagungen oder hast Lust, den Verein einmal aus einer anderen Perspektive mitzugestalten? Dann schau dir unsere aktuellen Ehrenamts-Ausschreibungen bei Colored Glasses an. Vielleicht ist jetzt genau der richtige Zeitpunkt, etwas Neues auszuprobieren. Mit schon 1 bis 2 Stunden pro Woche kannst du Colored Glasses auf einer anderen Ebene mitgestalten, neue Fähigkeiten entwickeln und weiterhin einen Unterschied für eine bunte Welt machen. Die vollständigen Ausschreibungen findest du in den verlinkten PDFs. Interesse oder Fragen? Melde dich bei Nina: roesch@yfu.de. Gerne weitersagen! [[https://padlet.com/roesch_yfu/colored-glasses-updates-a0qarp2decbnmcx6/wish/YBl3Z2O0qYYgWv16][Referent*in für Marketing & Social Media]] | [[https://padlet.com/roesch_yfu/colored-glasses-updates-a0qarp2decbnmcx6/wish/lkDVaKjnO6gAWPp9][Regionalkoordinator*in (Koordi) für die Organisation von Workshops]] | [[https://padlet.com/roesch_yfu/colored-glasses-updates-a0qarp2decbnmcx6/wish/Ae2Ravo6eV24Qnz4][Referent*in für Motivation & Fortbildung]]

*Weiterhin dringend Familienbesucher*innen benötigt! 🔎*
Es warten noch zwei Schüler auf ihre Gastfamilie. Doch bevor sie platziert werden können, braucht es einen Familienbesuch. Daher sind wir auf deine Unterstützung angewiesen!
Aktuell brauchen wir Besucher*innen in 04924 Bad Liebenwerda (im Dreieck von Leipzig, Dresden und Cottbus), 32478 Hille (bei Minden) und 79585 Steinen (bei Lörrach).
Du wohnst in der Nähe oder hast Lust auf einen Ausflug? Du hast bereits Erfahrung oder das wäre dein erster Ausflug ins Aufnahmeprogramm? Either way freuen wir uns auf deine Nachricht an gastfamilien@yfu.de! 🧡

*Werde Teil des YFU-Trainingswochenendes im Oktober – Trainierende gesucht!*
Wir möchten im Herbst wieder eine überregionale Teaming-Einweisung vom 02.-04.10. 2026 für unerfahrene und Teamende mit ersten Teamingerfahrungen, die aber noch nicht ganz die nötige Erfahrung für eine Seminarleitung besitzen, anbieten. Das Trainingskonzept und die Hälfte des Teams stehen, jetzt fehlen nur noch zwei Trainer*innen, um das Team zu vervollständigen. Parallel findet die SLS statt, so dass sich zukünftige Seminarleiter*innen und Teamende nebenher treffen, austauschen und netzwerken können genauso wie die Trainierenden. Hast du Lust, als Trainierende Teil dieses inspirierenden Wochenendes zu werden? Dann melde dich bei Janine Germer in der GS unter germer@yfu.de.
** Termine/Schulungen
*Colored Glasses Schulung am 18.-20. September in Hamburg oder am 06.-08. November in Kassel – Starte jetzt dein Engagement für eine bunte Gesellschaft!*
Mit Colored Glasses Workshops begeistern wir Kinder und Jugendliche der 5. bis 13. Klasse an Schulen und Jugendeinrichtungen in ganz Deutschland für Vielfalt und Toleranz. Wir machen uns stark gegen Diskriminierung und Vorurteile durch spannende Simulationen und Diskussionen auf Augenhöhe! Die Schulung ist dein Start ins Ehrenamt: Wir zeigen dir, wie du einen Workshop planst und durchführst. Erfahrene Ehrenamtliche geben dir Tipps und Tricks, damit du auch ohne Vorerfahrung einen echten Unterschied machen kannst. Du bist zwischen 16 und 29 Jahre alt und willst aktiv werden? Melde dich zur kostenlosen Schulung an. Gerne weitersagen, auch an Interessierte ohne YFU-Hintergrund! Bei Fragen wenden dich gerne an Nina unter roesch@yfu.de.
 - 18.-20. September in Hamburg | [[https://forms.cloud.microsoft/Pages/ResponsePage.aspx?id=OqhNyXAcyk-Cu3mnrCJZhxEnxqX0aqtEqMA8FMo_fd1UQ04xVEhJOTRHVkEyNTFSSVMyOEYxVEdUOS4u][Zur Anmeldung]] | [[https://coloredglasses.de/wp-content/uploads/2025/07/2026-09-Flyer-Schulung-Hamburg.pdf][Flyer als PDF]] – nur noch 2 Plätze frei!
 - 06.-08. November in Kassel | [[https://forms.cloud.microsoft/Pages/ResponsePage.aspx?id=OqhNyXAcyk-Cu3mnrCJZhxEnxqX0aqtEqMA8FMo_fd1UMEdJQVQ0SlZDRFdCVTJKRVVURlM1RUhSTS4u][Zur Anmeldung]] | [[https://coloredglasses.de/wp-content/uploads/2025/12/2026-11-CG-Schulung-Kassel.pdf][Flyer als PDF]]
*Letzte Plätze für Online-Betreuungsschulungen sichern 💻*
Es gibt noch ein paar wenige freie Plätze für unsere Online-Betreuungsschulungen Anfang September. Das Angebot richtet sich an alle, die gerne in die Betreuungsarbeit im Aufnahmeprogramm einsteigen bzw. ihr Wissen auffrischen möchten.
Melde dich jetzt an, wenn du dabei sein möchtest 🧡
👉 4-Module-Schulung für neue Betreuer*innen
📅Jeweils am 1.,2.,8. und 9.9. um 19 Uhr
📍Online
🦸‍♀️Trainerinnen: Caren Spamer & Ines Hintz
✅ Anmeldung: [[https://forms.cloud.microsoft/Pages/ResponsePage.aspx?id=QqKWNFDLrkCVZmI1B908iS2FBzkZ3HdJtoS0ZOggvE5UNlk3REVUQldBNVRMOFRTN0xRRkwyMFZXWS4u][Anmeldung zur 4-Module-Schulung "Einheit 1" Online]]
👉 Co-Betreuungsschulung/Refresh
📅Am 15.9. um 19 Uhr
📍Online
🦸‍♀️Trainerinnen: Caren Spamer & Ines Hintz
✅ Anmeldung: [[https://forms.cloud.microsoft/Pages/ResponsePage.aspx?id=QqKWNFDLrkCVZmI1B908iS2FBzkZ3HdJtoS0ZOggvE5UMEVJRVQyMVFGVFNBTjhKMkFWNkM1RTVTOC4u][Anmeldung zur Co-Betreuungsschulung Online]]

*Dein Einstieg ins Teamen: Das Wochenende in Kassel wartet auf dich! #YFUEducation*
Du willst als Teamer*in bei YFU loslegen? Dann komm zur überregionalen Teaming-Einweisung (Basis) vom 02.-04.10. 2026 in Kassel! Lerne, was es zu beachten gibt, damit du deine Kleingruppen auf YFU-Veranstaltungen zum Durchstarten kriegst. Danach werden „Brainstorming“ und „Fishbowl“ keine Fremdwörter mehr sein. Praxisnah bereiten wir dich auf deinen Einsatz als Teamende*n vor, üben Methoden und zeigen Abläufe – und du probierst dich direkt selbst aus. Dabei knüpfst du Kontakte zu anderen engagierten YFUler*innen und tankst YFU-Spirit. YFU übernimmt die Kosten für Unterkunft, Verpflegung und die An- und Abreise mit der Deutschen Bahn (2. Klasse). Noch unsicher? Kein Problem! Melde dich einfach bei Janine im YFU-Büro (germer@yfu.de, Durchwahl -93) und kläre deine offenen Fragen. Du bist dir sicher und willst dabei sein? Dann melde dich hier an!
** Sonstiges
*Dein Einstieg ins Teamen: Das Wochenende in Kassel wartet auf dich! #YFUEducation*
Du willst als Teamer*in bei YFU loslegen? Dann komm zur überregionalen Teaming-Einweisung (Basis) vom 02.-04.10. 2026 in Kassel! Lerne, was es zu beachten gibt, damit du deine Kleingruppen auf YFU-Veranstaltungen zum Durchstarten kriegst. Danach werden „Brainstorming“ und „Fishbowl“ keine Fremdwörter mehr sein. Praxisnah bereiten wir dich auf deinen Einsatz als Teamende*n vor, üben Methoden und zeigen Abläufe – und du probierst dich direkt selbst aus. Dabei knüpfst du Kontakte zu anderen engagierten YFUler*innen und tankst YFU-Spirit. YFU übernimmt die Kosten für Unterkunft, Verpflegung und die An- und Abreise mit der Deutschen Bahn (2. Klasse). Noch unsicher? Kein Problem! Melde dich einfach bei Janine im YFU-Büro (germer@yfu.de, Durchwahl -93) und kläre deine offenen Fragen. Du bist dir sicher und willst dabei sein? Dann melde dich [[https://forms.cloud.microsoft/e/enDv3SeTJA][hier]] an!
* Terminübersicht
** TERMINE 2026
*18.09. -20.09. 2026* &nbsp;&nbsp;&nbsp; Colored Glasses Schulung, Jugendherberge Horner Rennbahn *Hamburg*

*25.09.-27.09.2026* &nbsp;&nbsp;&nbsp; Training of Trainers (ToT), *Wiesbaden*

*02.10. - 04.10.2026*  &nbsp;&nbsp;&nbsp; Seminarleitungsschulung (SLS), Jugendherberge *Kassel*
*02.10. - 04.10.2026*  &nbsp;&nbsp;&nbsp; *(LG)* Aktivenwochenende

*06.11. – 08.11.2026* &nbsp;&nbsp;&nbsp; Colored Glasses Schulung, Jugendherberge *Kassel*

*20.11. - 22.11.2026* &nbsp;&nbsp;&nbsp; Betreuendenseminar, *Jugendherberge Stuttgart*

*22.11.2026* &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; *(LG)* Mitgliederversammlung, *Geschäftsstelle*

*27.11. - 29.11.2026* &nbsp;&nbsp;&nbsp; ÖA-Ausschusstreffen, *Hamburg*

*06.05. - 09.05.2027* &nbsp;&nbsp;&nbsp; BUT 2027, *tba*
