* Landesgruppe
**  Wichtige Info Aufrufe Newsletter
Diesen Newsletter findet ihr ab jetzt auch auf Whatsapp! Dafür einfach über diesen Link beitreten: https://chat.whatsapp.com/GBCBuLIU2U78zpim5yGxLF
---

Sehr gerne nehmen wir eure Aufrufe oder Danksagungen in den wöchentlichen Newsletter auf.

Schreibt mir ([[mailto://shh-newsletter@yfu-deutschland.de][shh-newsletter@yfu-deutschland.de]]) dafür einfach immer bis *Mittwochs 17:00 Uhr* eure Aufrufe, damit ich sie noch in den Newsletter der aktuellen Woche mit aufnehmen kann. Ansonsten nehme ich die Aufrufe natürlich gerne in den nächsten auf.

Vielen lieben Dank und ich freue mich auf eure Emails.

Liebe Grüße
Aimo
* Aufnahmeprogramm
** Teameraufruf Gastfamilien- und Austauschschülertreffen
Liebe Landesgruppe, 

wir suchen noch Teamer für das *Midyear-Treffen der Gastfamilien und Austauschschüler und Austauschschülerinnen* in Hamburg! 

Das Treffen findet *am Sonntag, dem 18. Januar 2026, von 9:30 Uhr bis 17 Uhr* (inklusive Vor- und Nachbesprechung) im Esche Jugendkunsthaus im Eschel​sweg 4 in 22767 Hamburg statt.  

Auf dem Treffen gibt es Gesprächsrunden getrennt für die Austauschschüler/-innen, die Gastgeschwister und die Gasteltern. Hier können sie ihre Erfahrungen austauschen und reflektieren, Sorgen loswerden und Tipps für den weiteren Verlauf des Austauschjahres bekommen. 

Für diese Gesprächsrunden brauchen wir euch!  

Egal ob Justee, älterer YFUler, ehemaliges Gastgeschwisterkind oder Gastelternteil: Ihr könnt nachvollziehen, wie es den Beteiligten gerade geht, eure eigenen Erfahrungen teilen und Fragen beantworten. So könnt ihr dafür sorgen, dass das Austauschjahr der diesjährigen Austauschschüler/-innen und Gasteltern so schön wie möglich wird! 

Um bei dieser Veranstaltung mitzuteamen ist keine Erfahrung notwendig.

Bitte meldet euch sobald wie möglich mit Namen, Handynummer und Austauschland und -jahr bei mir (Imke) [[mailto://imke.plesch@yfu-deutschland.de][imke.plesch@yfu-deutschland.de]] an.

Ich freu mich auf euch!

Viele Grüße,
Imke
* Externes und Überregionales
** Mitarbeiter-Gesuche/Stellen 
*Erfahrenes Teammitglied für Mittelseminar 1 Nord gesucht*

Du hast dir vorgenommen, in 2026 wieder mehr zu teamen? Dann ist das deine Chance! Für das Mittelseminar 1 Nord wird noch erfahrene Unterstützung gesucht.

Melde dich dafür direkt bei Sophia: ap-seminare@yfu.de
Wann? 20.-25. Februar 2026
Wo? Jugendbildungsstätte Kaubstr. Berlin
Wer? Ein tolles Team und 33 motivierte Schüler*innen warten auf dich

*Ausflug ins Winterwonderland gewünscht?*

Wir suchen eine engagierte Person, die einen Familienbesuch bei einer potenziellen Gastfamilie übernimmt.
Die Familie lebt im schönen Tittmoning, ganz in der Nähe von Salzburg.
Der Besuch sollte idealerweise bis Mitte Februar stattfinden.
Du hast Zeit und Lust und wohnst vielleicht sogar in der Umgebung? Dann melde dich bei Sophia unter gastfamilien@yfu.de.

*Justee als Teamer*in für Japan- und Thailand-VBT in Lauenburg gesucht*
- Findet statt vom 19.02.-24.02.26 in Lauenburg (Teilnehmende reisen am 21.02.26 an)
- Die Leitungen Anne und Onur suchen eine*n Justee, der oder die Lust hat, VBT-Luft zu schnuppern
- Du musst nicht selbst in Japan oder Thailand gewesen sein!
- Bitte melde dich bei Anne unter anne.steinfort@googlemail.com

*Leitungen und Teamer*innen für VBTs 2026 gesucht*
- Du hast Lust, 2026 eine VBT zu teamen oder zu leiten?
- Dann trage dich jetzt in den Leitungs- und Team-Survey ein (verfügbar bis zum 05.01.2026):
- VBT-Saison 2026 Leitungs- und Teamsuche
- Bei Fragen erreichst du Fenja unter vbt@yfu.de

*🥼🩺Arzt/Ärztin für das YES 2026 gesucht!*

Wir suchen einen Arzt oder eine Ärztin, die beim YES im Sommer 2026 Lust & Zeit hat, das Core-Team zu unterstützen. Als Fachperson bist du dafür zuständig, dass die Teilnehmenden die nötige medizinische Versorgung erhalten. Dabei arbeitest du zusammen mit einem Team aus erfahrenen Engagierten, die dir unter die Arme greifen. Das klingt nach einer spannenden Aufgabe für dich? Dann bewirb dich jetzt bis zum 15. Januar. Teilen der Nachricht erwünscht!🔁

✍️Die Ausschreibung mit allen Infos findest du hier: https://www.yfu-yes.org/yes-doctor
** Schulungen/Termine
*Powerstart ins Ehrenamt am 14. Januar um 20 Uhr*

Du möchtest aktiv werden oder wieder einsteigen und brauchst für den Start noch ein bisschen Orientierung? Dann haben wir einen Tipp für dich🔥! Starte mit unseren Ehrenamtlichen beim digitalen Powerstart ins Ehrenamt durch. Lerne das YFU 1x1, finde heraus, was es für dich zu tun gibt, wie du dich mit YFUler*innen in deiner Umgebung vernetzen kannst und welche Vorteile du als YFUler*in genießt.

✍️ Anmeldung: https://tinyurl.com/2vjjk6sf

📆 Weitere Termine: https://sway.cloud.microsoft/WKISSAGmmiab4CYG
* Terminübersicht
** TERMINE 2026
*30.01. - 02.02.2026* &nbsp;&nbsp;&nbsp; Seminarleitungsschulung (SLS) Jugendherberge Horner Rennbahn *Hamburg*

*31.01. - 01.02.2026* &nbsp;&nbsp;&nbsp; *(LG)* Referent*innen/ Landesgruppenwochenende *in Kiel* (Anmeldung für alle offen)

*27.02. - 01.03.2026* &nbsp;&nbsp;&nbsp; Colored Glasses Schulung, Jugendherberge *Leipzig*

*20.03. - 22.03.2026* &nbsp;&nbsp;&nbsp; Gremiensitzung Frühjahr, Jugendherberge Horner Rennbahn *Hamburg*

*27.03. - 29.03.2026* &nbsp;&nbsp;&nbsp; Betreuendenseminar in *Bad Bevensen*

*15.05. - 17.05.2026* &nbsp;&nbsp;&nbsp; Colored Glasses Schulung, Jugendherberge Burg Schwaneck (*bei München*)

*29.05 - 31.05.2026* &nbsp;&nbsp;&nbsp; ÖA-Ausschusstreffen

*05.06. - 07.06.2026* &nbsp;&nbsp;&nbsp; *(LG)* Nord-LGT

*20.06. - 21.06.2026* &nbsp;&nbsp;&nbsp; Colored Glasses Schulung, Liebfrauenschule Mühlhausen (*bei Duisburg*)

*18.09. -20.09. 2026* &nbsp;&nbsp;&nbsp; Colored Glasses Schulung, Jugendherberge Horner Rennbahn *Hamburg*

*25.09. - 27.09.2026* &nbsp;&nbsp;&nbsp; *(LG)* Aktivenwochenende

*02.10. - 04.10.2026*  &nbsp;&nbsp;&nbsp; Seminarleitungsschulung (SLS), Jugendherberge *Kassel*

*06.11. – 08.11.2026* &nbsp;&nbsp;&nbsp; Colored Glasses Schulung, Jugendherberge *Kassel*

*27.11. - 29.11.2026* &nbsp;&nbsp;&nbsp; ÖA-Ausschusstreffen
