* Landesgruppe
**  Wichtige Info Aufrufe Newsletter
Diesen Newsletter findet ihr ab jetzt auch auf Whatsapp! Dafür einfach über diesen Link beitreten: https://chat.whatsapp.com/GBCBuLIU2U78zpim5yGxLF
---

Sehr gerne nehmen wir eure Aufrufe oder Danksagungen in den wöchentlichen Newsletter auf.

Schreibt mir ([[mailto://shh-newsletter@yfu-deutschland.de][shh-newsletter@yfu-deutschland.de]]) dafür einfach immer bis *Mittwochs 17:00 Uhr* eure Aufrufe, damit ich sie noch in den Newsletter der aktuellen Woche mit aufnehmen kann. Ansonsten nehme ich die Aufrufe natürlich gerne in den nächsten auf.

Vielen lieben Dank und ich freue mich auf eure Emails.

Liebe Grüße
Aimo
** Unterstützung als kleiner Flughafendienst gesucht am Freitag, 28.08.26 ca. 10:30 Uhr
Für eine Abreisegruppe vom Hamburger Flughafen suchen wir noch eine Person, die 
Lust hätte die deutschen Austauschschüler*innen zu unterstützen. Hintergrund 
ist, dass die Reisegruppe bestehend aus 5 Teilnehmer*innen ohne Flugbegleitung 
abfliegen wird. Deine Aufgabe wäre es lediglich vor Ort zu sein/Präsenz zu 
zeigen und den Teilnehmer*innen gegebenfalls beim Check-In am Schalter zu helfen.

Der Flug (nach Dublin) geht am 28.08. um 13:35 Uhr. Treffpunkt und Zeit ist 3 
Stunden vor Abflug (also 10:35 Uhr) beim Check-In Schalter. Sobald alle 
Teilnehmer*innen eingecheckt sind, ihr Gepäck aufgegeben haben und in der 
Sicherheitskontrolle sind ist deine Aufgabe dann auch schon wieder erledigt 😄

Wenn du an dem Freitag Zeit und Lust hast, den Teilnehmer*innen zu helfen, melde 
dich bitte bei Jessi:
E-Mail: jessica.piedziak@yfu.de

Oder allgemein unter:
E-Mail (travel): reise@yfu.de
* Öffentlichkeitsarbeit
** Dankeschön und Save The Date!
Liebe Landesgruppe SHH,

der Sommer ist da und damit auch die Sommerpause der ÖA. Es haben in den letzten sechs Monaten bereits 8 Veranstaltungen stattgefunden und wir möchten uns bei allen Teamenden bedanken, die dies möglich gemacht haben: Mascha, Lotta, Kira, Elene, Hilla, Duy, Henrike, Hanna und Marie. Danke für euren Einsatz in der ÖA und dafür, dass ihr YFU bereits an so viele verschiedene Orte gebracht habt!

Und wie jedes Jahr starten wir im September dann nochmal richtig durch und freuen uns über viele ÖA-Motivierte für den Rest der Saison. Ihr findet unten schonmal eine Übersicht der kommenden Veranstaltungen.
 - 27.08.2026 (Hamburg)
 - 05.09.2026 (Hamburg)
 - 10.09.2026 (Norderstedt)
 - 10.09.2026 (Hamburg)
 - 16.09.2026 (Hamburg)
 - 17.09.2026 (Hamburg)
 - 22.09.2026 (Hamburg)
Liebe Grüße und einen schönen Sommer wünschen
Aimo, Annina, Duy, Kira, Lisa und Sophie
* Entsendeprogramm
** Auswahlleitungen und Einzelgesprächsleitungen für die PPP-Auswahlen gesucht
Die Bewerbungssaison für den PPP-Jahrgang 2027/28 hat begonnen und mit ihr die Suche nach Auswahlleitungen und Einzelgesprächsleitungen. Wenn Du Dir vorstellen kannst, diesen Herbst eine Auswahl zu leiten oder als Einzelgesprächsleitung zu begleiten, fülle bitte diese kurze Umfrage aus: 

[[https://forms.cloud.microsoft/e/9c4d3YZ1t5][PPP-Auswahlleitungen 2026]]

Wenn Du Dir unsicher bist, ob Du die Voraussetzungen erfüllst oder (noch) keine Schulung hast, melde Dich trotzdem gerne, im Herbst werden auch wieder Schulungen stattfinden. Bei Fragen wende Dich gerne an Keira (keira.geiss@yfu.de)
** Es werden immernoch NBT teamende gesucht?
Liebe Landesgruppe,

wir sind nach wie vor auf der Suche nach Personen, die unsere diesjährigen NBTs unterstützen möchten.

*NBT SHH 1: 13.08. – 16.08.2026, Spejdergården Tydal, Eggebek*
- 1-2 Teamende, gerne mit etwas Teamingerfahrung oder eine Person, die sich ausschließlich um die Verpflegung kümmern möchte.
Meldet euch gerne direkt bei Leon (leon.otten@yfu-deutschland.de)
*NBT SHH 2: 10.09. – 13.09.2026, CISV – Haus, Hamburg*
- 1-2 Teamende: Erfahrung egal, mind eine nicht-weibliche Person
*NBT SHH 3: 01.10. – 04.10.2026, Spejdergården Tydal, Eggebek*
- Leitung oder Leitungsteam
-  2- 3 Teamende, mind. eine nicht weibliche Person, gerne auch Personen mit etwas Erfahrung, aber wir freuen uns über alle Meldungen:)
Wenn ihr also Lust habt, die Austauschschüler*innen auf ihrem Rückkehrprozess zu begleiten, tolle Menschen zu sehen, YFU-Spirit zu verbreiten oder einfach mal wieder etwa für YFU zu machen oder noch Fragen habt, dann meldet euch gerne bei uns unter antonia.karg@yfu-deutschland.de oder greta.dahmen@yfu-deutschland.de.

Liebe Grüße
Greta &  Antonia
* Externes und Überregionales
** Mitmachen / Stellen
*Auswahlleitungen und Einzelgesprächsleitungen für die PPP-Auswahlen gesucht*
Die Bewerbungssaison für den PPP-Jahrgang 2027/28 hat begonnen und zahlreiche Jugendliche warten auf ihre PPP-Auswahl. Dafür suchen wir nun Auswahlleitungen und Einzelgesprächsleitungen.
Wenn Du Dir vorstellen kannst, diesen Herbst eine Auswahl zu leiten oder als Einzelgesprächsleitung zu begleiten, fülle bitte diese kurze Umfrage aus: [[https://forms.cloud.microsoft/e/9c4d3YZ1t5][PPP-Auswahlleitungen 2026]]
Bei Fragen melde Dich gerne bei Keira (keira.geiss@yfu.de)

*🔎Erfahrener männlicher Teamer für OWO 1 gesucht*
Für die OWO 1 vom 16. - 20.08 in Mainz suchen wir noch einen erfahrenen männlichen Teamer. Die OWO wird von Linus Stöckmann und Kati Krajnik geleitet.
Wenn du Lust hast dabei zu sein, melde dich gerne bei Mareen (📧ap-seminare@yfu.de). Alle weiteren Infos findest du [[https://intranet.yfu.de/downloads/files/3970][hier]].

*Co-Leitung für NBT Anfang August gesucht*
Du hast Lust die frisch zurück gekehrten Schüler*innen willkommen zu heißen und ihnen den Start in den Alltag in Deutschland etwas zu erleichtern? Dann bist du perfekt für unsere NH-NBT! Die NBT findet vom 07-09.08.2026 (Teamanreise 06.08) in Sibbesse statt. 
Explizit suchen wir noch eine (Co-)Leitung. Das Team ist super motiviert und bringt selbst einiges an Erfahrung mit.
Melden kannst du dich gerne bei Julia (julia.glatthaar@yfu-deutschland.de) oder Finja (finja.weinert@yfu-deutschland.de). Dankeschön vorab!

*Co-Leitung und Teamende für NBT Mitte August gesucht*
Du hast schon Erfahrung darin, frisch zurückgekehrte Austauschschüler*innen nachzubereiten und hast jetzt Lust selbst zu leiten? Wir suchen eine Co-Leitung, die zusammen mit der bestehenden und erfahrenen Leitung die SHH1-NBT vom 14.-16.08. (Teamanreise 13.08.) in 24825 Eggebek leiten möchte.
Du möchtest noch nicht leiten, aber teamen? Wir suchen außerdem 1-2 Teamende, sowohl erfahren als auch unerfahren, und freuen uns, dich im Team zu haben!
Melde dich bei Antonia Karg (antonia.karg@yfu-deutschland.de)

*Leitungsteam für NBT Ende August gesucht*
Für die RHWF-NBT vom 29.-31.08. (Teamanreise 28.08.) in 58091 Hagen suchen wir ein erfahrenes Leitungsteam. Ein vierköpfiges Team steht bereits, ebenso gibt es ein Auto – wir suchen ein Leitungsteam, dass die NBT komplettiert. Bitte melde dich bei Hendrik Röhr unter (hendrik.roehr@yfu-deutschland.de). Achtung: Die NBT geht bis Montag!

*Co-Leitung für NBT Ende August gesucht*
Für die BY2-NBT vom 28.-30.08. (Teamanreise 27.08.) in 82256 Fürstenfeldbruck suchen wir eine (Co)-Leitung. Nicole Celina leitet die NBT mit viel Erfahrung, viele Teamende stehen schon fest, es fehlt noch eine (Co)-Leitung als Verstärkung. Bitte melde dich direkt bei Nici unter nicole.celina@yfu-deutschland.de. 

*Lass dich zur PPP-Auswahlleitung schulen*
Für die neue PPP-Saison wollen wir wieder neue Auswahlleitungen schulen. Du hast Lust, in der neuen Saison eine PPP-Auswahl zu leiten, aber dir fehlt noch die nötige Schulung? Dann trage dich gerne in die [[https://forms.cloud.microsoft/Pages/ResponsePage.aspx?id=QqKWNFDLrkCVZmI1B908ibDdxUEoHapOoDj4h619qOdUQUVNSUdCTEwxT1I4WFVDSTEwUEtZTTBLWi4u][Abfrage]] ein. Voraussetzungen für die Schulung sind Erfahrungen als Teammitglied/ Einzelgesprächsleitung bei PPP-Auswahlen und bestenfalls eine KLT-Schulung.
Bei Fragen melde dich gerne bei Picabo (picabo.winands@yfu-deutschland.de).

*Austauschschüler*innen aus China und Mexiko: Wegen Visum dringend Gastfamilien benötigt für 6 Jugendliche!*
Wegen ihres Visums benötigen diese sechs Jugendlichen ganz besonders dringend ihre Gastfamilien in Deutschland: Alonso (15), José (15) und Luis (16) aus Mexiko sowie Ruize (16) und die beiden Mädchen Yinyuan (17) und Yiling (16) aus China. Auf der YFU-Website stellen sich die Jugendlichen etwas näher vor: https://www.yfu.de/austauschschueler.
Vielleicht könnte eine*r dieser Austauschschüler*innen gut in eure Familie passen? Auch als Willkommensfamilie für die ersten drei Monate seid ihr eine große Hilfe - ab Ende August oder auch Anfang/Mitte September. Bitte meldet euch unter gastfamilien@yfu.de, wenn ihr uns hier unterstützen könnt - vielen lieben Dank!
** Schulungen / Termine
*Absage ToT in diesem Jahr – neues Training für 2027 geplant*
Das für Ende September angekündigte Training of Trainers (ToT) wird nicht stattfinden. Ein neues Training ist für voraussichtlich Juni 2027 geplant. Sobald es dazu Neues gibt, wird es an dieser Stelle wieder ein Save-the-Date geben. Bei Fragen dazu, wendet euch an Rahel aus der GS (ehrenamt@yfu.de). 
** Sonstiges
*Globale YFU-Gastfamilienumfrage 📊*
Das Global Office führt aktuell eine globale Gastfamilienumfrage durch. Ihr wart Gasteltern oder Gastgeschwister? Dann füllt die Umfrage sehr gerne aus. Uns interessiert, wie eure Erfahrungen als Gastfamilie waren und was wir ggf. besser machen könnten.
Die Umfrage könnt ihr unter diesem Link aufrufen.
Danke für euren Input! 🧡
* Terminübersicht
** TERMINE 2026
*18.09. -20.09. 2026* &nbsp;&nbsp;&nbsp; Colored Glasses Schulung, Jugendherberge Horner Rennbahn *Hamburg*

*02.10. - 04.10.2026*  &nbsp;&nbsp;&nbsp; Seminarleitungsschulung (SLS), Jugendherberge *Kassel*
*02.10. - 04.10.2026*  &nbsp;&nbsp;&nbsp; *(LG)* Aktivenwochenende

*06.11. – 08.11.2026* &nbsp;&nbsp;&nbsp; Colored Glasses Schulung, Jugendherberge *Kassel*

*20.11. - 22.11.2026* &nbsp;&nbsp;&nbsp; Betreuendenseminar, *Jugendherberge Stuttgart*

*27.11. - 29.11.2026* &nbsp;&nbsp;&nbsp; ÖA-Ausschusstreffen, *Hamburg*

*06.05. - 09.05.2027* &nbsp;&nbsp;&nbsp; BUT 2027, *tba*
