* Landesgruppe
**  Wichtige Info Aufrufe Newsletter
Diesen Newsletter findet ihr ab jetzt auch auf Whatsapp! Dafür einfach über diesen Link beitreten: https://chat.whatsapp.com/GBCBuLIU2U78zpim5yGxLF
---

Sehr gerne nehmen wir eure Aufrufe oder Danksagungen in den wöchentlichen Newsletter auf.

Schreibt mir ([[mailto://shh-newsletter@yfu-deutschland.de][shh-newsletter@yfu-deutschland.de]]) dafür einfach immer bis *Mittwochs 17:00 Uhr* eure Aufrufe, damit ich sie noch in den Newsletter der aktuellen Woche mit aufnehmen kann. Ansonsten nehme ich die Aufrufe natürlich gerne in den nächsten auf.

Vielen lieben Dank und ich freue mich auf eure Emails.

Liebe Grüße
Aimo
** Einladung zum Nord-LGT 2026
Liebe Nord-LGs,
Wir konnten es alle kaum abwarten, aber jetzt ist es endlich so weit: das nächste Nord-LGT steht an! Wir freuen uns auf ein sommerliches Wochenende mit euch in Barmstedt bei Pinneberg (keine Sorge, das ist vom Hamburger Hauptbahnhof gut mit der Bahn erreichbar) mit vielen tollen Workshops, einem unterhaltsamen Programm und Zeit dafür, alte und neue Bekanntschaften wiederzusehen.

Wann? 05.-07..06.2026
Wo? Victor-Andersen-Haus Pinneberg (Düsterlohe 5, 25355 Barmstedt )
 
Meldet euch ab jetzt bis Mitte Mai über diesen Link an: [[https://forms.cloud.microsoft/e/JQQUuacHDj][Nord-LGT 2026 – Formular ausfüllen]]
Die Plätze sind begrenzt, also meldet euch schnell an. Anmeldeschluss ist der 15.05.2026.

Wir haben dieses Jahr eine Teilnahmegebühr von 20€. Solltet ihr Schwierigkeiten haben, diese zu erbringen, meldet euch gerne per Mail bei uns und wir finden eine Lösung dafür. Fahrtkosten erstatten wir für alle, die wollen, bis zu 30€, wenn ihr günstig und früh bucht. Das heißt bis 2 Wochen vor dem 05.06. (also 21.05.) und achtet gerne auf BahnCard und Deutschlandticket.  

Solltet ihr noch irgendwelche Fragen haben, erreicht ihr uns alle unter dieser Mailadresse: nordlgt@lists.yfu-deutschland.de. Wir freuen uns auf eure Anmeldungen!

Euer Nord-LGT Orga Team
* Öffentlichkeitsarbeit
** Neue Infos
Hallo liebe Landesgruppe,

die neue Bewerbungssaison bei YFU für das Programmjahr 2027/28 hat Anfang April gestartet und daher gibt es auch in der ÖA in den nächsten Wochen und Monaten immer wieder was zu tun! Um weiterhin viele Schüler für ein Auslandsjahr zu begeistern, brauchen wir wie immer eure Unterstützung. Wenn ihr also Lust und Zeit habt, meldet euch für die folgenden Termine gerne bei kira.thede@yfu-deutschland.de
** Info-Veranstalltung mit AFS am Goethe-Gymnasium
Wann: 21.05.2026
Wo: Goethe-Gymnasium Hamburg (Altona)
Rispenweg 28, 22547 Hamburg
Wer: 1-2 Teamer jedes Erfahrungsgerades
** Schulvortrag am Gymnasium Brunsbüttel
Wann: flexibel möglich!
Meldet euch gerne bei kira.thede@yfu-deutschland.de
Wo: Gamnasium Brunsbüttel
Kopernikusstr. 1
22541 Brunsbüttel
** Infoabend mit AJAOrgas in Husum
Wann: 09.06.2026 19:00
Wo: Theodor-Storm-Schule
Ludwig-Nissen-Str. 62
25813 Husum
Wer: 1-2 Teamer jedes Erfahrungsgerades
** Schulvortrag am Gymnasium Trittau
Wann: 18.06.2026
Wo: Gymnasium Trittau
Wer: 1-2 Teamer jedes Erfahrungsgerades
** Infoabend an der Schule am Meer
Wann: 25.06.2026 19:00
Wo: Schule am Meer, Büsum
Wer: 1-2 Teamer jedes Erfahrungsgerades
* Entsendeprogramm
** Teamende und Leitungen für die NBT-Saison gesucht
Liebe Landesgruppe,

es ist so weit, die NBT-Saison steht vor der Tür und wir suchen viele begeisterte Teamende und Leitungen.
Dieses Jahr organisieren wir drei NBTs in Schleswig-Holstein-Hamburg.

NBT SHH 1: *13.08. – 16.08.2026* (inklusive VNBT) Spejdergården Tydal, Eggebek
NBT SHH 2: *10.09. - 13.09.2026* (inklusive VNBT) CISV-Haus, Hamburg 
NBT SHH 3: *01.10. – 04.10.2026* (inklusive VNBT) Spejdergården Tydal, Eggebek

Wenn ihr also Lust habt, die Austauschschüler*innen auf ihrem Rückkehrprozess zu begleiten, tolle Menschen zu sehen, YFU-Spirit zu verbreiten oder einfach mal wieder etwa für YFU zu machen, dann meldet euch gerne bis zum 31.05.2025 unter folgendem Link an: https://tinyurl.com/YFUNBTEhrenamtlichensuche2026

Für die NBTs der anderen LGs könnt ihr euch ebenfalls unter diesem Link anmelden.

Bei Fragen meldet euch gerne bei uns unter antonia.karg@yfu-deutschland.de.
 
Liebe Grüße
Greta & Antonia
** Teamergesuch Re-Entry SHH
Moin,
Gibt es unter euch noch jemanden, der Zeit und Lust hat, die SHH-Re-Entry vom 5. - 7.6.26 in Warwisch zu unterstützen?

Erfahrung ist egal, Anreise ist Freitagvormittag.😃
Falls ja - oder es vorher noch Fragen gibt -, meldet euch seeeehr gerne direkt bei mir unter Ines.hintz@yfu-deutschland.de oder 0163-9180370.

Schon mal ein großes DANKESCHÖN!
Ines
* Externes und Überregionales
** Mitarbeiter-Gesuche/Stellen
*Dringend Teamende für VBT am Wochenende gesucht*
- Für die BY2-VBT vom 16.-21.05. in Mühlhausen suchen wir noch 4 Teamende
- Das Team braucht dringend Unterstützung, um die VBT durchzuführen
- Leitungen sind Julius Eder und Silas Busch
- Bitte melde dich bei Kati: katarzyna.krajnik@yfu-deutschland.de
*Leitungen und Teamende aufgepasst: Wünsch dir deine NBT bis zum 31.05.2026*
Liebe NBT-Begeisterte, ab sofort bis zum 31.05.2026 dürft ihr eure Wünsche angeben, welche unserer bundesweit angebotenen NBTs im Sommer ihr leiten oder teamen möchtet. 
👉 Füllt dafür bitte das folgende Abfrageformular aus: https://tinyurl.com/YFUNBTEhrenamtlichensuche2026. Nach Ablauf der Frist werden sich die jeweils zuständigen NBT-Referent*innen der Landesgruppen bei euch zurückmelden. 📧 Bei Fragen erreicht ihr uns jederzeit unter nachbereitung@yfu-deutschland.de.
Wir freuen uns über eure zahlreichen Meldungen und senden warme Frühlingsgrüße, Eure AG Nachbereitung.

*Komm ins Team Colored Glasses und bewirke Veränderung für Vielfalt bei Kindern und Jugendlichen deutschlandweit!*
Mit den Colored Glasses Toleranzworkshops bringen wir YFU-Spirit, Vielfalt und Weltoffenheit an Schulen in ganz Deutschland. Hast du Lust, in deinem Engagement bei YFU einen neuen Schwerpunkt zu setzen oder dich mal in einem anderen Bereich auszuprobieren? Dann ist vielleicht eine dieser Ausschreibungen etwas für dich. Melde dich jetzt bei Nina unter roesch@yfu.de zurück. Viele weitere Infos findest du auch [[https://padlet.com/roesch14/colored-glasses-updates-a0qarp2decbnmcx6][hier]]. Unbedingt weitersagen – auch an nicht-YFUler*innen.
- CG-Vorstandsmitglied mit Schwerpunkt Koordi-Koordination – Organisations- und Kommunikationstalente gesucht! Alle Infos [[https://coloredglasses.de/organisations-und-kommunikationstalent-gesucht/][hier]].
- Verstärkung für das Team „CG-Ehrenamts-Motivation und -Fortbildung“ – stärke das CG-Netzwerk mit deinen Ideen und weiteren Angeboten! [[https://coloredglasses.de/unsere-motivation-beginnt-mit-dir/][Hier]] gibt’s mehr Infos.
- Social-Media-Begeisterte für das CG-Marketing-Team – gestalte Instagram-Posts rund um CG und entwickle unsere Social Media Kanäle weiter. [[https://coloredglasses.de/referentin-marketing-team-gesucht/][Hier]] sind die Details.
*OWO-Leitungen gesucht*
- Für die OWO 1 vom 16. - 20.08 in Mainz suchen wir 1 erfahrene Leitung
- Für die OWO 4 vom 23. - 27.08 in Mainz suchen wir 2 Leitungen
- Für die OWO 5 vom 23. - 27.08 in Bingen suchen wir 1 Co-Leitung
Bitte meldet euch bei Mareen (📧 ap-seminare@yfu.de) oder füllt diese [[https://forms.office.com/e/KYWzZNfDNt?origin=lprLink][Umfrage]] aus. Alle weiteren Infos findet ihr [[https://intranet.yfu.de/downloads/files/3970][hier]].

*OWO-Teamende gesucht*
Du hast Lust auf Seminare im Aufnahmeprogramm? Du möchtest Austauschschüler*innen bei ihrem Start in ihr Austauschjahr unterstützen und sie für das Zusammenleben mit ihrer Gastfamilie wappnen? Du möchtest andere YFUler*innen wiedertreffen? Du kennst dich mit Kommunikation und Kultur super aus und hast vom 16. - 20.08 oder 23. - 27.08 Zeit? Dann sind das Top Voraussetzungen, um eine OWO zu teamen! Bitte melde dich bei Mareen (📧 ap-seminare@yfu.de) oder fülle diese [[https://forms.office.com/e/KYWzZNfDNt?origin=lprLink][Umfrage]] aus. Alle weiteren Infos findest du [[https://intranet.yfu.de/downloads/files/3970][hier]].

*USA for you Sachsen-Anhalt: Programmbegleitung (m/d) gesucht*
Für die Begleitung der USA for you-Teilnehmenden aus Sachsen-Anhalt nach Michigan vom 16. bis 30.10.2026 suchen noch eine Person (m/d), die die Gruppe in die USA begleitet und auch die VBT und die NBT gemeinsam mit der weiteren Programmbegleitung leitet. 
Die Ausschreibung findet ihr hier: https://intranet.yfu.de/article_tool/articles/2216
Für Fragen könnt ihr Thekla unter usaforyou@yfu.de, Durchwahl -77, kontaktieren.

*Germany for you in Halle (Saale): Teamer*in für zwei Workshops gesucht:*
Die amerikanischen Jugendlichen, die mit Germany for you für zwei Wochen in Halle sind, haben einen Arrival- und einen Pre-Departure Workshop. Dafür suchen wir noch eine Person (m/w/d), die am 15.6. und 16.6. (jeweils 8:30 - 12:00 Uhr) sowie am 26.6. (8:30-12:00 Uhr) unterstützt.
Meldet euch dazu gern bei Thekla: germanyforyou@yfu.de, Durchwahl -77

*Ehrenamtliche*r für „Germany for you“ in Halle (Saale) gesucht (Kurzaustauschprogramm für US-Amerikaner*innen vom 13. bis 28. Juni 2026)*
Für die Durchführung des Germany for you-Programms in Halle suchen wir noch eine Person, die vor Ort unterstützen kann. Du musst dafür nicht im gesamten Programmzeitraum verfügbar sein, sondern kannst punktuell, wie es dir zeitlich passt, unterstützen.
Die Ausschreibung findest du hier: https://intranet.yfu.de/article_tool/articles/2215
Wende dich bei Fragen an Thekla unter germanyforyou@yfu.de, Durchwahl -77

*Spontan Lust auf eine Woche Berlin?*
Für die Abschlussfahrt der US-amerikanischen PPP-Stipendiat*innen vom 18.05.-23.05. nach Berlin haben wir noch einen Platz im Team frei. Neben einigen spannenden Ausflügen ist das Highlight der Woche ein ganztägiger Empfang im Bundestag. Habt ihr Lust dabei zu sein? Dann meldet euch gerne direkt bei Jessi (jessica.piedziak@yfu-deutschland.de).

*Wir brauchen deine Expertise als Trainer*in fürs ToT (25.-27.09.)*
👑 Du entwirfst und gibst Workshops, Schulungen oder Trainings bei YFU oder woanders? Dein Herz schlägt für Didaktik & (Weiter-)Bildung ? Dir sind Orte für gemeinsames Lernen und Entwicklung im Miteinander wichtig? Dann brauchen wir deine Leidenschaft und Expertise für das nächste Training of Trainers (ToT)! Hier werden andere Ehrenamtliche im Peer-to-Peer Ansatz darin geschult, selbst zu Trainieren und Einheiten bis ganze Konzepte zu erstellen. Das ToT findet vom 25.-27. September 2026 in Wiesbaden statt. Lust bekommen oder Fragen? Dann melde dich bei Rahel (perschke@yfu.de, +49 40 22 70 02 44) aus der Geschäftsstelle. Dir passt der Termin nicht? Kein Problem, melde dich auch gerne, wenn du trotzdem Lust hast, das ToT inhaltlich mit vorzubereiten. 
** Schulungen / Termine
*Colored Glasses Schulung am 20./21. Juni bei Duisburg – Starte jetzt dein Engagement für eine bunte Gesellschaft!*
Mit Colored Glasses Workshops begeistern wir Kinder und Jugendliche der 5. bis 13. Klasse an Schulen und Jugendeinrichtungen in ganz Deutschland für Vielfalt und Toleranz. Wir machen uns stark gegen Diskriminierung und Vorurteile durch spannende Simulationen und Diskussionen auf Augenhöhe! Die Schulung ist dein Start ins Ehrenamt: Wir zeigen dir, wie du einen Workshop planst und durchführst. Erfahrene Ehrenamtliche geben dir Tipps und Tricks, damit du auch ohne Vorerfahrung einen echten Unterschied machen kannst. Du bist zwischen 16 und 29 Jahre alt und willst aktiv werden? Melde dich zur kostenlosen Schulung am 20./21.06. an der Liebfrauenschule Mühlhausen in Grefrath (bei Duisburg)an: [[https://forms.cloud.microsoft/e/vB4gw7NGtJ][hier]].  Anmeldefrist ist der 30. Mai. Es sind nur noch wenige Plätze frei! Bei Fragen wenden dich gerne an Nina unter roesch@yfu.de.

*Weitersagen: Online-Infoabende zum Gastfamilie werden mit YFU*
Wie jedes Jahr im Frühjahr bieten wir wieder einmal im Monat eine Online-Infoveranstaltung zum Thema Gastfamilie werden 🏡 💜 an. Interessierte können einfach an dem Infoabend teilnehmen - bequem von zu Hause aus und ohne vorherige Anmeldung. Dabei stellt ein kleines ÖA-Team aus Haupt- und Ehrenamtlichen unsere Gastfamilienprogramme vor, informiert über den allgemeinen Ablauf und berichtet von eigenen Erfahrungen. Natürlich ist auch Zeit für alle Fragen. Die nächsten Termine sind: [[https://www.yfu.de/infoveranstaltungen/online-infoabend-gastfamilie-werden_mai][Do, 21. Mai 2026, Beginn: 19 Uhr]] + [[https://www.yfu.de/infoveranstaltungen/online-infoabend-gastfamilie-werden_jun][Mo, 22. Juni 2026, Beginn: 19 Uhr]].
➡️ Gern weitersagen - oder selbst mal reinschauen! 🙂
** Sonstiges / Externes
*📩 Dein YFU im Wandel – bleib aktuell mit dem Strukturkompass*
Die Strukturreform klingt groß und fühlt sich immer noch ziemlich abstrakt an. 

/Was bedeutet das alles für dein Ehrenamt und deine Mitgliedschaft?/
/Wie verändert sich YFU konkret?/
/Und wo kannst du dich in Zukunft einbringen und mitgestalten?/

Der Strukturkompass gibt dir Orientierung. 
Darin informieren dich Nate aus der AG Strukturreform und Julia aus der Geschäftsstelle regelmäßig über die aktuelle Lage, teilen wichtige Vereinsentscheidungen und Meilensteine, geben Einblicke hinter die Kulissen und zeigen dir, wo und wie du mitwirken kannst. 
Jetzt ein Abo dalassen – denn gemeinsam gestalten wir die Zukunft von YFU. 🫶
📩 Hier kannst du ihn abonnieren: https://mailing.yfu.de/f/333241-426684/

*📝 Mach mit: Umfrage der AG Prävention sexualisierter Gewalt*
Die AG Prävention sexualisierter Gewalt arbeitet derzeit an einem Schutzkonzept, das in Zukunft helfen soll, YFU Deutschland sicherer zu machen. Dazu führen wir eine Umfrage unter allen aktuellen und ehemaligen Mitarbeitenden durch – egal, wie aktiv ihr momentan seid oder welche Erfahrungen ihr gemacht habt. Eure Antworten helfen uns. Die Umfrage läuft bis zum 31.05.26. Vielen Dank für eure Unterstützung! https://www.yfu-survey.org/poll/index.php/314721?lang=de-informal

*Jetzt bewerben: Qualifizierungsprogramm „FuturE“ der DSEE*
Du engagierst dich in einem Verein, einer Initiative oder Organisation – und willst mehr Verantwortung übernehmen? Dann ist FuturE genau das Richtige für dich! Das dreimonatige Qualifizierungsprogramm begleitet dich auf deinem Weg in eine ehrenamtliche Führungsposition durch Raum für Austausch, neue Perspektiven und konkrete Unterstützung.
Für Engagierte zwischen 18 und 27 Jahren | 3 Präsenzwochenenden + Onlinebegleitung | September bis November 2026 | weitestgehend kostenfrei; DSEE übernimmt alle anfallenden Reise- und Unterbringungskosten | bis zum 16. Juni [[https://www.deutsche-stiftung-engagement-und-ehrenamt.de/foerderung/futur-e-bewerbung/][hier]] bewerben!

*transform_D Summit 18./19. Juni 2026 in Berlin – kostenlose Konferenz für die engagierte Gesellschaft der DSEE!*
Der transform_D Summit 2026 wird erneut ein Ort des Austauschs für Engagierte, Entscheidungsträger:innen und Visionär:innen, die gemeinsam an einer zukunftsfähigen Gesellschaft arbeiten. Freut Euch auf inspirierende Keynotes, unter anderem von 321maxx, Katharina Nocun und Prof. Dr. Lorenz Narku Laing. Mehr als 50 zivilgesellschaftliche Organisationen gestalten das Programm mit eigenen Beiträgen – von Workshops über Diskussionen bis hin zu interaktiven Praxisformaten. [[https://www.deutsche-stiftung-engagement-und-ehrenamt.de/summit-2026/][Alle Infos hier!]] 

*Selbstbehauptungstraining für Engagierte – Deutsche Stiftung für Engagement und Ehrenamt (DSEE)*
Gemeinsam mit erfahrenen Trainerinnen und Trainern erlernt ihr Strategien und Techniken, um in schwierigen oder bedrohlichen Situationen sicher zu reagieren. Der Fokus liegt darauf, Konflikte frühzeitig zu erkennen, souverän aufzutreten und Eskalationen möglichst zu vermeiden. So könnt ihr auch in angespannten Momenten handlungsfähig bleiben – und euer Engagement mit mehr Sicherheit ausüben. | kostenlos, Fahrtkosten werden durch die DSEE erstattet | in 16 Städten in ganz Deutschland | Ab sofort, Termine bis September 2026 | [[https://www.deutsche-stiftung-engagement-und-ehrenamt.de/mitmachen/selbstbehauptung-fuer-engagierte/][Alle Infos und Termine – jetzt anmelden]].
* Terminübersicht
** TERMINE 2026
*15.05. - 17.05.2026* &nbsp;&nbsp;&nbsp; Colored Glasses Schulung, Jugendherberge Burg Schwaneck (*bei München*)

*29.05 - 31.05.2026* &nbsp;&nbsp;&nbsp; ÖA-Ausschusstreffen, *Hamburg*

*05.06. - 07.06.2026* &nbsp;&nbsp;&nbsp; *(LG)* Nord-LGT

*13.06. - 13.06.2026* &nbsp;&nbsp;&nbsp; Betreuungsschulung, *Berlin*

*20.06. - 21.06.2026* &nbsp;&nbsp;&nbsp; Colored Glasses Schulung, Liebfrauenschule Mühlhausen (*bei Duisburg*)

*18.09. -20.09. 2026* &nbsp;&nbsp;&nbsp; Colored Glasses Schulung, Jugendherberge Horner Rennbahn *Hamburg*

*25.09. - 27.09.2026* &nbsp;&nbsp;&nbsp; *(LG)* Aktivenwochenende

*02.10. - 04.10.2026*  &nbsp;&nbsp;&nbsp; Seminarleitungsschulung (SLS), Jugendherberge *Kassel*

*06.11. – 08.11.2026* &nbsp;&nbsp;&nbsp; Colored Glasses Schulung, Jugendherberge *Kassel*

*20.11. - 22.11.2026* &nbsp;&nbsp;&nbsp; Betreuendenseminar, *Jugendherberge Stuttgart*

*27.11. - 29.11.2026* &nbsp;&nbsp;&nbsp; ÖA-Ausschusstreffen, *Hamburg*
