* Landesgruppe
**  Wichtige Info Aufrufe Newsletter
Diesen Newsletter findet ihr ab jetzt auch auf Whatsapp! Dafür einfach über diesen Link beitreten: https://chat.whatsapp.com/GBCBuLIU2U78zpim5yGxLF
---

Sehr gerne nehmen wir eure Aufrufe oder Danksagungen in den wöchentlichen Newsletter auf.

Schreibt mir ([[mailto://shh-newsletter@yfu-deutschland.de][shh-newsletter@yfu-deutschland.de]]) dafür einfach immer bis *Mittwochs 17:00 Uhr* eure Aufrufe, damit ich sie noch in den Newsletter der aktuellen Woche mit aufnehmen kann. Ansonsten nehme ich die Aufrufe natürlich gerne in den nächsten auf.

Vielen lieben Dank und ich freue mich auf eure Emails.

Liebe Grüße
Aimo
** Unterstützung als kleiner Flughafendienst gesucht am Freitag, 28.08.26 ca. 10:30 Uhr
Für eine Abreisegruppe vom Hamburger Flughafen suchen wir noch eine Person, die 
Lust hätte die deutschen Austauschschüler*innen zu unterstützen. Hintergrund 
ist, dass die Reisegruppe bestehend aus 5 Teilnehmer*innen ohne Flugbegleitung 
abfliegen wird. Deine Aufgabe wäre es lediglich vor Ort zu sein/Präsenz zu 
zeigen und den Teilnehmer*innen gegebenfalls beim Check-In am Schalter zu helfen.

Der Flug (nach Dublin) geht am 28.08. um 13:35 Uhr. Treffpunkt und Zeit ist 3 
Stunden vor Abflug (also 10:35 Uhr) beim Check-In Schalter. Sobald alle 
Teilnehmer*innen eingecheckt sind, ihr Gepäck aufgegeben haben und in der 
Sicherheitskontrolle sind ist deine Aufgabe dann auch schon wieder erledigt 😄

Wenn du an dem Freitag Zeit und Lust hast, den Teilnehmer*innen zu helfen, melde 
dich bitte bei Jessi:
E-Mail: jessica.piedziak@yfu.de

Oder allgemein unter:
E-Mail (travel): reise@yfu.de
* Öffentlichkeitsarbeit
** Dankeschön und Save The Date!
Liebe Landesgruppe SHH,

der Sommer ist da und damit auch die Sommerpause der ÖA. Es haben in den letzten sechs Monaten bereits 8 Veranstaltungen stattgefunden und wir möchten uns bei allen Teamenden bedanken, die dies möglich gemacht haben: Mascha, Lotta, Kira, Elene, Hilla, Duy, Henrike, Hanna und Marie. Danke für euren Einsatz in der ÖA und dafür, dass ihr YFU bereits an so viele verschiedene Orte gebracht habt!

Und wie jedes Jahr starten wir im September dann nochmal richtig durch und freuen uns über viele ÖA-Motivierte für den Rest der Saison. Ihr findet unten schonmal eine Übersicht der kommenden Veranstaltungen.
 - 05.09.2026 (Hamburg)
 - 10.09.2026 (Norderstedt)
 - 10.09.2026 (Hamburg)
 - 16.09.2026 (Hamburg)
 - 17.09.2026 (Hamburg)
 - 22.09.2026 (Hamburg)
Liebe Grüße und einen schönen Sommer wünschen
Aimo, Annina, Duy, Kira, Lisa und Sophie
* Entsendeprogramm
** Auswahlleitungen und Einzelgesprächsleitungen für die PPP-Auswahlen gesucht
Die Bewerbungssaison für den PPP-Jahrgang 2027/28 hat begonnen und mit ihr die Suche nach Auswahlleitungen und Einzelgesprächsleitungen. Wenn Du Dir vorstellen kannst, diesen Herbst eine Auswahl zu leiten oder als Einzelgesprächsleitung zu begleiten, fülle bitte diese kurze Umfrage aus: 

[[https://forms.cloud.microsoft/e/9c4d3YZ1t5][PPP-Auswahlleitungen 2026]]

Wenn Du Dir unsicher bist, ob Du die Voraussetzungen erfüllst oder (noch) keine Schulung hast, melde Dich trotzdem gerne, im Herbst werden auch wieder Schulungen stattfinden. Bei Fragen wende Dich gerne an Keira (keira.geiss@yfu.de)
** Doch noch eine NBT teamen?
Liebe Landesgruppe,

der Beginn der NBT-Saison rückt immer näher und wir sind weiterhin auf der Suche nach Personen, die unsere NBT-Teams vervollständigen möchten. Besonders über Unterstützung für unsere erste NBT würden wir uns freuen:)

Wir suchen aktuell:
*NBT SHH 1: 13.08. – 16.08.2026*, Spejdergården Tydal, Eggebek
 - Leitung oder Leitungsteam
 - 1 -2 Teamende, Erfahrung + Geschlecht egal
*NBT SHH 2: 10.09. – 13.09.2026*, CISV – Haus, Hamburg           
 - 1- 2 Teamende, gerne auch Justees
*NBT SHH 3: 01.10. – 04.10.2026*, Spejdergården Tydal, Eggebek
 - Leitung oder Leitungsteam
 - 1- 2 Teamende
 - Mit Blick auf die aktuelle Teamzusammensetzung freuen wir uns besonders über männliche Teamende und Personen mit etwas Teamingerfahrung (m/w/d) :)
Wenn ihr also Lust habt, die Austauschschüler*innen auf ihrem Rückkehrprozess zu begleiten, tolle Menschen zu sehen, YFU-Spirit zu verbreiten oder einfach mal wieder etwa für YFU zu machen oder noch Fragen habt, dann meldet euch gerne bei uns unter antonia.karg@yfu-deutschland.de oder greta.dahmen@yfu-deutschland.de.

Liebe Grüße
Greta & Antonia
* Externes und Überregionales
** Mitmachen / Stellen
*Auswahlleitungen und Einzelgesprächsleitungen für die PPP-Auswahlen gesucht*
Die Bewerbungssaison für den PPP-Jahrgang 2027/28 hat begonnen und zahlreiche Jugendliche warten auf ihre PPP-Auswahl. Dafür suchen wir nun Auswahlleitungen und Einzelgesprächsleitungen.
Wenn Du Dir vorstellen kannst, diesen Herbst eine Auswahl zu leiten oder als Einzelgesprächsleitung zu begleiten, fülle bitte diese kurze Umfrage aus: [[https://forms.cloud.microsoft/e/9c4d3YZ1t5][PPP-Auswahlleitungen 2026]]
Bei Fragen melde Dich gerne bei Keira (keira.geiss@yfu.de)

*Teamer*in (m/w/d) gesucht: USA for you Sachsen-Anhalt*
Im Herbst 2026 fliegen15 Jugendliche aus Sachsen-Anhalt mit dem USA for you-Vollstipendium für zwei Wochen in die USA. Für die Unterstützung der beiden Programmbegleitungen bei der Vor- und Nachbereitung suchen wir noch eine*n Teamer*in (m/w/d). Du solltest an beiden Tagungen Zeit haben und am besten USA- oder sogar USA for you-Erfahrung haben. Die VBT ist vom 18.-20.9. und die NBT vom 13.-15.11.26, beides in 39326 Wolmirstedt. 
Bitte melde dich bei Interesse bei Thekla: usaforyou@yfu.de oder Durchwahl -77

*Co-Leitung für NBT Anfang August gesucht*
Du hast Lust die frisch zurück gekehrten Schüler*innen willkommen zu heißen und ihnen den Start in den Alltag in Deutschland etwas zu erleichtern? Dann bist du perfekt für unsere NH-NBT! Die NBT findet vom 07-09.08.2026 (Teamanreise 06.08) in Sibbesse statt. 
Explizit suchen wir noch eine (Co-)Leitung. Das Team ist super motiviert und bringt selbst einiges an Erfahrung mit.
Melden kannst du dich gerne bei Julia (julia.glatthaar@yfu-deutschland.de) oder Finja (finja.weinert@yfu-deutschland.de). Dankeschön vorab!

*Co-Leitung und Teamende für NBT Mitte August gesucht*
Du hast schon Erfahrung darin, frisch zurückgekehrte Austauschschüler*innen nachzubereiten und hast jetzt Lust selbst zu leiten? Wir suchen eine Co-Leitung, die zusammen mit der bestehenden und erfahrenen Leitung die SHH1-NBT vom 14.-16.08. (Teamanreise 13.08.) in 24825 Eggebek leiten möchte.
Du möchtest noch nicht leiten, aber teamen? Wir suchen außerdem 1-2 Teamende, sowohl erfahren als auch unerfahren, und freuen uns, dich im Team zu haben!
Melde dich bei Antonia Karg (antonia.karg@yfu-deutschland.de)

*Leitung für PPP-NBT in Berlin gesucht (24.-27.9.)*
Für den gerade zurückgekehrten PPP-Jahrgang sind wir auf der Suche nach einem Leitungsteam für das Nachbereitungsseminar. Es findet statt vom 25.-27. September in der Jugendherberge am Berliner Wannsee, die Teamanreise ist für den 24. September geplant. Es gibt ein Konzept und auch viele motivierte Teammeldungen. Wenn ihr Lust habt, die Gruppe kennenzulernen und spannende Geschichten aus den USA zu hören, meldet euch gern bei Lina unter ppp@yfu.de.

*Lass dich zur PPP-Auswahlleitung schulen*
Für die neue PPP-Saison wollen wir wieder neue Auswahlleitungen schulen. Du hast Lust, in der neuen Saison eine PPP-Auswahl zu leiten, aber dir fehlt noch die nötige Schulung? Dann trage dich gerne in die [[https://forms.cloud.microsoft/Pages/ResponsePage.aspx?id=QqKWNFDLrkCVZmI1B908ibDdxUEoHapOoDj4h619qOdUQUVNSUdCTEwxT1I4WFVDSTEwUEtZTTBLWi4u][Abfrage]] ein. Voraussetzungen für die Schulung sind Erfahrungen als Teammitglied/ Einzelgesprächsleitung bei PPP-Auswahlen und bestenfalls eine KLT-Schulung.
Bei Fragen melde dich gerne bei Picabo (picabo.winands@yfu-deutschland.de).
** Schulungen / Termine
*🚀 Powerstart ins Ehrenamt am 22. Juli von 19-20.30 Uhr mit Ines und Julia*
Du möchtest aktiv werden oder wieder einsteigen und brauchst für den Start noch ein bisschen Orientierung? Dann haben wir einen Tipp für dich🔥! Starte mit unseren Ehrenamtlichen beim digitalen Powerstart ins Ehrenamt durch. Lerne das YFU 1x1, finde heraus, was es für dich zu tun gibt, wie du dich mit YFUler*innen in deiner Umgebung vernetzen kannst und welche Vorteile du als YFUler*in genießt.
🔥 Anmeldung hier: https://tinyurl.com/jszynj7n
* Terminübersicht
** TERMINE 2026
*18.09. -20.09. 2026* &nbsp;&nbsp;&nbsp; Colored Glasses Schulung, Jugendherberge Horner Rennbahn *Hamburg*

*02.10. - 04.10.2026*  &nbsp;&nbsp;&nbsp; Seminarleitungsschulung (SLS), Jugendherberge *Kassel*
*02.10. - 04.10.2026*  &nbsp;&nbsp;&nbsp; *(LG)* Aktivenwochenende

*06.11. – 08.11.2026* &nbsp;&nbsp;&nbsp; Colored Glasses Schulung, Jugendherberge *Kassel*

*20.11. - 22.11.2026* &nbsp;&nbsp;&nbsp; Betreuendenseminar, *Jugendherberge Stuttgart*

*27.11. - 29.11.2026* &nbsp;&nbsp;&nbsp; ÖA-Ausschusstreffen, *Hamburg*

*06.05. - 09.05.2027* &nbsp;&nbsp;&nbsp; BUT 2027, *tba*
