* Landesgruppe
**  Wichtige Info Aufrufe Newsletter
Diesen Newsletter findet ihr ab jetzt auch auf Whatsapp! Dafür einfach über diesen Link beitreten: https://chat.whatsapp.com/GBCBuLIU2U78zpim5yGxLF
---

Sehr gerne nehmen wir eure Aufrufe oder Danksagungen in den wöchentlichen Newsletter auf.

Schreibt mir ([[mailto://shh-newsletter@yfu-deutschland.de][shh-newsletter@yfu-deutschland.de]]) dafür einfach immer bis *Mittwochs 17:00 Uhr* eure Aufrufe, damit ich sie noch in den Newsletter der aktuellen Woche mit aufnehmen kann. Ansonsten nehme ich die Aufrufe natürlich gerne in den nächsten auf.

Vielen lieben Dank und ich freue mich auf eure Emails.

Liebe Grüße
Aimo
* Aufnahmeprogramm
** Schulungen für neue Betreuer*innen 2026
Liebe AP-Mitarbeitenden,

ich hoffe, ihr seid gut ins neue Jahr gestartet! Es kommt mir schon viel länger vor als erst ein paar Wochen 😉

Ich möchte euch heute einen Überblick über die geplanten Schulungen/Seminare für neue Betreuer*innen sowie Menschen, die sich für die YFU-Betreuungsarbeit interessieren, geben.

Wir hatten ursprünglich geplant auf unserem Seminar in Bad Bevensen Ende März eine Einheit für neue Betreuer*innen anzubieten, haben unsere Pläne aber noch einmal geändert, da sich so viele erfahrene Betreuer*innen für die internationalen Workshops angemeldet haben, dass wir die Plätze dafür aufgestockt haben. Eine Einheit 1 wird in Bad Bevensen nun nicht stattfinden.

Stattdessen sind für 2026 jedoch folgende Termine für neue Betreuer*innen und Interessent*innen geplant:

Online Co-Betreuungsschulung/Refresh für Betreuenden
📅Dienstag, 3.2. um 19 Uhr für ca. 3 Stunden (weiterer Termin voraussichtlich im September)
📍Online
🦸‍♀️Trainerinnen: Caren Spamer & Ines Hintz
✅ Anmeldung: Anmeldung zur Co-Betreuungsschulung/Refresh für Betreuende

Eintägige Betreuungsschulung in Präsenz
📅Samstag, 13.6.
📍Berlin
🦸‍♀️Trainerinnen: Caren Spamer & N.N.
✅ Vormerkung per E-Mail bei Magdalene (lindemann@yfu.de) möglich

4-Module-Online-Schulung
📅voraussichtlich im September 2026
✅ weitere Infos tba

Wochenendseminar in Präsenz
📅voraussichtlich im November 2026
✅ weitere Infos tba

Leitet diese Infos gerne auch an interessierte Personen weiter.

Wir freuen uns darauf, viele von euch bei den Schulungen und Seminaren in Präsenz oder online kennenzulernen.

Liebe Grüße aus Hamburg
Magdalene
* Entsendeprogramm
** Leitung und Co-Leitung für die VBT SHH1 vom 04.04.26 bis 09.04.26 in Lauenburg gesucht
Du hast Leitungserfahrung und Lust eine VBT zu teamen?
Vom 04. – 09.04.26 findet in Lauenburg die SHH1 VBT statt. Es gibt auch schon viele Teammeldungen, du kannst dich also praktisch ins gemachte Nest setzen.
Für alle anderen Wünsche steht dir die EP-Leitung und die VBT-Referentin zur Seite.

Du hast eine Leitungsschulung hinter dir aber noch keine Erfahrung im Leiten?
Auch kein Problem! Wir suchen für die SHH1 VBT auch noch eine Co-Leitung. Das ist der perfekte Start um etwas Übung zu bekommen!

Bei Interesse meldet euch gerne bei Caren Bremer (caren.bremer@yfu-deutschland.de)
* Externes und Überregionales
** Mitarbeiter-Gesuche/Stellen 
*USA for you Sachsen-Anhalt: Programmbegleitungen gesucht*

Für die Begleitung der USA for you-Teilnehmenden aus Sachsen-Anhalt nach Michigan vom 16. bis 30.10.2026 suchen wir zwei Ehrenamtliche, die auch die VBT und die NBT gemeinsam leiten. 
Die Ausschreibung findet ihr hier: [[https://eur05.safelinks.protection.outlook.com/?url=https%3A%2F%2Fintranet.yfu.de%2Farticle_tool%2Farticles%2F2216&data=05%7C02%7Chh-newsletter%40yfu-deutschland.de%7Cc74b90987e9f4dcb72c708de694e8b49%7C3496a242cb5040ae9566623507dd3c89%7C0%7C0%7C639063983258786564%7CUnknown%7CTWFpbGZsb3d8eyJFbXB0eU1hcGkiOnRydWUsIlYiOiIwLjAuMDAwMCIsIlAiOiJXaW4zMiIsIkFOIjoiTWFpbCIsIldUIjoyfQ%3D%3D%7C0%7C%7C%7C&sdata=7560FHcMIbr6UDxmF7gdXVHrRNjB53xUuzJdd%2BaR0Rg%3D&reserved=0][Deutsches Youth For Understanding Komitee e.V. - Intranet]]
Für Fragen könnt ihr Thekla unter usaforyou@yfu.de, Durchwahl -77, kontaktieren.

*NBT-Leitung und Teamende für März gesucht*
- Wir suchen für die Nachbereitung der ersten Rückkehrenden des neuen Jahres…
- …ein Leitungsteam für die NBT I: Donnerstag, 12.03.2026, bis Sonntag, 15.03.2026 in Hamburg (Anreise Teilnehmende 13.03.)
- …Teamende für die NBT II: Donnerstag, 26.03.2025, bis Sonntag, 29.03.2025, in Würzburg (Anreise Teilnehmende 27.03.)
- Wenn du Interesse am Leiten oder Teamen hast, melde dich gern bei uns unter nachbereitung@yfu-deutschland.de
*Werde VBT-Leitung im April oder Mai*
- Für die Landesgruppen NO, SHH und MD suchen wir dich als VBT-Leitung
- Du hast bereits VBT- oder Seminarerfahrung und eine SLS-Schulung
- 04.04.-09.04. (NO) oder 08.04.-13.04. (SHH) in Lauenburg
- 14.04.-19.04. (MD) oder 03.05.-08.05. (MD) in Mühlhausen
- Melde dich bei Fenja unter vbt@yfu.de
*Wir suchen dich als Expert*in für unsere Länderwebinare*
- Du warst selbst im Ausland und hast Lust, deine Erfahrungen mit zukünftigen Austauschschüler*innen teilen?
- Du kommst aus einem anderen Land und hast Lust, Tipps und Erfahrungen dazu zu teilen?
- Dann werde Teamer*in auf einem Länderwebinar für den Jahrgang 26/27
- Trag dich gleich in den Survey [[https://eur05.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.yfu-survey.org%2Fpoll%2Findex.php%2F574632%3Flang%3Dde-informal&data=05%7C02%7Chh-newsletter%40yfu-deutschland.de%7Cc74b90987e9f4dcb72c708de694e8b49%7C3496a242cb5040ae9566623507dd3c89%7C0%7C0%7C639063983258815117%7CUnknown%7CTWFpbGZsb3d8eyJFbXB0eU1hcGkiOnRydWUsIlYiOiIwLjAuMDAwMCIsIlAiOiJXaW4zMiIsIkFOIjoiTWFpbCIsIldUIjoyfQ%3D%3D%7C0%7C%7C%7C&sdata=O%2BBjtPZq1zWx%2B1%2F65lBz4LSTHfleF%2F7f2it0gGd3mJE%3D&reserved=0][hier]] ein und wir melden uns bei dir!
*Wanted: Kooperationspartner AP-Sprachkurse*

Wir sind aktuell auf der Suche nach einem neuen Anbieter, der ab Herbst 2026 die Online-Deutschkurse für unsere Teilnehmenden im Aufnahmeprogramm durchführen möchte. Uns ist sehr an einer langfristigen Kooperation gelegen und wir würden das aktuelle Angebot im Bereich Sprachlernbegleitungen für unsere Austauschschüler*innen gerne noch ausbauen. Solltet ihr also selbst in dem Bereich tätig sein oder Kontakte in die Branche haben, meldet euch gerne bei Magdalene (lindemann@yfu.de).

*USA for you München 2026: Männliche Programmbegleitung gesucht*

15 Jugendliche von Münchener Mittelschulen starten am 24. Oktober 2026 in ein zweiwöchiges Abenteuer in Michigan mit Community Service, Sightseeing und Leben in Gastfamilien. Für die Vor- und Nachbereitung und die Begleitung der Gruppe in die USA suchen wir noch einen männlichen Ehrenamtlichen. Die Ausschreibung findest du hier:  Deutsches Youth For Understanding Komitee e.V. - Intranet

Bei Fragen: Kontaktiere Thekla unter usaforyou@yfu.de oder Durchwahl -77

*USA for you München 2026: Auswahl-Leitung und -Team gesucht*

Für die Auswahlgespräche für USA for you in München am 13. und 14. Juni 2026 suchen wir noch eine Leitung und Team-Mitglieder. Mehr Infos zu USA for you findet ihr hier: [[https://eur05.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.yfu.de%2Fkurzprogramme%2Fusa-for-you&data=05%7C02%7Chh-newsletter%40yfu-deutschland.de%7Cc74b90987e9f4dcb72c708de694e8b49%7C3496a242cb5040ae9566623507dd3c89%7C0%7C0%7C639063983258846677%7CUnknown%7CTWFpbGZsb3d8eyJFbXB0eU1hcGkiOnRydWUsIlYiOiIwLjAuMDAwMCIsIlAiOiJXaW4zMiIsIkFOIjoiTWFpbCIsIldUIjoyfQ%3D%3D%7C0%7C%7C%7C&sdata=FRNlvmHEoGn6ZS4mBGK8DVdV5n6k0EWlRP63GgqPI0w%3D&reserved=0][USA for you]]

Meldet euch bei Interesse gern bei Thekla: usaforyou@yfu.de, Durchwahl -77

*Leitung eines vierwöchigen Sommerkurses für US-amerikanische Austauschschüler*innen*

Du hast vom 25. Juli-21. August 2026 noch nichts vor, hast Erfahrung in der Leitung von Teams sowie in der Jugendarbeit? Englisch beherrscht du im Schlaf und eine Ersthelfer*innen-Ausbildung bringst du auch mit? Dann suchen wir genau 👉dich für die Leitung des PPP-Sprachcamps in Bonn. Das genaue Anforderungsprofil sowie die Aufgabenbeschreibung findest du [[https://eur05.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.yfu.de%2Fueber-yfu%2Fjobs-praktika&data=05%7C02%7Chh-newsletter%40yfu-deutschland.de%7Cc74b90987e9f4dcb72c708de694e8b49%7C3496a242cb5040ae9566623507dd3c89%7C0%7C0%7C639063983258862776%7CUnknown%7CTWFpbGZsb3d8eyJFbXB0eU1hcGkiOnRydWUsIlYiOiIwLjAuMDAwMCIsIlAiOiJXaW4zMiIsIkFOIjoiTWFpbCIsIldUIjoyfQ%3D%3D%7C0%7C%7C%7C&sdata=mzdIfYJtnizrYSxSyFeOTIR5Jd2lzDgQtZoeI%2FpEVBI%3D&reserved=0][hier]].

📧Fragen und Interessensbekundungen schickst du bitte Sophia (ap-seminare@yfu.de).

*Vierwöchiges interkulturelles Training und Betreuung für US-amerikanische Austauschschüler*innen*

Im Sommer reisen 42 PPP-Stipendiat*innen aus den USA für ihren Austausch nach Deutschland. Du hast Lust, sie bei ihren ersten Wochen in Bonn zu begleiten, interkulturelle Trainings durchzuführen, ihnen bei Rat und Tat zur Seite zu stehen sowie ein buntes Rahmenprogramm zu entwerfen? Für den 25. Juli-21. August 2026 steht noch nichts in deinem Kalender 📅 ? Dann komm ins Team des PPP-Sprachcamps 🚀. Die genauen Bewerbungsvoraussetzungen und Aufgabenbeschreibungen findest du [[https://eur05.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.yfu.de%2Fueber-yfu%2Fjobs-praktika&data=05%7C02%7Chh-newsletter%40yfu-deutschland.de%7Cc74b90987e9f4dcb72c708de694e8b49%7C3496a242cb5040ae9566623507dd3c89%7C0%7C0%7C639063983258882839%7CUnknown%7CTWFpbGZsb3d8eyJFbXB0eU1hcGkiOnRydWUsIlYiOiIwLjAuMDAwMCIsIlAiOiJXaW4zMiIsIkFOIjoiTWFpbCIsIldUIjoyfQ%3D%3D%7C0%7C%7C%7C&sdata=DHvi%2BIyNLmfvKMN9bShiIOLXVlCLWwYkYHg9SYLLqvI%3D&reserved=0][hier]] 🔎.

📧Fragen und Interessensbekundungen schickst du bitte Sophia (ap-seminare@yfu.de).

*Der Colored Glasses Vorstand sucht Organisations- und Kommunikationstalent für die ehrenamtliche Koordi-Koordination*

Du hast Lust, die strategische Entwicklung von Colored Glasses mitzugestalten und Verantwortung für die Koordination des ehrenamtlichen Koordi-Teams und das Koordi-Wissensmanagement zu übernehmen? Du bist kommunikativ, verlässlich und bringst idealerweise (nicht zwingend!) Erfahrung als CG-Teamer*in und/oder CG-Koordi mit? Dann schreib uns an vorstand@coloredglasses.de! Alle Details zur Ausschreibung findest du [[https://eur05.safelinks.protection.outlook.com/?url=https%3A%2F%2Fcoloredglasses.de%2Forganisations-und-kommunikationstalent-gesucht%2F&data=05%7C02%7Chh-newsletter%40yfu-deutschland.de%7Cc74b90987e9f4dcb72c708de694e8b49%7C3496a242cb5040ae9566623507dd3c89%7C0%7C0%7C639063983258904282%7CUnknown%7CTWFpbGZsb3d8eyJFbXB0eU1hcGkiOnRydWUsIlYiOiIwLjAuMDAwMCIsIlAiOiJXaW4zMiIsIkFOIjoiTWFpbCIsIldUIjoyfQ%3D%3D%7C0%7C%7C%7C&sdata=Us6dqvo1iGKbx0X%2F1jneFAYgUExcOuvfMa34%2FxSmCtE%3D&reserved=0][hier]]. Für alle Rückfragen stehen wir dir ebenfalls zur Verfügung.

*🚀 Powerstart-Verstärkung gesucht – komm ins Powerstart-Team!*

Unser Powerstart-Team möchte wachsen. Ab sofort suchen wir erfahrene Ehrenamtliche, die sich bei YFU gut auskennen und anderen souverän über das Ehrenamt berichten können. Gerne auch Ehrenamtliche, die schon etwas mehr Lebenserfahrung mitbringen und die Elterngeneration ansprechen können.

Was springt für dich dabei raus?  Du kannst dir deinen Einsatz flexibel nach Absprache einteilen, viele neue Leute kennenlernen, deine Moderationskompetenzen erweitern und hast ein starkes Team an deiner Seite. 💪

Klingt nach einer Aufgabe für dich? Melde dich bei Julia aus der Geschäftsstelle (kastner@yfu.de).
** Schulungen/Termine
*Last Call: Colored Glasses Schulung für neue Ehrenamtliche am 27. Februar bis 01. März in Leipzig - jetzt anmelden!*

Mit Colored Glasses Workshops begeistern wir Kinder und Jugendliche der 5. bis 13. Klasse an Schulen und Jugendeinrichtungen in ganz Deutschland für Vielfalt und Toleranz. Wir machen uns stark gegen Diskriminierung und Vorurteile durch spannende Simulationen und Diskussionen auf Augenhöhe! Die Schulung ist dein Start ins Ehrenamt: Wir zeigen dir, wie du einen Workshop planst und durchführst. Erfahrene Ehrenamtliche geben dir Tipps und Tricks, damit du auch ohne Vorerfahrung einen echten Unterschied machen kannst. Du bist zwischen 16 und 29 Jahre alt und willst aktiv werden? Melde dich bis zum 15.02. zur kostenlosen Schulung am 27.02.-01.03. in der Jugendherberge Leipzig [[https://eur05.safelinks.protection.outlook.com/?url=https%3A%2F%2Fforms.cloud.microsoft%2Fe%2FTyhKWXdhuY&data=05%7C02%7Chh-newsletter%40yfu-deutschland.de%7Cc74b90987e9f4dcb72c708de694e8b49%7C3496a242cb5040ae9566623507dd3c89%7C0%7C0%7C639063983258926319%7CUnknown%7CTWFpbGZsb3d8eyJFbXB0eU1hcGkiOnRydWUsIlYiOiIwLjAuMDAwMCIsIlAiOiJXaW4zMiIsIkFOIjoiTWFpbCIsIldUIjoyfQ%3D%3D%7C0%7C%7C%7C&sdata=LwKDxSoV3M%2BUPKiSYT%2FLR93jGV1kWWQNZUeQrA%2BUV8c%3D&reserved=0][hier]] an. Bei Fragen wenden dich gerne an Nina unter roesch@yfu.de.

*Datenschutz kompakt: Online-Einweisung am Mittwoch, 11. Februar um 18.00 Uhr sowie 10. März um 19 Uhr*

Die nächsten digitalen Datenschutzeinweisungen (ungefähr 45 min.) für Referent*innen, Gremienmitglieder und alle Interessierten finden statt am
- Mittwoch, 11. Februar um 18.00 Uhr
- Dienstag , 10. März um 19.00 Uhr
Wir freuen uns über alle, die dabei sind – gerne auch weitersagen!

Meldet euch unter datenschutz@yfu.de an. Weitere Infos folgen dann per mail. Mehr zum Thema Datenschutz bei YFU findet ihr im [[https://eur05.safelinks.protection.outlook.com/?url=https%3A%2F%2Fintranet.yfu.de%2Fdownloads%2Ffiles%3Fcategory%3D41&data=05%7C02%7Chh-newsletter%40yfu-deutschland.de%7Cc74b90987e9f4dcb72c708de694e8b49%7C3496a242cb5040ae9566623507dd3c89%7C0%7C0%7C639063983258946618%7CUnknown%7CTWFpbGZsb3d8eyJFbXB0eU1hcGkiOnRydWUsIlYiOiIwLjAuMDAwMCIsIlAiOiJXaW4zMiIsIkFOIjoiTWFpbCIsIldUIjoyfQ%3D%3D%7C0%7C%7C%7C&sdata=85%2Faq9iRoY5uGi26JeJvt1JaEjJ8gM8jl%2FVKcUO8tJA%3D&reserved=0][Intranet]]. Unsere aktuellen [[https://eur05.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.yfu.de%2Fdatenschutz&data=05%7C02%7Chh-newsletter%40yfu-deutschland.de%7Cc74b90987e9f4dcb72c708de694e8b49%7C3496a242cb5040ae9566623507dd3c89%7C0%7C0%7C639063983258967646%7CUnknown%7CTWFpbGZsb3d8eyJFbXB0eU1hcGkiOnRydWUsIlYiOiIwLjAuMDAwMCIsIlAiOiJXaW4zMiIsIkFOIjoiTWFpbCIsIldUIjoyfQ%3D%3D%7C0%7C%7C%7C&sdata=UbTwEzJq%2FkAwz%2FINutToMp4TYclR7Z1o51F02FKk1%2Fk%3D&reserved=0][Datenschutzhinweise]] stehen auf unserer Webseite zur Verfügung.
** Sonstiges / Externes
*SAVE THE DATE – Abschlussevent Gastfamilienkampagne am 26. März*
Euer Engagement, eure Offenheit und eure Erfahrungen haben die Kampagne [[https://eur05.safelinks.protection.outlook.com/?url=https%3A%2F%2Faustausch-braucht-gastfamilien.de%2F&data=05%7C02%7Chh-newsletter%40yfu-deutschland.de%7Cc74b90987e9f4dcb72c708de694e8b49%7C3496a242cb5040ae9566623507dd3c89%7C0%7C0%7C639063983258987549%7CUnknown%7CTWFpbGZsb3d8eyJFbXB0eU1hcGkiOnRydWUsIlYiOiIwLjAuMDAwMCIsIlAiOiJXaW4zMiIsIkFOIjoiTWFpbCIsIldUIjoyfQ%3D%3D%7C0%7C%7C%7C&sdata=80N48cbr9WKGXUucZNgwLBYSB2wW3ozuAzbVSqxArOQ%3D&reserved=0][„Offene Türen, offene Herzen – Austausch braucht Gastfamilien“]] getragen und lebendig gemacht. Zum Abschluss der Kampagne laden der AJA und seine Mitgliedsorganisationen euch herzlich zu einer Online-Veranstaltung ein, bei der wir gemeinsam Bilanz ziehen, zurückblicken, voneinander lernen und nach vorn schauen.

📅 Donnerstag, 26. März 2026, 🕕 18:00–19:45 Uhr, 💻 via Zoom

Wir freuen uns sehr, wenn Ihr euch die Zeit nehmt und eure Erfahrungen, Gedanken und Ideen einbringt.  Anmeldung unter: https://us06web.zoom.us/meeting/register/mFrPO6xCTgKYGA3jHJi1dQ

*Die DSEE fördert Mitmach-Aktionen zum Ehrentag*

„Der Ehrentag wird durch vielfältige Aktionen lebendig, bei denen Menschen zusammenkommen, sich kennenlernen und gemeinsam anpacken. Und alle können mitmachen: Ob Einzelperson, Initiative, Verein oder Kommune.“ (DSEE) Sei dabei und starte deine Aktion: für deine YFU-Landesgruppe, für Colored Glasses oder für ein anderes Projekt, das dir am Herzen liegt. Mitmach-Aktionen zum Ehrentag im Zeitraum vom 16. bis 31. Mai 2026 werden mit bis zu bis zu 500€ gefördert. Bewerbung ab sofort [[https://eur05.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.ehrentag.de%2Ffoerderprogramm%2F&data=05%7C02%7Chh-newsletter%40yfu-deutschland.de%7Cc74b90987e9f4dcb72c708de694e8b49%7C3496a242cb5040ae9566623507dd3c89%7C0%7C0%7C639063983259029200%7CUnknown%7CTWFpbGZsb3d8eyJFbXB0eU1hcGkiOnRydWUsIlYiOiIwLjAuMDAwMCIsIlAiOiJXaW4zMiIsIkFOIjoiTWFpbCIsIldUIjoyfQ%3D%3D%7C0%7C%7C%7C&sdata=aCMtXMB8yuRY%2FYaDuoO7CZjJ05sqFbrGJOF0YnQ3l50%3D&reserved=0][hier]]. Bewerbungsberechtigt sind Einzelpersonen, die für sich selbst oder im Namen von gemeinnützigen Organisationen ihre Aktionsidee einreichen.
* Terminübersicht
** TERMINE 2026
*27.02. - 01.03.2026* &nbsp;&nbsp;&nbsp; Colored Glasses Schulung, Jugendherberge *Leipzig*

*20.03. - 22.03.2026* &nbsp;&nbsp;&nbsp; Gremiensitzung Frühjahr, Jugendherberge Horner Rennbahn *Hamburg*

*27.03. - 29.03.2026* &nbsp;&nbsp;&nbsp; Betreuendenseminar in *Bad Bevensen*

*15.05. - 17.05.2026* &nbsp;&nbsp;&nbsp; Colored Glasses Schulung, Jugendherberge Burg Schwaneck (*bei München*)

*29.05 - 31.05.2026* &nbsp;&nbsp;&nbsp; ÖA-Ausschusstreffen

*05.06. - 07.06.2026* &nbsp;&nbsp;&nbsp; *(LG)* Nord-LGT

*20.06. - 21.06.2026* &nbsp;&nbsp;&nbsp; Colored Glasses Schulung, Liebfrauenschule Mühlhausen (*bei Duisburg*)

*18.09. -20.09. 2026* &nbsp;&nbsp;&nbsp; Colored Glasses Schulung, Jugendherberge Horner Rennbahn *Hamburg*

*25.09. - 27.09.2026* &nbsp;&nbsp;&nbsp; *(LG)* Aktivenwochenende

*02.10. - 04.10.2026*  &nbsp;&nbsp;&nbsp; Seminarleitungsschulung (SLS), Jugendherberge *Kassel*

*06.11. – 08.11.2026* &nbsp;&nbsp;&nbsp; Colored Glasses Schulung, Jugendherberge *Kassel*

*27.11. - 29.11.2026* &nbsp;&nbsp;&nbsp; ÖA-Ausschusstreffen
