* Landesgruppe
**  Wichtige Info Aufrufe Newsletter
Diesen Newsletter findet ihr ab jetzt auch auf Whatsapp! Dafür einfach über diesen Link beitreten: https://chat.whatsapp.com/GBCBuLIU2U78zpim5yGxLF
---

Sehr gerne nehmen wir eure Aufrufe oder Danksagungen in den wöchentlichen Newsletter auf.

Schreibt mir ([[mailto://shh-newsletter@yfu-deutschland.de][shh-newsletter@yfu-deutschland.de]]) dafür einfach immer bis *Mittwochs 17:00 Uhr* eure Aufrufe, damit ich sie noch in den Newsletter der aktuellen Woche mit aufnehmen kann. Ansonsten nehme ich die Aufrufe natürlich gerne in den nächsten auf.

Vielen lieben Dank und ich freue mich auf eure Emails.

Liebe Grüße
Aimo
* Entsendeprogramm
** Teamende für Goee-Treffen im Februar und März gesucht
Hei,

Ich suche aktuell einige Teamende, die Lust haben im Februar und März Treffen für Goees in Hamburg und/oder Schleswig-Holstein zu teamen. Die bisher durchgeführten Spieleabende kamen bei den Teilnehmenden sehr gut an. Terminlich seid ihr relativ flexibel solange die Termine in den Zeitraum von Februar bis Ende März liegen. Falls ihr darauf Lust hättet oder eine andere Idee für eine schöne Spaßveranstaltung für die Goees zum Kennenlernen habt meldet euch sehr gerne bei mir unter caren.bremer@yfu-deutschland.de

Liebe Grüße
Caren
* Externes und Überregionales
** Mitarbeiter-Gesuche/Stellen 
*Dringend Gastfamilie in und um Schwäbisch-Hall gesucht*

Seit letzten August verbringt Zeynep (16 Jahre) aus der Türkei ihr Austauschjahr in Deutschland und geht in Schwäbisch Hall zur Schule. Nun hat sich die berufliche Situation in ihrer aktuellen Gastfamilie geändert, so dass sie Zeynep leider nur noch bis spätestens Mitte Februar bei sich aufnehmen können. Weil es Zeynep vor Ort gut gefällt und sie schon Freund*innen gefunden hat, würde sie gerne in der Nähe bleiben. Um ihr das zu ermöglichen, suchen wir vor allem in Schwäbisch Hall und Umgebung nach einer neuen Familie für Zeynep, die sie *spätestens ab Mitte Februar bis zu ihrer Heimreise Ende Juni* bei sich aufnehmen möchte – und freuen uns über Unterstützung aus der YFU-Community! Ihr kennt Menschen in der Region? Dann leitet ihnen gern diesen Aufruf und [[https://eur05.safelinks.protection.outlook.com/ap/b-59584e83/?url=https%3A%2F%2Fyfuit.sharepoint.com%2F%3Ab%3A%2Ft%2FGSexterngeteilteDateien%2FIQC7M16m8DKPRrEru1eN4iYLAXvG7YZXwC7THPBOVTd7DdU%3Fe%3D5F88gv&data=05%7C02%7Chh-newsletter%40yfu-deutschland.de%7Ce3d5abd0cba14ed74a0208de53549bf0%7C3496a242cb5040ae9566623507dd3c89%7C0%7C0%7C639039820034679793%7CUnknown%7CTWFpbGZsb3d8eyJFbXB0eU1hcGkiOnRydWUsIlYiOiIwLjAuMDAwMCIsIlAiOiJXaW4zMiIsIkFOIjoiTWFpbCIsIldUIjoyfQ%3D%3D%7C0%7C%7C%7C&sdata=neYva3pkQ1IjvSCK6Gmj3e2DXvwISFuwNpqSR5f%2Bvm0%3D&reserved=0][pdf-Symbol Link zu Zeyneps Kurzprofil]] weiter! Oder vielleicht lebt ihr selbst dort und habt Platz für ein weiteres Familienmitglied auf Zeit? Dann meldet euch gern direkt beim AP-Team der YFU-Geschäftsstelle (gastfamilien@yfu.de), das euch auch gern eure Fragen zu Zeynep beantwortet.😊 Tausend Dank für eure Unterstützung!

*Zwei Teammitglieder für das Mittelseminar 1 Süd gesucht 🔎*

Du wolltest schon immer einmal Sissis Elternhaus besichtigen? Oder einfach ein paar Tage im wunderschönen Possenhofen verbringen? Dann haben wir genau das Richtige für dich!
Das *Mittelseminar 1 Süd* sucht noch *zwei engagierte Personen* zur Verstärkung des Teams.
Idealerweise *eine männliche Person* sowie *eine erfahrene Person*.
📅 Wann? 22.02. - 27.02.2026
📍 Wo? Jugendherberge Possenhofen, direkt bei München
Ein tolles Team und eine motivierte Gruppe Austauschschüler*innen freuen sich auf dich!

*KLT-Schulung am 28.01. um 19:30 Uhr*

Hallo in die Runde, neues Jahr, neue Sachen im Ehrenamt? Das kalte, schneehaltige Wetter lädt doch sehr dazu ein, sich mit einem warmen Tee in die eigenen vier Wände zu setzen und ein Kennenlerntreffen (KLT) zu teamen – oder? 🙂
Deshalb bieten wir am *28.01. um 19:30 Uhr* wieder eine KLT-Schulung via Teams an. Diese benötigt ihr, um KLTs zu teamen.
Du möchtest dabei sein? Dann schreibe gerne eine Mail an celine.huener@yfu.de!

*Noch viele freie Plätze im USA-Programm: Sagt’s gerne weiter!*

Anders als in der Vergangenheit haben wir zum jetzigen Zeitpunkt noch viele freie Plätze in unserem USA-Programm für 2026/27 – und seit kurzem auch ein USA-Halbjahr im Angebot! Angesichts der derzeit oft turbulenten Nachrichten aus den USA haben wir häufig gestellte Fragen unter https://www.yfu.de/faq-usa beantwortet – mit dem Fazit, dass man in den USA immer noch eine großartige Austauscherfahrung machen kann und Politik im Alltag oft keine große Rolle spielt. Wenn ihr Jugendliche kennt, die vielleicht Interesse haben: Ermutigt sie gerne, sich noch zu bewerben!

*Lehrkräfte, Ehrenamtliche und Studis in Rhein-Ruhr aufgepasst: Colored Glasses kooperiert mit der Uni Köln*

Im Sommersemester 2026 können Studierende der Uni Köln im Rahmen eines [[https://eur05.safelinks.protection.outlook.com/?url=https%3A%2F%2Fprofessionalcenter.uni-koeln.de%2Flehre%2Fservice-learning&data=05%7C02%7Chh-newsletter%40yfu-deutschland.de%7Ce3d5abd0cba14ed74a0208de53549bf0%7C3496a242cb5040ae9566623507dd3c89%7C0%7C0%7C639039820034724166%7CUnknown%7CTWFpbGZsb3d8eyJFbXB0eU1hcGkiOnRydWUsIlYiOiIwLjAuMDAwMCIsIlAiOiJXaW4zMiIsIkFOIjoiTWFpbCIsIldUIjoyfQ%3D%3D%7C0%7C%7C%7C&sdata=Yj7LSsfjugYXZZ1poqoGy0ql1Eh1rar%2B3fedlxP7zvI%3D&reserved=0][Service Learning Seminars]] 3 Leistungspunkte für ihr Engagement mit Colored Glasses erhalten. Damit dieses Pilotprojekt ein Erfolg wird, brauchen wir euch: Um für die Studis passende Workshopanfragen zu haben, brauchen wir insbesondere in Köln und Umgebung von Mitte Mai bis Ende Juli Workshopanfragen von Schulen – am besten nicht nur direkt vor den Sommerferien. Alle Details zu den CG-Workshops gibt’s [[https://eur05.safelinks.protection.outlook.com/?url=https%3A%2F%2Fcoloredglasses.de%2Finfos-fuer-lehrende-2%2Fworkshop-konzept%2F&data=05%7C02%7Chh-newsletter%40yfu-deutschland.de%7Ce3d5abd0cba14ed74a0208de53549bf0%7C3496a242cb5040ae9566623507dd3c89%7C0%7C0%7C639039820034738165%7CUnknown%7CTWFpbGZsb3d8eyJFbXB0eU1hcGkiOnRydWUsIlYiOiIwLjAuMDAwMCIsIlAiOiJXaW4zMiIsIkFOIjoiTWFpbCIsIldUIjoyfQ%3D%3D%7C0%7C%7C%7C&sdata=vf70VZVRQjYAB7YyofuRMF7cK3kdvHG7%2BIOAVjS0GjA%3D&reserved=0][hier]]. Außerdem suchen wir YFU/CG-erfahrene Ehrenamtliche, die in dieser Zeit zur Verfügung stehen, um gemeinsam mit den „Neuen“ die Workshops an Schulen durchzuführen. Schließlich sind besonders Studierende der Uni Köln, die bereits bei YFU aktiv sind, eingeladen, diese Chance zu ergreifen und sich ihr Ehrenamt noch zusätzlich im Studium anrechnen zu lassen! Du hast Lust, uns hier auf die eine oder andere Art zu unterstützen? Schreib schon jetzt Nina unter roesch@yfu.de für weitere Details und Rückfragen.

** Schulungen/Termine
*Betreuungsluft schnuppern? Jetzt zur Co-Betreuungsschulung/Refresh für Betreuende anmelden*

Ihr habt Lust eine Co-Betreuung für Austauschschüler*innen und Gastfamilien in Deutschland zu übernehmen oder möchtet euer Wissen im Bereich Betreuung auffrischen? Dann meldet euch für die Online-Schulung am 3. Februar 2026 an.
📅Dienstag, 3.2. um 19 Uhr für ca. 3 Stunden
📍Online
🦸‍♀️Trainerinnen: Caren Spamer & Ines Hintz
✅ Anmeldung: [[https://eur05.safelinks.protection.outlook.com/?url=https%3A%2F%2Fforms.office.com%2FPages%2FResponsePage.aspx%3Fid%3DQqKWNFDLrkCVZmI1B908iS2FBzkZ3HdJtoS0ZOggvE5UOTM4NTlNSlRBOTNaQjVHV0E0NzJTVzRMTC4u&data=05%7C02%7Chh-newsletter%40yfu-deutschland.de%7Ce3d5abd0cba14ed74a0208de53549bf0%7C3496a242cb5040ae9566623507dd3c89%7C0%7C0%7C639039820034751510%7CUnknown%7CTWFpbGZsb3d8eyJFbXB0eU1hcGkiOnRydWUsIlYiOiIwLjAuMDAwMCIsIlAiOiJXaW4zMiIsIkFOIjoiTWFpbCIsIldUIjoyfQ%3D%3D%7C0%7C%7C%7C&sdata=IWA9iX1%2BC%2BXrtNc9OcL7YWYaQn3GwniApFYWYiiCB90%3D&reserved=0][Anmeldung zur Co-Betreuungsschulung/Refresh für Betreuende]]
Ihr habt Fragen dazu? Meldet euch bei Magdalene (lindemann@yfu.de).

*Colored Glasses Schulung für neue Ehrenamtliche am 27. Februar bis 01. März in Leipzig - jetzt anmelden!*

Mit Colored Glasses Workshops begeistern wir Kinder und Jugendliche der 5. bis 13. Klasse an Schulen und Jugendeinrichtungen in ganz Deutschland für Vielfalt und Toleranz. Wir machen uns stark gegen Diskriminierung und Vorurteile durch spannende Simulationen und Diskussionen auf Augenhöhe! Die Schulung ist dein Start ins Ehrenamt: Wir zeigen dir, wie du einen Workshop planst und durchführst. Du bekommst alle Materialien, um mehr zum Thema zu lernen. Erfahrene Ehrenamtliche geben dir Tipps und Tricks, damit du auch ohne Vorerfahrung einen echten Unterschied machen kannst. Du bist zwischen 16 und 29 Jahre alt und willst aktiv werden? *Melde dich jetzt zur kostenlosen Schulung am 27.02.-01.03. in der Jugendherberge Leipzig [[https://eur05.safelinks.protection.outlook.com/?url=https%3A%2F%2Fforms.cloud.microsoft%2Fe%2FTyhKWXdhuY&data=05%7C02%7Chh-newsletter%40yfu-deutschland.de%7Ce3d5abd0cba14ed74a0208de53549bf0%7C3496a242cb5040ae9566623507dd3c89%7C0%7C0%7C639039820034766698%7CUnknown%7CTWFpbGZsb3d8eyJFbXB0eU1hcGkiOnRydWUsIlYiOiIwLjAuMDAwMCIsIlAiOiJXaW4zMiIsIkFOIjoiTWFpbCIsIldUIjoyfQ%3D%3D%7C0%7C%7C%7C&sdata=aGMr%2BWdxrEmDUNrX40olOI%2B6dMoMg4g0eBT7hxeDTV0%3D&reserved=0][hier]] an*. Du bist bereits YFU-erfahren und hast Interesse an einer CG-Kurzschulung? Lass es uns [[https://eur05.safelinks.protection.outlook.com/?url=https%3A%2F%2Fforms.cloud.microsoft%2Fe%2F142QZB212a&data=05%7C02%7Chh-newsletter%40yfu-deutschland.de%7Ce3d5abd0cba14ed74a0208de53549bf0%7C3496a242cb5040ae9566623507dd3c89%7C0%7C0%7C639039820034778938%7CUnknown%7CTWFpbGZsb3d8eyJFbXB0eU1hcGkiOnRydWUsIlYiOiIwLjAuMDAwMCIsIlAiOiJXaW4zMiIsIkFOIjoiTWFpbCIsIldUIjoyfQ%3D%3D%7C0%7C%7C%7C&sdata=D3nn2HbizsZmLWw9%2BAfQ6xAMkp1gaEYoksHc8YD0IL4%3D&reserved=0][über diese Umfrage]] wissen! Bei Fragen wenden dich gerne an Nina unter roesch@yfu.de.
** Sonstiges / Externes
*Mit YFU Polen nach Krakau und Danzig*

YFU Polen bietet im Frühjahr wieder zwei Trips nach Krakau und Danzig an.
Die Ausschreibungen mit Infos findet ihr hier:
- [[https://newsletter-shh.github.io/media/Cracow.pdf][Cracow]]
- [[https://newsletter-shh.github.io/media/Gdansk.pdf][Gdanks]]
Anmeldefrist ist der 18. Januar.
* Terminübersicht
** TERMINE 2026
*30.01. - 02.02.2026* &nbsp;&nbsp;&nbsp; Seminarleitungsschulung (SLS) Jugendherberge Horner Rennbahn *Hamburg*

*31.01. - 01.02.2026* &nbsp;&nbsp;&nbsp; *(LG)* Referent*innen/ Landesgruppenwochenende *in Kiel* (Anmeldung für alle offen)

*27.02. - 01.03.2026* &nbsp;&nbsp;&nbsp; Colored Glasses Schulung, Jugendherberge *Leipzig*

*20.03. - 22.03.2026* &nbsp;&nbsp;&nbsp; Gremiensitzung Frühjahr, Jugendherberge Horner Rennbahn *Hamburg*

*27.03. - 29.03.2026* &nbsp;&nbsp;&nbsp; Betreuendenseminar in *Bad Bevensen*

*15.05. - 17.05.2026* &nbsp;&nbsp;&nbsp; Colored Glasses Schulung, Jugendherberge Burg Schwaneck (*bei München*)

*29.05 - 31.05.2026* &nbsp;&nbsp;&nbsp; ÖA-Ausschusstreffen

*05.06. - 07.06.2026* &nbsp;&nbsp;&nbsp; *(LG)* Nord-LGT

*20.06. - 21.06.2026* &nbsp;&nbsp;&nbsp; Colored Glasses Schulung, Liebfrauenschule Mühlhausen (*bei Duisburg*)

*18.09. -20.09. 2026* &nbsp;&nbsp;&nbsp; Colored Glasses Schulung, Jugendherberge Horner Rennbahn *Hamburg*

*25.09. - 27.09.2026* &nbsp;&nbsp;&nbsp; *(LG)* Aktivenwochenende

*02.10. - 04.10.2026*  &nbsp;&nbsp;&nbsp; Seminarleitungsschulung (SLS), Jugendherberge *Kassel*

*06.11. – 08.11.2026* &nbsp;&nbsp;&nbsp; Colored Glasses Schulung, Jugendherberge *Kassel*

*27.11. - 29.11.2026* &nbsp;&nbsp;&nbsp; ÖA-Ausschusstreffen
