* Landesgruppe
**  Wichtige Info Aufrufe Newsletter
Diesen Newsletter findet ihr ab jetzt auch auf Whatsapp! Dafür einfach über diesen Link beitreten: https://chat.whatsapp.com/GBCBuLIU2U78zpim5yGxLF
---

Sehr gerne nehmen wir eure Aufrufe oder Danksagungen in den wöchentlichen Newsletter auf.

Schreibt mir ([[mailto://shh-newsletter@yfu-deutschland.de][shh-newsletter@yfu-deutschland.de]]) dafür einfach immer bis *Mittwochs 17:00 Uhr* eure Aufrufe, damit ich sie noch in den Newsletter der aktuellen Woche mit aufnehmen kann. Ansonsten nehme ich die Aufrufe natürlich gerne in den nächsten auf.

Vielen lieben Dank und ich freue mich auf eure Emails.

Liebe Grüße
Aimo
** Communitea Anmeldung
Liebe Community,

wir haben wieder Neuigkeiten! 🐣
Wir möchten euch herzlich zu einem frühlingshaften Communitea-Treffen einladen. Gemeinsam wollen wir mit den Austauschschüler*innen ein bisschen Ostern feiern und einen entspannten Nachmittag miteinander verbringen.

📅 Wann? 3. April, um 11 Uhr 
📍 Wo? Geschäftsstelle

Wir wollen gemeinsam Ostereier bemalen und die Frühlingszeit einläuten. Wer mag, kann außerdem gerne Snacks oder andere Kleinigkeiten zum Teilen mitbringen. Außerdem wäre es hilfreich, wenn alle bereits ausgepustete Eier mitbringen könnten.

Wenn ihr dabei seid, meldet euch bitte kurz [[https://forms.office.com/?redirecturl=https%3a%2f%2fforms.office.com%2fPages%2fDesignPageV2.aspx%3fsubpage%3ddesign%26FormId%3dQqKWNFDLrkCVZmI1B908iefgPGIVnodAt7lfuSHL-ZJUNjUyWFpBUzhIUVFMOU1YVllNRVZFSFJHWS4u&auth_pvr=OrgId][hier]] an.
Wir freuen uns auf euch und auf ein gemütliches Treffen!

Liebe Grüße 
Leah, Aimo und Ole
** SAVE THE DATE: 5.- 7. JUNI, NORD-LGT 2026
Liebe Landesgruppe,

Das YFU-Sommerloch lauert (noch weit entfernt) am Horizont, doch hier kommt eure Rettung: Das Nord-LGT 2026 vom 5.-7. Juni im Victor-Andresen-Haus in Pinneberg ​! Die offizielle Anmeldung folgt noch im April, aber streicht euch den Termin am besten schon jetzt im Kalender an!

Solltet ihr davor schon Fragen haben, könnt ihr euch gerne unter nordlgt@lists.yfu-deutschland.de melden.

Wir freuen uns auf euch!
Euer Nord-LGT-Planungsteam
* Öffentlichkeitsarbeit
** Neue Infos
Liebe Landesgruppe,

bald sind die Märzferien vorbei und wir suchen wieder eure Unterstützung.
Wenn ihr Zeit und Lust habt meldet euch gerne bei [[mailto:sophie.schnipkoweit@yfu-deitschland.de][sophie.schnipkoweit@yfu-deitschland.de]] oder bei [[mailto:kira.thede@yfu-deutschland.de][kira.thede@yfu-deutschland.de]]
** Schulvortrag am Gymnasium Brunsbüttel
Wann: Flexible Absprache mit Ansprechpartner der Schule

Wo:
Gymnasium Brunsbüttel
Kopernikusstr. 1
25541 Brunsbüttel

Wer: 2-3 erfahrene und unerfahrene Personen
** Schulvortrag am Gymnasium Farmsen
Wann: Am 14.04.2026; Beginn um 18 Uhr

Wo:
Gymnasium Farmsen
Swebenhöhe 50
22159 Hamburg

Wer: 1-2 erfahrene sowie unerfahrene Personen 

Meldet euch hier gerne bei Kira (kira.thede@yfu-deutschland.de)
** Schulvortrag am Johanneum Lüneburg
Wann: 23.04.2026, Vormittags

Wo:
Johanneum Lüneburg
Theodor-Heuss-Str. 1
21337 Lüneburg

Wer: 2-3 erfahrene und unerfahrene Personen 
* Aufnahmeprogramm
** Teamende für die ATS-Spaßveranstalltung
Liebe Ehrenamtliche im Aufnahmeprogramm,

beim letzten Communitea-Treffen waren viele Austauschschülerinnen dabei – was uns natürlich sehr gefreut hat! Gleichzeitig haben wir gemerkt, dass ein paar mehr Ehrenamtliche schön gewesen wären, um sich besser zu mischen, ins Gespräch zu kommen und gemeinsam Aktivitäten zu machen.

Deshalb möchten wir euch herzlich einladen, beim nächsten Communitea-Treffen dabei zu sein und ein bisschen Zeit mit den Austauschschülerinnen zu verbringen.

📅 Wann? 3. April, um 11 Uhr 
📍 Wo? Geschäftsstelle

Wir wollen gemeinsam Ostereier bemalen, uns austauschen und einen gemütlichen Vormittag verbringen. Wer möchte, kann außerdem gerne Snacks oder andere Kleinigkeiten zum Teilen mitbringen. Außerdem wäre es hilfreich, wenn alle bereits ausgepustete Eier mitbringen könnten.

Wenn ihr Zeit und Lust habt, vorbeizukommen, meldet euch bitte kurz [[https://forms.office.com/?redirecturl=https%3a%2f%2fforms.office.com%2fPages%2fDesignPageV2.aspx%3fsubpage%3ddesign%26FormId%3dQqKWNFDLrkCVZmI1B908iefgPGIVnodAt7lfuSHL-ZJUNjUyWFpBUzhIUVFMOU1YVllNRVZFSFJHWS4u&auth_pvr=OrgId][hier]] an. Wir freuen uns sehr über jede*n, der oder die dabei ist!

Liebe Grüße 
Leah, Aimo und Ole
* Externes und Überregionales
** Mitarbeiter-Gesuche/Stellen
*Leitung eines vierwöchigen Sommerkurses für US-amerikanische Austauschschüler*innen*
Du hast vom 25. Juli-21. August 2026 noch nichts vor, hast Erfahrung in der Leitung von Teams sowie in der Jugendarbeit? Englisch beherrscht du im Schlaf und eine Ersthelfer*innen-Ausbildung bringst du auch mit? Dann suchen wir genau 👉dich für die Leitung des PPP-Sprachcamps in Bonn. Das genaue Anforderungsprofil sowie die Aufgabenbeschreibung findest du [[https://www.yfu.de/ueber-yfu/jobs-praktika][hier]].
📧Fragen und Interessensbekundungen schickst du bitte Sophia (ap-seminare@yfu.de).

*Vierwöchiges interkulturelles Training und Betreuung für US-amerikanische Austauschschüler*innen*
Im Sommer reisen 42 PPP-Stipendiat*innen aus den USA für ihren Austausch nach Deutschland. Du hast Lust, sie bei ihren ersten Wochen in Bonn zu begleiten, interkulturelle Trainings durchzuführen, ihnen bei Rat und Tat zur Seite zu stehen sowie ein buntes Rahmenprogramm zu entwerfen? Für den 25. Juli-21. August 2026 steht noch nichts in deinem Kalender 📅 ? Dann komm ins Team des PPP-Sprachcamps 🚀. Die genauen Bewerbungsvoraussetzungen und Aufgabenbeschreibungen findest du [[https://www.yfu.de/ueber-yfu/jobs-praktika][hier]] 🔎.
📧Fragen und Interessensbekundungen schickst du bitte Sophia (ap-seminare@yfu.de).

*Germany for you: Programmbegleitung vom 13. bis 28. Juni 2026 in Halle (Saale) gesucht (Honorarvertrag)*
Für das Germany for you-Programm suchen wir eine Programmbegleitung (m/w/d), die gemeinsam mit einer amerikanischen Programmbegleitung und weiteren Ehrenamtlichen vor Ort in Halle eine Gruppe von 15 Jugendlichen aus den USA bei einem bunten Programm aus ehrenamtlichem Einsatz, Sightseeing (in Halle und Berlin), Sprachkurs und Sportprogramm begleitet.
Mehr Infos hier: https://intranet.yfu.de/article_tool/articles/2220
Meldet euch bei Interesse gern bei Thekla: germanyforyou@yfu.de, Durchwahl -77

*USA for you Sachsen-Anhalt: Co-Leitung/erfahrenes Team-Mitglied für den 9.5. gesucht*
Für die Auswahl der USA for you-Gruppe am 9. Mai 2026 in Halle (Saale) suchen wir noch eine Co-Leitung oder ein erfahrenes Team-Mitglied. 
Melde dich gern bei Thekla: usaforyou@yfu.de, Durchwahl -77

*USA for you München 2026: Männliche Programmbegleitung gesucht*
15 Jugendliche von Münchener Mittelschulen starten am 24. Oktober 2026 in ein zweiwöchiges Abenteuer in Michigan mit Community Service, Sightseeing und Leben in Gastfamilien. Für die Vor- und Nachbereitung und die Begleitung der Gruppe in die USA suchen wir noch einen männlichen Ehrenamtlichen. Die Ausschreibung findest du hier: https://intranet.yfu.de/article_tool/articles/2217
Bei Fragen: Kontaktiere Thekla unter usaforyou@yfu.de oder Durchwahl -77

*Die OWOs rufen! Bist du dabei?*
Du hast Lust auf Seminare im Aufnahmeprogramm? Du möchtest Austauschschüler*innen bei ihrem Start in ihr Austauschjahr unterstützen und sie für das Zusammenleben mit ihrer Gastfamilie wappnen? Du kennst dich mit Kommunikation und Kultur super aus und hast im August 2026 noch etwas Zeit? Dann brauchen wir genau dich als Leitung oder Teamer*in für die OWOs! Melde dich gerne bei Mareen (📧 ap-seminare@yfu.de) oder fülle diese Umfrage aus. Alle weiteren Infos findest du hier.

*Teamende mit Erfahrung für VBT in Mühlhausen gesucht*
- Für die MD-VBT vom 14.04.-19.04. suchen wir noch 3 Teamende mit Erfahrung
- Es gibt bereits ein Leitungsteam, dass noch Unterstützung sucht
- Bitte meldet euch unter vbt@yfu.de
*Teamende mit Erfahrung für VBT in Lauenburg gesucht*
- Für die SHH-VBT vom 20.04.-25.04. suchen wir noch 4 Teamende mit Erfahrung
- Es gibt bereits ein Leitungsteam, dass noch Unterstützung sucht
- Bitte meldet euch unter vbt@yfu.de
*Team für Nordost-VBT nächste Woche gesucht*
Für unsere zweite NO-VBT (08.04. (Anreise Team) – 13.04.26 in Lauenburg) suchen wir aufgrund von Absagen erneut nach Teammitgliedern. Wir freuen uns über Teammitglieder aller Geschlechter und Erfahrungsgrade, suchen aber insbesondere noch mindestens einen volljährigen männlichen Teamer. Solltet ihr Lust und Zeit haben, auf eine der VBTs zu fahren meldet euch gerne direkt bei mir (theodor.barkow@yfu-deutschland.de) oder vbt@yfu.de. Solltet ihr Fragen zu Teilnahme haben, oder nur ein Interesse bekunden wollen, ohne fest zuzusagen, dann schreibt ebenfalls.

*👑 Werde Teil des Trainierenden-Teams beim Training of Trainers (ToT) vom 25.-27.09. in Wiesbaden!*
Du hast Erfahrung als Workshop-Gebende*r, fühlst dich sicher in der Methodenauswahl und hast Strategien parat, mit Herausforderungen in der Workshop-Durchführung umzugehen. Du möchtest dein Expert*innen-Wissen und deine Erfahrung als Trainer*in an YFU-Ehrenamtliche weitergeben? Dann werde Teil des Trainierenden-Teams für das nächste ToT vom 25.-27. September 2026 in Wiesbaden und unterstütze andere dabei, selbst Workshops und Schulungen geben zu können. Lust bekommen oder Fragen? Dann melde dich bei Rahel (perschke@yfu.de, +49 40 22 70 02 44) aus der Geschäftsstelle.
** Schulungen / Termine
*Online-KLT-Schulung am 14.04. um 19:30 Uhr – jetzt anmelden!*
Bewerbende für den nächsten YFU-Jahrgang kennenlernen und dabei von euren eigenen Erfahrungen berichten – das könnt ihr bei den digitalen Kennenlerntreffen (KLTs)! Eine etwa anderthalbstündige Online-Schulung dafür wird am Dienstag, den 14.04. um 19:30 Uhr angeboten. Bei Interesse meldet euch unter kennenlernen@yfu.de – wir freuen uns auf euch!
** Sonstiges / Externes
*Neue Grafiken für die EP-Promo*
Im Download-Bereich des Intranets warten neue Grafiken darauf, in eurem WhatsApp Status oder eurer Insta Story gepostet zu werden, um das EP noch sichtbarer zu machen. Ihr findet sie unter: „Öffentlichkeitsarbeit“ → „Slides für WhatsApp und Instagram“: intranet.yfu.de/downloads/files?category=203
* Terminübersicht
** TERMINE 2026
*08.05. - 10.05.2026* &nbsp;&nbsp;&nbsp; Interessenseminar-Lateinamerika (ILSA), *in Rinteln*

*15.05. - 17.05.2026* &nbsp;&nbsp;&nbsp; Colored Glasses Schulung, Jugendherberge Burg Schwaneck (*bei München*)

*29.05 - 31.05.2026* &nbsp;&nbsp;&nbsp; ÖA-Ausschusstreffen, *Hamburg*

*05.06. - 07.06.2026* &nbsp;&nbsp;&nbsp; *(LG)* Nord-LGT

*13.06. - 13.06.2026* &nbsp;&nbsp;&nbsp; Betreuungsschulung, *Berlin*

*20.06. - 21.06.2026* &nbsp;&nbsp;&nbsp; Colored Glasses Schulung, Liebfrauenschule Mühlhausen (*bei Duisburg*)

*18.09. -20.09. 2026* &nbsp;&nbsp;&nbsp; Colored Glasses Schulung, Jugendherberge Horner Rennbahn *Hamburg*

*25.09. - 27.09.2026* &nbsp;&nbsp;&nbsp; *(LG)* Aktivenwochenende

*02.10. - 04.10.2026*  &nbsp;&nbsp;&nbsp; Seminarleitungsschulung (SLS), Jugendherberge *Kassel*

*06.11. – 08.11.2026* &nbsp;&nbsp;&nbsp; Colored Glasses Schulung, Jugendherberge *Kassel*

*20.11. - 22.11.2026* &nbsp;&nbsp;&nbsp; Betreuendenseminar, *Jugendherberge Stuttgart*

*27.11. - 29.11.2026* &nbsp;&nbsp;&nbsp; ÖA-Ausschusstreffen, *Hamburg*
