* Landesgruppe
**  Wichtige Info Aufrufe Newsletter
Diesen Newsletter findet ihr ab jetzt auch auf Whatsapp! Dafür einfach über diesen Link beitreten: https://chat.whatsapp.com/GBCBuLIU2U78zpim5yGxLF
---

Sehr gerne nehmen wir eure Aufrufe oder Danksagungen in den wöchentlichen Newsletter auf.

Schreibt mir ([[mailto://shh-newsletter@yfu-deutschland.de][shh-newsletter@yfu-deutschland.de]]) dafür einfach immer bis *Mittwochs 17:00 Uhr* eure Aufrufe, damit ich sie noch in den Newsletter der aktuellen Woche mit aufnehmen kann. Ansonsten nehme ich die Aufrufe natürlich gerne in den nächsten auf.

Vielen lieben Dank und ich freue mich auf eure Emails.

Liebe Grüße
Aimo
** Einladung zum Nord-LGT 2026
Liebe Nord-LGs,
Wir konnten es alle kaum abwarten, aber jetzt ist es endlich so weit: das nächste Nord-LGT steht an! Wir freuen uns auf ein sommerliches Wochenende mit euch in Barmstedt bei Pinneberg (keine Sorge, das ist vom Hamburger Hauptbahnhof gut mit der Bahn erreichbar) mit vielen tollen Workshops, einem unterhaltsamen Programm und Zeit dafür, alte und neue Bekanntschaften wiederzusehen.

Wann? 05.-07..06.2026
Wo? Victor-Andersen-Haus Pinneberg (Düsterlohe 5, 25355 Barmstedt )
 
Meldet euch ab jetzt bis Mitte Mai über diesen Link an: [[https://forms.cloud.microsoft/e/JQQUuacHDj][Nord-LGT 2026 – Formular ausfüllen]]
Die Plätze sind begrenzt, also meldet euch schnell an. Anmeldeschluss ist der 15.05.2026.

Wir haben dieses Jahr eine Teilnahmegebühr von 20€. Solltet ihr Schwierigkeiten haben, diese zu erbringen, meldet euch gerne per Mail bei uns und wir finden eine Lösung dafür. Fahrtkosten erstatten wir für alle, die wollen, bis zu 30€, wenn ihr günstig und früh bucht. Das heißt bis 2 Wochen vor dem 05.06. (also 21.05.) und achtet gerne auf BahnCard und Deutschlandticket.  

Solltet ihr noch irgendwelche Fragen haben, erreicht ihr uns alle unter dieser Mailadresse: nordlgt@lists.yfu-deutschland.de. Wir freuen uns auf eure Anmeldungen!

Euer Nord-LGT Orga Team
* Öffentlichkeitsarbeit
** Neue Infos
Hallo liebe Landesgruppe,

die neue Bewerbungssaison bei YFU für das Programmjahr 2027/28 hat Anfang April gestartet und daher gibt es auch in der ÖA in den nächsten Wochen und Monaten immer wieder was zu tun! Um weiterhin viele Schüler für ein Auslandsjahr zu begeistern, brauchen wir wie immer eure Unterstützung. Wenn ihr also Lust und Zeit habt, meldet euch für die folgenden Termine gerne bei kira.thede@yfu-deutschland.de

Momentan suchen wir dringend nach einer Person, die den AJA-Schulvortrag an der THS Pinneberg übernehmen kann!
** AJA-Schulvortrag an der THS Pinneberg (Dringend!)
Wann: 05.05.26, 19:00 Uhr (Aufbau bzw. Treffen bereits 18:30 Uhr)
Wo: Theodor-Heuss-Schule Pinneberg, 
Datumer Chaussee 2, 25421 Pinneberg
Wer: 2-3 motivierte Teamer jedes Erfahrungsgerades

** Info-Veranstalltung mit AFS am Goethe-Gymnasium
Wann: 21.05.2026
Wo: Goethe-Gymnasium Hamburg (Altona)
Rispenweg 28, 22547 Hamburg
Wer: 1-2 Teamer jedes Erfahrungsgerades
* Aufnahmeprogramm
** Betreuungsschulung in Berlin am 13. Juni
Liebe AP-Mitarbeitende,

wir möchten euch herzlich einladen zu einer Betreuungsschulung für neue Betreuer*innen und Menschen, die sich für die YFU-Betreuungsarbeit interessieren.

*Die Schulung findet am Samstag, den 13.06.2026 in Berlin statt (in Kreuzberg, Nähe Ostbahnhof).*
In dieser Schulung lernt ihr alles über die Betreuung im YFU-Aufnahmeprogramm lernen, was ihr wissen solltet: Wir beschäftigen uns mit der Rolle und den Erwartungen an Betreuende, wir erarbeiten verschiedene Gesprächstechniken, die für Gespräche hilfreich sind, und wir werfen einen Blick ins Intranet in den Bereich Betreuung und Dokumentation. Und natürlich wird es auch ausreichend Zeit geben, verschiedene Lerninhalte zu üben.

Nach der Schulung könnt ihr (z.B. zum Sommerjahrgang) direkt in die Betreuung einsteigen: als Hauptbetreuung, wenn ihr mindestens 21 Jahre alt seid oder als Co-Betreuung, wenn ihr unter 21 seid.

Hier könnt ihr euch für die Schulung anmelden:
[[https://forms.office.com/Pages/ResponsePage.aspx?id=QqKWNFDLrkCVZmI1B908iS2FBzkZ3HdJtoS0ZOggvE5UNjFPWkVMWjJQT1NYWVFRQlAwMlIyMERVWS4u][Anmeldung zur Betreuungsschulung in Berlin]]

*Die Schulung beginnt um 9:00 Uhr und dauert bis ca. 18:30 Uhr, für Verpflegung wird gesorgt, und die Fahrtkosten (mit der Bahn in der 2. Klasse) werden von YFU übernommen. Auch eine oder zwei Übernachtungen in einem nahegelegenen Hostel können wir für euch buchen.*

Bei Fragen meldet euch gerne bei uns.

Herzliche Grüße aus Hamburg
Magdalene 
** Aufruf GF Re-Entry
Liebe Landesgruppe,

für unsere Gastfamilien- Re-Entry im Haus Warwisch am 07.06. suchen wir noch dringend Teamende (Erfahrung egal). Die Veranstaltung geht meistens ca. von 12-16 Uhr - die genauen Zeiten werden noch bestätigt. Es geht darum, mit den Gastfamilien die Erfahrung gemeinsam zu reflektieren und den Nachmittag anschließend mit einem Buffet gemeinsam mit den Austauschschüler*innen ausklingen zu lassen. 

Meldet euch super gerne bei mir (amilou.fehr@yfu-deutschland.de oder unter 01786122651), wenn ihr Lust auf einen spannenden Nachmittag habt! 

LG und danke euch
Amilou
* Externes und Überregionales
** Mitarbeiter-Gesuche/Stellen
*Co-Leitung PPP-Fahrt nach Berlin*
Für die Fahrt der amerikanischen PPP-Stipendiat*innen nach Berlin suchen wir noch eine Co-Leitung. Die Fahrt findet vom19.-23.5.2026 statt (Anreise des Teams ist am 18.5.). Höhepunkt der Fahrt wird der Berlin-Tag am 21.5. sein, der vom Deutschen Bundestag für die amerikanischen PPPler*innen aller Austauschorganisationen durchgeführt wird.
Bitte melde dich bei Magdalene (lindemann@yfu.de), wenn du Lust hast dabei zu sein

*USA for you: Teamer*in für die NBT in Hamburg vom 8. bis 10. Mai gesucht*
Für die Nachbereitung der USA for you-Gruppe aus Hamburg suchen wir noch dringend ehrenamtliche Unterstützung (m/w/d). Die Tagung geht von Freitagnachmittag bis Sonntagmittag und wird von den beiden Programmbegleitungen, die mit der Gruppe in den USA waren, geleitet. 
Meldet euch bei Interesse bei Thekla: usaforyou@yfu.de, Durchwahl -77

*USA for you-Auswahl in Halle (Saale): Ein Team-Mitglied für den 09. Mai 2026 gesucht*
Um aus den zahlreichen USA for you-Bewerbungen wieder eine tolle Gruppe zusammenzustellen, suchen wir noch eine Person, die das Team bei der Auswahl unterstützt.  Reisekosten und ggf. Unterkunft werden übernommen. 
Meldet euch bei Interesse bei Thekla: usaforyou@yfu.de, Durchwahl -77

*USA for you Sachsen-Anhalt: Programmbegleitung (m/d) gesucht*
Für die Begleitung der USA for you-Teilnehmenden aus Sachsen-Anhalt nach Michigan vom 16. bis 30.10.2026 suchen noch eine Person (m/d), die die Gruppe in die USA begleitet und auch die VBT und die NBT gemeinsam mit der weiteren Programmbegleitung leitet. 
Die Ausschreibung findet ihr hier: https://intranet.yfu.de/article_tool/articles/2216
Für Fragen könnt ihr Thekla unter usaforyou@yfu.de, Durchwahl -77, kontaktieren.

*Germany for you in Halle (Saale): Teamer*in für zwei Workshops gesucht:*
Die amerikanischen Jugendlichen, die mit Germany for you für zwei Wochen in Halle sind, haben einen Arrival- und einen Pre-Departure Workshop. Dafür suchen wir noch eine Person (m/w/d), die am 15.6. und 16.6. (jeweils 8:30 - 12:00 Uhr) sowie am 26.6. (8:30-12:00 Uhr) unterstützt.
Meldet euch dazu gern bei Thekla: germanyforyou@yfu.de, Durchwahl -77

*Familienbesucher*in in 56477 Zehnhausen gesucht*
Wir haben eine engagierte Gastfamilie, die sich schon sehr auf ihr zukünftiges Gastkind freut. Was jetzt noch fehlt? Ein Familienbesuch!
Der Besuch sollte möglichst schnell, spätestens jedoch bis Ende Mai stattfinden.
Du wohnst in der Nähe von Zehnhausen (Rheinland-Pfalz) oder hast Lust auf einen kleinen Ausflug? 😊 Dann melde dich für weitere Informationen bei Sophia unter gastfamilien@yfu.de.
Auch wenn du bisher noch keine Erfahrung mit Familienbesuchen hast, aber grundsätzlich Interesse mitbringst, freuen wir uns sehr über deine Nachricht!

*Jetzt YFU bei der Gastfamiliensuche unterstützen: Dein Aufruf in der Lokalpresse!*
Mit wenig Aufwand YFU bei der Suche nach Gastfamilien in Deutschland unterstützen – kannst du mit einem Aufruf in der Zeitung bei dir vor Ort! Dafür musst du keinen Artikel schreiben, sondern kannst einfach unsere Vorlagen (Downloads im Intranet) herunterladen, mit wenigen Klicks anpassen und an die Redaktion der Lokalzeitung oder dem Anzeigenblatt bei dir vor Ort senden. Die freuen sich in der Regel über Beiträge mit regionalem Bezug und werden deinem Vorschlag viel offener gegenüberstehen als jeder Pressemitteilung aus der YFU-Geschäftsstelle. 😊 Deine Hilfe ist also Gold wert – und kann mit wenig Aufwand viele Menschen erreichen. Melde dich immer gern bei Corinna (schmidt@yfu.de) in der GS, wenn du Fragen zu den Vorlagen hast oder Unterstützung bei der Suche nach Kontaktadressen brauchst. Wir freuen uns, von dir zu hören und sagen DANKE für deine Hilfe bei der Gastfamiliensuche!

*Spontane Teamende für VBT nächste Woche gesucht*
Für die MD2-VBT vom 03.-08.05. in Mühlhausen suchen wir weiterhin Verstärkung für das Team
Sowohl Teamende mit viel Erfahrung als auch weniger erfahrene Teamende sind willkommen
Melde dich bei Charlie unter charlie.goetjes@yfu-deutschland.de

*Erfahrene und unerfahrene Teamende für VBT Mitte Mai gesucht*
Für die BY2-VBT vom 16.-21.05. in Mühlhausen sucht das Leitungsteam noch mehrere Teamende
Sowohl Teamende mit Erfahrung als auch ohne Erfahrung werden gesucht
Melde dich bei Fenja unter vbt@yfu.de 

*Justees aufgepasst: Fahr mit zur (V)VBT vom 20.-25. Mai in Lauenburg*
Wir haben noch Platz im Team für einen Justee und freuen uns dann mit vollem, motiviertem Team auf Tagung zu fahren 💜 Wenn jemand, jemanden kennt oder du vielleicht Justee bist und Lust hast, dann schreib mir gerne (annakoisarek@yfu-deutschland.de)” 

*Ansprechpersonen für Ungarn und Italien gesucht*
Um unsere Teilnehmenden auf den Aufenthalt in ihrem Zielland vorzubereiten suchen wir Ansprechpersonen, die von ihren Erfahrungen in dem Land berichten und Fragen beantworten können. Aktuell suchen wir noch Ansprechpersonen für Ungarn und Italien. Warst du im Austausch in Italien oder Ungarn und hast Lust, den neuen Jahrgang kennenzulernen und neugierige Fragen zu beantworten? Dann melde dich bei Fenja unter vbt@yfu.de

*OWO-Leitungen gesucht*
Für die OWO 1 vom 16. - 20.08 in Mainz suchen wir 1 erfahrene Leitung
Für die OWO 4 vom 23. - 27.08 in Mainz suchen wir 2 Leitungen
Für die OWO 5 vom 23. - 27.08 in Bingen suchen wir 1 Co-Leitung
Bitte meldet euch bei Mareen (📧 ap-seminare@yfu.de) oder füllt diese [[https://forms.office.com/e/KYWzZNfDNt?origin=lprLink][Umfrage]] aus. Alle weiteren Infos findet ihr [[https://intranet.yfu.de/downloads/files/3970][hier]].

*OWO-Teamende gesucht*
Du hast Lust auf Seminare im Aufnahmeprogramm? Du möchtest Austauschschüler*innen bei ihrem Start in ihr Austauschjahr unterstützen und sie für das Zusammenleben mit ihrer Gastfamilie wappnen? Du möchtest andere YFUler*innen wiedertreffen? Du kennst dich mit Kommunikation und Kultur super aus und hast vom 16. - 20.08 oder 23. - 27.08 Zeit? Dann sind das Top Voraussetzungen, um eine OWO zu teamen! Bitte melde dich bei Mareen (📧 ap-seminare@yfu.de) oder fülle diese [[https://forms.office.com/e/KYWzZNfDNt?origin=lprLink][Umfrage]] aus. Alle weiteren Infos findest du [[https://intranet.yfu.de/downloads/files/3970][hier]].
** Schulungen / Termine
*Last Call: noch zwei Plätze für Colored Glasses Schulung am 15.-17. Mai bei München – bis zum 03. Mai anmelden!*
Mit Colored Glasses Workshops begeistern wir Kinder und Jugendliche der 5. bis 13. Klasse an Schulen und Jugendeinrichtungen in ganz Deutschland für Vielfalt und Toleranz. Wir machen uns stark gegen Diskriminierung und Vorurteile durch spannende Simulationen und Diskussionen auf Augenhöhe! Die Schulung ist dein Start ins Ehrenamt: Wir zeigen dir, wie du einen Workshop planst und durchführst. Erfahrene Ehrenamtliche geben dir Tipps und Tricks, damit du auch ohne Vorerfahrung einen echten Unterschied machen kannst. Du bist zwischen 16 und 29 Jahre alt und willst aktiv werden? Melde dich zur kostenlosen Schulung an: am 15.-17.05. in der Jugendherberge Burg Schwaneck (bei München) [[https://forms.cloud.microsoft/e/e4gc6GAqC0][hier]]. Bei Fragen wenden dich gerne an Nina unter roesch@yfu.de.

*Online-KLT-Schulung am 27.05. um 19:30 Uhr – jetzt anmelden!*
Bewerbende für den nächsten YFU-Jahrgang kennenlernen und dabei von euren eigenen Erfahrungen berichten – das könnt ihr bei den digitalen Kennenlerntreffen (KLTs)! Eine etwa anderthalbstündige Online-Schulung dafür wird am Mittwoch, den 27.05. um 19:30 Uhr angeboten. Bei Interesse meldet euch unter kennenlernen@yfu.de – wir freuen uns auf euch!

*Betreuungsschulung in Berlin am 13.6.2026*
Du hast Lust, Austauschschüler*innen und Gastfamilien in unserem Aufnahmeprogramm zu betreuen? Am 13.6. (Samstag) findet eine eintägige Betreuungsschulung in Berlin-Kreuzberg statt. Die Schulung richtet sich an alle, die in die Betreuung einsteigen möchten oder bereits eingestiegen sind und noch keine Schulung/kein Seminar besucht haben. Beginn ist am 13.6. um 9:00 Uhr und Ende gegen 18:30 Uhr, für Verpflegung wird gesorgt, und die Fahrt- sowie mögliche Übernachtungskosten (im Hostel) werden von YFU übernommen. Anmelden kannst du dich unter diesem Link: [[https://forms.office.com/Pages/ResponsePage.aspx?id=QqKWNFDLrkCVZmI1B908iS2FBzkZ3HdJtoS0ZOggvE5UNjFPWkVMWjJQT1NYWVFRQlAwMlIyMERVWS4u][Anmeldung zur Betreuungsschulung - Tagesschulung in Berlin]]
Falls du Fragen hast, melde dich bei Magdalene (lindemann@yfu.de).

*🚀 Powerstart ins Ehrenamt am 21. Mai um 19.30 Uhr*
Du möchtest aktiv werden oder wieder einsteigen und brauchst für den Start noch ein bisschen Orientierung? Dann haben wir einen Tipp für dich🔥! Starte mit unseren Ehrenamtlichen beim digitalen Powerstart ins Ehrenamt durch. Lerne das YFU 1x1, finde heraus, was es für dich zu tun gibt, wie du dich mit YFUler*innen in deiner Umgebung vernetzen kannst und welche Vorteile du als YFUler*in genießt.
🔥 Anmeldung hier: https://sway.cloud.microsoft/WKISSAGmmiab4CYG
** Sonstiges / Externes
*💜🤝Was hat dein Ehrenamt mit dir gemacht?*
Ehrenamt verändert. Es bringt neue Perspektiven, stärkt Selbstvertrauen, schafft Begegnungen und hinterlässt oft mehr, als man im ersten Moment merkt.
Genau das möchten wir sichtbar machen. Erzähl uns, wie dich dein Ehrenamt verändert hat: Füll unsere kurze Umfrage aus, schick uns ein Foto von dir und werde Teil unserer Community‑Aktion!
Die Einsendungen veröffentlichen wir in unserer Community, auf Instagram, im Vereinsnewsletter und auf weiteren Social‑Media‑Kanälen – um Danke zu sagen, Engagement wertzuschätzen und andere zu ermutigen, selbst aktiv zu werden.
✨ Mach mit und zeig, wie Ehrenamt wirkt: https://forms.office.com/e/ERkvky3x6R
* Terminübersicht
** TERMINE 2026
*08.05. - 10.05.2026* &nbsp;&nbsp;&nbsp; Interessenseminar-Lateinamerika (ILSA), *in Rinteln*

*15.05. - 17.05.2026* &nbsp;&nbsp;&nbsp; Colored Glasses Schulung, Jugendherberge Burg Schwaneck (*bei München*)

*29.05 - 31.05.2026* &nbsp;&nbsp;&nbsp; ÖA-Ausschusstreffen, *Hamburg*

*05.06. - 07.06.2026* &nbsp;&nbsp;&nbsp; *(LG)* Nord-LGT

*13.06. - 13.06.2026* &nbsp;&nbsp;&nbsp; Betreuungsschulung, *Berlin*

*20.06. - 21.06.2026* &nbsp;&nbsp;&nbsp; Colored Glasses Schulung, Liebfrauenschule Mühlhausen (*bei Duisburg*)

*18.09. -20.09. 2026* &nbsp;&nbsp;&nbsp; Colored Glasses Schulung, Jugendherberge Horner Rennbahn *Hamburg*

*25.09. - 27.09.2026* &nbsp;&nbsp;&nbsp; *(LG)* Aktivenwochenende

*02.10. - 04.10.2026*  &nbsp;&nbsp;&nbsp; Seminarleitungsschulung (SLS), Jugendherberge *Kassel*

*06.11. – 08.11.2026* &nbsp;&nbsp;&nbsp; Colored Glasses Schulung, Jugendherberge *Kassel*

*20.11. - 22.11.2026* &nbsp;&nbsp;&nbsp; Betreuendenseminar, *Jugendherberge Stuttgart*

*27.11. - 29.11.2026* &nbsp;&nbsp;&nbsp; ÖA-Ausschusstreffen, *Hamburg*
