* Landesgruppe
**  Wichtige Info Aufrufe Newsletter
Diesen Newsletter findet ihr ab jetzt auch auf Whatsapp! Dafür einfach über diesen Link beitreten: https://chat.whatsapp.com/GBCBuLIU2U78zpim5yGxLF
---

Sehr gerne nehmen wir eure Aufrufe oder Danksagungen in den wöchentlichen Newsletter auf.

Schreibt mir ([[mailto://shh-newsletter@yfu-deutschland.de][shh-newsletter@yfu-deutschland.de]]) dafür einfach immer bis *Mittwochs 17:00 Uhr* eure Aufrufe, damit ich sie noch in den Newsletter der aktuellen Woche mit aufnehmen kann. Ansonsten nehme ich die Aufrufe natürlich gerne in den nächsten auf.

Vielen lieben Dank und ich freue mich auf eure Emails.

Liebe Grüße
Aimo
** Einladung Landesgruppen-Wochenende SHH vom 02.10. bis 04.10.26 Villa Falkenstein (Kiel)
Liebe Landesgruppe,

hiermit übersende ich euch die Einladung zum Landesgruppenwochenende vom 02.10 bis 04.10.26 in der Villa Falkenhorst! Die Adresse lautet Villa Falkenhorst, Falkensteiner Strand 35, 24159 Kiel.

Wir starten am Freitag (02.10.) um 18 Uhr mit einem gemeinsamen Abendessen und am Sonntag (04.10.) geht es dann gegen 14 Uhr wieder nach Hause. Grundsätzlich könnt ihr euch aber auch für nur einzelne Tage (z.B. nur den Samstag) anmelden, falls ihr nicht alle drei Tage Zeit habt.

Bisher ist unser Aktivitätenplan noch nicht sehr gefüllt, weshalb wir uns über eure Rückmeldung/Angebote z.B. für Workshops mit YFU-Bezug, aber auch gerne Kreatives oder Sport freuen würden. Außerdem benötigen wir eure Unterstützung beim Einkaufen/Kochen für das Wochenende, sofern ihr dort unterstützen könnt, gebt bitte auch eine Rückmeldung.

Hier der Link für die Anmeldung:
[[https://forms.cloud.microsoft/e/jUMPju7Lgg][Anmeldung Landesgruppenwochenende 02.10.-04.10.2026]]

Mit Blick auf die Villa als Ort, bedenkt bitte:
Zum Übernachten braucht ihr zwingend einen Schlafsack/eine Decke (Bezug und Innenleben), sowie ein Kopfkissen samt Bezug und ein Bettlaken. Vor Ort gibt es nur Matratzen.
Weiterhin sind Hausschuhe und ein Handtuch von Vorteil.
Gerne könnt ihr auch Gesellschaftsspiele oder ähnliches mitbringen.

Wir freuen uns, euch vor Ort zu sehen!
Lena für den eLGV
** Jetzt anmelden: Public Viewing für die Mitgliederversammlung am 22.11. in der Geschäftsstelle
Liebe Landesgruppe,

Am 30.6. haben wir uns auf einer Mitgliederversammlung für eine neue Satzung entschieden. Damit steht der neuen Struktur nichts mehr im Wege und es wird schon fleißig daran gearbeitet, um den Übergang möglichst fließend hinzubekommen.

Am 22.11. findet die online Mitgliederversammlung statt, auf der wir die nächsten Schritte besprechen und alle Verantwortungsträger*innen und Gestalter*innen für die neue Struktur wählen. Die offizielle Einladung wird nach dem Sommer kommen.

Da die Mitgliederversammlung von 10-18 Uhr angesetzt ist (inkl. einer langen Mittagspause, also keine Angst) haben wir für diesen Tag die Geschäftsstelle reserviert und freuen uns, wenn wir gemeinsam an der Mitgliederversammlung teilnehmen werden. Anmelden könnt ihr euch hier: [[https://forms.cloud.microsoft/e/nDC41S1w9m][Anmeldung zum Public Viewing für die Mitgliederversammlung am 22.11.2026 – Formular ausfüllen]]

Wir freuen uns, wenn viele von euch an dem Tag dabei sind!
* Öffentlichkeitsarbeit
** Neue Schulvorträge und Messen
Hi liebe ÖA-Begeisterte und alle die es werden wollen,

in einigen Wochen fängt die Schule wieder an und dann starten wir wie jedes Jahr nochmal richtig durch mit unseren Schulvorträgen! Außerdem kommen noch einige Messen auf uns zu, für die wir wieder mehrere Teamende suchen. Also: eure Chance (wieder) aktiv zu werden! Ganz egal ob und wie viel ÖA-Erfahrung ihr habt, wir freuen uns über alle Meldungen! 
Die genauen Termine findet ihr unten. 
Bei Interesse meldet euch bei kira.thede@yfu-deutschland.de für die Schulvorträge und bei dennisle-duy.nguyen@yfu-deutschland.de für die Messen.

Danke für euren Einsatz! 
Euer ÖA-Team SHH

| Veranstaltung                                              | Wo                                                          | Wann                                            |
|------------------------------------------------------------+-------------------------------------------------------------+-------------------------------------------------|
| Infoabend am Gymnasium Walddörfer                          | Im Allhorn 45, 22359 Hamburg                                | Di, 15.09.2026; 19–21 Uhr, Aufbau ab 18:30 Uhr  |
| Minimesse am Gymnasium Bondenwald                          | Bondenwald 14b, 22453 Hamburg                               | Mi, 16.09.2026; 19–21 Uhr, Aufbau ab 18:30 Uhr  |
| AJA-Messe in der Zinnschmelze Barmbek                      | Maurienstraße 19, 22305 Hamburg                             | Do, 17.09.2026; 17–19:30 Uhr, Aufbau ab 16 Uhr  |
| Infoabend an der Geschwister-Scholl-STS für die 10. Klasse | Glückstädter Weg 70, 22549 Hamburg                          | Do, 17.09.2026; abends                          |
| Infoveranstaltung an der Grundschule Krempe                | Am Burggraben 10, 25361 Krempe                              | Sa, 19.09.2026; 10–13 Uhr                       |
| Infoabend am Gymnasium Othmarschen                         | Walderseestraße 99, 22605 Hamburg                           | Di, 22.09.2026; ab 19 Uhr                       |
| Infoabend am Gymnasium Hochrad                             | Hochrad 2, 22605 Hamburg                                    | Di, 22.09.2026; 18-19:30 Uhr                    |
| Infoabend an der Julius-Leber-Schule                       | Halstenbeker Str. 41, 22457 Hamburg                         | Di, 29.09.2026; ca. 19 Uhr                      |
| Infoveranstaltung mit AFS & YFU                            | Gymnasium Hummelsbüttel                                     | Mi, 30.09.2026; Beginn 19 Uhr, Aufbau 18:30 Uhr |
| Schulvortrag an der ahfs Uhlenhorst                        | Bostelreihe 5, 22083 Hamburg                                | Fr, 09.10.2026; 10:45–11:45 Uhr                 |
| JuBi an der Stadtteilschule Bergedorf                      | Ladenbeker Weg 13, 21033 Hamburg                            | Sa, 14.11.2026; Zeit tba                        |
* Aufnahmeprogramm
** Teamer*innen gesucht für den Willkomemnsspaziergang (26.09)
Für den Willkommensspaziergang unserer diesjährigen Gastfamilien und den neuen Austauschschüler*innen am 26.09. suchen wir motivierte Menschen aller Erfahrungsgrade. Geplant ist ein bunter Austausch im lockeren Rahmen mit Buffet im Hamburger Stadtpark. Treffen ist fürs Team ab 13:30, das Treffen ist bis ca. 17 Uhr angesetzt. 

Melde dich gerne bei Amilou (amilou.fehr@yfu-deutschland.de), wenn du Lust hast, dabei zu sein oder irgendwelche Fragen hast. 🙂 

Wir freuen uns! 
* Entsendeprogramm
** Es werden immernoch NBT teamende gesucht!
Liebe Landesgruppe,

wir sind nach wie vor auf der Suche nach Personen, die unsere diesjährigen NBTs unterstützen möchten.
- NBT SHH 2: 10.09. – 13.09.2026, CISV – Haus, Hamburg
  männliches Teammitglied, Erfahrung egal
- NBT SHH 3: 01.10. – 04.10.2026, Spejdergården Tydal, Eggebek
  Leitung/Co-Leitung oder Leitungsteam, sowie weitere Teammitglieder
Wenn ihr also Lust habt, die Austauschschüler*innen auf ihrem Rückkehrprozess zu begleiten, tolle Menschen zu sehen, YFU-Spirit zu verbreiten oder einfach mal wieder etwa für YFU zu machen oder noch Fragen habt, dann meldet euch gerne bei uns unter antonia.karg@yfu-deutschland.de oder greta.dahmen@yfu-deutschland.de.

Liebe Grüße
Greta & Antonia
* Externes und Überregionales
** Mitmachen/Stellen
*Team für die USA for you-Auswahl gesucht (14./15.11.26 in Hamburg)*
Im Frühjahr 2027 dürfen wieder 15 Jugendliche aus Hamburg für 14 Tage mit einem Vollstipenidum in die USA reisen und Land und Leute und besonders das ehrenamtliche Engagement dort kennenlernen. Am 14. und 15.11. findet die Auswahl in Hamburg statt und wir suchen noch zwei Team-Mitglieder für Gruppen- und Einzelgespräche. Idealerweise kommst du aus Hamburg oder aus der Nähe und hast ein bisschen oder auch mehr Auswahl-/KLT-Erfahrung. Meldet euch gern bei Thekla unter [[mailto:usaforyou@yfu.de][usaforyou@yfu.de]] oder Durchwahl -77

*Leitungsteam für NBT im Oktober gesucht*
Für die SHH3-NBT vom 02.-04.10. (Teamanreise: 03.10.) suchen wir ein Leitungsteam. Die NBT findet in 24825 Eggebek statt. Melde dich bei Antonia unter [[mailto:antonia.karg@yfu-deutschland.de][antonia.karg@yfu-deutschland.de]]

*Familienbesucher*innen gesucht! 🔍*
Es warten weiterhin einige Familien auf den persönlichen Familienbesuch, der vor einer Platzierung stattfinden muss. Konkret suche ich Personen in der Nähe von 04924 Bad Liebenwerda (ca. 1,5h von Leipzig und 1h von Dresden), 16928 Gerdshagen (ca. 1,5h von Berlin) und in 03044 Cottbus. Melde dich auch, wenn du a) noch keine Familienbesuche gemacht hast, b) nicht in der Nähe wohnst, aber Lust auf einen Ausflug hast, oder c) einen digitalen Besuch übernehmen könntest. Kontakt in der Geschäftsstelle ist Sophia ([[mailto:gastfamilien@yfu.de][gastfamilien@yfu.de]]).

*Nach der OWO ist vor der OWO! 🧡*
Kaum ist unser Sommerjahrgang fast vollständig angekommen und mit vielen schönen Eindrücken von den OWOs gestartet, steht bereits der nächste Jahrgang in den Startlöchern: Im Januar 2027 reisen die Schüler*innen des Winterjahrgangs an. Sie freuen sich schon jetzt auf eine spannende Winter-OWO mit euch! Bist du dabei?
📅 Wann? 24.-28. Januar 2027
🗺️ Wer? Ca. 20 Jugendliche aus aller Welt
📍 Wo? Jugendherberge Wiesbaden
📧 Wie? Trage dich in diese [[https://forms.cloud.microsoft/Pages/ResponsePage.aspx?id=OqhNyXAcyk-Cu3mnrCJZh6KOYPtMfppBhidNFBnWvdtUQVNFV1FORzZaVTBXWE1KSDFLTkE0VUFUNy4u][Umfrage]] ein oder melde dich direkt per Mail bei Sophia ([[mailto:ap-seminare@yfu.de][ap-seminare@yfu.de]])

** Termine/Schulungen
*Dein Einstieg ins Teamen: Das Wochenende in Kassel wartet auf dich! #YFUEducation*
Du willst als Teamer*in bei YFU loslegen? Dann komm zur überregionalen Teaming-Einweisung (Basis) vom 02.-04.10. 2026 in Kassel! Lerne, was es zu beachten gibt, damit du deine Kleingruppen auf YFU-Veranstaltungen zum Durchstarten kriegst. Danach werden „Brainstorming“ und „Fishbowl“ keine Fremdwörter mehr sein. Praxisnah bereiten wir dich auf deinen Einsatz als Teamende*n vor, üben Methoden und zeigen Abläufe – und du probierst dich direkt selbst aus. Dabei knüpfst du Kontakte zu anderen engagierten YFUler*innen und tankst YFU-Spirit. YFU übernimmt die Kosten für Unterkunft, Verpflegung und die An- und Abreise mit der Deutschen Bahn (2. Klasse). Noch unsicher? Kein Problem! Melde dich einfach bei Janine im YFU-Büro ([[mailto:germer@yfu.de][germer@yfu.de]], Durchwahl -93) und kläre deine offenen Fragen. Du bist dir sicher und willst dabei sein? Dann melde dich [[https://forms.cloud.microsoft/e/enDv3SeTJA][hier]] an!

*Komm zur Weiterbildung für Teamende mit Vorerfahrung im Oktober*
Hast du bereits erste Erfahrungen als Teamende*r gesammelt und möchtest deine Fähigkeiten ausbauen? Dann ist unsere Wochenendschulung genau das Richtige für dich! Gemeinsam vertiefen wir dein Wissen, erweitern deine Kompetenzen und bereiten dich noch besser darauf vor, Inhalte im nichtformalen Setting zu vermitteln. Wir erweitern dein Methodenrepertoire, geben dir Tipps für die Moderation und den Umgang mit herausfordernden Situationen – damit du noch sicherer wirst. Wir bieten dir eine praxisnahe Ausbildung, bei der du dich mit anderen Teamenden austauschen kannst. Und natürlich bleibt genug Raum, um Fragen zu klären und neue Impulse zu sammeln! Melde dich [[https://forms.cloud.microsoft/e/cZkhSMtbpZ][hier]] für das Teaming für Fortgeschrittene vom 02.-04.10.2026 in Kassel an! YFU übernimmt die Kosten für Unterkunft, Verpflegung sowie die An- und Abreise mit der DB (2. Klasse).

** Sonstiges
*Hinweis: Vorschussabrechnung Ehrenamt*
Du reichst regelmäßig Vorschussabrechnung ein? Dann denke bitte unbedingt daran, nicht nur die Belege, sondern auch die dazugehörigen Teilnehmerlisten einzuscannen und gemeinsam mit der Vorschussabrechnung per E-Mail einzureichen. Die Teilnehmerlisten sind ebenfalls Bestandteil der Abrechnung und werden für die vollständige Prüfung benötigt. Am besten sendet ihr alle Unterlagen als PDF-Dateien, damit sie problemlos weiterverarbeitet werden können. Vielen Dank für eure Unterstützung, euer Finanzteam aus der GS! 😊

*YFU-Flandern sucht eine*n Praktikant*in für Schulbesuche und Marketing (ab September 2026)*
Du möchtest internationale Jugendarbeit mitgestalten? YFU-Flandern sucht eine*n Praktikant*in ab September 2026 (oder so bald wie möglich) für 3 bis 6 Monate, um Austauschprogramme an Schulen vorzustellen und YFU bei Marketing- und Recruiting-Aktivitäten zu unterstützen. Das bietet YFU: 250 € Taschengeld pro Monat, Unterkunft in einer Gastfamilie, kostenfreie Nutzung öffentlicher Verkehrsmittel in Belgien, Fahrrad und Niederländisch-Sprachkurs. Nicht inbegriffen: Kranken- und Privathaftpflichtversicherung & An- und Abreise nach bzw. von Belgien. Das solltest du mitbringen: Gute Englischkenntnisse (Arbeitssprache), Niederländisch-Kenntnisse (oder Bereitschaft die Sprache zu lernen), Freude an Präsentationen und der Arbeit mit Jugendlichen sowie der Kommunikation mit Schulen und Lehrkräften, Interesse an interkulturellem Austausch, Social-Media-Aktivitäten und weiteren Marketingmaßnahmen. Bewerbungsschluss: 18. September 2026. Bewerbungen an: voorzitter.rvb@yfu.be. [[https://intranet.yfu.de/downloads/files/4003][Ausschreibung ansehen]].

*YFU Argentinien sucht vier Praktikant*innen für die landesweite Tour 2027*
Wie jedes Jahr sucht YFU Argentinien vier Praktikant*innen, die durch das ganze Land reisen, die Programme von YFU bewerben und das lokale YFU-Netzwerk weiterentwickeln. Eine Person wird in Patagonien eingesetzt, eine im Nordosten, eine im Nordwesten und eine im Zentrum des Landes. Der Einsatz beginnt Ende Februar/Anfang März 2027 und sollte mindestens drei Monate dauern. Erforderlich: Spanischkenntnisse auf Grund- bis Mittelstufenniveau oder Kenntnisse einer anderen romanischen Sprache. Inbegriffen: Taschengeld in Höhe von 200 USD, Reisen und Unterbringung in anderen Städten im Rahmen von YFU-Aktivitäten, Unterkunft bei Gastfamilien oder ehrenamtlich Engagierten. Nicht inbegriffen: Visum/Aufenthaltsgenehmigung (für die meisten Länder ist kein Visum erforderlich), Krankenversicherung, An- und Abreise nach bzw. von Buenos Aires. [[https://intranet.yfu.de/downloads/files/4004][Weitere Informationen findest du in der Ausschreibung]]. Bewerbungen können bis zum 20. Oktober an [[mailto:admin@yfu.org.ar][admin@yfu.org.ar]] gesendet werden.
* Terminübersicht
** TERMINE 2026
*18.09. -20.09. 2026* &nbsp;&nbsp;&nbsp; Colored Glasses Schulung, Jugendherberge Horner Rennbahn *Hamburg*

*02.10. - 04.10.2026* &nbsp;&nbsp;&nbsp; Seminarleitungsschulung (SLS), Jugendherberge *Kassel*
*02.10. - 04.10.2026* &nbsp;&nbsp;&nbsp; *(LG)* Aktivenwochenende
*02.10. - 04.10.2026*  &nbsp;&nbsp;&nbsp; Überregionale Teamingeinweisung, Jugendherberge *Kassel*

*06.11. - 08.11.2026* &nbsp;&nbsp;&nbsp; Colored Glasses Schulung, Jugendherberge *Kassel*
*06.11. - 08.11.2026* &nbsp;&nbsp;&nbsp; Betreuendenseminar, *Jugendherberge Stuttgart*

*22.11.2026* &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; *(LG)* Mitgliederversammlung, *Geschäftsstelle*

*27.11. - 29.11.2026* &nbsp;&nbsp;&nbsp; Großes ÖA-Mäuse-Treffen, *Hamburg*

*06.05. - 09.05.2027* &nbsp;&nbsp;&nbsp; BUT 2027, *tba*
