* Landesgruppe
**  Wichtige Info Aufrufe Newsletter
Diesen Newsletter findet ihr ab jetzt auch auf Whatsapp! Dafür einfach über diesen Link beitreten: https://chat.whatsapp.com/GBCBuLIU2U78zpim5yGxLF
---

Sehr gerne nehmen wir eure Aufrufe oder Danksagungen in den wöchentlichen Newsletter auf.

Schreibt mir ([[mailto://shh-newsletter@yfu-deutschland.de][shh-newsletter@yfu-deutschland.de]]) dafür einfach immer bis *Mittwochs 17:00 Uhr* eure Aufrufe, damit ich sie noch in den Newsletter der aktuellen Woche mit aufnehmen kann. Ansonsten nehme ich die Aufrufe natürlich gerne in den nächsten auf.

Vielen lieben Dank und ich freue mich auf eure Emails.

Liebe Grüße
Aimo
** Jetzt anmelden: Public Viewing für die Mitgliederversammlung am 22.11. in der Geschäftsstelle
Liebe Landesgruppe,

Am 30.6. haben wir uns auf einer Mitgliederversammlung für eine neue Satzung entschieden. Damit steht der neuen Struktur nichts mehr im Wege und es wird schon fleißig daran gearbeitet, um den Übergang möglichst fließend hinzubekommen.

Am 22.11. findet die online Mitgliederversammlung statt, auf der wir die nächsten Schritte besprechen und alle Verantwortungsträger*innen und Gestalter*innen für die neue Struktur wählen. Die offizielle Einladung wird nach dem Sommer kommen.

Da die Mitgliederversammlung von 10-18 Uhr angesetzt ist (inkl. einer langen Mittagspause, also keine Angst) haben wir für diesen Tag die Geschäftsstelle reserviert und freuen uns, wenn wir gemeinsam an der Mitgliederversammlung teilnehmen werden. Anmelden könnt ihr euch hier: [[https://forms.cloud.microsoft/e/nDC41S1w9m][Anmeldung zum Public Viewing für die Mitgliederversammlung am 22.11.2026 – Formular ausfüllen]]

Wir freuen uns, wenn viele von euch an dem Tag dabei sind!
* Öffentlichkeitsarbeit
** Neue Schulvorträge und Messen
Hi liebe ÖA-Begeisterte und alle die es werden wollen,

in einigen Wochen fängt die Schule wieder an und dann starten wir wie jedes Jahr nochmal richtig durch mit unseren Schulvorträgen! Außerdem kommen noch einige Messen auf uns zu, für die wir wieder mehrere Teamende suchen. Also: eure Chance (wieder) aktiv zu werden! Ganz egal ob und wie viel ÖA-Erfahrung ihr habt, wir freuen uns über alle Meldungen! 
Die genauen Termine findet ihr unten. 
Bei Interesse meldet euch bei kira.thede@yfu-deutschland.de für die Schulvorträge und bei dennisle-duy.nguyen@yfu-deutschland.de für die Messen.

Danke für euren Einsatz! 
Euer ÖA-Team SHH
** Infoabend am Lise-Meitner Gymnasium
Wo: Knabeweg 3, 22549 Hamburg 
Wann: Do, 27.08.2026; 18 - 19 Uhr
** Infoabend an der Geschwister-Scholl-STS für die 9. Klasse
Wo: Glückstädter Weg 70, 22549 Hamburg
Wann: Do, 03.09.2026; abends
** JuBi am Christianeum
Wo: Otto-Ernst-Str. 34, 22605 Hamburg
Wann: Sa, 05.09.2026; 10 - 16 Uhr (zwei Schichten mit jeweils zwei Personen)
** Infoveranstaltung mit den Austauschexperten am Gymnasium Norderstedt
Wo: Coppernicusstr. 1, 22850 Norderstedt
Wann: Do, 10.09.2026; ab 18:30 Uhr
** Minimesse an der Geschwister-Scholl-STS
Wo: Glückstädter Weg 70, 22549 Hamburg
Wann: Do, 10.09.2026; Zeit tba
** Minimesse am Gymnasium Bondenwald
Wo: Bondenwald 14b, 22453 Hamburg
Wann: Mi, 16.09.2026; 19 - 21 Uhr, Aufbau ab 18:30 Uhr
** AJA-Messe in der Zinnschmelze Barmbek
Wo: Maurienstraße 19, 22305 Hamburg
Wann: Do, 17.09.2026; 17 - 19:30 Uhr, Aufbau ab 16 Uhr
** Infoabend an der Geschwister-Scholl-STS für die 10. Klasse
Wo: Glückstädter Weg 70, 22549 Hamburg
Wann: Do, 17.09.2026; abends
** Infoveranstaltung an der Grundschule Krempe
Wo: Am Burggraben 10, 25361 Krempe
Wann: Sa, 19.09.2026; 10 - 13 Uhr
** Infoabend am Gymnasium Othmarschen
Wo: Walderseestraße 99, 22605 Hamburg
Wann: Di, 22.09.2026; ab 19 Uhr 
** Infoabend am Gymnasium Walddörfer
Wo: Im Allhorn 45, 22359 Hamburg
Wann: Di, 22.09.2026; 19 - 21 Uhr, Aufbau ab 18:30 Uhr
** Schulvortrag an der ahfs Uhlenhorst
Wo: Bostelreihe 5, 22083 Hamburg
Wann: Fr, 09.10.2026; 10:45 - 11:45 Uhr
** JuBi an der Stadtteilschule Bergedorf
Wo: Ladenbeker Weg 13, 21033 Hamburg
Wann: Sa, 14.11.2026; Zeit tba
* Aufnahmeprogramm
** Teamer*innen gesucht für den Willkomemnsspaziergang (26.09)
Für den Willkommensspaziergang unserer diesjährigen Gastfamilien und den neuen Austauschschüler*innen am 26.09. suchen wir motivierte Menschen aller Erfahrungsgrade. Geplant ist ein bunter Austausch im lockeren Rahmen mit Buffet im Hamburger Stadtpark. Treffen ist fürs Team ab 13:30, das Treffen ist bis ca. 17 Uhr angesetzt. 

Melde dich gerne bei Amilou (amilou.fehr@yfu-deutschland.de), wenn du Lust hast, dabei zu sein oder irgendwelche Fragen hast. 🙂 

Wir freuen uns! 
* Entsendeprogramm
** PPP Auswahlleitungen gesucht
Liebe Landesgruppe,

Für eine PPP-Auswahl am 08.11. in Hamburg wird noch eine Auswahlleitung gesucht.
Falls du Zeit und Interesse hast, melde dich bei Keira (keira.geiss@yfu.de).
** Es werden immernoch NBT teamende gesucht!
Liebe Landesgruppe,

wir sind nach wie vor auf der Suche nach Personen, die unsere diesjährigen NBTs unterstützen möchten.
- NBT SHH 2: 10.09. – 13.09.2026, CISV – Haus, Hamburg
  männliches Teammitglied, Erfahrung egal
- NBT SHH 3: 01.10. – 04.10.2026, Spejdergården Tydal, Eggebek
  Leitung/Co-Leitung oder Leitungsteam, sowie weitere Teammitglieder
Wenn ihr also Lust habt, die Austauschschüler*innen auf ihrem Rückkehrprozess zu begleiten, tolle Menschen zu sehen, YFU-Spirit zu verbreiten oder einfach mal wieder etwa für YFU zu machen oder noch Fragen habt, dann meldet euch gerne bei uns unter antonia.karg@yfu-deutschland.de oder greta.dahmen@yfu-deutschland.de.

Liebe Grüße
Greta & Antonia
* Externes und Überregionales
** Mitmachen / Stellen
*Dringend Gastfamilien in Deutschland für die letzten zwei Austauschschüler gesucht!*
Über 200 Austauschschüler*innen starten in diesen Tagen in ihr Austauschjahr in Deutschland – und zwei warten noch sehnlichst auf den Namen ihrer Gastfamilie! Mete und Kağan stammen beide aus der Türkei und sind 15 Jahre alt. Damit sie rechtzeitig anreisen und an ihrer OWO teilnehmen können, brauchen wir dringend zwei Gastfamilien ab Ende August oder Anfang/Mitte September – für drei Monate oder auch länger. Als Gastfamilie kommt ihr für Unterkunft und Verpflegung eures Gastkindes auf, alle weiteren Kosten übernehmen die Jugendlichen selbst. Ein Unterhaltungsprogramm oder besonderer Luxus sind ebenfalls nicht nötig: Am allerwichtigsten ist es, euer Gastkind auf Zeit herzlich bei euch willkommen zu heißen. Meldet euch einfach direkt im AP-Team der Geschäftsstelle, wenn ihr Gastfamilie werden möchtet oder noch Fragen habt: gastfamilien@yfu.de, 040 227002-778. Viele Infos findet ihr auch auf der [[https://www.yfu.de/gastfamilie-werden][YFU-Website]], wo sich Mete und Kağan etwas näher vorstellen. Wir freuen uns, von euch zu hören – und danken euch schon jetzt von Herzen für eure Unterstützung! 💜

*Teamende für NW NBT gesucht*
Für die NW-NBT vom 29.-31.08. (Sa-Mo) (Teamanreise Fr., 28.08.) in Dörverden (wir können euch von Bremen aus mit dem Auto mitnehmen) suchen wir noch eine*n Teamende*n! Wir suchen eine Person, die Lust hat, sowohl mit zu teamen als auch ein bisschen beim Kochen zu unterstützen. Egal ob unerfahren oder erfahren, wir freuen uns über dich im Team! Wir haben die NBT gut vorbereitet, versuchen Stress vor Ort möglichst zu reduzieren und werden einfach ein cooles Wochenende zusammen verbringen.🙃🐛
Melde dich bei Michelle (michelle.gutsch@yfu-deutschland.de) oder Emma (emma.foessing@yfu-deutschland.de) 

*Co-Leitung und Teamende für NBT Anfang/Mitte September gesucht*
Bock auf einen All-Inclusive-Kurztrip in den Spreewald? Dann komm ins NBT-Team! Für unsere NO2-NBT vom 10.9. (Teamanreise) bis zum 13.9. in 03096 Burg (Spreewald) suchen wird noch dringend eine Co-Leitung sowie Teamende. Besonders freuen wir uns über Meldungen von Menschen mit etwas Erfahrung, aber melde dich gerne auch, wenn du bisher noch keine Teamingerfahrung gesammelt hast. Überzeugt? Dann melde dich bei Karla unter karla.golze@yfu-deutschland.de

*Werde Teil des YFU-Trainingswochenendes im Oktober – Trainierende gesucht!*
Wir möchten im Herbst wieder eine überregionale Teaming-Einweisung vom 02.-04.10. 2026 für unerfahrene und Teamende mit ersten Teamingerfahrungen, die aber noch nicht ganz die nötige Erfahrung für eine Seminarleitung besitzen, anbieten. Das Trainingskonzept und die Hälfte des Teams stehen, jetzt fehlen nur noch zwei Trainierende, um das Team zu vervollständigen. Parallel findet die SLS statt, so dass sich zukünftige Seminarleitungen und Teamende nebenher treffen, austauschen und netzwerken können genauso wie die Trainierenden. Hast du Lust, als Trainierende Teil dieses inspirierenden Wochenendes zu werden? Dann melde dich bei Janine Germer in der GS unter germer@yfu.de.

*✨ Hier sehen wir dich: Komm ins Community-Team deiner Region*
Wir suchen Ehrenamtliche, die....neue YFUlis kennenlernen wollen🫂...gerne Social-Media-Content machen 📱...Lust auf Eventplanung haben 🥳...leidenschaftlich Texte für Newsletter usw. schreiben 📝...den Lead übernehmen wollen 🦾
✨ Denn ab 2027 wollen wir richtig durchstarten.
Unsere Vision: Mehr Begegnungen, mehr Veranstaltungen, mehr Gemeinschaft. Und mehr Menschen, die Lust haben, sich ehrenamtlich bei uns zu engagieren. 🌱
Das Beste daran: ✅ Du hast ein tolles ehrenamtliches Team, lernst Leute aus ganz Deutschland kennen, kannst deine Kompetenzen einbringen und erweitern, bekommst Support, eine Ehrenamtskarte und ein nices Merchandise-Piece on top.
Klingt gut? Klick dich durch die Ausschreibungen und melde dich bei uns unter community@yfu.de
👉 Ausschreibungen: https://padlet.com/yfucommunity/ubersicht-community-teams-eatrra9l4sc3i6nw

*Dein Einstieg ins Teamen: Das Wochenende in Kassel wartet auf dich! #YFUEducation*
Du willst als Teamende bei YFU loslegen? Dann komm zur überregionalen Teaming-Einweisung (Basis) vom 02.-04.10. 2026 in Kassel! Lerne, was es zu beachten gibt, damit du deine Kleingruppen auf YFU-Veranstaltungen zum Durchstarten kriegst. Danach werden „Brainstorming“ und „Fishbowl“ keine Fremdwörter mehr sein. Praxisnah bereiten wir dich auf deinen Einsatz als Teamende*n vor, üben Methoden und zeigen Abläufe – und du probierst dich direkt selbst aus. Dabei knüpfst du Kontakte zu anderen engagierten YFUler*innen und tankst YFU-Spirit. YFU übernimmt die Kosten für Unterkunft, Verpflegung und die An- und Abreise mit der Deutschen Bahn (2. Klasse).
Noch unsicher? Kein Problem! Melde dich einfach bei Janine im YFU-Büro (germer@yfu.de, Durchwahl -93) und kläre deine offenen Fragen. Du bist dir sicher und willst dabei sein? Dann melde dich unter https://forms.cloud.microsoft/e/enDv3SeTJA an!

*Leitungsteam für NBT im Oktober gesucht*
Für die SHH3-NBT vom 02.-04.10. (Teamanreise: 03.10.) suchen wir ein Leitungsteam. Die NBT findet in 24825 Eggebek statt.
Melde dich bei Antonia unter antonia.karg@yfu-deutschland.de

*Weiterhin dringend Familienbesucher*innen benötigt! 🔎*
Es warten noch zwei Schüler auf ihre Gastfamilie. Doch bevor sie platziert werden können, braucht es einen Familienbesuch. Daher sind wir auf deine Unterstützung angewiesen!
Aktuell brauchen wir Besucher*innen in 91126 Schwabach-Wolkersdorf (bei Nürnberg), 32478 Hille (bei Minden) und 33758 Schlossholte (bei Bielefeld).
Du wohnst in der Nähe oder hast Lust auf einen Ausflug? Du hast bereits Erfahrung oder das wäre dein erster Ausflug ins Aufnahmeprogramm? Either way freuen wir uns auf deine Nachricht an gastfamilien@yfu.de! 🧡

*Jetzt für Online-Betreuungsschulungen anmelden!*
Wir haben zwei tolle Online-Schulungsangebote für alle, die im Aufnahmeprogramm Austauschschüler*innen und Gastfamilien betreuen möchten.
Bei Fragen dazu meldet euch bei Magdalene (lindemann@yfu.de)
👉 4-Module-Schulung für neue Betreuer*innen
📅Jeweils am 1.,2.,8. und 9.9. um 19 Uhr
📍Online
🦸‍♀️Trainerinnen: Caren Spamer & Ines Hintz
✅ [[https://forms.cloud.microsoft/Pages/ResponsePage.aspx?id=QqKWNFDLrkCVZmI1B908iS2FBzkZ3HdJtoS0ZOggvE5UNlk3REVUQldBNVRMOFRTN0xRRkwyMFZXWS4u][Anmeldung: Anmeldung zur 4-Module-Schulung "Einheit 1" Online]]
👉 Co-Betreuungsschulung/Refresh
📅Am 15.9. um 19 Uhr
📍Online
🦸‍♀️Trainerinnen: Caren Spamer & Ines Hintz
✅ [[https://forms.cloud.microsoft/Pages/ResponsePage.aspx?id=QqKWNFDLrkCVZmI1B908iS2FBzkZ3HdJtoS0ZOggvE5UMEVJRVQyMVFGVFNBTjhKMkFWNkM1RTVTOC4u][Anmeldung: Anmeldung zur Co-Betreuungsschulung Online]]

*Erfahrene Seminarleitungen und solche, die es werden wollen, aufgepasst: Kommt zur SLS vom 02.-04.10.2026 in Kassel!*
Du hast Erfahrung als Teamer*in gesammelt, fühlst dich methodisch fit und suchst nach der nächsten Herausforderung? Als bereits erfahrene Seminarleitung wünschst du dir neuen Input und Gelegenheit zur Reflexion deiner Leitungsrolle? Dann komm zur Seminarleitungsschulung (SLS) vom 2.-4. Oktober 2026 in Kassel! 🚀In dieser Schulung werden die Basics vermittelt, die du als Seminarleitung kennen solltest, aber darüber hinaus gibt es auch Angebote für erfahrene Leitungen sich bspw. zum Umgang mit Menschenfeindlichkeit und Extremismus oder dem Thema Coaching weiterzubilden. [[https://intranet.yfu.de/article_tool/articles/2225][Hier findest du mehr Infos zu den angebotenen Inhalten]]. [[https://forms.office.com/e/GKHKtJmCfy][Melde dich gleich an!]] Bei Fragen kontaktiere Rahel aus der GS (ehrenamt@yfu.de, Durchwahl -44).

*Auswahlleitungen für die PPP-Auswahlen in Bremen, Passau und Dresden gesucht*
Die Bewerbungssaison für den PPP-Jahrgang 2027/28 hat begonnen und zahlreiche Jugendliche warten auf ihre PPP-Auswahl. Dafür suchen wir nun Auswahlleitungen und Einzelgesprächsleitungen. Vor allem in Bremen, Passau und Dresden sind wir dringend auf der Suche nach Auswahlleitungen. Wenn Du Dir vorstellen kannst, diesen Herbst eine Auswahl zu leiten, fülle bitte diese kurze Umfrage aus [[https://forms.cloud.microsoft/e/9c4d3YZ1t5][PPP-Auswahlleitungen 2026 – Formular ausfüllen]]  oder melde Dich gerne direkt bei Keira (keira.geiss@yfu.de)

*Erfahrene Teamer*innen für PPP-Nachbereitungsseminar in Berlin gesucht (24.-27.9.)*
Ende September trifft sich der gerade zurückgekehrte PPP-Jahrgang in Berlin, um gemeinsam auf das Jahr in den USA zurückzublicken. Das Leitungsteam steht, viele Teamplätze sind bereits besetzt. Jetzt fehlst nur noch du - als erfahrene*r Teamer*in, um das Team zu vervollständigen!
📍 Berlin-Wannsee
📅 Seminar: 25.–27. September | Teamanreise: 24. September
Ihr habt Lust auf eine tolle Gruppe, spannende USA-Geschichten und ein buntes YFU-Wochenende? Dann meldet euch bei Lina unter ppp@yfu.de!

*Neue PPP-Auswahlleitungen gesucht*
Für die neue PPP-Saison wollen wir wieder neue Auswahlleitungen schulen. Du hast Lust, in der neuen Saison eine PPP-Auswahl zu leiten, aber dir fehlt noch die nötige Schulung? Dann trage dich gerne in die [[https://forms.cloud.microsoft/Pages/ResponsePage.aspx?id=QqKWNFDLrkCVZmI1B908ibDdxUEoHapOoDj4h619qOdUQUVNSUdCTEwxT1I4WFVDSTEwUEtZTTBLWi4u][Abfrage]] ein. Voraussetzungen für die Schulung sind Erfahrungen als Teammitglied/ Einzelgesprächsleitung bei PPP-Auswahlen und bestenfalls eine KLT-Schulung. Bei Fragen melde dich gerne bei Picabo (picabo.winands@yfu-deutschland.de).

*💻 Weiterhin 2 Leitungen für Digitale OWO gesucht 🔎*
Wir suchen weiterhin zwei Personen, die Lust haben, zusammen die OWO im digitalen Format für die verspätete Anreise durchzuführen.
- Für die digitale OWO gibt es ein eigenes Konzept mit 7 AGs; Zeitumfang: ca. 10 Stunden
- Zeitraum: September, die konkrete Terminplanung liegt bei euch: Ihr könnt die OWO beispielsweise an einem Wochenende oder verteilt über mehrere Abendtermine anbieten.
- Die genaue Anzahl der Teilnehmenden sowie deren Ankunftszeiten und Herkunftsländer werden erst Ende August feststehen. Die Organisation erfolgt in enger Abstimmung mit der Geschäftsstelle.
Auch für ATS, die verspätet anreisen, ist die OWO wichtig, damit sie gut vorbereitet in ihr Austauschjahr starten. Meldet euch gerne bei Mareen (ap-seminare@yfu.de), wenn ihr euch vorstellen könnt, die digitale OWO zu leiten.

*Colored Glasses Schulung am 18.-20. September in Hamburg – Starte jetzt dein Engagement für eine bunte Gesellschaft!*
Mit Colored Glasses Workshops begeistern wir Kinder und Jugendliche der 5. bis 13. Klasse an Schulen und Jugendeinrichtungen in ganz Deutschland für Vielfalt und Toleranz. Wir machen uns stark gegen Diskriminierung und Vorurteile durch spannende Simulationen und Diskussionen auf Augenhöhe! Die Schulung ist dein Start ins Ehrenamt: Wir zeigen dir, wie du einen Workshop planst und durchführst. Erfahrene Ehrenamtliche geben dir Tipps und Tricks, damit du auch ohne Vorerfahrung einen echten Unterschied machen kannst. Du bist zwischen 16 und 29 Jahre alt und willst aktiv werden? Melde dich zur kostenlosen Schulung am 18.-20. September in Hamburg [[https://forms.cloud.microsoft/e/x3uPwy2qkx][hier]] an. Gerne weitersagen, auch an Interessierte ohne YFU-Hintergrund!  Alle Infos hier als [[https://yfuit.sharepoint.com/:b:/t/GSexterngeteilteDateien/IQCYPKGgpbi7QpQ7CZyjoKDlAYz9QPWCf9MW5jmXvvjQYLQ?e=Wgi1gU][Flyer zum Download]]. Bei Fragen wenden dich gerne an Nina unter roesch@yfu.de.

*Trainer*innen gesucht für Colored Glasses Schulung vom 06.–08.11. in Kassel!*
Die Schulung richtet sich an junge Menschen ab 16 Jahren, die sich bei [[https://www.yfu.de/schule-und-yfu/colored-glasses][Colored Glasses]] engagieren möchten. Als Trainer*innen begleitet ihr sie mit Methoden, Austausch und euren Erfahrungen. Materialien und Ablaufvorschläge sind vorhanden. Beim Team achten wir auf einen guten Mix aus Personen mit aktueller CG-Workshop-Erfahrung, YFU-Bezug und YFU/CG-Trainings-Erfahrung. Wenn du Lust hast, neue Ehrenamtliche auf ihrem Einstieg bei CG zu begleiten, freuen wir uns über deine Rückmeldung. Wir suchen noch 2 Trainer*innen, die das Team ergänzen. Eine erfahrene CG-Trainerin haben wir bereits gewonnen.
Interesse oder Fragen? Melde dich bei Nina: roesch@yfu.de
** Sonstiges
*EEE-YFU is looking for a dedicated Educational Events intern via the Erasmus+ traineeship program (6-10 months)*
The GO is looking for an intern via the Erasmus+ traineeship program which is connected to universities in Europe. Duration: 5 to 10 months. Starting date: Ideally by November 1st, 2026. Location: Brussels. The intern in educational projects will have the chance to enhance their organizational skills by supporting the educational activities as well as learn about long-term Intercultural Youth Exchanges worldwide, by being involved in the organization and promotion of the YFU Support Conference as well as YES 2027, including fundraising for it and related reporting. To learn about the tasks in detail, logistical arrangements as well as the required key skills plus eligibility criteria look up [[https://about.yfu.org/work-with-us][Work with us - About Youth For Understanding Intercultural Exchange Programs]]. You can apply there by filling out a form and sharing your CV + motivation. You also need a confirmation of Erasmus+ eligibility from your university or sending institution. Application deadline: August 31, 2026.

*Das Border Focal Point Network der Europäischen Kommission sucht 10 ‘Cross-Border Ambassadors’*
Bring dich in der grenzüberschreitenden Politik und Kommunikation ein! Du musst kein Politikprofi sein — bring einfach deine Stimme, deine Neugier und deine persönliche Grenzgeschichte mit. Ob du in einer Grenzregion aufgewachsen bist, dort studiert hast oder dich engagierst – dieses Programm ist für dich. Bewirb dich bis zum 📅 31. August 2026, um Teil eines sechsmonatigen EU-Programms mit monatlichen Meetings mit der GD REGIO, kreativer Content-Produktion und Diskussionen über EU-Politik zu werden. Mehr Infos + Bewerbung: [[https://futurium.ec.europa.eu/en/border-focal-point-network/news/call-applications-cross-border-ambassadors-2026-2027-mandate][Call for Applications – Cross-Border Ambassadors – 2026 Mandate | Futurium]] Fragen? Schreib uns an: borders@loweurope.eu

*Megafon Nach dem YES ist vor dem YES – Bewirb dich fürs Core Team 2027*
Vor wenigen Wochen haben noch hunderte Schüler*innen und Ehrenamtliche aus aller Welt beim Youth Empowerment Seminar (YES) das Ende ihres Austauschjahres gefeiert. Nun suchen wir bereits wieder Ehrenamtliche für das Core Team, das das nächste YES vom 21. bis 25. Juni 2027 am Werbellinsee in Brandenburg organisiert und mit Leben füllt. 
Für diese Rollen kannst du dich bewerben: 🫂IGL Coordinator, 🎤Hosts,🧯Operations Coordinator, 🎓 Head(s) of Track, 🤳 Social Media Manager, ✈️ Travel Coordinators
Deadline für die Bewerbung: 16. September 2026 
👉 Alle Infos zu den Aufgaben und der Bewerbung: https://www.yfu-yes.org/volunteer-2027

*🌍 Werde die Stimme von YFU in Europa! 🌍*
Hast du Lust, dich für Jugendaustausch auf politischer Ebene einzusetzen? Das Global Office sucht Ehrenamtliche aus Deutschland für den Pool of Representatives (PoR) für den Zeitraum 2027–2028!
Was machst du im PoR? Du vertrittst YFU bei internationalen Konferenzen, triffst politische Entscheidungsträger*innen und setzt dich dafür ein, dass Schüleraustausch und Ehrenamt in Europa mehr Anerkennung und Förderung erhalten.
Das erwartet dich: ✅ Vertretung von YFU auf europäischer Ebene. ✅ Professionelles Training in der Schweiz (Anfang 2027). ✅ Einzigartiges Netzwerk & wertvolle Skills.
Das bringst du mit: 👉 18+, Commitment für 2 Jahre, politisches Interesse, Wohnsitz in Europa, gutes Englisch & Reisebereitschaft.
⏳ Bewerbung bis 31.08.2026
🔗 Infos & Bewerbung: https://advocacy.yfu.org/call-for-volunteers-pool-of-representatives

*Mental Health in der Internationalen Jugendbildung - Teilnehmende für Fokusgruppen gesucht!*
Das Projekt beschäftigt sich mit der mentalen Gesundheit von jungen Menschen und Fachkräften in der Internationalen Bildungsarbeit. Untersucht wird, welche Herausforderungen sich im Arbeitsfeld zeigen, welche bestehenden Ansätze hilfreich sind und was es braucht, um Fachkräfte und junge Menschen besser zu unterstützen. Für die Fokusgruppen mit Fachkräften und jungen Menschen werden noch Teilnehmende gesucht, die im Kontext Internationaler Bildungsarbeit – zum Beispiel bei einer Jugendbegegnung, einem Workcamp, einer Kinder- und Jugendreise, einem Freiwilligendienst oder Schüler*innenaustausch – mit dem Thema mentale Gesundheit in Berührung gekommen sind. Die Fokusgruppen finden voraussichtlich zwischen dem 19. und 23. Oktober digital statt und dauern etwa 60 bis 90 Minuten.
Ihr möchtet Eure Erfahrungen und Perspektiven einbringen? Dann freut sich das Projekt über eine kurze Nachricht an fpd@transfer-ev.de.
* Terminübersicht
** TERMINE 2026
*18.09. -20.09. 2026* &nbsp;&nbsp;&nbsp; Colored Glasses Schulung, Jugendherberge Horner Rennbahn *Hamburg*

*25.09.-27.09.2026* &nbsp;&nbsp;&nbsp; Training of Trainers (ToT), *Wiesbaden*

*02.10. - 04.10.2026*  &nbsp;&nbsp;&nbsp; Seminarleitungsschulung (SLS), Jugendherberge *Kassel*
*02.10. - 04.10.2026*  &nbsp;&nbsp;&nbsp; *(LG)* Aktivenwochenende

*06.11. – 08.11.2026* &nbsp;&nbsp;&nbsp; Colored Glasses Schulung, Jugendherberge *Kassel*

*20.11. - 22.11.2026* &nbsp;&nbsp;&nbsp; Betreuendenseminar, *Jugendherberge Stuttgart*

*22.11.2026* &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; *(LG)* Mitgliederversammlung, *Geschäftsstelle*

*27.11. - 29.11.2026* &nbsp;&nbsp;&nbsp; ÖA-Ausschusstreffen, *Hamburg*

*06.05. - 09.05.2027* &nbsp;&nbsp;&nbsp; BUT 2027, *tba*
