* Landesgruppe
**  Wichtige Info Aufrufe Newsletter
Diesen Newsletter findet ihr ab jetzt auch auf Whatsapp! Dafür einfach über diesen Link beitreten: https://chat.whatsapp.com/GBCBuLIU2U78zpim5yGxLF
---

Sehr gerne nehmen wir eure Aufrufe oder Danksagungen in den wöchentlichen Newsletter auf.

Schreibt mir ([[mailto://shh-newsletter@yfu-deutschland.de][shh-newsletter@yfu-deutschland.de]]) dafür einfach immer bis *Mittwochs 17:00 Uhr* eure Aufrufe, damit ich sie noch in den Newsletter der aktuellen Woche mit aufnehmen kann. Ansonsten nehme ich die Aufrufe natürlich gerne in den nächsten auf.

Vielen lieben Dank und ich freue mich auf eure Emails.

Liebe Grüße
Aimo
* Öffentlichkeitsarbeit
** Neue Infos
Liebe Landesgruppe

Wir sind fast am Ziel: Wir haben schon 90 - und wir wollen 100 Botschafter*innen für die AJA-Kampagne „Offene Türen, offene Herzen - Austausch braucht Gastfamilien“ gewinnen!
Hast du noch einen Kontakt in die Politik - oder kurz Zeit, um Abgeordnete aus deiner Region zu kontaktieren? Melde dich für die fertige Mailvorlage und Tipps bei mir! 
Danke und liebe Grüße, Annina (duchardt@yfu.de)

https://www.austausch-braucht-Gastfamilien.de
** Schulvortrag am Gymnasium Brunsbüttel
Wann: 12.03.2026 um 18:00 Uhr.

Wo:
Gymnasium Brunsbüttel
Kopernikusstr. 1
25541 Brunsbüttel

Wer: 2-3 erfahrene und unerfahrene Personen

* Externes und Überregionales
** Mitarbeiter-Gesuche/Stellen
*Werkstudent:in in der GS gesucht im Projekt Schule:Global*
Für das Projekt Schule:Global suchen wir eine:n Werkstudierende:n zur Unterstützung im Bereich Schulkooperationen. Die Aufgaben umfassen v.a. Kommunikation mit Schulen und administrative Tätigkeiten. Alle Infos zur Stelle findet ihr hier.

*‎FSJ der Politik & Demokratie bei Colored Glasses – komm ins YFU-Team!*
In deinem FSJ gibst du selbst Workshops zu Vielfalt & Diskriminierung, diskutierst mit Jugendlichen auf Augenhöhe und verstärkst so unser ehrenamtliches Team. Außerdem unterstützt du uns bei Aufgaben im Büro, kannst dich im Marketing einbringen und andere Bereiche des internationalen Jugendaustausches von YFU kennenlernen. Das FSJ geht vom 01. September 2026 bis zum 31. August 2027. Arbeitsort im Hamburger YFU-Büro, mit Workshopeinsätzen bundesweit. Du bist zwischen 18 und 26 Jahren alt, verfügst über sehr gute Deutschkenntnisse und bist begeistert für Vielfalt, Toleranz und gesellschaftlichen Zusammenhalt? Schicke deine Bewerbung und Fragen ab sofort an Nina (gerne per Du!) unter roesch@yfu.de. Alle Infos [[https://coloredglasses.de/dein-freiwilliges-soziales-jahr-fsj-politik-demokratie-bei-colored-glasses-m-w-d/][hier]]. FSJ-Träger sind die [[https://www.ijgd.de/inland/fsj-politik][ijgd]].

*Germany for you: Programmbegleitung vom 13. bis 28. Juni 2026 in Halle (Saale) gesucht (Honorarvertrag)*
Für das Germany for you-Programm suchen wir eine Programmbegleitung (m/w/d), die gemeinsam mit einer amerikanischen Programmbegleitung und weiteren Ehrenamtlichen vor Ort in Halle eine Gruppe von 15 Jugendlichen aus den USA bei einem bunten Programm aus ehrenamtlichem Einsatz, Sightseeing (in Halle und Berlin), Sprachkurs und Sportprogramm begleitet.
Mehr Infos hier: https://intranet.yfu.de/article_tool/articles/2220
Meldet euch bei Interesse gern bei Thekla: germanyforyou@yfu.de, Durchwahl -77

USA for you Sachsen-Anhalt: Programmbegleitungen gesucht*
Für die Begleitung der USA for you-Teilnehmenden aus Sachsen-Anhalt nach Michigan vom 16. bis 30.10.2026 suchen wir zwei Ehrenamtliche, die auch die VBT und die NBT gemeinsam leiten. 
Die Ausschreibung findet ihr hier: https://intranet.yfu.de/article_tool/articles/2216
Für Fragen könnt ihr Thekla unter usaforyou@yfu.de, Durchwahl -77, kontaktieren.

*USA for you München 2026: Männliche Programmbegleitung gesucht*
15 Jugendliche von Münchener Mittelschulen starten am 24. Oktober 2026 in ein zweiwöchiges Abenteuer in Michigan mit Community Service, Sightseeing und Leben in Gastfamilien. Für die Vor- und Nachbereitung und die Begleitung der Gruppe in die USA suchen wir noch einen männlichen Ehrenamtlichen. Die Ausschreibung findest du hier: https://intranet.yfu.de/article_tool/articles/2217
Bei Fragen: Kontaktiere Thekla unter usaforyou@yfu.de oder Durchwahl -77

*USA for you München 2026: Auswahl-Leitung und -Team gesucht*
Für die Auswahlgespräche für USA for you in München am 13. und 14. Juni 2026 suchen wir noch eine Leitung und Team-Mitglieder. Mehr Infos zu USA for you findet ihr hier: https://www.yfu.de/kurzprogramme/usa-for-you
Meldet euch bei Interesse gern bei Thekla: usaforyou@yfu.de, Durchwahl -77

*Familienbesucher:in in Riesbürg gesucht*
Wir haben eine engagierte Gastfamilie, die sich schon sehr auf ihr zukünftiges Gastkind freut. Was jetzt noch fehlt? Ein Familienbesuch!
Der Besuch sollte möglichst zeitnah, spätestens jedoch bis Mitte April stattfinden.
Du wohnst in der Nähe von Riesbürg (Baden-Württemberg) oder hast Lust auf einen kleinen Ausflug? 😊 Dann melde dich für weitere Informationen bei Sophia unter gastfamilien@yfu.de.
Auch wenn du bisher noch keine Erfahrung mit Familienbesuchen hast, aber grundsätzlich Interesse mitbringst, freuen wir uns sehr über deine Nachricht!

*Leitung eines vierwöchigen Sommerkurses für US-amerikanische Austauschschüler:innen*
Du hast vom 25. Juli-21. August 2026 noch nichts vor, hast Erfahrung in der Leitung von Teams sowie in der Jugendarbeit? Englisch beherrscht du im Schlaf und eine Ersthelfer*innen-Ausbildung bringst du auch mit? Dann suchen wir genau 👉dich für die Leitung des PPP-Sprachcamps in Bonn. Das genaue Anforderungsprofil sowie die Aufgabenbeschreibung findest du [[https://www.yfu.de/ueber-yfu/jobs-praktika][hier]].
📧Fragen und Interessensbekundungen schickst du bitte Sophia (ap-seminare@yfu.de).

*Vierwöchiges interkulturelles Training und Betreuung für US-amerikanische Austauschschüler:innen*
Im Sommer reisen 42 PPP-Stipendiat*innen aus den USA für ihren Austausch nach Deutschland. Du hast Lust, sie bei ihren ersten Wochen in Bonn zu begleiten, interkulturelle Trainings durchzuführen, ihnen bei Rat und Tat zur Seite zu stehen sowie ein buntes Rahmenprogramm zu entwerfen? Für den 25. Juli-21. August 2026 steht noch nichts in deinem Kalender 📅 ? Dann komm ins Team des PPP-Sprachcamps 🚀. Die genauen Bewerbungsvoraussetzungen und Aufgabenbeschreibungen findest du [[https://www.yfu.de/ueber-yfu/jobs-praktika][hier]] 🔎.
📧Fragen und Interessensbekundungen schickst du bitte Sophia (ap-seminare@yfu.de).

*🚀 Powerstart-Verstärkung gesucht – komm ins Powerstart-Team!*
Unser Powerstart-Team möchte wachsen. Ab sofort suchen wir erfahrene Ehrenamtliche, die sich bei YFU gut auskennen und anderen souverän über das Ehrenamt berichten können. Gerne auch Ehrenamtliche, die schon etwas mehr Lebenserfahrung mitbringen und die Elterngeneration ansprechen können.
Was springt für dich dabei raus?  Du kannst dir deinen Einsatz flexibel nach Absprache einteilen, viele neue Leute kennenlernen, deine Moderationskompetenzen erweitern und hast ein starkes Team an deiner Seite. 💪 Klingt nach einer Aufgabe für dich? Melde dich bei Julia aus der Geschäftsstelle (kastner@yfu.de).

*Werde VBT-Leitung in Lauenburg oder Mühlhausen*
Der Frühling steht vor der Tür und die VBT-Saison auch – wir suchen für einige VBTs noch euch als Leitungen, oft stehen sogar schon Teams bereit. Wir freuen uns sehr, wenn ihr den nächsten Jahrgang auf ein spannendes Austauschjahr vorbereitet! Meldet euch gerne direkt bei Fenja unter vbt@yfu.de
- SHH1: 04.04.-09.04. in Lauenburg: Leitungsteam
- NO2: 08.04.-13.04. in Lauenburg: Leitungsteam
- MD1: 14.04.-19.04. in Mühlhausen: Co-Leitung
- SHH3: 20.04.-25.04. in Lauenburg: Co-Leitung
- MD2: 03.05.-08.05. in Mühlhausen: Leitungsteam
- BY2: 16.05.-21.05. in Mühlhausen: Leitungsteam
** Schulungen / Termine
*Datenschutz kompakt: Online-Einweisung am Dienstag, 10. März um 19.00 Uhr*
Die nächste digitale Datenschutzeinweisungen (ungefähr 45 min.) für Referent*innen, Gremienmitglieder und alle Interessierte findet statt am
- Dienstag , 10. März um 19.00 Uhr
Wir freuen uns über alle, die dabei sind – gerne auch weitersagen! Meldet euch unter datenschutz@yfu.de an. Weitere Infos folgen dann per mail. Mehr zum Thema Datenschutz bei YFU findet ihr im [[https://intranet.yfu.de/downloads/files?category=41][Intranet]]. Unsere aktuellen [[https://www.yfu.de/datenschutz][Datenschutzhinweise]] stehen auf unserer Webseite zur Verfügung.

*Colored Glasses Schulung am 15.-17. Mai bei München – Starte jetzt dein Engagement für eine bunte Gesellschaft!*
Mit Colored Glasses Workshops begeistern wir Kinder und Jugendliche der 5. bis 13. Klasse an Schulen und Jugendeinrichtungen in ganz Deutschland für Vielfalt und Toleranz. Wir machen uns stark gegen Diskriminierung und Vorurteile durch spannende Simulationen und Diskussionen auf Augenhöhe! Die Schulung ist dein Start ins Ehrenamt: Wir zeigen dir, wie du einen Workshop planst und durchführst. Erfahrene Ehrenamtliche geben dir Tipps und Tricks, damit du auch ohne Vorerfahrung einen echten Unterschied machen kannst. Du bist zwischen 16 und 29 Jahre alt und willst aktiv werden? Melde dich zur kostenlosen Schulung am 15.-17.05. in der Jugendherberge Burg Schwaneck (bei München) [[https://forms.cloud.microsoft/e/e4gc6GAqC0][hier]] an. Bei Fragen wenden dich gerne an Nina unter roesch@yfu.de.
** Sonstiges / Externes
*KLT-Teamende aufgepasst: Umfrage zu den Kennenlerntreffen*
Die Zukunftswerkstatt Auswahlen überarbeitet derzeit das Konzept der Kennenlerntreffen und braucht dafür die Perspektive und praktische Erfahrungswerte von euch KLT-Teamenden. Dafür haben sie eine anonyme Umfrage erstellt. Hierfür ist euer KLT-Erfahrunsggrad total egal – füllt die Umfrage gerne auch aus, wenn ihr noch nicht so viele oder bisher keine KLTs geteamt habt! Auch Feedback zu dem organisatorischen Drumherum hilft ihnen sehr weiter.
👉 Link zur der  Umfrage: [[https://forms.cloud.microsoft/Pages/ResponsePage.aspx?id=OqhNyXAcyk-Cu3mnrCJZhyx9_nTarRNInwMj_eVUVAFUNzRNUEJQQjZPWTJUTjBUMkdKRkhXQTNFVC4u][KLT-Umfrage – Formular ausfüllen]]
⌛ Deadline: 15. März 2026
🤔 Fragen & Sonstiges: celine.huener@yfu.de

*Alles rund um die Strukturreform – FAQ*
Dieses Jahr wird entschieden, wie das Vereinsleben von YFU in Zukunft aussehen soll. Viele Fragen werden gestellt: Was bedeuten die Veränderungen für Ehrenamtliche und Mitglieder? Wie sehen die neuen Organe aus? Wer entscheidet in Zukunft über den Verein? Damit ihr gut informiert seid, haben wir ein FAQ zur Strukturreform für euch zusammengestellt, das alle wichtigen Fragen transparent beantwortet: [[https://sway.cloud.microsoft/75ukJpXLBadjHr2v][Zum FAQ-Strukturrefor]]

*Abschlussevent Gastfamilienkampagne am 26. März - jetzt anmelden!*
Euer Engagement, eure Offenheit und eure Erfahrungen haben die Kampagne [[https://austausch-braucht-gastfamilien.de/][„Offene Türen, offene Herzen – Austausch braucht Gastfamilien“]] getragen und lebendig gemacht. Zum Abschluss der Kampagne laden der AJA und seine Mitgliedsorganisationen euch herzlich zu einer Online-Veranstaltung ein, bei der wir gemeinsam Bilanz ziehen, zurückblicken, voneinander lernen und nach vorn schauen.
📅 Donnerstag, 26. März 2026, 🕕 18:00–19:45 Uhr, 💻 via Zoom
Wir freuen uns sehr, wenn Ihr euch die Zeit nehmt und eure Erfahrungen, Gedanken und Ideen einbringt.  Anmeldung unter: https://us06web.zoom.us/meeting/register/mFrPO6xCTgKYGA3jHJi1dQ
* Terminübersicht
** TERMINE 2026
*20.03. - 22.03.2026* &nbsp;&nbsp;&nbsp; Gremiensitzung Frühjahr, Jugendherberge Horner Rennbahn *Hamburg*

*27.03. - 29.03.2026* &nbsp;&nbsp;&nbsp; Betreuendenseminar in *Bad Bevensen*

*15.05. - 17.05.2026* &nbsp;&nbsp;&nbsp; Colored Glasses Schulung, Jugendherberge Burg Schwaneck (*bei München*)

*29.05 - 31.05.2026* &nbsp;&nbsp;&nbsp; ÖA-Ausschusstreffen, *Hamburg*

*05.06. - 07.06.2026* &nbsp;&nbsp;&nbsp; *(LG)* Nord-LGT

*13.06. - 13.06.2026* &nbsp;&nbsp;&nbsp; Betreuungsschulung, *Berlin*

*20.06. - 21.06.2026* &nbsp;&nbsp;&nbsp; Colored Glasses Schulung, Liebfrauenschule Mühlhausen (*bei Duisburg*)

*18.09. -20.09. 2026* &nbsp;&nbsp;&nbsp; Colored Glasses Schulung, Jugendherberge Horner Rennbahn *Hamburg*

*25.09. - 27.09.2026* &nbsp;&nbsp;&nbsp; *(LG)* Aktivenwochenende

*02.10. - 04.10.2026*  &nbsp;&nbsp;&nbsp; Seminarleitungsschulung (SLS), Jugendherberge *Kassel*

*06.11. – 08.11.2026* &nbsp;&nbsp;&nbsp; Colored Glasses Schulung, Jugendherberge *Kassel*

*20.11. - 22.11.2026* &nbsp;&nbsp;&nbsp; Betreuendenseminar, *Jugendherberge Stuttgart*

*27.11. - 29.11.2026* &nbsp;&nbsp;&nbsp; ÖA-Ausschusstreffen, *Hamburg*
